### ISSUE TITLE
When a new coil is defined with kjs, the server cannot be started

### ISSUE THREAD

**Issue by MOYINGCrystal** [GregTechCEu/GregTechCEu-1.19#1005]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.1.3b

### Recipe Viewer Installed

No Recipe Viewer

### Environment

Dedicated Server

### Cross-Mod Interaction

Yes

### Other Installed Mods

architectury-9.2.14-forge
rhino-forge-2001.2.2-build.18
kubejs-forge-2001.6.4-build.138

### Expected Behavior

just work

### Actual Behavior

The server cannot be started. logs\kubejs\startup.log contains:
Error in 'StartupEvents.registry': net/minecraft/client/renderer/texture/MissingTextureAtlasSprite
java.lang.NoClassDefFoundError: net/minecraft/client/renderer/texture/MissingTextureAtlasSprite

Maybe shouldn't import the contents of the net.minecraft.client package into CoilBlockBuilder?

### Steps to Reproduce

1) Write something like this in startup_scripts:
```js
StartupEvents.registry("block", event => {
    const coils = [
        ["stone", "12600", "16", "8"]
    ]
    coils.forEach((coil) => {
        event.create(coil[0] + "_coil_block", "gtceu:coil")
            .texture("kubejs:block/" + coil[0] + "_coil_block")
            .temperature(coil[1])
            .energyDiscount(16)
            .level(coil[2])
            .tier(coil[3])
            .coilMaterial(GTMaterials.get(coil[0]))
            .hardness(5)
            .requiresTool(true)
            .soundType("stone")
            .noValidSpawns(true)
    })
})
```
2) start server

**Comment by screret** [comment]
Pls attach the log file

**Comment by MOYINGCrystal** [comment]
[latest.log](https://github.com/GregTechCEu/GregTech-Modern/files/14735307/latest.log)
[startup.log](https://github.com/GregTechCEu/GregTech-Modern/files/14735308/startup.log)
