### ISSUE TITLE
Bucket Texture has Borders

### ISSUE THREAD

**Issue by IGCBOOM** [GregTechCEu/GregTechCEu-1.19#1008]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.1.4

### Recipe Viewer Installed

REI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

GTCEu, REI

### Expected Behavior

Bucket not to have a border around the texture.

### Actual Behavior

But has a border around the texture.

### Steps to Reproduce

Put bucket in hand, border is visible in first and third person. Example below.
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/11730326/ad366422-3040-4b5b-9f0a-94444c1e791b)
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/11730326/b7b47488-e891-40bc-87d9-f2ac0638d516)

**Comment by screret** [comment]
oh that's REALLY weird..

**Comment by screret** [comment]
I hope that's not the forge bucket model being broken

**Comment by IGCBOOM** [comment]
I have checked some other Forge mods and they don't appear to have they issue. Not sure if that is related or not though, could be that they use their own texture rather than forge's.
