### ISSUE TITLE
Energy Acception?

### ISSUE THREAD

**Issue by 34486** [GregTechCEu/GregTechCEu-1.19#101]
### GregTech CEu Version

1.0.4

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

I would expect any GTCEU energy source (electric) to be able to supply the AE2 Energy acceptor with energy to power AE devices.

### Actual Behavior

No connection/conversion of energy.

### Steps to Reproduce

Hook up any form of power generation directly from output to acceptor or by using cables/wires.

### Additional Information

From what I understand from asking around in the discord is that its gtceu side not ae2 side??????? Please correct me if wrong! Thank you!

**Comment by Yefancy** [comment]
converter added in #112
