### ISSUE TITLE
Crash when GTCEu is installed with AE2 and Spice of Life: Valheim Edition

### ISSUE THREAD

**Issue by RushanM** [GregTechCEu/GregTechCEu-1.19#1016]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.0.20.b

### Recipe Viewer Installed

No Recipe Viewer

### Environment

I can't get into the game

### Cross-Mod Interaction

Yes

### Other Installed Mods

- Applied Energistics 2
- Spice of Life: Valheim Edition
- Architectury
- Cloth Config API
- Fabric API

### Expected Behavior

To get the game running so I can play

### Actual Behavior

The game doesn't launch, throwing me a crash

### Steps to Reproduce

Install GregTechCEu Modern, Applied Energistics 2 and Spice of Life: Valheim Edition along with their dependencies and run the game

### Additional Information

I was running the game on Minecraft 1.20.1 Fabric 0.15.7.
It is this combination of three mods that prevents the game from starting. If you install only the other two mods (it doesn't matter which two of them) without the third one, the game will start.
[crash-2024-03-26_07.38.12-client.txt](https://github.com/GregTechCEu/GregTech-Modern/files/14752580/crash-2024-03-26_07.38.12-client.txt)

**Comment by screret** [comment]
fabric version is unsupported.
