### ISSUE TITLE
[Possible Enhancement?][Question] Best method to safely transform one or more input itemstacks in a machine recipe without removing them from the input bus?

### ISSUE THREAD

**Issue by AncientShotgun** [GregTechCEu/GregTechCEu-1.19#1028]
Question title. 
Additional details: I want to be able to choose when the itemstack(s) get(s) transformed, specifically between 'after recipe lookup but before processing start' and 'after recipe completion'. I also need the solution to work well with parallelization logic, so I can perform the same transformation on the target(s) as many times as the recipe was parallelized that processing cycle. Bonus points if the solution allows me to perform different transformations at different times in the processing iteration on different itemstacks. More bonus points if the solution functions in a multiblock with distinct buses, if that feature has already been implemented.
By 'safe', I mean a solution that isn't too hacky/cumbersome and doesn't cause server-client desync or inventory bugs w.r.t the machine's input inventory.
Additionally, is this safe method possible to implement in KubeJS, and if it is, how?
If you've seen the ExxonMobil Chemical Plant multiblock from GTNH and how it damages, but doesn't consume, a catalyst item a player must provide for some recipes during operation, that is the approximate phenomenon I want to emulate.

**Comment by screret** [comment]
not possible currently without very specialized logic (especially not in KJS), but can be done at some point if you make a feature request.

**Comment by AncientShotgun** [comment]
Made the feature request, will close this issue thread now.
