### ISSUE TITLE
Crash when create a new world or into an existing world.

### ISSUE THREAD

**Issue by 854342681** [GregTechCEu/GregTechCEu-1.19#1038]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.1.4.a

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

- SuperMartijn642's Core Lib
- 0Pack2Reload
- ModernFix
- Moderately Enough Effect Descriptions
- Food Effect Tooltips
- YUNG's Better Strongholds
- GeckoLibIrisCompat
- Angel Block Renewed
- AI-Improvements
- YUNG's Better Desert Temples
- Create Liquid Fuel
- AEInfinityBooster
- Aqua combat
- Simply Swords
- Charm of Undying
- Nature's Compass
- Elytra Slot
- Universal Bone Meal
- Labels
- Attack Speed Enchantment
- YUNG's Better Nether Fortresses
- Immersive Aircraft
- Just Enough Characters
- Nether's Delight
- GeckoLib 4
- Forbidden & Arcanus
- Just Enough Resources
- Patchouli
- LootJS
- Combat Nouveau
- Companion
- Enderman Overhaul
- Extreme Sound Muffler
- Better Mods Button
- Create: Connected
- Durability Tooltip
- Xaero's Minimap
- Fruits Delight
- Clear Water
- Applied Energistics 2
- Titanium
- Kotlin for Forge
- Collective
- Entangled
- libIPN
- Distinguished Potions
- Iceberg
- Forge Config Screens
- Majrusz Library
- Stylish Effects
- Just Enough Professions (JEP)
- Bookshelf
- Clumps
- Iron's Spells 'n Spellbooks
- Alex's Caves
- MekanismTweaks
- Alternate Current
- Curios API
- Ancient Reforging
- Spice of Life Onion
- Puzzles Lib
- CorgiLib
- Enhanced Celestials
- CreativeCore
- L2 Artifacts
- Cristel Lib
- Apotheosis
- Create Diesel Generators
- Kiwi Library
- Passive Skill Tree
- Player Animator
- L2 Library
- Structure Credits
- AE2NetworkAnalyzer
- Majrusz's Enchantments
- Time In A Bottle
- Rhino
- Just Enough Items
- YUNG's Better End Island
- Enchantment Sort
- Ars Énergistique
- ProbeJS
- Sophisticated Backpacks
- Domestication Innovation
- Cloth Config v10 API
- Controlling
- Ars Nouveau
- Searchables
- Create Big Cannons
- L2 Complements
- Sophisticated Core
- Euphoria Patcher
- Building Gadgets 2
- Open Parties and Claims
- Nimble
- Botarium
- Create Utilities
- AlmostUnified
- Yeetus Experimentus
- Aquamirae
- Catalogue
- Create: Big Contraptions
- EMI
- U Team Core
- YUNG's Bridges
- AttributeFix
- Leaves Be Gone
- Resourceful Lib
- Xaero's World Map
- Touhou Little Maid
- True Ending: Ender Dragon Overhaul
- YUNG's Better Dungeons
- Inventory HUD+(Forge edition)
- Explorer's Compass
- Mekanism: Generators
- Obscure API
- Citadel
- Tool Belt
- Glodium
- Create Ore Excavation
- LaserIO
- Trash Cans
- Jade Addons
- Casualness Delight
- EnchantmentDescriptions
- YUNG's Better Jungle Temples
- [Let's Do] Brewery
- Vintage Delight
- Farmer's Delight
- Time in a bottle Curio Support
- Oculus
- Apothic Attributes
- Create: Power Loader
- Jade
- Caelus API
- Create Confectionery
- MmmMmmMmmmmm
- Light Overlay
- Blueprint
- Pick Up Notifier
- Homing Ender Eye
- Fusion
- Create Enchantment Industry
- Pipez
- Faster Ladder Climbing
- Apotheotic Additions
- Oculus Flywheel Compat
- Cataclysm Mod
- TES
- Dave's Potioneering
- JAOPCA
- Overflowing Bars
- Create: New Age
- Lava Clear View
- Freecam
- Bad Packets
- Placebo
- L2 Archery
- Lucent
- Embeddium++
- Mekanism: Weapons
- ME Requester
- Night Vision Enchantment
- Sophisticated Storage
- Valhelsia Core
- Miner's Delight
- Packet Fixer
- Embeddium
- Polymorphic Energistics
- AppleSkin
- Creeper Overhaul
- Mouse Tweaks
- NonConflictKeys
- YUNG's Better Mineshafts
- Apotheosis/Create Addon
- ShetiPhian-Core
- I18nUpdateMod
- TexTrue's Embeddium Options
- Entity Texture Features
- [Let's Do] API
- End's Delight
- PassiveSearchBar
- Better Combat
- YUNG's API
- Sunrise & Sunset Audio
- FTB Library
- YUNG's Better Witch Huts
- ExtendedAE
- X-PlayerInfo
- Create: Balanced Flight
- Compressed Creativity
- MaxHealthFix
- Architectury
- Applied Mekanistics
- Functional Storage
- Passable Foliage
- L2 Hostility
- Moonlight Library
- KubeJS Create
- Just Enough Effects Descriptions
- PriorityTarget
- Item Production Lib
- Apothic Curios
- X-Enchantment
- Create: Steam 'n' Rails
- FTB Ultimine
- YUNG's Better Ocean Monuments
- L2 Weaponry
- Create: Central Kitchen
- Mekanism Cardboard Tooltip
- Merge Enchantments
- Inventory Profiles Next
- Create
- ContingameIME
- Extra Sounds
- YUNG's Extras
- Resourcefulconfig
- Create: The Factory Must Grow
- Flat Bedrock
- Entity Model Features
- Mekanism
- Delightful
- PneumaticCraft: Repressurized
- Modern UI
- Just Enough Mekanism Multiblocks
- SuperMartijn642's Config Library
- Ferrite Core
- KubeJS
- Passive Shield
- Polymorph
- GregTechCEu Modern
- Celestial Artifacts
- Immersive Engineering
- Celestial Core
- Extra enchantment
- Gregicality Rocketry
- Gregtrip
- Gregtech: Extended Chemistry
- Gregified Integrations

### Expected Behavior

1. start game.
2. create a new world or into an existing world.
3. into the world.

### Actual Behavior

1. start game.
2. create a new world or into an existing world.
3. the game will crash.

### Steps to Reproduce

1. start game.
2. create a new world or into an existing world.
3. the game will crash.

### Additional Information

crash report: [https://paste.fastmirror.net/?c32042d27bf4761c#ADRsyADxufDMSX1NimqCupEovunma57TLxSn5b5j4q7E](url)

**Comment by screret** [comment]
gregTrip is broken, ask the developer to update it to the latest GT version maybe?
