### ISSUE TITLE
Wiremill GUI Messed Up After 1.1.4a Update

### ISSUE THREAD

**Issue by mk0003** [GregTechCEu/GregTechCEu-1.19#1039]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.20.1-1.1.4a

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Custom Modpack : ProjectE, Quark, Apotheosis, Refined Storage

### Expected Behavior

Result item being right side and circuit number bottom left.

### Actual Behavior

Result item middle and circuit is at right side.

### Steps to Reproduce

Place wiremill
Set circuit number to 1
Put any wire ingredient inside machine

### Additional Information

This is how it looks
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/6971901/b492919e-8418-469b-bb6e-506ce33e23f9)

**Comment by screret** [comment]
break & replace the block.

**Comment by mk0003** [comment]
Breaking and replacing fixed the issue. Thanks

**Comment by chemlzh** [comment]
Bug still exists in v1.1.4.b, and breaking & replacing it cannot fix it.

Additional mod: Terrafirmagreg 0.7.2, with GTCEu manually upgraded.

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/32123043/c4b51ae7-80d5-4a66-9ef4-c8c533c83b08)

**Comment by chemlzh** [comment]
The bug disappeared when game was restarted. Great!

> Bug still exists in v1.1.4.b, and breaking & replacing it cannot fix it.
> 
> Additional mod: Terrafirmagreg 0.7.2, with GTCEu manually upgraded.
> 
> ![image](https://private-user-images.githubusercontent.com/32123043/320252640-c4b51ae7-80d5-4a66-9ef4-c8c533c83b08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwNTk1MjMsIm5iZiI6MTcxMzA1OTIyMywicGF0aCI6Ii8zMjEyMzA0My8zMjAyNTI2NDAtYzRiNTFhZTctODBkNS00YTY2LTllZjQtYzhjNTMzYzgzYjA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDAxNDcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhMTViZTUwMWVmNGZkMzNhOTZiOGRmMWRiZWIzY2FlYWM2MDQ2NWY4OTA3ODhmMTk4NzdkNzVkNGZlZTQzMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S-LSA8xaOtp-CJHtodOpE66bzaii9MzpnZfeSJ0_EsU)
