### ISSUE TITLE
Some tools (like drills) can't get unbreaking from the enchantment table

### ISSUE THREAD

**Issue by cuberyl-catastrophe** [GregTechCEu/GregTechCEu-1.19#1045]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.1.4a

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

Nomifactory CEU.

### Expected Behavior

Tools should have a chance to get unbreaking when enchanting using the enchantment table

### Actual Behavior

Too sdo not get unbreaking when enchanting using the enchantment table

### Steps to Reproduce

try enchanting a drill (this bug affects some other tools too)
You will never get unbreaking

**Comment by screret** [comment]
intended.
