### ISSUE TITLE
Iron III Chloride named Iron Iii Chloride in game

### ISSUE THREAD

**Issue by Leclowndu93150** [GregTechCEu/GregTechCEu-1.19#1059]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

any

### Recipe Viewer Installed

EMI

### Environment

MP

### Cross-Mod Interaction

No

### Other Installed Mods

GregTech

### Expected Behavior

Be named Iron III Chloride

### Actual Behavior

Iii

### Steps to Reproduce

Search in JEI

**Comment by Avikbajpai** [comment]
Hi Team, 

I would like to contribute in this project, can someone let me know if this codebase is locally debuggable as I am new here. 

Thanks,
Avik

**Comment by minecraft7771** [comment]
> Hi Team,
> 
> I would like to contribute in this project, can someone let me know if this codebase is locally debuggable as I am new here.
> 
> Thanks, Avik

You can fork this repository and then edit that locally and PR the fix once its done. For more information joining the discord and asking for directions there is probably faster

**Comment by Avikbajpai** [comment]
> > Hi Team,
> > I would like to contribute in this project, can someone let me know if this codebase is locally debuggable as I am new here.
> > Thanks, Avik
> 
> You can fork this repository and then edit that locally and PR the fix once its done. For more information joining the discord and asking for directions there is probably faster

Sure please share me the discord invite, Thanks

**Comment by screret** [comment]
https://discord.gg/gregtech-ce-unofficial-701354865217110096
