### ISSUE TITLE
[Bug] Titanium fluid cells turn into tungstensteel when recycled by arc furnace or macerator

### ISSUE THREAD

**Issue by chemlzh** [GregTechCEu/GregTechCEu-1.19#1068]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.1.4.b

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Terrafirmagreg 0.7.2, with GTCEuM manually updated. (Update: it's not induced by TFG)

### Expected Behavior

Titanium fluid cells should be turned into 6 titanium ingots per item.

(Updated) Titanium fluid cells should be crashed into 6 titanium dusts per item.

### Actual Behavior

Titanium fluid cells are transformed into 6 tungstensteel ingots per item.

(Updated) Titanium fluid cells are crashed into 6 tungstensteel dusts per item.

### Steps to Reproduce

Put titanium fluid cells in the arc furnace with enough oxygen

### Additional Information

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/32123043/da9405e7-f1bc-49bd-8b74-15e7d41a8522)

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/32123043/4921e23f-4da3-4bd5-a970-3b20aac382be)

**Comment by chemlzh** [comment]
This bug can be reproduced with only GTCEuM and EMI. @screret 
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/32123043/406d0501-61fb-47ff-b16c-c2009e585723)

**Comment by screret** [comment]
Well duh , it's a recipe error

**Comment by chemlzh** [comment]
> Well duh , it's a recipe error

No, it's not a recipe error. I have debugged for so long, and finally I found this bug in GTitems.java

```java
    public static ItemEntry<ComponentItem> FLUID_CELL_LARGE_TITANIUM = REGISTRATE.item("titanium_fluid_cell", ComponentItem::create)
            .lang("Titanium Cell")
            .model(GTModels::cellModel)
            .color(() -> GTItems::cellColor)
            .onRegister(compassNodeExist(GTCompassSections.ITEMS, "empty_cell"))
            .onRegister(modelPredicate(GTCEu.id("fluid_cell"), (itemStack) -> FluidTransferHelper.getFluidContained(itemStack) == null ? 0f : 1f))
            .onRegister(attach(cellName(), ThermalFluidStats.create((int)FluidHelper.getBucket() * 128, GTMaterials.TungstenSteel.getProperty(PropertyKey.FLUID_PIPE).getMaxFluidTemperature(), true, false, false, false, true), new ItemFluidContainer()))
            .onRegister(materialInfo(new ItemMaterialInfo(new MaterialStack(GTMaterials.TungstenSteel, GTValues.M * 6)))).register();
```

In codeblock above "GTMaterials.TungstenSteel" should be "GTMaterials.Titanium"

To my regret, I cannot edit source code even if I fork GTM code. Maybe you could do me a favor to help fix it. @screret
