### ISSUE TITLE
[Bug or feature?] electrotine are crafted with 1 redstone and 1 electrum, but 8 electrotine can only be centrifuged into 1 redstone and 1 electrum

### ISSUE THREAD

**Issue by chemlzh** [GregTechCEu/GregTechCEu-1.19#1069]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.1.4.b

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Terrafirmagreg 0.7.2, with GTCEu manually upgraded.

### Expected Behavior

Since electrotine are crafted with 1 redstone and 1 electrum, centrifuge it will get 1 redstone and 1 electrum, which guarantees material transformation with no loss.

### Actual Behavior

To get 1 redstone and 1 electrum, we need 8 electrotine to be centrifuged.

### Steps to Reproduce

1) Put 1 redstone and 1 electrum in the mixer, we get 1 electrotine;
2) Put 1 electrotine in the centrifuge, it will not work.

### Additional Information

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/32123043/8d71feb0-d9eb-4486-b242-660d36182990)
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/32123043/9d312978-3d02-4a6a-a05a-234ab08b3cd3)

**Comment by screret** [comment]
I believe intended? cc @serenibyss
