### ISSUE TITLE
Updated Material Textures

### ISSUE THREAD

**Issue by stanieldev** [GregTechCEu/GregTechCEu-1.19#107]
### Feature Description

I would like to have the materials match the style of modern Minecraft post-1.13.

This would include most materials found under assets/gtceu/textures/items/material_sets.

**Comment by screret** [comment]
aren't they already?

**Comment by stanieldev** [comment]
Some are, but I noticed that the nuggets don't fit the theme as I would have expected.

However, if that is intentional, then I'll close the issue.
