### ISSUE TITLE
Custom ore doesn't work in an ore vein

### ISSUE THREAD

**Issue by Onigeshi** [GregTechCEu/GregTechCEu-1.19#1086]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.1.4.b

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

KubeJS, Mekanism, AlmostUnified

### Expected Behavior

to be able to add a custom ore/material I've created into a ore vein.

### Actual Behavior

the ore/material gets created but when I tried to add it into a vein it doesn't work making the ore vein not spawn. 

errors I get: https://pastebin.com/LunS5YFf 

### Steps to Reproduce

startup script:

```
GTCEuStartupEvents.registry('gtceu:material', event => {
    event.create('testore').gem().ore().color(0xfcfcfc).secondaryColor(0xebfaf3).iconSet(GTMaterialIconSet.RUBY)
});
```

serverscript script:
```
GTCEuServerEvents.oreVeins(event => {
    event.add("kubejs:testore_vein", vein => {
        vein.weight(30)
        vein.clusterSize(30)
        vein.density(0.15) 
        vein.layer("deepslate")
        vein.dimensions("minecraft:overworld")
        vein.biomes("#minecraft:is_overworld")
        vein.heightRangeTriangle(-50, -15)
        vein.layeredVeinGenerator(generator => generator
            .buildLayerPattern(pattern => pattern
                .layer(l => l.weight(1).mat(GTMaterials.Testore).size(1, 1))
                //.layer(l => l.weight(1).block(() => Block.getBlock('gtceu:testore_ore')).size(1, 2)) << this works
            )
        )
        vein.surfaceIndicatorGenerator(indicator => indicator
            .surfaceRock(GTMaterials.Testore)
            .placement("above") 
        ) 
    })
})
```

**Comment by screret** [comment]
you can't access it with a `GTMaterials.Thing` reference. do `.mat('gtceu:testore')` instead.

**Comment by Onigeshi** [comment]
> you can't access it with a `GTMaterials.Thing` reference. do `.mat('gtceu:testore')` instead.

hi, thanks for the reply but it didn't work, tho I did a bit more searching in discord and I found a way to make it work by using `.mat(GTMaterials.get('testore'))`

**Comment by screret** [comment]
👍
