### ISSUE TITLE
Mining ore inconsistencies

### ISSUE THREAD

**Issue by mk0003** [GregTechCEu/GregTechCEu-1.19#1092]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.2.0

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

No other mods

### Expected Behavior

Pickaxes and hammers being consistent and fortune being applied incorrectly. Some of behaviours probably expected but i was not sure and listed all.

### Actual Behavior

1. Fortune on pickaxes only affects stone dust drops and not main ore drop. Pickaxes always yields one raw ore and maybe some stone dust.
2. Hammer without fortune enchantment destroys ores but yields nothing, not even the raw ore.
3. Hammer with "Fortune I" yields only one crushed ore.
4. Hammer with "Fortune III" yield maximum 3 crushed ores instead of expected 4 crushed ores.
5. Hammering some ores destroys the ore and yields nothing even if it is enchanted with fortune. Examples are Realgar Ore, Green Sapphire Ore, Sapphire Ore, Nether Topaz Ore, Rock Salt Ore, Salt Ore.

### Steps to Reproduce

Place the some ores and break with a pickaxe, a hammer and with a fortune enchanted pickaxe/hammer and see the drops.

### Additional Information

Looks like hammer calculates fortune drop amount like it have 1 less fortune level. Thats why it drops nothing when there is no fortune enchantment on it (Counts as Fortune 0). Fortune II works like Fortune II etc.

I noticed all the ores that drop nothing when broken with an unenchanted hammer has a gem form and/or siftable.

BTW i am **not** talking about mining hammers, i am talking about normal hammer that used for crafting and such.

Have a good day and thanks for the all the efforts.

**Comment by screret** [comment]
1 is intended, the rest less so.

**Comment by mk0003** [comment]
I also found out that crushed realgar doesn't have a forge hammer recipe from raw realgar while crushed diamond and crushed emerald have the forge hammer recipe. Diamond and emerald have gem forms but hammer doesn't destroy them. This might the reason.

**Comment by YoungOnionMC** [comment]
fixed in #1668

**Comment by Astral-Haze** [comment]
This issue, or at least some ores like salt dropping nothing when hammered, is present again in 1.4.6
