### ISSUE TITLE
Long distance pipelines don't work

### ISSUE THREAD

**Issue by Phoupraw** [GregTechCEu/GregTechCEu-1.19#1096]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.2.0

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

GCP

### Expected Behavior

It should transfer fluid.
![图片](https://github.com/GregTechCEu/GregTech-Modern/assets/50520903/ad201788-57e9-428e-95e4-dcd32320ac8c)

### Actual Behavior

It doesn't transfer fluid.

### Steps to Reproduce

1. Place a super tank.
2. Put in some fluid.
3. Set auto output.
4. Place long enough fluid pipeline.
5. Place another super tank.
6. Place pipeline endpoints.
7. No fluid are transferred.

### Additional Information

Both item and fluid pipelines don't work.
Though I set the min length to one, it still doesn't work.

**Comment by screret** [comment]
You sure you checked for existing issues? This one's pinned, even.

**Comment by Phoupraw** [comment]
> You sure you checked for existing issues? This one's pinned, even.

You say TODO-List? But long distance pipes are checked.

**Comment by screret** [comment]
oh wait I had to unpin it
https://github.com/GregTechCEu/GregTech-Modern/issues/978

**Comment by Phoupraw** [comment]
Oh I just searched "long" and "distance" but didn't search "LD".
