### ISSUE TITLE
Distillation tower is not working

### ISSUE THREAD

**Issue by METABYTECODE** [GregTechCEu/GregTechCEu-1.19#1097]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-1.20.1-1.2.0.a-build_587

### Recipe Viewer Installed

JEI

### Environment

Single

### Cross-Mod Interaction

Yes

### Other Installed Mods

I try this on ATM 9 and only Forge+GTCEU

### Expected Behavior

lightly steam cracked naphta -> 11 liquids
liquid air -> argon and etc.

And other luquids

### Actual Behavior

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/62258232/96f37004-47e3-4581-8c5b-89904ed109e4)
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/62258232/fceb8e06-1788-48b4-8098-52da9a98e6e1)

### Steps to Reproduce

Build DisTower -> In input (lightly steam cracked naphta) -> machine is not star process

**Comment by screret** [comment]
...do you have enough output space?

**Comment by METABYTECODE** [comment]
> ...do you have enough output space?

12 outputs. Its a max build size

**Comment by screret** [comment]
and an output bus?

**Comment by METABYTECODE** [comment]
> and an output bus?

No(. The visualization of the structure does not show the need for an export bus
