### ISSUE TITLE
[1.19.2] JEI compatibility bug

### ISSUE THREAD

**Issue by Igneaalis** [GregTechCEu/GregTechCEu-1.19#1112]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.2.0.a

### Recipe Viewer Installed

JEI

### Environment

Both

### Cross-Mod Interaction

Yes

### Other Installed Mods

https://pastebin.com/3pwS24WL

### Expected Behavior

Recipe viewer has to show all recipes (macerator, alloy smelter etc.)

### Actual Behavior

Recipe viewer shows only workbench recipes.

Recipe viewer: https://imgur.com/a/KBBSM7A
Usage viewer woks fine: https://imgur.com/a/uotzBbX

### Steps to Reproduce

Press R on a Copper Wire, there must be a wiremill in the recipe viewer but there is not.

### Additional Information

1.1.4b works perfectly.

**Comment by Igneaalis** [comment]
Recipe viewer: https://imgur.com/a/KBBSM7A
Usage viewer woks fine: https://imgur.com/a/uotzBbX

**Comment by screret** [comment]
1.19?

**Comment by Igneaalis** [comment]
> 1.19?

Yes, sorry. Now the MC version is in the title.

**Comment by screret** [comment]
in that case, known issue. but thanks for putting it on the tracker
