### ISSUE TITLE
[Bug or feature?] Poor ores that can be crushed into more than 1 crushed ore gain more byproducts than planned

### ISSUE THREAD

**Issue by chemlzh** [GregTechCEu/GregTechCEu-1.19#1118]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.2.0.a, but may exist in older versions

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Tested with Terrafirmagreg modpack.

### Expected Behavior

Poor ores that can be crushed into more than 1 crushed ore (main product) should gain only 1-3 additional ore(s) with a probability.

### Actual Behavior

Poor ores that can be crushed into more than 1 crushed ore (main product) gain additional ores that are 1-3 times equal to main products with a probability, thus making normal/rich ores production relatively decreased.

### Steps to Reproduce

Put the poor ores into the macerator with voltage no lower than HV. The poor ores must be crushed into more than 1 crushed ore in macerator with MV-or-lower voltage.

### Additional Information

As shown in EMI, at HV:
1 poor raw redstone ore can produce 5*(0.75+0.5+0.25+0.125)=8.125
1 normal raw redstone ore can produce 5*1+1*(0.5+0.25+0.125)=5.875
1 rich raw redstone ore can produce 10*1+1*(0.5+0.25+0.125)=10.875

With higher voltage, poor ores chan produce more crushed ores, since byproduct generation probability greatly increases.

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/32123043/90f7ca2e-edad-4a5d-9cbf-2eb2613dffad)
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/32123043/d0fbb4e9-a540-44ae-b8b3-48061f611260)
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/32123043/5421d429-6086-40fd-87ef-3b605d20af95)

**Comment by chemlzh** [comment]
I doubt that this bug is not from poor ores, but normal and rich ores. That is, normal and rich ore byproducts should be equal to their main products, not just 1. @screret

**Comment by screret** [comment]
Base GT doesn't have poor ores.

**Comment by chemlzh** [comment]
> Base GT doesn't have poor ores.

I'm sorry for not figuring out the bug source. Thank you for your reply, I'll report it the TFG team.
