### ISSUE TITLE
Modify the oreprocessing gui to look like the following image

### ISSUE THREAD

**Issue by 3453890470** [GregTechCEu/GregTechCEu-1.19#1120]
### Feature Description

Modify the oreprocessing gui to look like the following image
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/104831916/faa7b188-5dd9-4443-8b89-3940f75d5e98)
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/104831916/6e602631-6bbd-467d-9357-734ccf8a4f7f)

**Comment by xingluo01** [comment]
副产品=Secondary product
浸洗流体=Chemical Bath Fluid

**Comment by xingluo01** [comment]
I thought it would be a lot cleaner

**Comment by xingluo01** [comment]
![oreprocessing gui](https://github.com/GregTechCEu/GregTech-Modern/assets/104831916/eb3ff5d8-0980-4613-8a45-e3b38e62f174)

**Comment by xingluo01** [comment]
I think using Cauldron to clean dust and crushed ore doesn't need to be added to the oreprocessing gui.

**Comment by xingluo01** [comment]
The initial handling of ore in the old oreprocessing gui is incorrect. raw ore crushing output Only crushing ore without by-products, ore block crushing output will have by-products

**Comment by screret** [comment]
Why, though? What's so great about this layout?
Also the chart's first step only applies to ore blocks, I thought that that was pretty clear.

**Comment by screret** [comment]
It really isn't that much clearer either, IMO.

**Comment by 3453890470** [comment]
It'll look a little bit more straight and horizontal

**Comment by xingluo01** [comment]
> IMO，它真的也没有那么清楚。IMO，它真的也没有那么清楚。

It'll look a little bit more straight and horizontal
