### ISSUE TITLE
Introducing Gregtech6 style fission reactor

### ISSUE THREAD

**Issue by iijunxz** [GregTechCEu/GregTechCEu-1.19#1122]
### Feature Description

To be short: Fission reactors does not exist in GTM itself now, but it can be useful. Gregtech6's reactors are good. 
---
I wonder why there are no fission reactor in GTCEu and GTM...

Now, at least in my experiences, GTM's power generation has a great gap between burning fuels and plasma generators, which was bridged by fission reactors. So, fission reactors might be considerably meaningful.

In GT5, the fission reactor was provided by IC2, which is no longer the dependence of GregTechs now. As for GTCE, reactors were provided by Gregicality and so on. 

Since the GTCEu born, the reactors have been provided by external mods, such as the NuclearCraft, and its higher version alternative. However, they are still external, which demands massive modifications to embed them into Gregtech's process. 

Therefore, and because GTM is integrating contents from Gregicality, Gregtech6 and other mods, I think it might be reasonable to add fission reactors into GTM itself.

If intended to do so, introducing GT6-like reactors might be a good idea, because of their innovativeness and Gregtech origin. They are also interesting enough to be chosen.

**Comment by screret** [comment]
fission is planned for GTCEu.
