### ISSUE TITLE
add a setter for progress in recipelogic

### ISSUE THREAD

**Issue by gjmhmm8** [GregTechCEu/GregTechCEu-1.19#1123]
### Feature Description

add a setter for progress in recipelogic

**Comment by screret** [comment]
...and why can't you just do `getRecipeLogic().progress = value`?

**Comment by gjmhmm8** [comment]
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/73775469/85ffb6b9-a7f6-4fac-a805-8ed980e45b36)
How to do it，it is protected，no public

**Comment by screret** [comment]
oh wait, it is.
