### ISSUE TITLE
Parallel Control Hatch Bug

### ISSUE THREAD

**Issue by gjmhmm8** [GregTechCEu/GregTechCEu-1.19#1125]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-1.20.1-1.2.0.a-build_606

### Recipe Viewer Installed

None

### Environment

Singleplaye

### Cross-Mod Interaction

Yes

### Other Installed Mods

AE2 and so on

### Expected Behavior

.

### Actual Behavior

In a multi-block structure, when producing items with the same voltage as the machine, if the Parallel Control Hatch is set to more than 1, the machine will not operate properly.

### Steps to Reproduce

.

**Comment by screret** [comment]
1 I've been trying to test but haven't been able to encounter it in isolation.
2 is caused by us changing how the recipe modifiers are applied.

**Comment by gjmhmm8** [comment]
1 
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/73775469/0a0769f4-d81a-46da-9922-b85c7fea4e05)
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/73775469/144711ab-48db-4caf-a607-6169138f562e)
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/73775469/979db120-3733-44f3-bd2e-fdf3658d935d)
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/73775469/647a4be9-3a7c-45b5-9e7b-a6ece87a5304)
const gtr = event.recipes.gtceu
gtr.polarizer("kubejs:magnetic_netherite_rod")
        .itemInputs("kubejs:netherite_rod")
        .itemOutputs("kubejs:magnetic_netherite_rod")
        .EUt(GTValues.VA[GTValues.UHV])
        .duration(200)

**Comment by gjmhmm8** [comment]
If I put one item in at a time, it can be synthesized normally, but if the number of items put in at one time requires a level of processing that exceeds the voltage level, the processing cannot be done.

**Comment by gjmhmm8** [comment]
I hope that no matter how many parallel control cabins are adjusted, it can take the maximum value between the number of parallel control cabins and the maximum number that can be processed by the current voltage, and each time it will detect the maximum value that the current recipe can process, rather than only processing one portion no matter how much material is inside after I put one portion in at the beginning.

**Comment by gjmhmm8** [comment]
@screret

**Comment by gjmhmm8** [comment]
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/73775469/9e83d4af-a8c6-483a-8eac-d72829a95dee)
fix
