### ISSUE TITLE
Request: Color shifting iconset

### ISSUE THREAD

**Issue by DMNerd** [GregTechCEu/GregTechCEu-1.19#1128]
### Cross-mod Integration

Gaia ingot in Botania

### Feature Description

Colorshifting iconset would be great feature for modpack makers

**Comment by gjmhmm8** [comment]
you can make this by datapack

**Comment by DMNerd** [comment]
> you can make this by datapack

You would but having this as a part of the mod would be easier. 

Do you have an example datapack perchance?

**Comment by screret** [comment]
sure! [link](https://github.com/Argent-Matter/Galactic-Trade-Corporation/blob/main/kubejs/assets/gtceu/textures/item/material_sets/infinity/backround.png)
What I did was I made the ingot itself white and added the color in the iconset.
