### ISSUE TITLE
No recipe for facade covers

### ISSUE THREAD

**Issue by hron84** [GregTechCEu/GregTechCEu-1.19#1129]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.20.1-1.1.4

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

I use the modpack Sky Greg

### Expected Behavior

There is no recipe for facade covers and also the compass does not contain any info for them. Previously (in 1.12) IIRC it was craaftable with iron plate + any block but now... I dunno. Please add at least a recipe for them.

### Actual Behavior

N/A

### Steps to Reproduce

Check a recipe for facade covers

**Comment by screret** [comment]
recipes do exist. iron plate + any block.

**Comment by hron84** [comment]
In this specific version I cannot use this recipe, nor EMI lists it.
![2024-04-19_10 19 38](https://github.com/GregTechCEu/GregTech-Modern/assets/88636/396ef8fc-b057-4f2f-a14e-6c18b19880b2)
![2024-04-19_10 19 52](https://github.com/GregTechCEu/GregTech-Modern/assets/88636/e53f10bb-a811-4261-809b-0e41f518c257)

**Comment by screret** [comment]
oh that's weird, let me try

**Comment by screret** [comment]
hmm, try 4 iron plates?

**Comment by screret** [comment]
sorry, 3

**Comment by hron84** [comment]
Ahh, it works. Could you please at least add it to the "Compass"?
