### ISSUE TITLE
Crash when connecting boiler to steam machine

### ISSUE THREAD

**Issue by EmiPiplu** [GregTechCEu/GregTechCEu-1.19#113]
### GregTech CEu Version

1.0.3

### Recipe Viewer Installed

REI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Expected Behavior

Steam is transferred to the macerator from the boiler.
also the game not crashing.

### Actual Behavior

Game crashes, No steam transferred. 
On logging into the world again it will not crash unless the pipe is replaced

Setup Used
![image](https://github.com/GregTechCEu/GregTechCEu-1.19/assets/62481444/ab0cb1a1-c0fc-494a-b2cf-8a62e52dcc20)

### Steps to Reproduce

Place a steam boiler with an infinite water cover on and fill with fuel

Connect to a steam macerator with a pipe

Game crashes.

### Additional Information

Crash Report

[crash-2023-06-21_20.14.12-server.txt](https://github.com/GregTechCEu/GregTechCEu-1.19/files/11824002/crash-2023-06-21_20.14.12-server.txt)

latest.log

[latest.log](https://github.com/GregTechCEu/GregTechCEu-1.19/files/11824011/latest.log)

**Comment by screret** [comment]
damn that's an ancient issue
i guess we have to make a github release soon
