### ISSUE TITLE
Create a multiblock with parallel hatches, there is a chance of a crash upon startup

### ISSUE THREAD

**Issue by nutant233** [GregTechCEu/GregTechCEu-1.19#1135]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-1.20.1-1.2.0.a-build_606

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

KubeJS and so on

### Expected Behavior

Normal game launch.

### Actual Behavior

The game may crash upon startup.

### Steps to Reproduce

GTCEuStartupEvents.registry("gtceu:recipe_type", event => {event.create("plasma_condenser")
        .setEUIO("in")
        .setSlotOverlay(false, false, GuiTextures.SOLIDIFIER_OVERLAY)
        .setMaxIOSize(2, 2, 2, 2)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.COOLING)})
GTCEuStartupEvents.registry("gtceu:machine", event => {event.create("plasma_condenser", "multiblock")
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType("plasma_condenser")
        .recipeModifiers(GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.NON_PERFECT_OVERCLOCK))
        .appearanceBlock(GTBlocks.CASING_ALUMINIUM_FROSTPROOF)
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("       ", "       ", "  aaa  ", "  aaa  ", "  aaa  ", "       ", "       ")
            .aisle("       ", "  aaa  ", " aaaaa ", " aabaa ", " aaaaa ", "  aaa  ", "       ")
            .aisle("  aaa  ", " aaaaa ", "aabbbaa", "aabcbaa", "aabbbaa", " aaaaa ", "  aaa  ")
            .aisle("  aaa  ", " aabaa ", "aabcbaa", "abcccba", "aabcbaa", " aabaa ", "  aaa  ")
            .aisle("  aaa  ", " aaaaa ", "aabbbaa", "aabcbaa", "aabbbaa", " aaaaa ", "  aaa  ")
            .aisle("       ", "  aaa  ", " aaaaa ", " aabaa ", " aaaaa ", "  aaa  ", "       ")
            .aisle("       ", "       ", "  aaa  ", "  ada  ", "  aaa  ", "       ", "       ")
            .where("a", Predicates.blocks("gtceu:frostproof_machine_casing")
                .setMinGlobalLimited(120)
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1))
                .or(Predicates.autoAbilities(definition.getRecipeTypes()))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1)))
            .where("b", Predicates.blocks("kubejs:neutronium_pipe_casing"))
            .where("c", Predicates.blocks("kubejs:laser_cooling_casing"))
            .where("d", Predicates.controller(Predicates.blocks(definition.get())))
            .where(" ", Predicates.any())
            .build()
        )
        .workableCasingRenderer(
            "gtceu:block/casings/solid/machine_casing_frost_proof",
            "gtceu:block/multiblock/vacuum_freezer", false
        )})

### Additional Information

No response

**Comment by screret** [comment]
put the recipe modifiers in [].
like `.recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.NON_PERFECT_OVERCLOCK)])`
