### ISSUE TITLE
add more kubejs api

### ISSUE THREAD

**Issue by gjmhmm8** [GregTechCEu/GregTechCEu-1.19#1137]
### Feature Description

1. add IOpticalComputationProvider machine and   int requestCWUt(int cwut, boolean simulate)  int getMaxCWUt()  boolean canBridge()  call back
2. add  boolean input(RecipeCapability<?> cap,List<Content> content,boolean simulate) and boolean output(RecipeCapability<?> cap,List<Content> content,boolean simulate) in RecipeLogic

**Comment by screret** [comment]
for 1, any singleblock (even vanilla GT ones) can now technically use CWU.
for 2, I think either making an addon or just using a recipe is a better idea at that point.

**Comment by screret** [comment]
if you think otherwise, make a PR and I'll think harder about it
