### ISSUE TITLE
Generate double plates with flag GENERATE_PLATE or with a new tag

### ISSUE THREAD

**Issue by DMNerd** [GregTechCEu/GregTechCEu-1.19#1144]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

latest

### Recipe Viewer Installed

JEI

### Environment

singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Kubejs

### Expected Behavior

Generate plates flag should generate double plates

### Actual Behavior

it does not

### Steps to Reproduce

Set generate Plates flag and watch nothing happen

### Additional Information

If such flag exits it is wholy undocumented

**Comment by screret** [comment]
You need:
- an ingot
- `GENERATE_PLATE`
- NO `NO_SMASHING`

**Comment by DMNerd** [comment]
I dont have NO_SMASHING set. Double plates do not generate anyway

**Comment by DMNerd** [comment]
I found out with tinkering they generate only if no other flags are set but GENERATE_PLATE
