### ISSUE TITLE
ABS requires osmium wires

### ISSUE THREAD

**Issue by Caldar** [GregTechCEu/GregTechCEu-1.19#1145]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.20.a

### Recipe Viewer Installed

EMI

### Environment

Server

### Cross-Mod Interaction

No

### Other Installed Mods

Monifactory

### Expected Behavior

Being able to craft a ABS when it’s appropriate.

### Actual Behavior

ABS is part of mid game progression. It shouldn’t take wires that require LuV to craft.

### Steps to Reproduce

Try to build an ABS controller.

### Additional Information

I assume this is a bug on this end after the comment by screret in monifactory chat.

**Comment by Deepacat** [comment]
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/52133154/0f26ec5a-a044-49ba-90f4-45779f528850)
