### ISSUE TITLE
Recipes sometimes doesn't work because of tags in fluid input

### ISSUE THREAD

**Issue by 4dam3k** [GregTechCEu/GregTechCEu-1.19#1170]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.2.0.a

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Monifactory (1.20.1)
(Nuclearcraft included)

### Expected Behavior

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/66412368/98ed483d-487e-4e05-ac82-09c21a0a6b5d)
This

### Actual Behavior

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/66412368/6397447c-10ff-40b9-869e-8969c711e3e3)
Proper power is supplied
But the recipe does not work, this occurs frequently but not always, and rebooting the game fixes it (although not 100% always)
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/66412368/ad89e4c9-dbaf-4c04-a2ff-60793a7cc1bf)

### Steps to Reproduce

1. Use recipe with fluid tag in fluid input (tags are here because the nuclearcraft's fluids are also acceptable)
2. It will or will not work depending on mood of the game

**Comment by screret** [comment]
already fixed. try the latest github release.
