### ISSUE TITLE
kjs can't input item with nbt in recipe

### ISSUE THREAD

**Issue by gjmhmm8** [GregTechCEu/GregTechCEu-1.19#1171]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

build 615

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

dev

### Expected Behavior

.

### Actual Behavior

can‘t input item with nbt by kubejs

### Steps to Reproduce

.itemInputs(Item.of('gtceu:tempered_glass', "{RepairCost:0,display:{Name:'{\"text\":\"test\"}'}}"))

**Comment by screret** [comment]
what exactly is there to "fix" here?

**Comment by gjmhmm8** [comment]
> what exactly is there to "fix" here?

KubeJS is unable to add items with NBT data as materials.

**Comment by screret** [comment]
try doing `.strongNBT()` at the end?

**Comment by screret** [comment]
I believe that by default KubeJS ignores NBT inputs in recipes.
