### ISSUE TITLE
Tooltips from GregTech machines render behind EMI UI

### ISSUE THREAD

**Issue by esmenard** [GregTechCEu/GregTechCEu-1.19#1172]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.20.1-1.2.0.a build 621

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

EMI

### Expected Behavior

Tooltip from the "i" button on the top right of the machine's UI appears either in front of the EMI UI or to the left so it doesn't overlap

### Actual Behavior

Tooltip appears behind the EMI UI
![2024-04-29_22 49 53](https://github.com/GregTechCEu/GregTech-Modern/assets/53749130/afcc57bc-0733-4d05-a77a-3c0c4e78aef0)

### Steps to Reproduce

Right click on a GregTech machine and hover the mouse over the "i" button at the top right of the UI

### Additional Information

Depending on screen size it might happen only on certain GUI scales (screenshot was made with scale set to 3)

**Comment by Strubbelkopp** [comment]
Also an issue with JEI (1.21.1), so it seems to be a more general problem
![image](https://github.com/user-attachments/assets/9fd44765-67d3-4674-97bb-8111d8c410fb)

**Comment by Xefyr0** [comment]
Can confirm that it occurs on 1.20.1, even on GUI elements that are not specific to GTM
![2024-09-22_23 29 12](https://github.com/user-attachments/assets/49323a01-4389-4b31-a110-d8278b8d56b7)

**Comment by Phoupraw** [comment]
This bug has been there since at least last septempber, from 1.20 to 1.21.
