### ISSUE TITLE
Electric Blast Furnace does not accept more than two energy hatches

### ISSUE THREAD

**Issue by Rafaloko34** [GregTechCEu/GregTechCEu-1.19#1177]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.2.0a

### Recipe Viewer Installed

JEI

### Environment

Single Player

### Cross-Mod Interaction

Yes

### Other Installed Mods

A lot of mods

### Expected Behavior

The multiblock should accept more than 2 Energy hatches

### Actual Behavior

It does not accept more than 2

### Steps to Reproduce

build as normal but when put the 3rd energy hatch the multiblock wil not form

### Additional Information

This is a bad problem because you need the EBF for making aluminium for the MV Tier, impeding progression.

**Comment by screret** [comment]
You only need 2. Intended.
