### ISSUE TITLE
network switch crashes game

### ISSUE THREAD

**Issue by moosecrazy13** [GregTechCEu/GregTechCEu-1.19#1178]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.2.0a

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

ATM9

### Expected Behavior

Make the network switch mutli block and open up gui

### Actual Behavior

Make the network switch mutli block and try to open gui and crashes back to launcher

### Steps to Reproduce

Make network switch multi block and try to open gui and crashes

### Additional Information

Network switch has other issuses where it crashes if try to use it to hookup hpcas and use the research station and crashes game and makes it so cant load world unless you get rid of a file i world save folder for the optical pipe

**Comment by screret** [comment]
already fixed.
