### ISSUE TITLE
[Feature] Add  "current running recipe" to Jade (both multi and single blocks)

### ISSUE THREAD

**Issue by 4dam3k** [GregTechCEu/GregTechCEu-1.19#1185]
### Cross-mod Integration

Jade

### Feature Description

Add "current running recipe" details to jade

Multiblock:
Current:
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/66412368/b6d73dc6-7e73-4992-aae4-4be3f0f44d4e)
Example:
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/66412368/124d6a42-ecb5-4040-8b48-615e4d2d5ae3)

Single block machine
Current: (The recipe is stainless steel to stainless plates, the screenshot I took is showing the plate that was made but not yet exported to ae2, the feature request is to add "current running recipe")
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/66412368/9e46321c-64c9-4fb1-a431-45fb8cf4e2ad)
Example:
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/66412368/a3c8988b-5a79-4ebe-8054-d6ef2b217e2d)

**Comment by 4dam3k** [comment]
My paint and photoshop skills are damn fine

**Comment by ZHENGLOC** [comment]
maby you can use *[Monazite](https://modrinth.com/mod/monazite)* (1.20.1 only)

**Comment by 4dam3k** [comment]
> maby you can use _[Monazite](https://modrinth.com/mod/monazite)_ (1.20.1 only)

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/66412368/83d87c5b-503f-4475-9ee4-3f0690cb7f39)

Thats exactly what I was looking for, Thank you

**Comment by 4dam3k** [comment]
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/66412368/90d19cf4-0658-4da7-af37-08401cccb9bf)
