### ISSUE TITLE
Chunks don't stay loaded once everyone leaves the server

### ISSUE THREAD

**Issue by ZacharyCarey** [GregTechCEu/GregTechCEu-1.19#1186]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.1.4

### Recipe Viewer Installed

JEI

### Environment

Dedicated Server

### Cross-Mod Interaction

Yes

### Other Installed Mods

GregTech Community Pack Modern

### Expected Behavior

Claiming chunks using FTB Chunks should keep those chunks loaded at all times.

### Actual Behavior

Chunks claimed using FTB Chunks will always stay loaded as long as someone is logged into the server. Once all users are logged out of the server the claimed chunks no longer stay loaded, and all machines in those chunks stop running.

### Steps to Reproduce

1) Start and join dedicated server
2) Open FTB chunks and claim several chunks
3) Shift-click the chunks to set them as "force loaded"
4) Start smelting a stack of items in a furnace
5) Log out of the server
6) After some time has past, rejoin the server and note that no items were smelted

**Comment by 4dam3k** [comment]
Check this:
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/66412368/4ff0f3d9-59de-413b-9da5-c6bbd966f3fa)


I'm playing singleplayer so no way to check if that's a bug or just config setting

Config settings are in this purple cog

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/66412368/3f235dc5-ac6d-4f2f-91e6-840dc2a05b49)
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/66412368/334f00b9-7b01-4db1-96f3-ab7ef04fdf22)

**Comment by screret** [comment]
...and how is this a GTM issue?

**Comment by ZacharyCarey** [comment]
@4dam3k Thanks a ton! I was digging through the server config files but couldn't find any options related to this. Google searches were not helpful either, so at a certain point I just assumed a mod was conflicting or something.

**Comment by 4dam3k** [comment]
> @4dam3k Thanks a ton! I was digging through the server config files but couldn't find any options related to this. Google searches were not helpful either, so at a certain point I just assumed a mod was conflicting or something.

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/66412368/eeffd375-c2b2-4b52-8453-b74881aa6576)
