### ISSUE TITLE
Separating recipe removal of raw ore blocks from disableManualCompression.

### ISSUE THREAD

**Issue by ANZUARIAKE0127** [GregTechCEu/GregTechCEu-1.19#1193]
### Feature Description

Raw ore blocks do not have a significant impact on Gregtech progression, but they are useful for decoration and storage compression. Consider separating the raw ore block removal recipe from the disableManualCompression option.

**Comment by screret** [comment]
It's still compression and manual.

**Comment by screret** [comment]
> ...and storage compression.
exactly the reason that config exists, btw.
