### ISSUE TITLE
Tooltip newlines are broken

### ISSUE THREAD

**Issue by lonevox** [GregTechCEu/GregTechCEu-1.19#12]
### GregTech CEu Version

1.0.0

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Expected Behavior

The newlines are respected:
![image](https://user-images.githubusercontent.com/38600896/226764801-3f79b3af-4d58-4f10-8c78-889cd09ae1c8.png)

### Actual Behavior

Newlines are visible:
![image](https://user-images.githubusercontent.com/38600896/226764781-8908e8d1-95ef-471c-a992-e4fc8368c5a2.png)

### Steps to Reproduce

Hover over any GUI that has tooltips with newlines. Any single block machine will do.

### Additional Information

Firstly all the newlines in the lang files are using forward slash when they should be using backslash. Changing them to backslash only works on forge when the window is small enough that the text wraps and the newline is displayed correctly. Otherwise an lf character is displayed where the newline should be:
![2023-03-22_12 02 46](https://user-images.githubusercontent.com/38600896/226765463-da406a0e-9e3a-4021-bed8-31fc0490e0c0.png)
This is because forge adds wrapping for tooltips as this is not in the base game. Fabric has the [ToolTipFix](https://github.com/kyrptonaught/tooltipfix) mod which allows wrapping on newlines, but there doesn't seem to be an alternative for forge. To make it work for both forge and fabric I think the only way would be to split the lines in the lang file into multiple lines (this is what is recommended on the [Fabric wiki](https://fabricmc.net/wiki/tutorial:lang#adding_a_new_line)), like so:
Original:
```
provider.add("gtceu.gui.overclock.description", "Overclock Button/n§7Recipes can overclock up to the set tier");
```
New:
```
provider.add("gtceu.gui.overclock.description.1", "Overclock Button");
provider.add("gtceu.gui.overclock.description.2", "§7Recipes can overclock up to the set tier");
```
Then the location where the original tooltip was used also needs to be changed.
Original:
![image](https://user-images.githubusercontent.com/38600896/226766199-06ccdef1-36e6-4550-8503-a59c4522eecd.png)
New:
![image](https://user-images.githubusercontent.com/38600896/226766240-f154b0d6-0af6-4930-87e5-9c18f905181f.png)
This correctly displays the newline:
![image](https://user-images.githubusercontent.com/38600896/226767547-9cb3cbbf-476a-454a-bed3-10cfedc51d09.png)
I can make a PR with these changes for all tooltips if this is desired.

**Comment by Yefancy** [comment]
that would be appreciate. it is a big work. I'm not sure dan is going to deal with tooltips. @DStrand1

**Comment by DStrand1** [comment]
If you want to make a tooltip correcting these newline issues, feel free. I do plan to go over lang in the future, but I'd appreciate the help
