### ISSUE TITLE
Add DuraDisplay compat

### ISSUE THREAD

**Issue by 3453890470** [GregTechCEu/GregTechCEu-1.19#1208]
### Cross-mod Integration

DuraDisplay

### Feature Description

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/104831916/a02fb005-883e-4781-bd1b-5e5eed11aa7b)

**Comment by Leclowndu93150** [comment]
i'm too bad of a dev to add the compat myself, if you guys would add it, it would be nice
i know you won't do it for me because yk but do it for the people that want it

**Comment by screret** [comment]
Well, learn. I even gave you a hint on what you should do.

**Comment by screret** [comment]
But I sure as hell won't be the one to do it

**Comment by Leclowndu93150** [comment]
if you don't want my name in your code you can always pr to mine

**Comment by Leclowndu93150** [comment]
1.21 has it
