### ISSUE TITLE
Crash when placing wire next to active power generator?

### ISSUE THREAD

**Issue by 34486** [GregTechCEu/GregTechCEu-1.19#121]
### GregTech CEu Version

1.0.5_16

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

I expected wire to just be placed next to power generating source, such as steam turbine, basic combustion generator etc. 

### Actual Behavior

Game seized and crashed! 

### Steps to Reproduce

Put down a generator, see that you can hook up wires or place wires near and around it. Break the wires, fuel the generator, then try to place a wire next to it and it will crash right away before you attempt to hook it up with a wrench. 

### Additional Information

Related to pipe logic with previous issue..? #102  I will continue to try to do some more research on it along with the current pipe issue, (102 not solved yet unless I am using my complete ignorance to the best of my ignorance to miss everything in front of me plus more..?) 

Thank you!

EDIT: Might help to add crash log. 
[crash-2023-06-23_19.18.43-server.txt](https://github.com/GregTechCEu/GregTechCEu-1.19/files/11853811/crash-2023-06-23_19.18.43-server.txt)

EDIT2: Crash log with NOTHING but GT installed. 
[crash-2023-06-23_20.16.48-server.txt](https://github.com/GregTechCEu/GregTechCEu-1.19/files/11853950/crash-2023-06-23_20.16.48-server.txt)

**Comment by Yefancy** [comment]
thanks, my fault. 
fixed in the 68765f5
