### ISSUE TITLE
UHV+ field gen textures

### ISSUE THREAD

**Issue by ThePansmith** [GregTechCEu/GregTechCEu-1.19#1212]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

latest

### Recipe Viewer Installed

EMI

### Environment

SP

### Cross-Mod Interaction

No

### Other Installed Mods

N/A

### Expected Behavior

For all the fieldgens to have matching zedtech textures. 

100% me just being a nitpicking ghoul but someone has to do it :trollface:

### Actual Behavior

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/70342772/87cfa9db-6bc0-4e12-a6cd-b2bfff622d9f)

### Steps to Reproduce

N/A

**Comment by MOYINGCrystal** [comment]
![opv](https://github.com/GregTechCEu/GregTech-Modern/assets/26853616/32a30e10-4ae6-45a5-ab41-5d29dd4649bc)
And opv robot arm

**Comment by nutant233** [comment]
[field_generator.zip](https://github.com/GregTechCEu/GregTech-Modern/files/15262193/field_generator.zip)
