### ISSUE TITLE
The fluid hatch locking fix have a minor bug with EMI

### ISSUE THREAD

**Issue by 4dam3k** [GregTechCEu/GregTechCEu-1.19#1219]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.2.1-build_641

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Monifactory, but the cross-mod interaction is because of EMI

### Expected Behavior

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/66412368/2db018ef-b6cc-45e2-b8eb-1659ec04f4a7)

### Actual Behavior

You cannot lock fluid hatches directly from EMI, you have to pin the fluid that is either created or used in a recipe so that it have "1000mb" in it's tooltip
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/66412368/e823f9b7-4a14-43c2-89cd-8c4a1333570c)
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/66412368/5e1dd6a8-c671-4a8a-9bda-589cec1d4be0)

### Steps to Reproduce

1. place hatch
2. lock it using right side of EMI
3. cry
4. open random recipe with that fluid, pin the fluid
5. now it works

### Additional Information

At least the locking fix works, but still, that's a minor flaw

**Comment by screret** [comment]
I actually believe dragging fluids from any recipe viewer into ghost slots doesn't work...

**Comment by 4dam3k** [comment]
> I actually believe dragging fluids from any recipe viewer into ghost slots doesn't work...

As I highlighted in the bug report, atlesst in EMI, ypu can dragg fluid from it, but only of the fluid is pinned with some type of amount of it, and since fluids on the right side of emi does not have fluid amount it cannot be dragged

**Comment by YoungOnionMC** [comment]
works in 1.4.6
