### ISSUE TITLE
incompatible with connectedness

### ISSUE THREAD

**Issue by LENGBAI4775** [GregTechCEu/GregTechCEu-1.19#122]
crash my game when i add both
[minecraft-exported-logs-2023-06-24T12-38-23.log](https://github.com/GregTechCEu/GregTechCEu-1.19/files/11854530/minecraft-exported-logs-2023-06-24T12-38-23.log)

**Comment by LENGBAI4775** [comment]
version 1.0.5

**Comment by Yefancy** [comment]
full log and crash report please. 
also latest.log

**Comment by LENGBAI4775** [comment]
[latest.log](https://github.com/GregTechCEu/GregTechCEu-1.19/files/11915813/latest.log)

**Comment by LENGBAI4775** [comment]
> 请给我完整的日志和事故报告。也是最新的. log
[latest.log](https://github.com/GregTechCEu/GregTechCEu-1.19/files/11915953/latest.log)

**Comment by Yefancy** [comment]
```log
[19:24:57] [Render thread/WARN]: @Redirect conflict. Skipping gtceu-common.mixins.json:ModelBakeryMixin->@Redirect::gtceu$injectModelBakery(Lnet/minecraft/util/profiling/ProfilerFiller;Ljava/lang/String;)V with priority 999, already redirected by connectedness.mixins.json:ModelLoaderMixin->@Redirect::continuity$onFinishAddingModels(Lnet/minecraft/util/profiling/ProfilerFiller;Ljava/lang/String;Lnet/minecraft/server/packs/resources/ResourceManager;Lnet/minecraft/client/color/block/BlockColors;Lnet/minecraft/util/profiling/ProfilerFiller;I)V with priority 1000
```

Help me remember the problem when I work on it

modid: `continuity` 
reason: mixin `@Redirect` comflicts

**Comment by LENGBAI4775** [comment]
> ```
> [19:24:57] [Render thread/WARN]: @Redirect conflict. Skipping gtceu-common.mixins.json:ModelBakeryMixin->@Redirect::gtceu$injectModelBakery(Lnet/minecraft/util/profiling/ProfilerFiller;Ljava/lang/String;)V with priority 999, already redirected by connectedness.mixins.json:ModelLoaderMixin->@Redirect::continuity$onFinishAddingModels(Lnet/minecraft/util/profiling/ProfilerFiller;Ljava/lang/String;Lnet/minecraft/server/packs/resources/ResourceManager;Lnet/minecraft/client/color/block/BlockColors;Lnet/minecraft/util/profiling/ProfilerFiller;I)V with priority 1000
> ```
> 
> 当我解决问题时，帮我记住问题
> 
> modid:`continuity`原因:mixin`@Redirect`冲突

more info maybe...
[crash-2023-06-30_20.49.58-client.txt](https://github.com/GregTechCEu/GregTechCEu-1.19/files/11916416/crash-2023-06-30_20.49.58-client.txt)
