### ISSUE TITLE
[BUG] HPCA related multiblock machines, incorrect structure preview, direction reversed

### ISSUE THREAD

**Issue by DancingSnow0517** [GregTechCEu/GregTechCEu-1.19#1220]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.2.1

### Recipe Viewer Installed

EMI

### Environment

SP

### Cross-Mod Interaction

No

### Other Installed Mods

Jade

### Expected Behavior

The preview direction is correct

### Actual Behavior

place Network Swith Contoler preview Direction  is correct
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/60736156/b86fd89e-ad4f-4ef0-adf1-4acfc6d9c68a)

### Steps to Reproduce

place Network Swith Contoler, Empty hand shift right click
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/60736156/73315cfa-3941-4f3d-aff8-6ac7f4f3cd16)
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/60736156/d6f44ee5-a586-4ef7-9a67-6142b2d60e5a)
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/60736156/bf1c0e65-63fa-45ea-aa1f-7f47a3365ad9)

**Comment by YoungOnionMC** [comment]
fixed in #1468
