### ISSUE TITLE
Steam Oven cant smelt parallel recipes

### ISSUE THREAD

**Issue by alex256z** [GregTechCEu/GregTechCEu-1.19#1221]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.2.1

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

JEI

### Expected Behavior

Steam Oven must smelt up to 8 items from stack

### Actual Behavior

Steam Oven smelts only 1 item from stack

### Steps to Reproduce

Build steam oven, supply it with steam, throw in input 64 cobble.

### Additional Information

This bug appeared in 1.2.1, because in 1.2.0a steam oven works as intended.

**Comment by screret** [comment]
known & fixed.
