### ISSUE TITLE
Threated stick can't create in 1.2.1

### ISSUE THREAD

**Issue by Rybalchenko-Ruslan** [GregTechCEu/GregTechCEu-1.19#1225]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

Gregtech CEu version 1.2.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Reproduced on GregFactory Sky modpack

### Expected Behavior

2 threated wood planks produced 4 threated wood stick

### Actual Behavior

2 threated wood planks produced 4 stick

### Steps to Reproduce

open crafting interface and place 2 threated wook planks one upper one
Like this: 
X
X

**Comment by screret** [comment]
seems to work fine for me?

**Comment by Phoupraw** [comment]
Me, too.
