### ISSUE TITLE
Treated wood planks can craft Treated wood planks

### ISSUE THREAD

**Issue by Phoupraw** [GregTechCEu/GregTechCEu-1.19#1250]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.2.2.a

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

- ae2 15.2.1
- architectury 9.2.14
- badpackets 0.4.3
- balm 7.2.2
- bookshelf 20.1.10
- brightnessslider 1.0
- cloth_config 11.1.118
- collective 7.57
- craftingstation 1.20.1-1.1
- curios 5.9.0+1.20.1
- embeddium 0.3.18+mc1.20.1
\-- rubidium 0.7.1
- emi 1.1.4-SNAPSHOT+1.20.1+forge
- emi_loot 0.6.5+1.20.1+forge
- entityculling 1.6.2
- expatternprovider 1.20-1.1.6-forge
- fastbench 8.0.4
- fastfurnace 8.0.2
- fastsuite 5.0.1
- ferritecore 6.0.1
- forge 47.1.44
- forgeconfigscreens 8.0.2
- fpsreducer 1.20-2.5
- glodium 1.20-1.5-forge
- gtceu 1.2.2.a
|-- configuration 2.2.0
\-- ldlib 1.0.25.g
- gtmpa 0.7.5
- ingameime 1.0.6-1.20.1
- inventoryprofilesnext 1.10.10
- jade 11.8.0
- jei 15.3.0.4
- jeresources 1.4.0.238
- journeymap 5.9.21
- kotlinforforge 4.8.0
- kubejs 2001.6.4-build.138
- l2library 2.4.20
|-- l2screentracker 0.1.3
|-- l2tabs 0.1.5
\-- mixinextras 0.2.0-beta.8
- libipn 4.0.2
- libx 1.20.1-5.0.14
- mafglib 0.1.6-mc1.20.1
- mcpitanlib 2.2.4-1.20.1-forge
- merequester 1.20.1-1.1.4
- minecraft 1.20.1
- monazite 1.1.3
- mysterious_mountain_lib 1.4.5-1.20.1
- nckey 1.0.0
- placebo 8.6.0
- puzzleslib 8.1.19
\-- puzzlesaccessapi 8.0.7
- rapid_leaf_decay 2.0.2
- rhino 2001.2.2-build.18
- sethome 1.0.0
- sophisticatedbackpacks 3.20.5.1044
- sophisticatedcore 0.6.22.611
- stepitup 2.0.1-1.20.1
- supermartijn642configlib 1.1.8
- supermartijn642corelib 1.1.17
- tweakerge 0.1.3-mc1.20.1
- untranslateditems 1.20.1-1.7
- xray 1.20.1-2.18.1-build.22

### Expected Behavior

Treated wood planks shouldn't craft Treated wood planks.

### Actual Behavior

Treated wood planks can craft Treated wood planks.
![图片](https://github.com/GregTechCEu/GregTech-Modern/assets/50520903/80f56441-d989-4039-a086-265089b9fbdd)

### Steps to Reproduce

1. Get some treated wood planks and some other wood planks.
2. Craft treadted wood planks by JEI/REI/EMI auto filling.
3. Treated wood planks are consumed.

### Additional Information

Though, manually crafting can avoid this problem entirely, however, it would be fine if treated wood planks is excluded out of the ingredient, just like vanilla wool dying recipes.

**Comment by screret** [comment]
the GT treated wood planks aren't in the minecraft:planks tag by default, you or someone else has added it into there.

**Comment by Phoupraw** [comment]
I checked my kubejs and ensure that it doesn't modify tags. I didn't install datapack in my save. I am not sure if there is a mod modifying tags but I think there doesn't. Because #1225, I think it's a general bug.

**Comment by screret** [comment]
Nope. I've had 2 people confirm it works for them.
Check what tags treated wood planks have, please?

**Comment by Phoupraw** [comment]
Just `#minecraft:planks`
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/50520903/c7600a1d-f0ce-40b6-8464-f2642d7a3114)

**Comment by Phoupraw** [comment]
I tested with only EMI and GTM enabled, and treated wood planks is still in this tag.
