### ISSUE TITLE
Implosion compressor does not consume or require TNT

### ISSUE THREAD

**Issue by Wyrmlet** [GregTechCEu/GregTechCEu-1.19#1257]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.2.2.a

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Most recent gregtech community pack modern

### Expected Behavior

The implosion compressor consumes both gem dusts and TNT, producing gems as a result

### Actual Behavior

The implosion compressor only consumes gem dusts and produces gems, TNT is not required for operation.

### Steps to Reproduce

1. Try to make gems with dusts in the compressor
2. Be confused why the TNT is still in the input bus

### Additional Information

Also spotted [here](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/issues/313), so this does not seem to be directly related to any modpack in particular.

**Comment by screret** [comment]
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/68943070/d09ae6c1-16e7-4041-93a7-fb883335d9c2)
yes it does?
