### ISSUE TITLE
Unable to mine while charging from batteries.

### ISSUE THREAD

**Issue by CrossVas** [GregTechCEu/GregTechCEu-1.19#1261]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.20.1-1.2.2.a

### Recipe Viewer Installed

REI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

GregTech Community Pack Modern - 1.20.1

### Expected Behavior

Be able to mine while recharging. 

### Actual Behavior

Mining Tool just keeps triggering `reequip animation` while charging, resetting the break progress

### Steps to Reproduce

1. Get a drill
2. Get a battery
3. Switch battery to `Discharge Mode Enabled`
4. Mine something.

**Comment by YoungOnionMC** [comment]
this is a bug in forge, it will be fixed in 1.20.5/1.21 neoforge
