### ISSUE TITLE
Since 1.2.1+ crashes mod pack on loading

### ISSUE THREAD

**Issue by frizzle101101** [GregTechCEu/GregTechCEu-1.19#1264]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.2.1

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

All the mods 9 - 0.2.58

### Expected Behavior

load properly and not crash on mod loading

### Actual Behavior

crashes on mod loading

### Steps to Reproduce

1. get All the mods 9 - 0.2.58 on curse forge
2. allow content management
3. update gregtech to any 1.2.1+
4. observe crash on mod loading

### Additional Information

Version 1.2.0a works fine so some changes after that are causing the crash report attached

**Comment by frizzle101101** [comment]
[crash-2024-05-16_16.10.10-client.txt](https://github.com/GregTechCEu/GregTech-Modern/files/15340399/crash-2024-05-16_16.10.10-client.txt)

**Comment by screret** [comment]
gonna say this is ATM's fault, they have an issue in the advanced large chemical reactor code.

**Comment by frizzle101101** [comment]
that doesnt make much sense, isnt the advanced large chemical reactor apart of your mod

**Comment by YoungOnionMC** [comment]
No it's a part of atm9

**Comment by frizzle101101** [comment]
do you know what mod of theirs adds it?

**Comment by YoungOnionMC** [comment]
Its a kube script iirc

**Comment by YoungOnionMC** [comment]
https://github.com/AllTheMods/ATM-9/blob/main/kubejs/startup_scripts/gtceu/alcr.js

**Comment by frizzle101101** [comment]
by chance do you know what may need to change in that script? if not I can try to figure it out

**Comment by frizzle101101** [comment]
it seems they already had the fixed function call there for recipeModifiers commented out, I guess they know what to do when they update. 

I wonder how they knew what to change cuz working with kubejs script seems not very assisted unless I'm missing some dev environment to create those scripts, I just cant figure out what made the definition of that function different and how that commented out statments syntax works, or how is it better.
