### ISSUE TITLE
[Kube JS] Be able to request the ingredients for a recipie by providing a recipie id

### ISSUE THREAD

**Issue by zcarp7220** [GregTechCEu/GregTechCEu-1.19#1265]
### Cross-mod Integration

Kube JS

### Feature Description

I want to be able to put a recipe id ie. gtceu:shaped/electric_piston_lv and get the items used in it.

**Comment by screret** [comment]
this should be done on KubeJS's side, if anywhere.
also be more specific about what you want. is this in a recipe event? in a tick event?
