### ISSUE TITLE
Is planned a backport to 1.16.5?

### ISSUE THREAD

**Issue by ArnauGames** [GregTechCEu/GregTechCEu-1.19#127]
### Feature Description

I think that Gregtech will be grate with the mods with that version

**Comment by screret** [comment]
no

**Comment by NemEzanevem** [comment]
1.16.5 is already dropped as the LTS(Long Term Support) and probably even 1.18.2 will be droppes aswell if a lot of mods update like EnderIO

**Comment by Irgendwer01** [comment]
> 1.16.5 is already dropped as the LTS(Long Term Support) and probably even 1.18.2 will be droppes aswell if a lot of mods update like EnderIO

It isn't about it being dropped as we develop for 1.12 as well, it's more about what's the use to backport it
