### ISSUE TITLE
Recipe for glass/tempered glass not shown when using EMI

### ISSUE THREAD

**Issue by HandsomeAsianMan** [GregTechCEu/GregTechCEu-1.19#1272]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.2.2.a

### Recipe Viewer Installed

EMI

### Environment

1.2.2.a

### Cross-Mod Interaction

No

### Other Installed Mods

EMI

### Expected Behavior

Use glass block in recipe

### Actual Behavior

Uses no input

### Steps to Reproduce

Just try to craft tempered glass?

### Additional Information

![Screenshot 2024-05-17 181953](https://github.com/GregTechCEu/GregTech-Modern/assets/160423885/50a81280-62e5-4a6a-ba05-b9b092d45e32)
![Screenshot 2024-05-17 181943](https://github.com/GregTechCEu/GregTech-Modern/assets/160423885/93fe20ea-3bd7-4a06-b50a-2786e1b99b97)
![Screenshot 2024-05-17 181844](https://github.com/GregTechCEu/GregTech-Modern/assets/160423885/5e024518-5474-42ce-8bf2-345e2f91810d)
![Screenshot 2024-05-17 181728](https://github.com/GregTechCEu/GregTech-Modern/assets/160423885/3345ad1c-8228-4e84-9e40-50010a95f885)
![Screenshot 2024-05-17 180648](https://github.com/GregTechCEu/GregTech-Modern/assets/160423885/a4bdb018-a5c2-4e47-8021-3ad8dc92821a)

**Comment by screret** [comment]
recipe viewer issue.

**Comment by screret** [comment]
as in, our fault, but an error in our EMI integration

**Comment by screret** [comment]
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/68943070/3abf30df-0799-4e9e-bf6f-aa74ddd11fd7)
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/68943070/a38a246a-6267-46e8-9e1c-20bd3bd39120)
appears to be working perfectly for us in development on latest EMI. mod conflict.

**Comment by HandsomeAsianMan** [comment]
I tested this with just EMI and GT tho. Tho that was a week ago or smth

**Comment by HandsomeAsianMan** [comment]
![Screenshot 2024-05-27 131736](https://github.com/GregTechCEu/GregTech-Modern/assets/160423885/dfdb3bf7-1b9e-4238-8d68-0df668e5622a)
![Screenshot 2024-05-27 131756](https://github.com/GregTechCEu/GregTech-Modern/assets/160423885/8a7defb1-41dc-47d6-9292-53322c163a28)
![Screenshot 2024-05-27 131715](https://github.com/GregTechCEu/GregTech-Modern/assets/160423885/cf11f357-b2a7-4d7b-9cd6-fe6cb85b6a7d)

  Fresh install

**Comment by screret** [comment]
what LDLib version?

**Comment by HandsomeAsianMan** [comment]
1.0.25.j

**Comment by screret** [comment]
ok turns out my testing is on an older EMI version, let me test on the latest one

**Comment by screret** [comment]
can confirm on latest EMI.

**Comment by screret** [comment]
***NOT*** a GT issue, see https://github.com/emilyploszaj/emi/issues/534.
