### ISSUE TITLE
Crash While Createing a new world

### ISSUE THREAD

**Issue by hkyzyh** [GregTechCEu/GregTechCEu-1.19#1277]
### Checked for existing issues

- [ ] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.2.2a

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

AE2 GT-- EMI Jade EnderIO KubeJS Crafttweaker...

### Expected Behavior

I Opened a new game in curseforge launcher ,then i click the"singleplayer" button, at last ,It Crashed.

### Actual Behavior

Just Crash.

### Steps to Reproduce

1:enter a new game
2:Click The 'singleplayer' button
3:Crash

### Additional Information

CrashReport:  https://mclo.gs/Z6DPIzN

**Comment by screret** [comment]
GTNN error.

**Comment by hkyzyh** [comment]
thx
