### ISSUE TITLE
ME Buses and Hatches are not functioning correctly

### ISSUE THREAD

**Issue by YiRanMushroom** [GregTechCEu/GregTechCEu-1.19#1281]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.2.2.a-build_688

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

AE2

### Expected Behavior

Place and connect the buses and hatches to a network with sufficient channels, expected it to function normally.

### Actual Behavior

The output bus and hatch are sometimes offline, and sometimes the recipe cannot start, or the output buses and hatches voids items and fluids. The me input buses and hatches are also voiding fluids when the recipe starts (i.e. the recipe starts but there is no produsts), or the recipes cannot start when providing with enough ingredients in it.

### Steps to Reproduce

As I mentioned above.

### Additional Information

The network logic itself is very buggy, sometimes the cable cannot even connect the buses and hatches, especially after rotating using a wrench.

**Comment by screret** [comment]
yup, correct, they're buggy as fuck.
they should:tm: connect after they have contents though. at least sometimes.

**Comment by YiRanMushroom** [comment]
And also, I don't know if this is intended. The recipes cannot start when the output bus and hatch are offline, which means that the recipe will never start when only ME output bus and hatch are provided. So I don't know how could they "have contents".

**Comment by YiRanMushroom** [comment]
It seems like it's another bug cause the recipe not starting, not because of this one, the ME output bus and hatch can indeed work correctly, although it's said that the device is offline.

**Comment by YiRanMushroom** [comment]
I don't think they should be used though, all the me parts are extremely buggy, cannot start recipe, and often voids products and ingredients.
