### ISSUE TITLE
[Bug?] When electronic tools run out their durability, the tool breaks up without returning any power unit

### ISSUE THREAD

**Issue by chemlzh** [GregTechCEu/GregTechCEu-1.19#1283]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.2.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

Terrafirmagreg 0.7.8 (GTM manually upgraded from 1.2.0.a to 1.2.1)

### Expected Behavior

In GTCEu (1.12.2), when a electronic tool ran out of its durability, it returns a energy unit with the same charge. If these features have not been changed in 1.20.1, electronic tools should not directly break up.

### Actual Behavior

When I use a electronic chainsaw with <1% durability to cut down a tree, it just totally broke up, and nothing returned to me (except for logs).

### Steps to Reproduce

Use a electronic chainsaw with low durability to cut down trees, until the durability used up.

**Comment by screret** [comment]
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/68943070/5a95b208-bb43-41dd-919b-15b4ea9c4215)
working for me, you might have something stopping the break event before GT gets to it?

**Comment by chemlzh** [comment]
> ![image](https://private-user-images.githubusercontent.com/68943070/331981637-5a95b208-bb43-41dd-919b-15b4ea9c4215.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMTYyMTAsIm5iZiI6MTcxNjIxNTkxMCwicGF0aCI6Ii82ODk0MzA3MC8zMzE5ODE2MzctNWE5NWIyMDgtYmI0My00MWRkLTkxOWItMTViNGVhOWM0MjE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE0MzgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1M2RlZjYyMWY5YzdjOGQ2Yjk1NTVjZDNlNTBkYmQxMzQ3Y2FhM2EyYTJkZmQ2MDA4YTlmMWQ3MzE4YzJhMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bs6Jn3n367kCYAVZhoEaxfSFxQ-VcGHiRHZfWSm5i2I) working for me, you might have something stopping the break event before GT gets to it?

Another strange thing is that when GT chainsaw is used for cutting down TFC trees, its charge is not reduced, but only the durability is consumed. I remember your group has pushed a fix, but this fix has not been adopted. (This commit does not belong to any branch on this repository) See https://github.com/GregTechCEu/GregTech-Modern/commit/422395cc632d8f2803c50e11e1cf5f94ece1ad2e

**Comment by chemlzh** [comment]
> ![image](https://private-user-images.githubusercontent.com/68943070/331981637-5a95b208-bb43-41dd-919b-15b4ea9c4215.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMTYyMTAsIm5iZiI6MTcxNjIxNTkxMCwicGF0aCI6Ii82ODk0MzA3MC8zMzE5ODE2MzctNWE5NWIyMDgtYmI0My00MWRkLTkxOWItMTViNGVhOWM0MjE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE0MzgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1M2RlZjYyMWY5YzdjOGQ2Yjk1NTVjZDNlNTBkYmQxMzQ3Y2FhM2EyYTJkZmQ2MDA4YTlmMWQ3MzE4YzJhMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bs6Jn3n367kCYAVZhoEaxfSFxQ-VcGHiRHZfWSm5i2I) working for me, you might have something stopping the break event before GT gets to it?

I remember in TFG 0.7.8, a mod called Panda's Falling Tree's is introduced, which makes every tree fall like trees from [Dynamic trees](https://www.curseforge.com/minecraft/mc-mods/dynamictrees). Does it matter? @screret

**Comment by screret** [comment]
> Another strange thing is that when GT chainsaw is used for cutting down TFC trees, its charge is not reduced, but only the durability is consumed. I remember your group has pushed a fix, but this fix has not been adopted. (This commit does not belong to any branch on this repository) See [422395c](https://github.com/GregTechCEu/GregTech-Modern/commit/422395cc632d8f2803c50e11e1cf5f94ece1ad2e)

that one's just not yet in a release

**Comment by chemlzh** [comment]
> > Another strange thing is that when GT chainsaw is used for cutting down TFC trees, its charge is not reduced, but only the durability is consumed. I remember your group has pushed a fix, but this fix has not been adopted. (This commit does not belong to any branch on this repository) See [422395c](https://github.com/GregTechCEu/GregTech-Modern/commit/422395cc632d8f2803c50e11e1cf5f94ece1ad2e)
> 
> that one's just not yet in a release

So I'm curious about the reason why this fix hasn't been released yet. Does this fix cause more bugs?

**Comment by screret** [comment]
well we just haven't released yet. because there were more bugs to fix. that's literally it.

**Comment by chemlzh** [comment]
> well we just haven't released yet. because there were more bugs to fix. that's literally it.

OK thx. I'm glad that at least it has a fix.
