### ISSUE TITLE
Cannot drag to filters/temp slots from recipe viewer

### ISSUE THREAD

**Issue by Deepacat** [GregTechCEu/GregTechCEu-1.19#1287]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.2.2

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/52133154/f3d6668c-ef27-4b9b-9e64-0092c994bf56)

### Expected Behavior

Items/fluids dragged to filters and probably creative fluid/chests appear in them

### Actual Behavior

the dragged objects do not apply to the filter

### Steps to Reproduce

Drag item into filter
item does not appear in filter

### Additional Information

Happens with JEI and EMI
With JEI it shows the green line for dragging but still doesnt put in
Tested 1.2.0 to current git release

**Comment by YoungOnionMC** [comment]
fixed in #1973
