### ISSUE TITLE
Server crashes after exiting machine GUI

### ISSUE THREAD

**Issue by NangNJ** [GregTechCEu/GregTechCEu-1.19#1294]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.20.1-1.2.2a

### Recipe Viewer Installed

None

### Environment

Server

### Cross-Mod Interaction

Yes

### Other Installed Mods

![sad](https://github.com/GregTechCEu/GregTech-Modern/assets/170600696/f23712f2-8b77-4049-8c06-603f17d4fd25)
![sad1](https://github.com/GregTechCEu/GregTech-Modern/assets/170600696/c388612b-2aba-4d78-97ba-bd12a11dfea5)

### Expected Behavior

no problem

### Actual Behavior

The server will crash if you exit the gui after opening the machine gui.

### Steps to Reproduce

i opened machine gui

### Additional Information

crash-report:https://mclo.gs/9LHknDY,
hope u slove the problem early,thank u

**Comment by screret** [comment]
don't use archlight. or any hybrid server.

**Comment by NangNJ** [comment]
？
