### ISSUE TITLE
Dense Obsidian plates cannot be crafted

### ISSUE THREAD

**Issue by JuiceyBeans** [GregTechCEu/GregTechCEu-1.19#1296]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.2.2.a

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

JEI

### Expected Behavior

Dense obsidian plates should be able to be crafted using a bender

### Actual Behavior

No recipes found

### Steps to Reproduce

1. Press R or left click on dense obsidian plate in JEI

**Comment by NicholasBaldwinSE** [comment]
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/136097593/a481c28c-6211-480e-84dd-fe2db4be014a)

Recipe appears in dev in JEI and is craftable, so if it wasn't beforehand it will likely show up with the release of 2.2.3a
