### ISSUE TITLE
Steam Oven broken again

### ISSUE THREAD

**Issue by alex256z** [GregTechCEu/GregTechCEu-1.19#1311]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.2.3

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

JEI

### Expected Behavior

Steam Oven should smelt 8 items in parallel

### Actual Behavior

Steam Oven smelting by 1 item

### Steps to Reproduce

Put 8 items into steam oven

**Comment by screret** [comment]
I tested the damn thing wtf

**Comment by alex256z** [comment]
Thanks for fixing!😻 I really need this useful damn thing. 👍
