### ISSUE TITLE
Cant create powered rail

### ISSUE THREAD

**Issue by AcidSoap** [GregTechCEu/GregTechCEu-1.19#1312]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.2.3

### Recipe Viewer Installed

JEI

### Environment

singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

GREG tech community edition modern pack

### Expected Behavior

powered rail

### Actual Behavior

redstone torch

### Steps to Reproduce

1. Place any assembler and give them power
2. Set circuit for mode 1
3. Place materials (First 12 gold rods then 1 stick and 1 redstone)
4. Instead rails u will get redstone torch

**Comment by YoungOnionMC** [comment]
Fixed in #1345
