### ISSUE TITLE
"Overfilling" barrel or drum voids fluid.

### ISSUE THREAD

**Issue by 34486** [GregTechCEu/GregTechCEu-1.19#132]
### GregTech CEu Version

1.0.5_26

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

Fluid not to be voided, filling of fluid to be rejected and nothing occurs. 

### Actual Behavior

Fluid voids. 

### Steps to Reproduce

Get a barrel or drum and drain it by a fraction of a bucket, say it holds 32 buckets of lava and you took out .5 buckets of lava and you go to put another bucket of lava into it, the entire bucket you just tried to put in it is voided unless one full or more buckets can fit into it. :'""""(

### Additional Information

I can't seem to prove or disprove the same thing occurs while something is pushing fluids or power into something else, can that somehow be tested?

**Comment by Yefancy** [comment]
vid?

**Comment by 34486** [comment]
https://drive.google.com/file/d/1lq6nITmiCGpanCg7qMXUTGGN6A7C4qPV/view?usp=sharing
