### ISSUE TITLE
Could not Change the Configuration of Programmed Circuit in MultiPlayer

### ISSUE THREAD

**Issue by UraraChiya** [GregTechCEu/GregTechCEu-1.19#133]
### GregTech CEu Version

1.0.5-build_23

### Recipe Viewer Installed

REI

### Environment

Dedicated Server

### Cross-Mod Interaction

No

### Expected Behavior

Could change the Configuration of Programmed Circuit in GUI of machine.

### Actual Behavior

Could not change the Configuration.

### Steps to Reproduce

![Programmed Circuit](https://github.com/GregTechCEu/GregTechCEu-1.19/assets/47343409/fce486e0-8792-43a0-a478-01c8ab203121)

### Additional Information

When I change the Configuration, the server has a log:
`[296月2023 14:06:16.039] [Server thread/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER`

Mod Lists:
```
architectury-6.5.85-forge.jar
cloth-config-8.2.88-forge.jar
gtceu-forge-1.19.2-1.0.5-build_23.jar
Mekanism-1.19.2-10.3.8.477.jar
REIPluginCompatibilities-forge-9.0.48.jar
RoughlyEnoughItems-9.1.619.jar
```

**Comment by Drackion** [comment]
try updating to the latest release
https://github.com/GregTechCEu/GregTechCEu-1.19/releases/tag/1.0.5-build_26

**Comment by UraraChiya** [comment]
> 尝试更新到最新版本 https://github.com/GregTechCEu/GregTechCEu-1.19/releases/tag/1.0.5-build_26

I also want to use the latest version, but like my other [issue](https://github.com/GregTechCEu/GregTechCEu-1.19/issues/128), the new version can't run on the server.

**Comment by Drackion** [comment]
looks like just need to wait for the maintance branch to get merged as it has the fixes in it for your other issue

**Comment by UraraChiya** [comment]
I tested the build of the [sc-maintenance](https://github.com/GregTechCEu/GregTechCEu-1.19/tree/sc-maintenance), the server can startup, but still can't change the Configuration of Programmed Circuit.

**Comment by Yefancy** [comment]
itis a bug from ldlib that breaks all GUI behavior and I cant believe that i just found it today
