### ISSUE TITLE
Bedrock vein crash

### ISSUE THREAD

**Issue by Deepacat** [GregTechCEu/GregTechCEu-1.19#1339]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.2.3.a-build_716

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

in crashlog

### Expected Behavior

Server is reloaded without pause causing a crash with bedrock veins

### Actual Behavior

After a server reload a crash occurs when pausing the game related to bedrock veins

### Steps to Reproduce

Have a script add bedrock veins
Load a world
? Use a prospector on bedrock vein mode
Reload the server
Pause game

### Additional Information

[crash-2024-05-27_17.52.45-server.txt](https://github.com/GregTechCEu/GregTech-Modern/files/15462242/crash-2024-05-27_17.52.45-server.txt)

**Comment by Deepacat** [comment]
After more testing it seems related to prospectors

**Comment by YoungOnionMC** [comment]
This still happens?
