### ISSUE TITLE
Alternative Hazard Config Option

### ISSUE THREAD

**Issue by ThePansmith** [GregTechCEu/GregTechCEu-1.19#1342]
### Feature Description

Currently, holding certain dusts will cause the player to be poisoned, as the tooltip states they are poisonous when inhaled. In gameplay, this proves to be annoying as having said item for even a second will cause you to get debuffed with 15 seconds of poison.

An alternative config option would be to instead have the player "hold their breath" (decreasing the air meter) when said items are held, and take damage as normal when air runs out. This would still prevent players from running around with said dusts in their inventory, but would be much less annoying to deal with.

**Comment by screret** [comment]
have you even looked at the recent dev versions we already fixed this issue
