### ISSUE TITLE
Early game hazardous material handling

### ISSUE THREAD

**Issue by Wyrmlet** [GregTechCEu/GregTechCEu-1.19#1347]
### Feature Description

Some of the hazardous materials are needed before MV (like lead), but there is no way to counteract the negative effects until you can make PVC. A workaround is using a portable inventory like a backpack, but there should probably be some kind of way of doing this without extra mods.

**Comment by screret** [comment]
this has been added after the latest release.

**Comment by WaterMelwin** [comment]
ok so what is it
