### ISSUE TITLE
Macerators no longer process *Vanilla* Deepslate Ore

### ISSUE THREAD

**Issue by Tiln1** [GregTechCEu/GregTechCEu-1.19#1353]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.2.3a

### Recipe Viewer Installed

JEI

### Environment

Dedicated Server

### Cross-Mod Interaction

No

### Other Installed Mods

ATM9

### Expected Behavior

The Ore gets processed into the crushed version (+side products)

### Actual Behavior

The ore sits there not being processed

### Steps to Reproduce

Put a vanilla Deepslate Ore into an otherwise working Macerator and watch it not get processed

### Additional Information

It processed them in 1.2.2a.
Other vanilla ore is still processed.
Tested on a big macerator that is successfully processing other stuff and a small Elite II macerator that is successfully processing other stuff.
Tested with Redstone, Diamond, Gold, Iron, Copper, which should be sufficient to say the other 3 fail, too.
The Forge Hammer still processes them successfully.
The macerator handles GregTech Deepslate ores fine, but I don't have the GregTech versions of these vanilla ores to test.

**Comment by screret** [comment]
still happens?

**Comment by Tiln1** [comment]
Well there hasn't been any GregTech updates, but I did check just for you, and yea, of course it still happens.

**Comment by screret** [comment]
...I meant on the latest github version

**Comment by Tiln1** [comment]
I do not know how to build Minecraft mods from source code :L

I'm sure I could spend a couple hours figuring it out, but can't say I feel like doing that

**Comment by screret** [comment]
https://github.com/GregTechCEu/GregTech-Modern/releases/tag/1.20.1-1.2.3.a-build_753

**Comment by screret** [comment]
I said "github version" because we release a build after each and every merge.

**Comment by Pumpkin7266** [comment]
I think this can be closed but I'll check later

**Comment by Pumpkin7266** [comment]
Can confirm still bugged as of 1.4.0.
Just tested on a instance of just Gregtech+Ldlib+Jei
It does show the recipe on JEI but doesn't process idk why

**Comment by MatthiasMann** [comment]
Not sure if it's related - but I'm on gtceu-1.20.1-1.4.0-build_1035-SNAPSHOT and I can't get either the LV macerator or the low pressure steam macerator to process either end iron ore, end sphalerite ore or normal sphalerite ore.

According to JEI it says it's an ULV recipe using 2 EU/t.

**Comment by YoungOnionMC** [comment]
> Not sure if it's related - but I'm on gtceu-1.20.1-1.4.0-build_1035-SNAPSHOT and I can't get either the LV macerator or the low pressure steam macerator to process either end iron ore, end sphalerite ore or normal sphalerite ore.
> 
> According to JEI it says it's an ULV recipe using 2 EU/t.

yea this hasnt been fixed just quite yet

**Comment by YoungOnionMC** [comment]
fixed in #1910
