### ISSUE TITLE
Mallets seem to all have the same durability

### ISSUE THREAD

**Issue by InfamousSonDR** [GregTechCEu/GregTechCEu-1.19#1355]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.2.3.a

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

Nothing

### Expected Behavior

Mallets created with more expensive rubbers should have higher durability

### Actual Behavior

They all have only 128 durability and 128 crafting uses

### Steps to Reproduce

Run Gregtech Modern and look at the mallets durability

**Comment by YoungOnionMC** [comment]
fixed in #1468
