### ISSUE TITLE
Cobalt Oxide is part of Cobalt's byproduct list even though it doesnt have an ore property

### ISSUE THREAD

**Issue by YoungOnionMC** [GregTechCEu/GregTechCEu-1.19#1359]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.2.3a

### Recipe Viewer Installed

JEI

### Environment

Dev

### Cross-Mod Interaction

No

### Other Installed Mods

N/A

### Expected Behavior

Some sort of material checks for ore recipe handler

### Actual Behavior

It miraculously works cause it only checks for dust tag prefix which cobalt oxide has

### Steps to Reproduce

Run the game

**Comment by screret** [comment]
Onion this is the expected brhaviour of that

**Comment by YoungOnionMC** [comment]
Ghost tried using material.orebyproduct[0] as crushed form and it failed, it should make sense that all materials in the ore byproduct list has the ore property and not just dust property.

**Comment by screret** [comment]
Well, no not really
We use them as dusts only so why should it require an ore form?

**Comment by screret** [comment]
Anyone using them otherwise can do the additional checks required IMO

**Comment by YoungOnionMC** [comment]
Cobalt oxide is the only material that fails this check every other vanilla materials have the ore property
