### ISSUE TITLE
The use of a client class in the server side has caused the server to fail to start.

### ISSUE THREAD

**Issue by nutant233** [GregTechCEu/GregTechCEu-1.19#1374]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.2.3.a-build_741

### Recipe Viewer Installed

None

### Environment

Dedicated Serve

### Cross-Mod Interaction

Yes

### Other Installed Mods

None

### Expected Behavior

Server successfully started.

### Actual Behavior

Server cannot start.

### Steps to Reproduce

[latest.log](https://github.com/user-attachments/files/15566293/latest.log)

**Comment by screret** [comment]
already fixed, grab a build from https://github.com/GregTechCEu/GregTech-Modern/actions/runs/9362971857?pr=1372
