### ISSUE TITLE
Multiplayer server cannot be accessed.

### ISSUE THREAD

**Issue by nutant233** [GregTechCEu/GregTechCEu-1.19#1377]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-1.20.1-1.2.3.a-build_486

### Recipe Viewer Installed

None

### Environment

Dedicated Server

### Cross-Mod Interaction

No

### Other Installed Mods

None

### Expected Behavior

Accessed the server

### Actual Behavior

<img width="854" alt="image" src="https://github.com/GregTechCEu/GregTech-Modern/assets/65939836/07e40cc7-a17a-423b-9d81-5b67498c384e">

### Steps to Reproduce

Accessed a server that only has GTM.

**Comment by WhitePhant0m** [comment]
I have the same issue on 1.2.3a-build_751, both server and client only have GTM.

https://mclo.gs/KF5suG2 - Client log
https://mclo.gs/tfAvmFK - Server log

**Comment by screret** [comment]
> I have the same issue on 1.2.3a-build_751, both server and client only have GTM.
> 
> https://mclo.gs/KF5suG2 - Client log https://mclo.gs/tfAvmFK - Server log

1. not the same issue
2. neither of those logs contain any errors?

**Comment by screret** [comment]
wait hm, might be the same issue

**Comment by WhitePhant0m** [comment]
It's the same, I get the same error message when it boots me out.
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/33400200/f492f2e1-0d8b-4392-866c-3f72abe34b5b)
But nothing in logs.

**Comment by screret** [comment]
Just tested it myself on the latest github version setup and couldn't replicate.
could you test on forge 47.1.3?

**Comment by WhitePhant0m** [comment]
Same result.

**Comment by forteen14desu** [comment]
![error](https://github.com/GregTechCEu/GregTech-Modern/assets/107360311/4b02f499-505f-46f5-8440-fadd26117117)
Test using 1.2.3.a-build_751, forge 47.3.1 and 47.1.3 both have the same problem.
Client and server full debug log (too long to mclo.gs)
https://drive.google.com/drive/folders/1CjItkjfd2LODlWOebTKTMJXnuR6qf41I?usp=sharing

**Comment by liansishen** [comment]
I have tested and find this issue was caused by this commit https://github.com/GregTechCEu/GregTech-Modern/pull/1348
I commented the code in function[onPlayerJoinServer]  and then I can join the server.

**Comment by screret** [comment]
> Test using 1.2.3.a-build_751, forge 47.3.1 and 47.1.3 both have the same problem. Client and server full debug log (too long to mclo.gs) https://drive.google.com/drive/folders/1CjItkjfd2LODlWOebTKTMJXnuR6qf41I?usp=sharing

could you also add this to your java arguments on the client: `-Dforge.logging.mojang.level=DEBUG`?

**Comment by forteen14desu** [comment]
> > Test using 1.2.3.a-build_751, forge 47.3.1 and 47.1.3 both have the same problem. Client and server full debug log (too long to mclo.gs) https://drive.google.com/drive/folders/1CjItkjfd2LODlWOebTKTMJXnuR6qf41I?usp=sharing
> 
> could you also add this to your java arguments on the client: `-Dforge.logging.mojang.level=DEBUG`?

new one https://drive.google.com/file/d/1sRHLP9tSkNmWZ3RmL4YXsevovEm4LqGA/view?usp=sharing
