### ISSUE TITLE
Change "L/t" to "mb/t" to reduce confusion

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [GregTechCEu/GregTechCEu-1.19#1378]
### Feature Description

The mod shouldn't specialize itself by using "Liter/tick" (from here on out as "L/t"). It's highly confusing and causes more issues than necessary.

Change the nomen-clature from "L/t" to "mb/t" to keep in line with the last 10 years of modded nomenclature. Or at-least provide a setting to change it from "L/t" to "mb/t".

This is also highly inconsistent as "Liter" in the realworld is 1000 milliliter (in-game as millibuckets as 1 Bucket = 1 L).
The tanks also use Buckets (or millibuckets in recipes). Thus being highly confusing for no other reason than the sake of it being that way.

This issue is also very easily fixable and has no backlash and it would make it easier for newer players to gregtech to understand the various units of measurement in-game.

**Comment by theMegaTech** [comment]
> This is also highly inconsistent as "Liter" in the realworld is 1000 milliliter (in-game as millibuckets as 1 Bucket = 1 L). The tanks also use Buckets (or millibuckets in recipes). Thus being highly confusing for no other reason than the sake of it being that way.

That point specifically makes no real sense. 1 Bucket is NOT 1 Liter, it's 1000L, because 1 block of liquid is equal to 1 cubic metre of liquid (we do know from vanilla advancements that 1 block is in fact 1 meter long/tall/high). So, no, current system makes total sense. 1L is exactly 1/1000 of 1m3 of liquid.

**Comment by 3x1t-5tyl3** [comment]
> > This is also highly inconsistent as "Liter" in the realworld is 1000 milliliter (in-game as millibuckets as 1 Bucket = 1 L). The tanks also use Buckets (or millibuckets in recipes). Thus being highly confusing for no other reason than the sake of it being that way.
> 
> That point specifically makes no real sense. 1 Bucket is NOT 1 Liter, it's 1000L, because 1 block of liquid is equal to 1 cubic metre of liquid (we do know from vanilla advancements that 1 block is in fact 1 meter long/tall/high). So, no, current system makes total sense. 1L is exactly 1/1000 of 1m3 of liquid.

i guess I can't argue that. However the "liter" still makes no sense here as pretty much all other mods (except greg) use mb. This alone should be reason enough to switch to mb. Together with the fact that greg itself uses mb in storage tanks anyhow..

EDIT: For all I give a shit. You can make a mod that changes all other mods to L/t instead, but that's just as silly as only 1 mod having their own silly measurement system. At-least power in gregtech is it's own system with amperage. But the fluids are
A: Inconsistent as mentioned above storage tank still uses mb.
B: Pretty much all other mods with exception of gregtech and maybe some lesser known mods with <100 Downloads use a different type than mb/buckets
C: It's already established. So why try to change some language for no reason?

**Comment by Strubbelkopp** [comment]
Also while a bucket in Minecraft technically holds 1000L it's still weird as real buckets hold nowhere close to that amount. I think because of that a more abstract unit like mb makes more sense. It's intuitive in the context of Minecraft, consistent with other mods and doesn't sound outlandish

**Comment by theMegaTech** [comment]
> Also while a bucket in Minecraft technically holds 1000L it's still weird as real buckets hold nowhere close to that amount.

....and real humans don't carry tonns upon tonns of stuff in their pockets.

**Comment by theMegaTech** [comment]
> EDIT: For all I give a shit. You can make a mod that changes all other mods to L/t instead, but that's just as silly as only 1 mod having their own silly measurement system. At-least power in gregtech is it's own system with amperage. But the fluids are A: Inconsistent as mentioned above storage tank still uses mb. B: Pretty much all other mods with exception of gregtech and maybe some lesser known mods with <100 Downloads use a different type than mb/buckets C: It's already established. So why try to change some language for no reason?

Yes, it is established. Established to use liters in gregtech, for already like 12 years or so. Even gt4 and gt3, iirc, used liters already. So, yeah, even tho i'm not against the config option, that should not, in my opinion, be the default option. Gregtech is "realistic tech mod", why should it not use proper volume measurements even if it did for ~same time as mB existed?

**Comment by screret** [comment]
Don't argue in github comments.
Alao we were moving stuff to mB but that's kind of half-done currently.

**Comment by htmlcsjs** [comment]
the reason Litre (L) was used in 1.12 was to fit it in some UI elements that mB wouldnt fit in, its not that deep
