### ISSUE TITLE
Add syncronized to ConfigHolder#init

### ISSUE THREAD

**Issue by pietro-lopes** [GregTechCEu/GregTechCEu-1.19#1387]
https://github.com/GregTechCEu/GregTech-Modern/blob/a09b68814dc0668ddaf8bf7bc1d2fe39c482c723/src/main/java/com/gregtechceu/gtceu/config/ConfigHolder.java#L21

Please add syncronized here so addons/mods relying on this doesn't fail to read config file.

This is happening on Gregitas-Core, and multiple workers sometimes execute this and causes IO errors and resets config file to default.

**Comment by screret** [comment]
if you're doing the dependency correctly you *shouldn't* need that anymore, afaik

**Comment by pietro-lopes** [comment]
So we should just remove this init from our mod?

**Comment by pietro-lopes** [comment]
ops, miss click, damn mobile
