### ISSUE TITLE
No recipe for 16A UV, 16A UHV, 64A UHV Dynamo Hatch

### ISSUE THREAD

**Issue by davidlee0512** [GregTechCEu/GregTechCEu-1.19#1391]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.2.3.a

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

None

### Expected Behavior

able to craft 16A UV, 16A UHV, 64A UHV Dynamo Hatch

### Actual Behavior

No recipe show in jei

### Steps to Reproduce

N/A

**Comment by Igor-Movchan** [comment]
True, same for me. Tried on newest version 1.3.1

**Comment by YoungOnionMC** [comment]
fixed in #1791
