### ISSUE TITLE
Is it possible to allow extract item/fluid from single-block machine's input slot?

### ISSUE THREAD

**Issue by ConstasJ** [GregTechCEu/GregTechCEu-1.19#1394]
### Cross-mod Integration

AE2

### Feature Description

As all we know, some recipes in crafting table and GTCEu machines requires something that won't be consumpted, like programmable circuits and molds. I want to achieve processing automation using AE2, and I wish I can recycle these "unconsumpted" items. And I think the easiest way is to add feature that allows to extract item/fluid from input slot.
Is it possible to add this feature?

**Comment by Igneaalis** [comment]
Yeah, it would be pretty awesome, because currently we need 1 machine per 1 NC item (mold/lens/circuit). I'd like to use my Laser Engraver for all recipes and not only for the single recipe (each type of wafers)

**Comment by screret** [comment]
no, and won't be.
