### ISSUE TITLE
battarey alloy ingot not poisonous

### ISSUE THREAD

**Issue by AcidSoap** [GregTechCEu/GregTechCEu-1.19#1399]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.2.3a

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Greg tech community pack modern

### Expected Behavior

Player get poisoning

### Actual Behavior

Player not poisoning

### Steps to Reproduce

1) Take battarey alloy ingot in hand
2) Turn into survival mode

### Additional Information

In info about ingot told that ingot will take poison to player.

**Comment by AcidSoap** [comment]
lead ingot,plate has same issue

**Comment by silask7188** [comment]
I'm pretty sure this is intentional because the dust is poisonous when you inhale it, and since lead ingots are not airborne you cannot breathe lead ingots in.
