### ISSUE TITLE
Cant create cauldron

### ISSUE THREAD

**Issue by AcidSoap** [GregTechCEu/GregTechCEu-1.19#1402]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.2.3.a

### Recipe Viewer Installed

JEI

### Environment

singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

GregTech community edition pack modern

### Expected Behavior

Cauldron crafing

### Actual Behavior

Nothing happened

### Steps to Reproduce

1. Place any assembler
2. Give them power
3. Set circuit for mode 1
4. Put into them 7 iron plates

**Comment by screret** [comment]
cauldron recipe is circuit 7.
