### ISSUE TITLE
Americium problem

### ISSUE THREAD

**Issue by moosecrazy13** [GregTechCEu/GregTechCEu-1.19#1409]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.2.3a

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

ATM9

### Expected Behavior

Americium being made in mega fusion reactor

### Actual Behavior

Americium not being made in mega fusion reactor. Take 1 recipe worth and stops at 1 out of 2 ticks

### Steps to Reproduce

Take 1 recipe worth and stops at 1 out of 2 ticks

**Comment by screret** [comment]
mega fusion reactor isn't a GTCEu multiblock, but rather one from ATM9.
