### ISSUE TITLE
incompatible with Moonlight

### ISSUE THREAD

**Issue by AshdoII** [GregTechCEu/GregTechCEu-1.19#1410]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.0.20.b fabric

### Recipe Viewer Installed

No Recipe Viewer

### Environment

Server

### Cross-Mod Interaction

Yes

### Other Installed Mods

 fabric-api-0.92.2+1.20.1, moonlight-1.20-2.11.33

### Expected Behavior

Start server normally.

### Actual Behavior

Crash when start.

### Steps to Reproduce

1)install fabric server 1.20.1 0.15.11
2)install gtceu-fabric-1.20.1-1.0.20.b, fabric-api-0.92.2+1.20.1, moonlight-1.20-2.11.33
3)start server, crash.
[crash-2024-06-13_10.23.01-server.txt](https://github.com/user-attachments/files/15816457/crash-2024-06-13_10.23.01-server.txt)

### Additional Information

[latest 13.13.23.log](https://github.com/user-attachments/files/15816458/latest.13.13.23.log)
https://github.com/MehVahdJukaar/Moonlight/issues/223

**Comment by screret** [comment]
fabric is unsupported.

**Comment by AshdoII** [comment]
btw, I would like to know if fabric is still supported. Since its been a long time after fabric branch get updated.

**Comment by AshdoII** [comment]
> fabric is unsupported.

Got it. I expected so.
