### ISSUE TITLE
[1.21} GregTechCEu Modern Invalid File

### ISSUE THREAD

**Issue by Periam** [GregTechCEu/GregTechCEu-1.19#1419]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-1.21-1.3.0.jar

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Other Installed mod:

None

### Expected Behavior

To Actually launch

### Actual Behavior

After starting the game, the same validate mods and crash
![Screenshot 2024-06-14 172543](https://github.com/GregTechCEu/GregTech-Modern/assets/13920185/20aae86d-28f4-4c50-ab1d-341e8d5e1ccf)

### Steps to Reproduce

Add or enable the mod and launch the same.

### Additional Information

Attached logs
[crash-2024-06-14_17.29.10-fml.txt](https://github.com/user-attachments/files/15843157/crash-2024-06-14_17.29.10-fml.txt)

**Comment by screret** [comment]
We do NOT support forge 1.21.

**Comment by screret** [comment]
Use neoforge

**Comment by Periam** [comment]
Curse installed the mod on Forge 1.21, so I guess is Curse fault then...

**Comment by screret** [comment]
Guh i fixed the wrong loader tag already
