### ISSUE TITLE
Wire connection visuals gone when holding wrench (and not operable)

### ISSUE THREAD

**Issue by 34486** [GregTechCEu/GregTechCEu-1.19#142]
### GregTech CEu Version

1.0.6_30

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

I expected to see the mini gui to overlay on the wires/cables so I can use the wrench to hook up and disconnect wires/cables.

### Actual Behavior

It just outlines the box of where it would be. 
![2023-07-01_18 29 24](https://github.com/GregTechCEu/GregTechCEu-1.19/assets/19638851/731fabb8-2198-4d8e-838b-c91beeb28e41)

### Steps to Reproduce

Place wires and machines, try to connect or disconnect them using wrench. 

### Additional Information

It used to work?

**Comment by Drackion** [comment]
You use wire cutters on cables and wires

**Comment by 34486** [comment]
oof my noob mistake, sorry, got used to having to use wrench and freaked out lol.
