### ISSUE TITLE
[crash]crash on start up when playing modpack "sky greg"

### ISSUE THREAD

**Issue by Lightcx** [GregTechCEu/GregTechCEu-1.19#1425]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.2.1 and higher

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

Sky Greg v1.2.5

### Expected Behavior

not crash on mod loading

### Actual Behavior

game crash on mod loading

### Steps to Reproduce

1.download and install Sky Greg v1.2.5
2.update GTCEu Modern to v1.2.1 or any version higher
3.start the game
4.crash on start up

### Additional Information

i have tested and v1.2.0a and v1.1.4 works fine so idk maybe something to do with things added or changed in v1.2.1

**Comment by screret** [comment]
Don't update mods in premade packs.
