### ISSUE TITLE
EMI does not display the recipe correctly

### ISSUE THREAD

**Issue by JunYier** [GregTechCEu/GregTechCEu-1.19#1426]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.2.3.a

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

GregTech Leisure

### Expected Behavior

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/161495579/a00179b1-38ec-438c-80e4-b64c18b3d6c1)
I don't know what the black fluid in the formula is. The EMI didn't tell me waht it is.

### Actual Behavior

The black fluid in each washing plant formula is unknown, and neither JEI nor EMI is displayed.
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/161495579/a00179b1-38ec-438c-80e4-b64c18b3d6c1)

### Steps to Reproduce

No matter how you operate the game, it remains the same

### Additional Information

The display structure of the dimensionally transitional dent forge console is correct, but it does not work after I insert the materials, only showing standby

**Comment by screret** [comment]
EMI issue.

**Comment by screret** [comment]
Already reported to them, too. Try downgrading EMI to was it 1.3.0?

**Comment by JunYier** [comment]
OK,I'll give it a try
&nbsp;


Yi_Joy
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月16日(星期天) 晚上6:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [GregTechCEu/GregTech-Modern] EMI does not display the recipe correctly (Issue #1426)





 
Already reported to them, too. Try downgrading EMI to was it 1.3.0?
 
&mdash;

**Comment by screret** [comment]
also the empty fluid is just water :)
