### ISSUE TITLE
Invalid player data

### ISSUE THREAD

**Issue by skyinr** [GregTechCEu/GregTechCEu-1.19#1427]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.3.0

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

ModernUI-Forge-1.20.1-3.10.1.4-universal
journeymap-1.20.1-5.9.21-forge
Jade-1.20.1-forge-11.9.2
monazite-1.20.1-1.1.6
craftingtweaks-forge-1.20.1-18.2.3
probejs-6.0.1-forge
rhino-forge-2001.2.2-build.18
kubejs-forge-2001.6.5-build.7
cloth-config-11.1.118-forge
configured-forge-1.20.1-2.2.3
MouseTweaks-forge-mc1.20.1-2.25.1
BlueMap-3.21-forge-1.20
jei-1.20.1-forge-15.3.0.4
gtnn-1.0.7
gtceu-1.20.1-1.3.0
FluxNetworks-1.20.1-7.2.1.15
megacells-forge-2.4.4-1.20.1
ae2wtlib-15.2.3-forge
appliedenergistics2-forge-15.2.1
architectury-9.2.14-forge
curios-forge-5.9.1+1.20.1
balm-forge-1.20.1-7.2.2
appleskin-forge-mc1.20.1-2.5.1
LimitedLives-1.20.1-Forge-1.2.2
storagedrawers-1.20.1-12.0.3
fruitsdelight-1.0.9
barbequesdelight-1.0.2
miners_delight-1.20.1-1.2.3
FarmersDelight-1.20.1-1.2.4
mysterious_mountain_lib-1.4.5-1.20.1
corn_delight-1.0.4-1.20.1
spark-1.10.53-forge

### Expected Behavior

join world

### Actual Behavior

Unable to enter the world

### Steps to Reproduce

Use KubeJS script add Bedrock ore vein

### Additional Information

This bug appears after updating to 1.3.0
log: https://mclo.gs/lpDGbMi
my script：https://mclo.gs/mGGUJIh

**Comment by screret** [comment]
you can't initialize the vein materials with an array.
use the correct builder methods.

**Comment by skyinr** [comment]
Still failing

new script : https://mclo.gs/uAxyozu

**Comment by screret** [comment]
you don't set the materials like that, as I said.
use the provided builders.

**Comment by screret** [comment]
wait sorry I misread, you'll have to load the `com.mojang.datafixers.util.Pair` class and do `Pair.of(material, chance)` instead of `[material, chance]`

**Comment by skyinr** [comment]
Thank you, I used the builder model , I can run it now.

**Comment by Zeratul4340** [comment]
hello, I am also having trouble with invalid player data on a singleplayer 1.6.1 gtceu singleplayer world. I tried adding a goethite bedrock vein.

my JS script: [here](https://mclo.gs/cvGRBPm)
