### ISSUE TITLE
Error: java.lang.NoClassDefFoundError. Fabric 1.20.1. moonlight-1.20-2.11.37-fabric + gtceu-fabric-1.20.1-1.0.20.b.

### ISSUE THREAD

**Issue by worm-in-concrete** [GregTechCEu/GregTechCEu-1.19#1428]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-fabric-1.20.1-1.0.20.b

### Recipe Viewer Installed

None

### Environment

Dedicated Server

### Cross-Mod Interaction

Yes

### Other Installed Mods

moonlight-1.20-2.11.37-fabric

### Expected Behavior

It was expected that the server would start up and begin creating the world.

### Actual Behavior

The error occurs on the hosting server. When running the client crash does not happen, but when I run these two mods (moonlight-1.20-2.11.37-fabric + gtceu-fabric-1.20.1-1.0.20.b) on the hosting server it crashes.

### Steps to Reproduce

install these mods: gtceu-fabric-1.20.1-1.0.20.b, moonlight-1.20-2.11.37-fabric, fabric-api-0.92.2+1.20.1 and start the server

### Additional Information

Separately the mods work fine. I also tried to run the server with a standalone porting_lib mod.
crash-2024-06-16_18.33.48-server.txt - https://mclo.gs/RGRrd2h
latest.log - https://mclo.gs/0i9RowA

**Comment by screret** [comment]
issue already exists, and fabric has been unsupported for like half a year at least

**Comment by WetABQ** [comment]
See https://github.com/GregTechCEu/GregTech-Modern/issues/2352#issuecomment-2545008353
