### ISSUE TITLE
[ISSUE] - Ore Veins are not being generated in Non-Minecraft dimensions even with appropriate StoneType+ WorldGenLayer

### ISSUE THREAD

**Issue by Ghostipedia** [GregTechCEu/GregTechCEu-1.19#1429]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.3.0 build 788

### Recipe Viewer Installed

JEI

### Environment

Both

### Cross-Mod Interaction

Yes

### Other Installed Mods

KubeJS GTCEU Plugin

### Expected Behavior

Creating a vein with a vein layer targeting another dimension to generate a vein in that dimension

### Actual Behavior

Your choice of recipe viewer will show the vein exists in the 'Ore Vein Diagram' page, however trying to find it generating in the dimension you've define does not occur

### Steps to Reproduce

Install GTCEU, KubeJS, and Any Mod with a dimension (In my case I tested with Undergarden, Aether, Ad Astra)
Create a Stonetype for a valid stone in said dimension
Create a World Gen layer targeting the same stonetype and the dimension
Create a vein using that  generation layer
Load into game
Tp to dim
Pull out prospector scanner and view there are no valid ores
Additionally use worldstripper to verify the issue isn't with the scanner
See no ore

### Additional Information

This issue appeared between 1.2.3.a and 1.3.0 - As downgrading to 1.2.3.a fixes this issue

In all tests the stonetypes were fine, and infact worked prior to this update as well - it seems to be only the placement of the veins and surface indicators that do not happen

**Comment by DancingSnow0517** [comment]
you need register a oreTagPrefix to add other variety ores.

use script like this to register 
```js
GTCEuStartupEvents.registry('gtceu:tag_prefix', event => {
    event.create('moon_stone', 'ore')
        .stateSupplier(() => Block.getBlock('ad_astra:moon_stone').defaultBlockState())
        .baseModelLocation('ad_astra:block/moon_stone')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
})
```

**Comment by screret** [comment]
they've already done that

**Comment by Ghostipedia** [comment]
> you need register a oreTagPrefix to add other variety ores.
> 
> use script like this to register
> 
> ```js
> GTCEuStartupEvents.registry('gtceu:tag_prefix', event => {
>     event.create('moon_stone', 'ore')
>         .stateSupplier(() => Block.getBlock('ad_astra:moon_stone').defaultBlockState())
>         .baseModelLocation('ad_astra:block/moon_stone')
>         .unificationEnabled(true)
>         .materialIconType(GTMaterialIconType.ore)
>         .generationCondition(ItemGenerationCondition.hasOreProperty)
> })
> ```

This has been done, the key takeaway is that an already working ore-vein in a different dim in 1.2.3.a no longer generates in 1.3.0+ 
Players recently started to report in my pack since I moved GTM to 1.3.0 that oreveins no longer generate in other dims. hence this post

**Comment by DancingSnow0517** [comment]
> > you need register a oreTagPrefix to add other variety ores.
> > use script like this to register
> > ```js
> > GTCEuStartupEvents.registry('gtceu:tag_prefix', event => {
> >     event.create('moon_stone', 'ore')
> >         .stateSupplier(() => Block.getBlock('ad_astra:moon_stone').defaultBlockState())
> >         .baseModelLocation('ad_astra:block/moon_stone')
> >         .unificationEnabled(true)
> >         .materialIconType(GTMaterialIconType.ore)
> >         .generationCondition(ItemGenerationCondition.hasOreProperty)
> > })
> > ```
> 
> This has been done, the key takeaway is that an already working ore-vein in a different dim in 1.2.3.a no longer generates in 1.3.0+ Players recently started to report in my pack since I moved GTM to 1.3.0 that oreveins no longer generate in other dims. hence this post

I didn't notice it was version 1.3.0, and I haven't tested it in this version yet. my bad.

**Comment by daimonoss** [comment]
Sorry for necro, did you ever find a fix for this? Been having the same issue on latest version of modern.
