### ISSUE TITLE
Casting Mold (Name) doesn't rename item

### ISSUE THREAD

**Issue by Bosspc1234** [GregTechCEu/GregTechCEu-1.19#1439]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.3.0 build 794

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Gregtech Community Pack Modern

### Expected Behavior

Item input with renamed casting mold should rename item in forming press.

### Actual Behavior

The item stay in input side of forming press and doesn't get rename.
![Screenshot 2024-06-18 212334](https://github.com/GregTechCEu/GregTech-Modern/assets/128601014/e8a8a538-e902-4614-8fff-83f09e5452b9)
![Screenshot 2024-06-18 2123072](https://github.com/GregTechCEu/GregTech-Modern/assets/128601014/3d7d91e0-8661-4f28-b010-10f9643d0558)

### Steps to Reproduce

1. Remaned the casting mold (name) into any name
2. Put both the mold and item you want to rename in the forming press.
3. Forming press doesn't run

**Comment by screret** [comment]
it's NYI then
