### ISSUE TITLE
crash with kubejs

### ISSUE THREAD

**Issue by redgoblin88** [GregTechCEu/GregTechCEu-1.19#1440]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.3.0

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Architectury - 13.0.1 [Kubejs dependency]
Rhino - 2100.2.5 build 28
Kubejs - 2100.7.0 build 33

### Expected Behavior

the game to launch

### Actual Behavior

the game crashes as it is attempting to start

### Steps to Reproduce

install the mods

launch

### Additional Information

i have tried to reduce how many mods are active to try and narrow it down, but having kubejs dissabled and rhino/architectury enabled the crash does not occur, so this is either kubejs or gregtech (which the crashlog claims)

crashlog:
https://paste.gg/p/anonymous/d40d682808b34352b8f5e57ac98c0512

**Comment by screret** [comment]
could you send the latest.log?

**Comment by screret** [comment]
something went wrong before this crash in the loading process and forge ate the error

**Comment by redgoblin88** [comment]
https://paste.gg/p/anonymous/765020f0ed364930a3733ab15bd00073
