### ISSUE TITLE
Vein information is displayed incorrectly.

### ISSUE THREAD

**Issue by nutant233** [GregTechCEu/GregTechCEu-1.19#1444]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.3.0-build_799

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

jei

### Expected Behavior

Correct Display

### Actual Behavior

![844e9a49c7006c462a90565ec646237b](https://github.com/GregTechCEu/GregTech-Modern/assets/65939836/26711dcb-54ac-416c-8f57-d65043ade0ef)

### Steps to Reproduce

Open JEI

**Comment by screret** [comment]
Lmao, oops.
