### ISSUE TITLE
Machines are not working properly in parallel.

### ISSUE THREAD

**Issue by skyc10** [GregTechCEu/GregTechCEu-1.19#1448]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.3.0

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

GregTech Leisure

### Expected Behavior

The machines were supposed to work in parallel.

### Actual Behavior

They ceased operation.

### Steps to Reproduce

Set the parallelism of the large press machine to 64.

**Comment by screret** [comment]
any kind of notes on what you did leading up to this? screenshots?

**Comment by MatthiasMann** [comment]
keep in mind that you need to supply enough power for the machines to be able to operate in parallel

**Comment by paopaochen180** [comment]
![547d2bdf5fe72ee079575fe5890e92e8](https://github.com/GregTechCEu/GregTech-Modern/assets/129570152/1c09713b-ce0e-4521-bd38-6c703d6bb583)
![77912813ede5ebdc66eab3c7ee814fc9](https://github.com/GregTechCEu/GregTech-Modern/assets/129570152/39363831-e17b-4fea-b0cf-30428da212f9)
I confirm that the machine has enough power

**Comment by screret** [comment]
you can't mix recipes.

**Comment by paopaochen180** [comment]
> you can't mix recipes.

This is the recipes for two types of ingot to make gears

**Comment by skyc10** [comment]
It doesn't work when only steel ingot in it.
![1](https://github.com/GregTechCEu/GregTech-Modern/assets/87356226/34a8e272-83f7-46e4-a1d5-7dc206b926a5)
![2](https://github.com/GregTechCEu/GregTech-Modern/assets/87356226/b599549a-ee83-414d-aa93-c3e134c569ee)
