### ISSUE TITLE
1.3.0-a breaks game options (1.21 NeoForge)

### ISSUE THREAD

**Issue by aAndrew3030** [GregTechCEu/GregTechCEu-1.19#1459]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.21-1.3.0-a

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

-

### Expected Behavior

-

### Actual Behavior

-

### Steps to Reproduce

-

### Additional Information

After updating the mod to version 1.3.0-a, the options file is ignored  and the game reverts back to as if being played for the first time. Tested on NeoForge .17 - .20 with only GTCEU and LDLib 1.0.25.t and LDLib 1.0.25.s

[debug.log](https://github.com/user-attachments/files/15915669/debug.log)

**Comment by screret** [comment]
Oh what the fuck i thought this was a devenv issue

**Comment by screret** [comment]
[20Jun2024 10:34:05.196] [Render thread/ERROR] [net.minecraft.client.Options/]: Failed to load options
java.lang.NullPointerException: Cannot read field "compat" because "com.gregtechceu.gtceu.config.ConfigHolder.INSTANCE" is null
	at TRANSFORMER/gtceu@1.3.0-a/com.gregtechceu.gtceu.api.datafixer.DataFixesInternals.get(DataFixesInternals.java:58) ~[gtceu-1.21-1.3.0-a.jar%23185!/:?]

Fuck me the config isnt loaded yet

**Comment by nickkeane** [comment]
I'm getting the same issue w/ the latest version where Minecraft options aren't saving. Was the fix integrated?
