### ISSUE TITLE
Gregtech and Create 5.0 and 5.1 crash on startup - Something about flowing aluminium

### ISSUE THREAD

**Issue by nekomaster** [GregTechCEu/GregTechCEu-1.19#147]
### GregTech CEu Version

1.0.6 build 33

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

Launch Minecraft 1.19.2 with forge 43.2.14 using gtceu-forge-1.19.2-1.0.6-build_33.jar and either
create-1.19.2-0.5.0.i.jar (**OR**) create-1.19.2-0.5.1.c.jar

I expect the game to load with GT and either version of Create

### Actual Behavior

Game crashes on startup after loading for a bit (almost as if its going to fully load into the menu)

(I've attached some logs which may help)
[2023-07-06-1.log](https://github.com/GregTechCEu/GregTechCEu-1.19/files/11973904/2023-07-06-1.log)
[debug.log](https://github.com/GregTechCEu/GregTechCEu-1.19/files/11973905/debug.log)
[latest.log](https://github.com/GregTechCEu/GregTechCEu-1.19/files/11973906/latest.log)

### Steps to Reproduce

Have minecraft 1.19.2 forge 43.2.14 installed and launch forge with gtceu-forge-1.19.2-1.0.6-build_33.jar and either

create-1.19.2-0.5.0.i.jar (**OR**) create-1.19.2-0.5.1.c.jar

The game will load for a moment and than crash.

### Additional Information

This issue is happening with create 5.0 and 5.1 now, where as previously gtceu was incompatible with **JUST** create 5.1

This sucks as I rather like create for the water powered mechanical stuff, and its ore generation.

I hope this can be resolved in the future.

**Comment by Drackion** [comment]
use create 0.5.1.b

**Comment by nekomaster** [comment]
> 

OH Nice it loadede, thanks!
