### ISSUE TITLE
The machine disregarded the recipe tier.

### ISSUE THREAD

**Issue by nutant233** [GregTechCEu/GregTechCEu-1.19#1478]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.3.0

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

kjs

### Expected Behavior

Work according to recipe tier.

### Actual Behavior

disregarded the recipe tier.

### Steps to Reproduce

Using SOC to fabricate nano processors.
![397f989adadf3895516ca7aa94e4da61](https://github.com/GregTechCEu/GregTech-Modern/assets/65939836/d87fcb2c-e0c0-465e-bb6e-d8bc1edd0445)
![d613c8ef6f2ca9531509c2649e31a864](https://github.com/GregTechCEu/GregTech-Modern/assets/65939836/a8ab7dcc-7f6c-4760-8c3a-df2cda52124e)

**Comment by screret** [comment]
Fixed already.
