### ISSUE TITLE
[1.21 - Build 824] Crash on config hover

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [GregTechCEu/GregTechCEu-1.19#1482]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.3.0-a-build_824 for 1.21

### Recipe Viewer Installed

None

### Environment

All

### Cross-Mod Interaction

Unsure

### Other Installed Mods

ldlib-neoforge-1.21-1.0.25.t.jar
gtceu-1.21-1.3.0-a-build_824.jar
neoforge-21.0.31-beta-universal.jar
Running java 21

### Expected Behavior

Config hover shows description

### Actual Behavior

Client crashes

### Steps to Reproduce

Go into "Mods" on the menu screen -> Gregtech -> Any submodule -> hover over any setting

### Additional Information

I checked the latest but the release availalbe on Modrinth and CF all have the same crash issue on 1.3.0-a
[crash-2024-06-24_13.32.22-client.txt](https://github.com/user-attachments/files/15954632/crash-2024-06-24_13.32.22-client.txt)

**Comment by screret** [comment]
Gotta update the config library ig
