### ISSUE TITLE
Machine does not work when setting maximum number in parallel

### ISSUE THREAD

**Issue by paopaochen180** [GregTechCEu/GregTechCEu-1.19#1484]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-1.20.1-1.3.0-a-build_829

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

no

### Expected Behavior

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/129570152/0ac883d4-7d5f-4d3c-8fda-dec0f319b025)
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/129570152/4a168d1c-100b-48fb-a742-f1d672517c4d)
The machine should be working properly

### Actual Behavior

The machine is not working ， needs to be reduced in parallel to the maximum voltage provided in order to function properly

### Steps to Reproduce

 just like #1266

**Comment by paopaochen180** [comment]
https://github.com/GregTechCEu/GregTech-Modern/assets/129570152/c52b69b5-2240-41ab-8157-aea74313ebd2
This is the results of my testing in build842 version

**Comment by YoungOnionMC** [comment]
fixed in #1468
