### ISSUE TITLE
Coil bonuses dont work when the minimum voltage is used 

### ISSUE THREAD

**Issue by tTheEddie** [GregTechCEu/GregTechCEu-1.19#1489]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v 1.3.0-a

### Recipe Viewer Installed

JEI

### Environment

singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

gregtech community pack modern

### Expected Behavior

coil bonuses apply when using the minimum voltage to run the recipe 
example: the coke oven will take 16 seconds to do a 32 sec recipe when using rtm coils and mv 

### Actual Behavior

coil bonuses do not apply when using the minimum voltage to run the recipe 
example: a mv coke even with cupronickel coils will still run at 32 secs even if the coils give a time penalty 
and a coke oven with rtm coils will still run at 32 secs

### Steps to Reproduce

just build any multiblock that gives coil bonuses and use any recipe at the minimum voltage tier to run them

**Comment by YoungOnionMC** [comment]
fixed in #1850
