### ISSUE TITLE
large assemblers still perform recipes they arent allowed to do 

### ISSUE THREAD

**Issue by tTheEddie** [GregTechCEu/GregTechCEu-1.19#1490]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v 1.3.0-a

### Recipe Viewer Installed

JEI

### Environment

singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

gregtech community pack modern

### Expected Behavior

large assemblers cant perform recipe that are above the voltage of the energy hatch even if its a 4 amp one 

### Actual Behavior

the large assemblers can do recipes that are above the voltage of the energy hatch if a 4 amp one is used
example: a large assembler with a 4 amp ev energy hatch can do iv recipes even if the gui tells it can only do ev

### Steps to Reproduce

build a large assembler and get any 4 amp hatch and then run any recipe thats one tier above the hatch used
example: a iv recipe with ev 4 amp hatch

**Comment by YoungOnionMC** [comment]
fixed in #1468
