### ISSUE TITLE
Vacuum Freezer does not cool down air no more

### ISSUE THREAD

**Issue by sztosz** [GregTechCEu/GregTechCEu-1.19#1492]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-1.20.1-1.3.0-a-build_828 and later

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Monifactory 0.5.5

### Expected Behavior

Vacuum Freezer should cool down/freeze air to liquid air.

### Actual Behavior

Vacuum Freezer does not cool down/freeze air to liquid air.

### Steps to Reproduce

Just build a vacuum freezer and add to input hatch air 

### Additional Information

gtceu-1.20.1-1.3.0-a-build_826 freezes oxygen without problem
updating jar, and not changing anything else to gtceu-1.20.1-1.3.0-a-build_828 or gtceu-1.20.1-1.3.0-a-build_833 and Vacuum Freezer is just idling. 
After reverting jar to gtceu-1.20.1-1.3.0-a-build_826 and Vacuum Freezer freezes air to liquid air without any problem again.

**Comment by sztosz** [comment]
I know it's a separate issue, but I also noticed that, Assembly Line that is formed correctly and working in build_826 says Structure Incomplete in build_833 :shrug:

**Comment by YoungOnionMC** [comment]
works in 1.3.1
