### ISSUE TITLE
Drill works without remaining battery power.

### ISSUE THREAD

**Issue by suzushiro226** [GregTechCEu/GregTechCEu-1.19#1494]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-1.20.1-1.2.3a
gtceu-1.20.1-1.3.0-a-build_838

### Recipe Viewer Installed

EMI

### Environment

Singleplayer (gtceu-1.20.1-1.3.0-a-build_838)
Multiplayer (TerraFirmaGreg-1.20.x-0.7.12 / gtceu-1.20.1-1.2.3a)

### Cross-Mod Interaction

Unsure

### Other Installed Mods

Instance built for testing.
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/84512237/48693952-2c8c-4033-85b6-05693edb747f)

### Expected Behavior

A drill with zero battery power will not function as a pickel / shovel.

### Actual Behavior

The drill will continue to function regardless of the battery power.

### Steps to Reproduce

Try the drill in a new world.
![2024-06-26_19 48 52](https://github.com/GregTechCEu/GregTech-Modern/assets/84512237/aa0e20cc-9928-47ea-8205-537c2a45383e)
![2024-06-26_19 48 56](https://github.com/GregTechCEu/GregTech-Modern/assets/84512237/8a8278b2-43a6-4d35-8ef4-cceb11082f94)

### Additional Information

It continues to work regardless of single/multi block mode.
I noticed this issue with modpack TerraFirmaGreg-1.20.x-0.7.12 (multiplayer)
If I remember correctly, I ran into the same problem with GTCEu 1.12

**Comment by screret** [comment]
intended. it'll just use durability instead.

**Comment by suzushiro226** [comment]
My knowledge seems to stop at 1.7.10. Thank you!
