### ISSUE TITLE
[1.21] Latest Mod crashed on game loading

### ISSUE THREAD

**Issue by Periam** [GregTechCEu/GregTechCEu-1.19#1495]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-1.21-1.3.0-a.jar

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Advent of Ascension (Nevermine)
AoA3-1.21-3.7.8.jar

### Expected Behavior

To launch the game.

### Actual Behavior

The game crash with a report related to Java error

### Steps to Reproduce

1-Install Greg Tech
2-Install depency LDLib
3-Install Advent of ascension
4-launch the game

### Additional Information

[crash-2024-06-26_10.52.29-client.txt](https://github.com/user-attachments/files/15990328/crash-2024-06-26_10.52.29-client.txt)

**Comment by screret** [comment]
I'll need your latest.log to diagnose this, something went wrong earlier in the loading process.

**Comment by Periam** [comment]
Hi, sorry the delay here is the file

[latest.log](https://github.com/user-attachments/files/15992465/latest.log)

**Comment by screret** [comment]
your AoA isn't updated to the latest neoforge version.

**Comment by screret** [comment]
they did a breaking change in some damage-related events so mods need to update to that.

**Comment by Periam** [comment]
it is the only version availble of AoA...

**Comment by Periam** [comment]
here is another log, without AoA, i added Gobber (Gobber-NeoForge-1.21-2.10.2.jar)

[latest.log](https://github.com/user-attachments/files/15992566/latest.log)
