### ISSUE TITLE
Extremely long recipe

### ISSUE THREAD

**Issue by edshPC** [GregTechCEu/GregTechCEu-1.19#1500]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.20.1-1.3.0a 

### Recipe Viewer Installed

JEI

### Environment

Forge Dedicated Server

### Cross-Mod Interaction

Unsure

### Other Installed Mods

JEI, Jade, ...
[full modpack](https://www.curseforge.com/minecraft/modpacks/evgesha1067-adventure)

### Expected Behavior

It occurs with liquid rubber LV recipe in Chemical reactor.
Normally it should take 30 sec, as showed in JEI
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/116029298/8076b432-203f-42eb-af42-b7e6458fb388)

### Actual Behavior

Actually, recipe time is unexpected, it can be normal 30 sec, or 240 sec, or, as on screenshot, it takes 3000 sec!!
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/116029298/22ef191c-22cf-4d3c-b185-b0add4783596)

### Steps to Reproduce

Start the liquid rubber recipe in LV chemical reactor on Dedicated Server

### Additional Information

I'm not sure if it happens on other machines or recipies, I had issues only with this recipe.
Also I couldn't reproduce it in local world

**Comment by screret** [comment]
you got pollution?

**Comment by screret** [comment]
because pollution makes CRs take longer, as well as some other machines

**Comment by edshPC** [comment]
uh well, yes..
Sorry, I got it, but 3k secs is still wild

> you got pollution?

**Comment by Ghostipedia** [comment]
> uh well, yes.. Sorry, I got it, but 3k secs is still wild
> 
> > you got pollution?

To be fair, it does warn you about it on the tool-tip 
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/46772882/f23b1c29-ede1-48fc-96e0-055481ecf65b)

Thought I think in this case it should just disable the machine @screret vs slow it down that much. Like after some  upper limit, the recipe duration just swaps to 'can't start' - ideally with some Jade and/or UI popup in the machine UI (under the Info icon)

**Comment by JasonMoisesSteele** [comment]
It also appears to set the recipe time too its maximum (base recipe 8s, maximum 800s) when the chuck pollution is at a low value 0.1 ~ 2. But if the chunk pollution is at say 50~ the recipe time is just doubled (base recipe 8s, maximum 16s).

**Comment by screret** [comment]
lmao the scaling was backwards
