### ISSUE TITLE
Suspects that parallel logic is not checking item output

### ISSUE THREAD

**Issue by YiRanMushroom** [GregTechCEu/GregTechCEu-1.19#1505]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-1.20.1-1.3.0-a-build_842

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

ATM9

### Expected Behavior

Use a Hatch Parallel, and when the parallel amout is set very high, expects the recipe to run.

### Actual Behavior

if the output space of it is not big enough, and the input is excessive, the recipe cannot run. And if we reduce the parallel limit, the recipe can run.

### Steps to Reproduce

I used a electrolizer recipe.

**Comment by YoungOnionMC** [comment]
fixed in #1850
