### ISSUE TITLE
Auto Output ignores Filter

### ISSUE THREAD

**Issue by Midius** [GregTechCEu/GregTechCEu-1.19#1507]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

GTCEu 1.20.1 1.3.0

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Monifactory

### Expected Behavior

The auto output of machines should respect the filter when placed on the output side

### Actual Behavior

Right now the filter is just ignored. doesn't matter if the (fluid)-filter is on the machine or an attached pipe.

### Steps to Reproduce

Place down a machine that produces different fluids, filter it with a fluid-filter and auto-output through that side.
![grafik](https://github.com/GregTechCEu/GregTech-Modern/assets/1699477/568e5b3c-8ac5-4052-b493-a1ca2681f9bc)

**Comment by wapachoo** [comment]
This also applies to single-block boilers. Fluid filters aren't respected when placed on the pipe _or_ the boiler.
