### ISSUE TITLE
incompatibility with Mana and Artifice

### ISSUE THREAD

**Issue by Fedorka234** [GregTechCEu/GregTechCEu-1.19#1508]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.3.0-a

### Recipe Viewer Installed

EMI

### Environment

Singlepalyer, Dedicated Server, Open to LAN

### Cross-Mod Interaction

Yes

### Other Installed Mods

**gtceu-1.20.1-1.3.0-a** and **Mana and Artifice 3.0.0.15**

### Expected Behavior

In Mana and Artifice there is an item "**Chimerite Gem**", that should drop from Diamond Ore and Deepslate Diamond ore as an additional drop besides diamond.

### Actual Behavior

GregTech changes diamond ore generation, and it looks like Mana & Artifice can`t recognize GT diamond ores as a diamond ore, so Chimerite Gems are not obtainable.

### Steps to Reproduce

1. Install Mana and Artifice and GTCEu altogether.
2. Place GT diamond ore, try to get Chimerite Gem drop (you won`t)
3. Place vanilla diamond ore, try to get Chimerite Gem from it (you will get it)

### Additional Information

I found old bugreport in MnA github and it looks simillar, maybe it will help to solve this problem:
https://github.com/Mithion/Mana-And-Artifice/issues/154

**Comment by screret** [comment]
we use a different loot table for our drops instead of the vanilla one, and as such, the M&A loot modification can not apply.
add some other way to get the item maybe?

**Comment by Fedorka234** [comment]
thanks for quick answer! That`s not a big problem, i will resolve my problem with datapack
