### ISSUE TITLE
firebox z-fighting

### ISSUE THREAD

**Issue by gateguardian523** [GregTechCEu/GregTechCEu-1.19#1511]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.3.0-a-build_847

### Recipe Viewer Installed

REI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

I encountered it in the gtm development environment

### Expected Behavior

firebox overlays do not z fight

### Actual Behavior

firebox overlays z fight when in working multiblocks

### Steps to Reproduce

1. Build a Large Boiler
2. Observe that the firebox overlay is z-fighting when the boiler is working

### Additional Information

![屏幕截图 2024-06-28 163258](https://github.com/GregTechCEu/GregTech-Modern/assets/147252672/1157c441-a6f0-48e5-96fb-8ef83af2d24b)

**Comment by gateguardian523** [comment]
I found that this is related to CTM. Moreover, the situation with # 55 has occurred again, but only in large steam machines

**Comment by screret** [comment]
hm, guess we'll need to add a slight offset to the models.

**Comment by Zen9890** [comment]
Same thing applies to the steam I/O busses in 1.3.0a release used in GTCP modern

**Comment by YoungOnionMC** [comment]
fixed as of 1.4.4
