### ISSUE TITLE
ECE consuming way too much Liquid Oxygen

### ISSUE THREAD

**Issue by meoluoi2001** [GregTechCEu/GregTechCEu-1.19#1519]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-1.20.1-1.3.0-a

### Recipe Viewer Installed

JEI

### Environment

Open to LAN

### Cross-Mod Interaction

Unsure

### Other Installed Mods

GregTech CEu Modern Community Pack
Some extra Mod: EMI, Simple Resource Generator, SkyBlock Builder, ExHammer

### Expected Behavior

One EV Vacuum Freezer able to support a boosted ECE (produce 83mb/s and consume 80mb/s)

### Actual Behavior

ECE consume like 80mb per tick

### Steps to Reproduce

I just set up ECE with Liquid Oxygen as an input in a Quad Input Hatch

### Additional Information

Here is a video showing the useage

https://github.com/GregTechCEu/GregTech-Modern/assets/28429779/66b7060f-2dd4-45c3-8c7e-4fdbad1327cf

**Comment by YoungOnionMC** [comment]
fixed in #1913
