### ISSUE TITLE
Sub tick Parallels not apply with parallels hatch

### ISSUE THREAD

**Issue by DancingSnow0517** [GregTechCEu/GregTechCEu-1.19#1520]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.3.0-a-build_855

### Recipe Viewer Installed

JEI

### Environment

SP

### Cross-Mod Interaction

No

### Other Installed Mods

GTM, jade, jei

### Expected Behavior

the eu/t is enougth to Parallels
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/60736156/a39c03ec-0314-49b3-b8ea-ed991e72cbe0)
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/60736156/ab38646d-227d-4a95-af71-63bbe25866a5)
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/60736156/2860dc4e-8da2-4916-b0ae-8eec7363aeb7)

### Actual Behavior

not apply Sub tick Parallels only has parallels hatch parallels.

### Steps to Reproduce

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/60736156/79d91dd6-af4a-4c6e-b212-27242672531c)
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/60736156/e64f1e6d-616c-4e14-bbc0-c97d2fc2763a)

**Comment by screret** [comment]
what about 856?

**Comment by DancingSnow0517** [comment]
in older version build_828 it work fine, but not check the output space to parallels

**Comment by DancingSnow0517** [comment]
> what about 856?

856 is 1.21 build

**Comment by DancingSnow0517** [comment]
855 is Latest build in 1.20.1

**Comment by screret** [comment]
> 856 is 1.21 build

oh lol that means the thing that generates changelogs likes to break
