### ISSUE TITLE
Server crash with AE integration

### ISSUE THREAD

**Issue by BazZziliuS** [GregTechCEu/GregTechCEu-1.19#1529]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.3.0a

### Recipe Viewer Installed

JEI

### Environment

Dedicated Server.

### Cross-Mod Interaction

No

### Other Installed Mods

The crash log contains all the information - https://paste.fuix.net/amdRZkG

### Expected Behavior

The crash log contains all the information - https://paste.fuix.net/amdRZkG

### Actual Behavior

The crash log contains all the information - https://paste.fuix.net/amdRZkG

### Steps to Reproduce

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/18011884/438d6240-b3e8-4a2b-a76d-03f4a60273b7)
In an attempt to configure the gtceu:me_input_hatch, the server crashes (When you enter the text)

**Comment by Li14i4a** [comment]
I think it's problem must be fixed. I WANT PLAY IN MY FAVORITE MOD IN COMPUTER GAME MINECRAFT BUT CAN'T.

**Comment by screret** [comment]
it's getting fixed.
also stop screaming

**Comment by Li14i4a** [comment]
thx for fast answer i will scream until this problem will be fixed
