### ISSUE TITLE
Make Super / Quantum Tank Save Fluid After Breaking and Allow Them to Store Fluid in Item Form.

### ISSUE THREAD

**Issue by YiRanMushroom** [GregTechCEu/GregTechCEu-1.19#1530]
### Feature Description

Just as I mentioned in the title, quantum tanks should be able to store fluid in item form, just like the drums. I don't know why this is not implemented yet, and I think 1.12.2 gtceu already have this feature.

**Comment by MatthiasMann** [comment]
At least in gtceu-1.20.1-1.2.3-build_706 the super tanks keep the stored fluid when I break them with a wrench
