### ISSUE TITLE
Recipe for Sodium Hydroxide in the Chemical Reactor does not exist

### ISSUE THREAD

**Issue by werwerwsx** [GregTechCEu/GregTechCEu-1.19#1534]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

GregTechCEu 1.21-1.3.0a

### Recipe Viewer Installed

JEI

### Environment

SinglePlayer

### Cross-Mod Interaction

No

### Other Installed Mods

JEI
LDLib 1.21-1.0.25.u-neoforge

### Expected Behavior

Expected that a recipe would exist to produce 3 sodium hydroxide from 1000 mb of water and one sodium dust

### Actual Behavior

The recipe does not exist, a recipe for electrolyzing salt water does

### Steps to Reproduce

Install the latest version of GregTech Modern along with a recipe viewer
View the recipes for sodium hydroxide

**Comment by screret** [comment]
intended.
