### ISSUE TITLE
GL errors if installed together with Lodestone

### ISSUE THREAD

**Issue by slava110** [GregTechCEu/GregTechCEu-1.19#1536]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.3.1

### Recipe Viewer Installed

No Recipe Viewer

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Lodestone 1.20.1-1.6.1

### Expected Behavior

Having clean and nice log

### Actual Behavior

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/26705162/91839bb0-a823-4a22-a4fc-475ffdbd31fc)
I'm getting
```
[Render thread/INFO] [mojang/GlDebug]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Depth formats do not match.'
```
message in the logs repeatedly whenever I'm in the world

### Steps to Reproduce

1) Install GregTech and Lodestone
2) Enter any singleplayer world

**Comment by screret** [comment]
do they change the shader depth format?? the shit

**Comment by PinkDisorder** [comment]
This got fixed on their side https://github.com/LodestarMC/Lodestone/issues/33
