### ISSUE TITLE
Fluid pipes don't shutter

### ISSUE THREAD

**Issue by KP2048** [GregTechCEu/GregTechCEu-1.19#1549]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.3.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

TerraFirmaGreg modpack

### Expected Behavior

The wrench should toggle the shutter when I shift click

### Actual Behavior

the mode switch interaction consumes the event before that code runs and it just switches the mode instead

### Steps to Reproduce

place down a pipe and try to shutter it so it doesn't slosh

**Comment by KP2048** [comment]
I just had something in my offhand, disregard this issue

**Comment by Wyrmlet** [comment]
This probably should be fixed or otherwise mentioned somewhere, I've been looking for a solution for this for ages! Turns out I was just holding a shield in my offhand, so my wrench changed modes instead. Really doesn't feel like intended functionality.
