### ISSUE TITLE
Crash at launch with other(s) mods conflict

### ISSUE THREAD

**Issue by modpacka2** [GregTechCEu/GregTechCEu-1.19#1555]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.3.1

### Recipe Viewer Installed

EMI

### Environment

NONE, it's when I open the game on client side

### Cross-Mod Interaction

Yes

### Other Installed Mods

[Macaw's Doors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-doors)
[Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/comforts)
[Snad (by TheRoBrit)](https://www.curseforge.com/minecraft/mc-mods/snad)
[CreativeCore (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[Productive Bees (by LobsterJonn)](https://www.curseforge.com/minecraft/mc-mods/productivebees)
[Cupboard (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/cupboard)
[Just Enough Professions (JEP) (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/just-enough-professions-jep)
[Mekanism Tools (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-tools)
[Serene Seasons (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/serene-seasons)
[Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[FTB Library (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge)
[XyCraft: World (by Soaryn)](https://www.curseforge.com/minecraft/mc-mods/xycraft-world)
[Easy Magic [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/easy-magic)
[Clean Swing Through Grass (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/clean-swing-through-grass)
[XyCraft (by Soaryn)](https://www.curseforge.com/minecraft/mc-mods/xycraft)
[Just Enough Effect Descriptions (JEED) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/just-enough-effect-descriptions-jeed)
[Additional Structures (by XxRexRaptorxX)](https://www.curseforge.com/minecraft/mc-mods/additional-structures)
[Cloth Config API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)
[FTB Filter System (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-filter-system)
[Searchables (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/searchables)
[Corpse (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/corpse)
[Easy Anvils [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/easy-anvils)
[Mekanism (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism)
[Just Player Heads (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/just-player-heads)
[EMI (by EmilyPloszaj)](https://www.curseforge.com/minecraft/mc-mods/emi)
[Macaw's Paths and Pavings (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-paths-and-pavings)
[GregTechCEu Modern (by KilaBash)](https://www.curseforge.com/minecraft/mc-mods/gregtechceu-modern)
[Trade Cycling (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/trade-cycling)
[Fuel Goes Here (by LobsterJonn)](https://www.curseforge.com/minecraft/mc-mods/fuelgoeshere)
[Architectury API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Map Tooltip (by VendoAU)](https://www.curseforge.com/minecraft/mc-mods/map-tooltip)
[fix GPU memory leak[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/fix-gpu-memory-leak)
[NetherPortalFix (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/netherportalfix)
[KleeSlabs (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/kleeslabs)
[ImmediatelyFast (by RaphiMC)](https://www.curseforge.com/minecraft/mc-mods/immediatelyfast)
[Yeetus Experimentus (by Sunekaer)](https://www.curseforge.com/minecraft/mc-mods/yeetusexperimentus)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Underwater Enchanting (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/underwater-enchanting)
[Continents (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/continents)
[Amplified Nether (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/amplified-nether)
[Configured (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/configured)
[Macaw's Trapdoors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-trapdoors)
[Tom's Simple Storage Mod (by tom54541)](https://www.curseforge.com/minecraft/mc-mods/toms-storage)
[FancyMenu (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/fancymenu)
[Chat Heads (by dzwdz)](https://www.curseforge.com/minecraft/mc-mods/chat-heads)
[Connectivity[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/connectivity)
[Jade 🔍 (by Snownee)](https://www.curseforge.com/minecraft/mc-mods/jade)
[Visual Workbench [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/visual-workbench)
[BadOptimizations (by thosea)](https://www.curseforge.com/minecraft/mc-mods/badoptimizations)
[Konkrete [Forge/NeoForge] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/konkrete)
[Fresh Waystones Texture (by zozozrob_zadrot)](https://www.curseforge.com/minecraft/texture-packs/fresh-waystones-texture)
[Structory: Towers (by botanydev)](https://www.curseforge.com/minecraft/mc-mods/structory-towers)
[AI Improvements (by QueenOfMissiles)](https://www.curseforge.com/minecraft/mc-mods/ai-improvements)
[Just Enough Archaeology (by LobsterJonn)](https://www.curseforge.com/minecraft/mc-mods/just-enough-archaeology)
[Macaw's Fences and Walls (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[JCPlugin (by PT400C)](https://www.curseforge.com/minecraft/mc-mods/jcplugin)
[FTB Quests (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-quests-forge)
[Tough As Nails (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/tough-as-nails)
[Distant Horizons: A Level of Detail mod (by James_Seibel)](https://www.curseforge.com/minecraft/mc-mods/distant-horizons)
[Modpack Update Checker (by Jab125)](https://www.curseforge.com/minecraft/mc-mods/modpack-update-checker)
[Simple Weather (by Soaryn)](https://www.curseforge.com/minecraft/mc-mods/simple-weather)
[Macaw's Bridges (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges)
[Client Tweaks (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/client-tweaks)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Adorned (Curios) (by LobsterJonn)](https://www.curseforge.com/minecraft/mc-mods/adorned)
[Inventory Totem (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/inventory-totem)
[LootJS: KubeJS Addon (by Lytho)](https://www.curseforge.com/minecraft/mc-mods/lootjs)
[Not Enough Recipe Book [NERB] (by SSKirillSS)](https://www.curseforge.com/minecraft/mc-mods/notenoughrecipebook)
[Athena (by CodexAdrian)](https://www.curseforge.com/minecraft/mc-mods/athena)
[Packet Fixer (by TonimatasDEV)](https://www.curseforge.com/minecraft/mc-mods/packet-fixer)
[Theurgy (by kli_kli)](https://www.curseforge.com/minecraft/mc-mods/theurgy)
[Melody (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/melody)
[CraftTweaker (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/crafttweaker)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[Rhino (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/rhino)
[FTB Chunks (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge)
[Cherished Worlds (Fabric/Forge/NeoForge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/cherished-worlds)
[Memory Settings[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/memory-settings)
[Structory (by botanydev)](https://www.curseforge.com/minecraft/mc-mods/structory)
[Iron Furnaces (by XenoMustache)](https://www.curseforge.com/minecraft/mc-mods/iron-furnaces)
[XyCraft: Machines (by Soaryn)](https://www.curseforge.com/minecraft/mc-mods/xycraft-machines)
[Better Than Mending (by legobmw99)](https://www.curseforge.com/minecraft/mc-mods/better-than-mending)
[DefaultSettings (by PT400C)](https://www.curseforge.com/minecraft/mc-mods/defaultsettings)
[Chunky (Forge/NeoForge) (by pop4959)](https://www.curseforge.com/minecraft/mc-mods/chunky-pregenerator-forge)
[Get It Together, Drops! (by bl4ckscor3)](https://www.curseforge.com/minecraft/mc-mods/get-it-together-drops)
[XyCraft: Override (by Soaryn)](https://www.curseforge.com/minecraft/mc-mods/xycraft-override)
[No Chat Reports (by Aizistral)](https://www.curseforge.com/minecraft/mc-mods/no-chat-reports)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Resource Pack Overrides [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/resource-pack-overrides)
[Model Gap Fix (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/model-gap-fix)
[FramedBlocks (by XFactHD)](https://www.curseforge.com/minecraft/mc-mods/framedblocks)
[Mekanism Generators (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-generators)
[Macaw's Lights and Lamps (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-lights-and-lamps)
[Modonomicon (by kli_kli)](https://www.curseforge.com/minecraft/mc-mods/modonomicon)
[Entity Culling Fabric/Forge (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/entityculling)
[Just Enough Breeding (JEBr) (by Christofmeg)](https://www.curseforge.com/minecraft/mc-mods/justenoughbreeding)
[Sound Physics Remastered (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered)
[Catalogue (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/catalogue)
[Packing Tape (by gigaherz)](https://www.curseforge.com/minecraft/mc-mods/packing-tape)
[Let Me Despawn (by frikinjay)](https://www.curseforge.com/minecraft/mc-mods/let-me-despawn)
[Aquaculture 2 (by Shadow)](https://www.curseforge.com/minecraft/mc-mods/aquaculture)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[Sit (by bl4ckscor3)](https://www.curseforge.com/minecraft/mc-mods/sit)
[AmbientSounds 6 (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/ambientsounds)
[Crafting Tweaks (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/crafting-tweaks)
[KubeJS (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/kubejs)
[Better Fps - Render Distance[Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance)
[Cycle Paintings (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/cycle-paintings)
[Just Enough Mekanism Multiblocks (by gisellevonbingen)](https://www.curseforge.com/minecraft/mc-mods/just-enough-mekanism-multiblocks)
[Smaller Nether Portals (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/smaller-nether-portals)
[LDLib (by KilaBash)](https://www.curseforge.com/minecraft/mc-mods/ldlib)
[Resourceful Lib (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib)
[Dismount Entity (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/dismount-entity)
[FTB XMod Compat (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-xmod-compat)
[Double Doors (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/double-doors)
[Not Enough Animations (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/not-enough-animations)
[Polymorph (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/polymorph)
[Pick Up Notifier [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/pick-up-notifier)
[Skin Layers 3D (Fabric/Forge) (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/skin-layers-3d)
[Tax Free Levels (Fabric/(Neo)Forge) (by Fourmisain)](https://www.curseforge.com/minecraft/mc-mods/tax-free-levels)
[FTB Teams (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-teams-forge)
[PolyLib (by Official_CreeperHost)](https://www.curseforge.com/minecraft/mc-mods/polylib)
[Cosmetic Armor Reworked (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
[Accelerated Decay (by ErrorMikey)](https://www.curseforge.com/minecraft/mc-mods/accelerated-decay)
[Terralith (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/terralith)
[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[Utilitarian (by LobsterJonn)](https://www.curseforge.com/minecraft/mc-mods/utilitarian)
[FTB Backups 2 (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-backups-2)
[Puzzles Lib [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[ModernFix (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/modernfix)
[GlitchCore (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/glitchcore)
[Better Compatibility Checker (by Gaz_)](https://www.curseforge.com/minecraft/mc-mods/better-compatibility-checker)
[Chipped (by terrariumearth)](https://www.curseforge.com/minecraft/mc-mods/chipped)
[Embeddium (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/embeddium)
[FerriteCore ((Neo)Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)

### Expected Behavior

The game launching without crashing

### Actual Behavior

The game crash with this error 
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/75133238/a0d44606-73d9-490a-b906-77c3ef09e208)
(my graphic card is a rtx 3060 and with the latest update)

This behavior only happen when I launch the game with this mod and here's a part of the crash report to show you : 

-- Head --
Thread: Render thread
Stacktrace:
	at TRANSFORMER/gtceu@1.3.1/com.gregtechceu.gtceu.common.material.MaterialRegistryManager.getRegisteredMaterials(MaterialRegistryManager.java:88) ~[gtceu-1.21-1.3.1.jar%23379!/:?] {re:classloading}

### Steps to Reproduce

I don't really know, but try to lauch it with the mod that I have installed or check if it happen with specific graphic card or settings

### Additional Information

When I remove this mod the modpack launch without problem

I am using neoforge 21.0.76 (mekanism has a problem on this version, but it's not linked with this)

**Comment by modpacka2** [comment]
I test without the other mod and with only EMI and it work so I will try more things to find the real issue of compatibility I guess

**Comment by screret** [comment]
I don't see anything relating to your GPU here?

**Comment by modpacka2** [comment]
I found that it's link to mekanism, so I cannot know which mod as the issue. I was reporting here because the crash report was only saying that this mod is the issue in the modpack.
