### ISSUE TITLE
Solid fuel steam boilers (single block) randomly not accepting wooden planks, slabs and single charcoal

### ISSUE THREAD

**Issue by Michepoli** [GregTechCEu/GregTechCEu-1.19#1558]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.3.1

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

Gregtech comminuty pack modern

### Expected Behavior

Expected: boiler starts producing steam when planks/charcoal is placed inside as fuel

### Actual Behavior

Behavior 1: boiler won't accept planks either manually or through pipes
Behavior 2: boiler won't accept planks either manually or through pipes with oak planks being the exception
Behavior 3: planks/charcoal is accepted inside as fuel but boiler won't start producing, in both cases everything made from wood and charcoal blocks will work

### Steps to Reproduce

1) place a solid fuel boiler
2) open its GUI and try to manually place planks/charcoal or through pipes

**Comment by YoungOnionMC** [comment]
fixed in #1998
