### ISSUE TITLE
Steam extractors can not process recipes with fluid outputs

### ISSUE THREAD

**Issue by novaisadumbass** [GregTechCEu/GregTechCEu-1.19#1563]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.3.1 modern

### Recipe Viewer Installed

EMI

### Environment

Singleplayer, Server

### Cross-Mod Interaction

No

### Other Installed Mods

none, issue was reproduced on a clean instance of 1.20.1 with only gtceu modern.

### Expected Behavior

All extractors are supposed to be able to extract seed oil from seeds (per rei, emi).

### Actual Behavior

Both steam variant extractors do not extract seed oil.

### Steps to Reproduce

Power either steam extractor, place any seed variant inside, observe nothing being done.

### Additional Information

It works fine on lv+ extractors, i dunno if this is actually intended behavior but i think it would be weird and also it is incongruent with recepie viewer mods either way. hope this helps. i regret crafting 32 high pressure steam extractors lol

**Comment by MatthiasMann** [comment]
steam extractors only work on ULV recipes, not on LV or higher. Eg red alloy ingots don't work either but do in an LV extractor.

**Comment by novaisadumbass** [comment]
I am aware. The recipe is ULV.
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/80481728/2d4bbd37-a8f0-40c6-8592-54d6d2b25463)

**Comment by novaisadumbass** [comment]
I did some more testing and found out that steam extractors are not able to process any recipes that have a fluid output

**Comment by screret** [comment]
Correct.

**Comment by novaisadumbass** [comment]
why do they have a fluid slot and multiple ULV fluid output recipes then?

**Comment by screret** [comment]
Steam extractors have a fluid slot?
Also steam machines just run lv recipes

**Comment by novaisadumbass** [comment]
I am pretty sure ulv tier recipes are supposed to work in all machines, since it is the lowest tier, no?
Also both steam extractors have fluid slots and have had them since at least v1.0.16a, probably even before that though
This effects seed oil, fish oil, charcoal to wood tar and wood pulp to plant ball/creosote recipes
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/80481728/c18ed4f0-7972-4824-8994-2bb9df65b4ac)
