### ISSUE TITLE
Steam macerator only doing 1 cycle then stopping

### ISSUE THREAD

**Issue by Ashley123477** [GregTechCEu/GregTechCEu-1.19#1574]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-1.21-1.3.1

### Recipe Viewer Installed

EMI

### Environment

Single Player and Dedicated Server

### Cross-Mod Interaction

Yes

### Other Installed Mods

[mods.TXT](https://github.com/user-attachments/files/16182416/mods.TXT)

### Expected Behavior

Macerator to continue macerating items

### Actual Behavior

The macerator macerates one item then stops

### Steps to Reproduce

Put multiple items in steam macerator, it will only process one time, this does not happen with gregtech installed alone

### Additional Information

This does not happen with the steam compressor which is the only block i tried, just the macerator.

**Comment by YoungOnionMC** [comment]
Where is the vent output located

**Comment by Ashley123477** [comment]
my bad your right, i had a block behind the macerator and not behind the compressor, apologies
