### ISSUE TITLE
Question about state of Fabric loader support

### ISSUE THREAD

**Issue by nshcat** [GregTechCEu/GregTechCEu-1.19#1579]
Hello,

I hope issues are the right format for this question but - I am well aware that for testing and dev purposes, using Forge builds of this mod is recommended - probably also the reason for why the dev builds are released for forge only.

Im just wondering whether Fabric loader support is still planned for eventual releases, or if that goal has been dropped? 
If not, is it possible to build the mod for Fabric for dev purposes myself? If so, does the Fabric version have feature parity with the forge version?

Im thinking about contributing, and I'm mainly just curious about the planned course for this project.

Thanks!

**Comment by 3x1t-5tyl3** [comment]
Not a dev. But probably not. Fabric support was dropped some time ago. (About half a year)

https://github.com/GregTechCEu/GregTech-Modern/issues/1410#issuecomment-2165014432
Image links to the message on the discord.
[![Goe3GfUeEjckO51x](https://github.com/user-attachments/assets/eb8de97c-d619-4f6d-b142-6768d12e2259)](https://discord.com/channels/701354865217110096/1086528125711700028/1249044629886734448)

**Comment by htmlcsjs** [comment]
some more context 
![Screenshot_20240715-120013](https://github.com/user-attachments/assets/4d2625cd-2010-44ea-a8e7-3b646e75d66d)

**Comment by nshcat** [comment]
> some more context 
> ![Screenshot_20240715-120013](https://github.com/user-attachments/assets/4d2625cd-2010-44ea-a8e7-3b646e75d66d)
> 

Thank you! That does clear things up.

I wonder - the fabric version I tested had a sort of interactive compendium, the files for which were deleted in the commit that removed fabric support.

Is the compendium (called compass in the sources) a fabric feature?

**Comment by Deepacat** [comment]
Fabric is on a older version, compass has been disabled I'm newer ones due to it being very incomplete
