### ISSUE TITLE
Powered armour doesn't seem to be working

### ISSUE THREAD

**Issue by Wyrmlet** [GregTechCEu/GregTechCEu-1.19#1587]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.3.1

### Minecraft Version

1.20.1

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Fresh 1.20.1 instance with nothing besides GTCEu modern

### Expected Behavior

Powered armours added by the mod provide protection against enemy attacks.

### Actual Behavior

Powered armours do not provide any protection, damage recieved remains the same and the armour bar does not increase when the set is charged and worn.

### Steps to Reproduce

1. Equip any powered armour
2. No protection provided!

**Comment by screret** [comment]
already fixed.
