### ISSUE TITLE
It is impossible to create iridium without iridium.

### ISSUE THREAD

**Issue by 300f20t** [GregTechCEu/GregTechCEu-1.19#1588]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.3.1

### Minecraft Version

Forge 1.20.1

### Recipe Viewer Installed

JEI

### Environment

Dedicated Server or Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

AE2, ExtendedAE, CC:Tweaked.

### Expected Behavior

To be able to get iridium in survival.

### Actual Behavior

![image](https://github.com/user-attachments/assets/334a6c9e-64da-4552-a719-b373af3be53e)
![image](https://github.com/user-attachments/assets/5f90333b-b573-44c9-a5aa-26991e11b3dc)
![image](https://github.com/user-attachments/assets/24fd37a1-d08e-48c9-ac38-0398f2038ab8)
![image](https://github.com/user-attachments/assets/6458b5d1-b7f8-44fc-bc81-ecd540470bb9)
![image](https://github.com/user-attachments/assets/6c43cc4f-27eb-49eb-8e51-d93e793acc4f)
The iridium recipe is only available in the IV large chemical reactor, but an elite coil is needed to create it, which requires iridium. I couldn't find any other ways to get iridium, if there are any.

### Steps to Reproduce

To create a chemical reactor IV without iridium to produce iridium.

**Comment by YoungOnionMC** [comment]
use 2 ev energy hatches
