### ISSUE TITLE
Hazardous Materials Suits are displayed in wrong places in 1.19.2

### ISSUE THREAD

**Issue by BedrockComparator** [GregTechCEu/GregTechCEu-1.19#1599]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.2.3.a

### Minecraft Version

1.19.2

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

No other mods installed.

### Expected Behavior

Hazardous Materials Suits (including 4 armor pieces) should be displayed **only** in the "GregTechCEu Items" category in creative inventory.

### Actual Behavior

Hazardous Materials Suits are displayed in almost every categories (including vanilla ones and modded ones if other mods are installed) in creative inventory. 
![screenshot1](https://github.com/user-attachments/assets/943d4ffc-245b-44ac-8f54-5f65199af6a9)
There is even a Hazardous Materials Suit Chestpiece displayed over the "Destroy Item" slot.
![screenshot2](https://github.com/user-attachments/assets/d725adae-79ee-4883-b1df-014e3cbdbb4c)

### Steps to Reproduce

1) Switch to creative mode.
2) Press 'E' to open inventory and then browse the categories.
3) You can find out these Armors are displayed in wrong places.

### Additional Information

This bug only occurs in Minecraft 1.19.2 with GTM v1.2.3.a (the latest version for 1.19.2)
However, things works correctly in Minecraft 1.20.1 with GTM v1.2.3.a (and the latest version v1.3.1 for 1.20.1)

**Comment by screret** [comment]
1.19 is unsupported.
