### ISSUE TITLE
Vacuum Freezer requires Muffler hatch

### ISSUE THREAD

**Issue by Xefyr0** [GregTechCEu/GregTechCEu-1.19#1600]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.3.1

### Minecraft Version

1.20.1

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

N/A
Discovered in Monifactory Alpha, then reproduced on an instance running exclusively GTCEu.

### Expected Behavior

Vacuum Freezer multiblock would form without muffler hatch.
![2024-07-22_00 20 00](https://github.com/user-attachments/assets/7f8943f4-1369-4e03-8613-fd472bc698f5)

### Actual Behavior

Vacuum Freezer multiblock only forms with muffler hatch.
![2024-07-22_00 20 10](https://github.com/user-attachments/assets/0fce6401-c536-4e91-aa33-9ac8fe0283c8)

### Steps to Reproduce

1. Create new instance in Prism launcher with:
Minecraft 1.20.1
Forge 47.2.21
GTCEU 1.3.1
2. Create New World
3. Try to form Vacuum Freezer multiblock.

### Additional Information

According to those I contacted about this issue in the Monifactory Discord, the Muffler Hatch was not used in the Vacuum Freezer in 1.12 GT, or in GTCEu until recently.

**Comment by screret** [comment]
intended.
