### ISSUE TITLE
Error in machines

### ISSUE THREAD

**Issue by Water-Gate-King** [GregTechCEu/GregTechCEu-1.19#1608]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.3.1

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

Xaero's map, Create, Patchouli, Embeddium, Ferritecore, Kubejs, Jade, The One Prode, Oculus, NuclearCraft Neoteric

### Expected Behavior

The machine works

### Actual Behavior

The GUI turns to black, and soon the game reports error

### Steps to Reproduce

https://github.com/user-attachments/assets/2b827b50-2313-4a1e-914d-e9138b2c71a5

**Comment by screret** [comment]
Crash log?

**Comment by Water-Gate-King** [comment]
Crash log
[crashlog.log](https://github.com/user-attachments/files/16362486/crashlog.log)

**Comment by screret** [comment]
I need the crash report

**Comment by Water-Gate-King** [comment]
This issue appeared again.
The game does not crash, just exits from the world. How do I get crush report?
In addition, I find that 1.3.0a does not have this issue, only 1.3.1

**Comment by screret** [comment]
do you have a debug.log?

**Comment by Water-Gate-King** [comment]
[debug-1.log](https://github.com/user-attachments/files/16573457/debug-1.log)

**Comment by screret** [comment]
what if you remove minecraft transit railway?

**Comment by Water-Gate-King** [comment]
not work

**Comment by Water-Gate-King** [comment]
I have found the source of this issue: interaction with The One Probe.
