### ISSUE TITLE
Disappearance of liquid

### ISSUE THREAD

**Issue by Li14i4a** [GregTechCEu/GregTechCEu-1.19#1610]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-1.20.1-1.3.1

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

Dedicated Server.

### Cross-Mod Interaction

Unsure

### Other Installed Mods

badpackets-forge-0.4.3.jar
balm-forge-1.20.1-7.2.2.jar
BetterF3-7.0.2-Forge-1.20.1.jar
Bookshelf-Forge-1.20.1-20.1.10.jar
buildinggadgets2-1.0.7.jar
bwncr-forge-1.20.1-3.17.0.jar
centurybranding-1.0.0.jar
clienttweaks-forge-1.20-11.1.0.jar
cloth-config-11.1.118-forge.jar
Clumps-forge-1.20.1-12.0.0.4.jar
cmapi-0.0.1.jar
cmcore-0.0.1-client.jar
cmfixed-0.0.1.jar
cmhelper-0.0.1.jar
cmmisc-0.0.1-client-proguard.jar
cmsync-0.0.1-client.jar
cmworld-0.0.1-client.jar
configured-forge-1.20.1-2.2.3.jar
Controlling-forge-1.20.1-12.0.2.jar
craftingtweaks-forge-1.20.1-18.2.3.jar
curios-forge-5.9.0+1.20.1.jar
DarkModeEverywhere-1.20.1-1.2.2.jar
defaultoptions-forge-1.20-18.0.1.jar
elevatorid-1.20.1-lex-1.9.jar
embeddium-0.3.19+mc1.20.1-all.jar
embeddiumplus-1.20.1-v1.2.12.jar
ExtendedAE-1.20-1.1.9-forge.jar
FastLeafDecay-31.jar
Fastload-Reforged-mc1.20.1-3.4.0.jar
FastSuite-1.20.1-5.0.1.jar
ferritecore-6.0.1-forge.jar
findme-3.2.1-forge.jar
Forgematica-0.1.5-mc1.20.1.jar
FpsReducer2-forge-1.20-2.5.jar
FramedBlocks-9.2.2.jar
ftb-library-forge-2001.2.1.jar
ftb-quests-forge-2001.4.2.jar
ftb-teams-forge-2001.3.0.jar
ftb-xmod-compat-forge-2.1.1.jar
Glodium-1.20-1.5-forge.jar
gtceu-1.20.1-1.3.1.jar
Iceberg-1.20.1-forge-1.1.16.jar
Iceberg-1.20.1-forge-1.1.21.jar
inventoryessentials-forge-1.20.1-8.2.3.jar
item-filters-forge-2001.1.0-build.59.jar
Jade-1.20.1-forge-11.6.3.jar
jei-1.20.1-forge-15.3.0.8.jar
JustEnoughResources-1.20.1-1.4.0.247.jar
justzoom_forge_1.0.2_MC_1.20.1.jar
konkrete_forge_1.8.0_MC_1.20-1.20.1.jar
kotlinforforge-4.10.0-all.jar
kubejs-forge-2001.6.5-build.11.jar
LegendaryTooltips-1.20.1-forge-1.4.5.jar
libIPN-forge-1.20-4.0.2.jar
lootjs-forge-1.20.1-2.11.0.jar
MaFgLib-0.1.11-mc1.20.1.jar
melody_forge_1.0.3_MC_1.20.1-1.20.4.jar
modernfix-forge-5.17.0+mc1.20.1.jar
MouseTweaks-forge-mc1.20-2.25.jar
MyServerIsCompatible-1.20-1.0.jar
NoChatReports-FORGE-1.20.1-v2.2.2.jar
notenoughcrashes-4.4.6+1.20.1-forge.jar
Placebo-1.20.1-8.6.1.jar
polylib-forge-2000.0.3-build.133.jar
polymorph-forge-0.49.3+1.20.1.jar
Prism-1.20.1-forge-1.0.5.jar
rhino-forge-2001.2.2-build.18.jar
rubidium-extra-0.5.4.3+mc1.20.1-build.121.jar
Searchables-forge-1.20.1-1.0.3.jar
Shimmer-forge-1.20.1-0.2.4.jar
smoothboot(reloaded)-mc1.20.1-0.0.4.jar
sophisticatedbackpacks-1.20.1-3.20.5.1044.jar
sophisticatedcore-1.20.1-0.6.22.611.jar
sophisticatedstorage-1.20.1-0.10.25.804.jar
spark-1.10.53-forge.jar
starlight-1.1.2+forge.1cda73c.jar
trofers-forge-5.0.2.jar
voicechat-forge-1.20.1-2.5.15.jar
worldeditcui-1.20.1.jar
Xaeros_Minimap_24.2.0_Forge_1.20.jar
XaerosWorldMap_1.38.8_Forge_1.20.jar
xtonesreworked-1.0.1-F_1.20.1-47.2.0.jar
3dskinlayers-forge-1.5.4-mc1.20.1.jar
alternate_current-mc1.20-1.7.0.jar
appleskin-forge-mc1.20.1-2.5.1.jar
appliedenergistics2-forge-15.2.1.jar
Architects-Palette-1.20.1-1.3.6.1.jar
architectury-9.2.14-forge.jar
AttributeFix-Forge-1.20.1-21.0.4.jar

### Expected Behavior

A tank broken by a magnesium drill goes into inventory with liquid

### Actual Behavior

If you break a barrel/super tank with a magnetism drill (maybe other tools with magnetism), the liquid in the tank will disappear.

### Steps to Reproduce

A tank broken by a magnesium drill goes into inventory without liquid

### Additional Information

1) put a tank/super tank with liquid
2) break with a drill with magnetism (made of naquadah alloy or other materials)
3) observe a clean tank without liquid

**Comment by forteen14desu** [comment]
already fixed in 1.3.1-build_880, using the latest build can solve the problem.
