### ISSUE TITLE
using FluxNetworks in GTM machines cause crashed

### ISSUE THREAD

**Issue by MotocoZg** [GregTechCEu/GregTechCEu-1.19#1615]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-1.20.1-1.3.1

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

Singleplayer,

### Cross-Mod Interaction

Yes

### Other Installed Mods

ad_astra-forge-1.20.1-1.15.19.jar
ad_astra_rocketed-forge-1.20.1-1.0.3.jar
ae2wtlib-15.2.3-forge.jar
AngelRing2-1.20.1-2.2.2.jar
Applied-Mekanistics-1.4.2.jar
appliedenergistics2-forge-15.2.10.jar
AppliedFlux-1.20-1.1.7-forge.jar
architectury-9.2.14-forge.jar
balm-forge-1.20.1-7.3.6-all.jar
bigger_ae2-1.20.1-1.3.4.jar
botarium-forge-1.20.1-2.3.4.jar
buildinggadgets2-1.0.7.jar
cloth-config-11.1.118-forge.jar
constructionwand-1.20.1-2.11.jar
CTM_DEV-1.20.1-1.1.8+6.jar
curios-forge-5.9.1+1.20.1.jar
embeddium-0.3.27+mc1.20.1.jar
embeddiumplus-1.20.1-v1.2.13.jar
ExtendedAE-1.20-1.1.11-forge.jar
FastFurnace-1.20.1-8.0.2.jar
FastLeafDecay-32.jar
FastSuite-1.20.1-5.0.1.jar
FastWorkbench-1.20.1-8.0.4.jar
ferritecore-6.0.1-forge.jar
FluxNetworks-1.20.1-7.2.1.15.jar
ftb-chunks-forge-2001.3.1.jar
ftb-essentials-forge-2001.2.2.jar
ftb-library-forge-2001.2.3.jar
ftb-quests-forge-2001.4.8.jar
ftb-teams-forge-2001.3.0.jar
ftb-ultimine-forge-2001.1.5.jar
ftb-xmod-compat-forge-2.1.1.jar
ftbbackups2-forge-1.20-1.0.23.jar
Glodium-1.20-1.5-forge.jar
gpumemleakfix-1.20.1-1.8.jar
gregiceng-1.20.1-1.0.5-fix.jar
gtceu-1.20.1-1.3.1.jar
gtmthings-1.3.0.jar
Infinity Cells-1.0.0.jar
invtweaks-1.20.1-1.1.0.jar
Jade-1.20.1-forge-11.9.4.jar
jecharacters-1.20.1-forge-4.5.11.jar
jei-1.20.1-forge-15.8.0.17.jar
jeiintegration_1.20.1-10.0.0.jar
JustEnoughResources-1.20.1-1.4.0.247.jar
kubejs-forge-2001.6.5-build.14.jar
laserio-1.6.8.jar
LibX-1.20.1-5.0.14.jar
mae2-1.2.1.jar
Mekanism-1.20.1-10.4.8.43.jar
MekanismGenerators-1.20.1-10.4.8.43.jar
memoryleakfix-forge-1.17+-1.1.5.jar
merequester-forge-1.20.1-1.1.4.jar
modernfix-forge-5.18.10+mc1.20.1.jar
ModernUI-Forge-1.20.1-3.10.1.4-universal.jar
monomorphism-1.20.1-1.1.1.jar
MouseTweaks-forge-mc1.20.1-2.25.1.jar
oculus-mc1.20.1-1.7.0.jar
PackMenu-1.20.1-6.1.1.jar
pipez-forge-1.20.1-1.2.12-GTLE.jar
Placebo-1.20.1-8.6.2.jar
polylib-forge-2000.0.3-build.143.jar
radium-mc1.20.1-0.12.3+git.50c5c33.jar
Re-Avaritia-forged-1.20.1-1.3.8.2.jar
redirector-5.0.0.jar
resourcefulconfig-forge-1.20.1-2.1.2.jar
resourcefullib-forge-1.20.1-2.1.25.jar
rhino-forge-2001.2.2-build.18.jar
rubidium-extra-0.5.4.3+mc1.20.1-build.121.jar
storagedrawers-1.20.1-12.0.3.jar
ToolBelt-1.20.1-1.20.01.jar
TravelAnchors-1.20.1-5.0.1.jar
CustomSkinLoader_ForgeActive-14.19.1.jar
cookingforblockheads-forge-1.20.1-16.0.6.jar
InGameAccountSwitcher-Forge-1.20-8.0.2.jar

### Expected Behavior

mod Flux Networks provide GTEU to the machine

### Actual Behavior

cause crashed

### Steps to Reproduce

1、Flux Point connected to GT machines
2、cause crashed

### Additional Information

maybe it's caused by #1593

**Comment by MotocoZg** [comment]
[crash-2024-07-27_13.35.22-server.txt](https://github.com/user-attachments/files/16398350/crash-2024-07-27_13.35.22-server.txt)

**Comment by screret** [comment]
flux networks issue.
