### ISSUE TITLE
Recycling Cut Copper blocks in Arc Furnace and Macerator

### ISSUE THREAD

**Issue by Largechemicalreactor** [GregTechCEu/GregTechCEu-1.19#1623]
### Feature Description

I noticed there is no recipe to recycle Cut Copper block, Stairs and Slabs in either the Arc Furnace and or Macerator.

Using the crafting table recipe, 4 Cut Copper blocks is made with 4 Copper blocks. However, the Stonecutter recipe grants 4 Cut Copper Blocks with just 1 Copper Block. So recycling Cut Copper block should give 2 Copper ingots (rounded down from 2,25), if the Stonecutter is used to get the ratios.

Since Cut Copper Slabs is half of a block, it should give 1 Copper ingot.

The Cut Copper Stairs could also grant 2 Copper ingots as a Stonecutter recipe equates Cut Copper Stairs to Cut Copper Blocks. However, 4 Cut Copper Stairs can be made with 6 Cut Copper blocks, so it could also grant 0,375 ingot per Stair. 0,375 ingot is equivalent to 1,5 small dust, or 3,375 tiny dust.

**Comment by YoungOnionMC** [comment]
fixed in #2563
