### ISSUE TITLE
crashes with kubejs

### ISSUE THREAD

**Issue by redgoblin88** [GregTechCEu/GregTechCEu-1.19#1624]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.3.1

### Minecraft Version

1.21

### Recipe Viewer Installed

No Recipe Viewer

### Environment

singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

LDLib 1.0.26.a (dependency for gretech)
kubejs 2100.7.0-B117
rhino 2100.2.5-B44 (dependency for kubejs)

### Expected Behavior

to be able to make a new world and join it

### Actual Behavior

crashes upon clicking "create new world"

### Steps to Reproduce

1. create a blank instance with only the 4 mods listed (this includes gregtech of course)
2. go to "create new world"
3. crash

### Additional Information

crashlog: https://paste.gg/p/anonymous/3d3c1f8b88a84e6bb93bf58d54d577f2

I have contacted kubejs discord asking if theres a "more stable" version of kubejs as i assumed that was the problem, however lat pointed out this is a "outdated kjs addon"

**Comment by DrDarkfire** [comment]
I have had this happen to me in my own pack also.

Upon removal of kubejs I can create a new world, but all mod recipes seem to get nuked in the process. I have AoA amongst other mods in my modpack and everything is uncraftable including GT stuff.
