### ISSUE TITLE
game crash by trying to load a world

### ISSUE THREAD

**Issue by GalaxyOfZero** [GregTechCEu/GregTechCEu-1.19#1630]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.20.1-1,3,1

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

Singelplayer

### Cross-Mod Interaction

No

### Other Installed Mods

 architectury 9.2.14,  jei-1.20.1 15.8.2.25, kubejs 2001.6.5-build.14, rhino 2001.2.2-build.18

### Expected Behavior

by trying to load a world the game crash instaly

### Actual Behavior

[crash-2024-07-31_19.18.32-client.txt](https://github.com/user-attachments/files/16445189/crash-2024-07-31_19.18.32-client.txt)

### Steps to Reproduce

1) install from the Other Installed Mods line
2) start game and create a world
3) game will crash

**Comment by screret** [comment]
already fixed.

**Comment by GalaxyOfZero** [comment]
> already fixed.

it is good to know but ther is no new version or a update

**Comment by screret** [comment]
yes there is.

**Comment by screret** [comment]
![image](https://github.com/user-attachments/assets/1983038b-72b7-46ff-99e6-b242c922c8dc)

**Comment by GalaxyOfZero** [comment]
okay then i have to wait of CurseForge then -_-
