### ISSUE TITLE
Crash with gregtech, JEI, Jade, and JEI integrations

### ISSUE THREAD

**Issue by donoya** [GregTechCEu/GregTechCEu-1.19#1632]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.3.1

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

JEI, Jade, JEI integrations

### Expected Behavior

Upon attempting to join a world, the game should render and be playable.

### Actual Behavior

The game crashes upon attempting to join a world.

### Steps to Reproduce

Start minecraft, start a new singleplayer world.

**Comment by donoya** [comment]
Here's the logs (both crash report and latest log). Crash report: https://pastebin.com/hvervfTW Log: https://pastebin.com/Qmu2AfGg

**Comment by donoya** [comment]
I've narrowed it down to just JEI and gregtech.

**Comment by screret** [comment]
Already fixed.

**Comment by Deepacat** [comment]
Install latest ldlib to fix it until the next gtm release where it's built in
