### ISSUE TITLE
Power Substations can't receive lasers until they've been "started" by a regular energy hatch.

### ISSUE THREAD

**Issue by fmbellomy** [GregTechCEu/GregTechCEu-1.19#1656]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.3.1

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Dedicated Server

### Cross-Mod Interaction

No

### Other Installed Mods

Monifactory 0.7.0a

### Expected Behavior

Expected power to transfer from full power substation into empty power substation via lasers alone.

### Actual Behavior

Energy successfully transferred to the _target hatch,_ but did not then get pulled into the multiblock's internal buffer. It only started to pull from the target hatch when the power substation received power through other means.

### Steps to Reproduce

Create a power substation and try to send energy into it with a laser hatch.

**Comment by YoungOnionMC** [comment]
works as of 1.6.1, closing
