### ISSUE TITLE
The game crashed whilst initializing game 1.21 NEOFORGE

### ISSUE THREAD

**Issue by Rislir** [GregTechCEu/GregTechCEu-1.19#1663]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.3.1

### Minecraft Version

1.21

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

JEI

### Expected Behavior

For the game to launch without crashing.

### Actual Behavior

The game crashed whilst initializing game
Error: java.lang.IllegalStateException: Cannot retrieve all materials before registration

### Steps to Reproduce

The game crashes when trying to run. Only 2 mods are installed (gregtechceu modern 1.3.1 + JEI 19.7.0.92 ) NEOFORGE

### Additional Information

If you remove JEI, everything works, but it's impossible to play without it...

**Comment by screret** [comment]
jei made a breaking update, we haven't updated to it.

**Comment by Rislir** [comment]
Do I need to install an older JEI?

> jei made a breaking update, we haven't updated to it.

**Comment by screret** [comment]
yes. or emi.

**Comment by Rislir** [comment]
> yes. or emi.

EMI or JEI better for interacting with GregTech?

**Comment by screret** [comment]
imo, EMI
