### ISSUE TITLE
Game crush when enter a world

### ISSUE THREAD

**Issue by Water-Gate-King** [GregTechCEu/GregTechCEu-1.19#1679]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.3.1build938

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

Mod List: 
		dynamiclightsreforged-1.20.1_v1.6.0.jar|Rubidium Dynamic Lights       |dynamiclightsreforged         |1.20.1_v1.6.0       |PROCESS_IM|Manifest: NOSIGNATURE
		terrestria-6.0.13$terraform-tree-api-v1-7.0.3_mapp|Terraform Tree API (v1)       |terraform_tree_api_v1         |7.0.3               |PROCESS_IM|Manifest: NOSIGNATURE
		kuma-api-forge-20.1.8+1.20.1.jar                  |KumaAPI                       |kuma_api                      |20.1.8              |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-renderer-api-v1-3.2.1+1d29b44577.jar       |Fabric Renderer API (v1)      |fabric_renderer_api_v1        |3.2.1+1d29b44577    |PROCESS_IM|Manifest: NOSIGNATURE
		netherportalfix-forge-1.20-13.0.1.jar   |NetherPortalFix               |netherportalfix               |13.0.1              |PROCESS_IM|Manifest: NOSIGNATURE
		createdeco-2.0.2-1.20.1-forge.jar                 |Create Deco                   |createdeco                    |2.0.2-1.20.1-forge  |PROCESS_IM|Manifest: NOSIGNATURE
		botarium-forge-1.20.1-2.3.4.jar                   |Botarium                      |botarium                      |2.3.4               |PROCESS_IM|Manifest: NOSIGNATURE
		kubejs-bridge-1.11.2+1.20.1.jar                   |Connector Extras KubeJS Bridge|connectorextras_kubejs_bridge |1.11.2+1.20.1       |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-item-api-v1-2.1.28+4d0bbcfa77.jar          |Fabric Item API (v1)          |fabric_item_api_v1            |2.1.28+4d0bbcfa77   |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-rendering-fluids-v1-3.0.28+4ac5e37a77.jar  |Fabric Rendering Fluids (v1)  |fabric_rendering_fluids_v1    |3.0.28+4ac5e37a77   |PROCESS_IM|Manifest: NOSIGNATURE
		terrestria-6.0.13$terrestria-common-6.0.13_mapped_|Terrestria: Common            |terrestria_common             |6.0.13              |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-models-v0-0.4.2+7c3892a477.jar             |Fabric Models (v0)            |fabric_models_v0              |0.4.2+7c3892a477    |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-convention-tags-v1-1.5.5+fa3d1c0177.jar    |Fabric Convention Tags        |fabric_convention_tags_v1     |1.5.5+fa3d1c0177    |PROCESS_IM|Manifest: NOSIGNATURE
		XaerosWorldMap_1.38.8_Forge_1.20.jar |Xaero's World Map             |xaeroworldmap                 |1.38.8              |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-command-api-v1-1.2.34+f71b366f77.jar       |Fabric Command API (v1)       |fabric_command_api_v1         |1.2.34+f71b366f77   |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-block-view-api-v2-1.0.1+0767707077.jar     |Fabric BlockView API (v2)     |fabric_block_view_api_v2      |1.0.1+0767707077    |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-command-api-v2-2.2.13+561530ec77.jar       |Fabric Command API (v2)       |fabric_command_api_v2         |2.2.13+561530ec77   |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-data-attachment-api-v1-1.0.0+30ef839e77.jar|Fabric Data Attachment API (v1|fabric_data_attachment_api_v1 |1.0.0+30ef839e77    |PROCESS_IM|Manifest: NOSIGNATURE
		mixinextras-forge-0.2.0.jar                       |MixinExtras                   |mixinextras                   |0.2.0               |PROCESS_IM|Manifest: NOSIGNATURE
		rei-bridge-1.11.2+1.20.1.jar                      |Connector Extras REI Bridge   |connectorextras_rei_bridge    |1.11.2+1.20.1       |PROCESS_IM|Manifest: NOSIGNATURE
		terrestria-6.0.13$biolith-1.0.0-beta.1_mapped_srg_|Biolith                       |biolith                       |1.0.0-beta.1        |PROCESS_IM|Manifest: NOSIGNATURE
		create_dragon_lib-1.20.1-1.4.3.jar                |Create: Dragon Lib            |create_dragon_lib             |1.4.3               |PROCESS_IM|Manifest: NOSIGNATURE
		createdieselgenerators-1.20.1-1.2i.jar|Create Diesel Generators      |createdieselgenerators        |1.20.1-1.2i         |PROCESS_IM|Manifest: NOSIGNATURE
		ldlib-forge-1.20.1-1.0.26.jar                     |LowDragLib                    |ldlib                         |1.0.26              |PROCESS_IM|Manifest: NOSIGNATURE
		balm-forge-1.20.1-7.3.6-all.jar                   |Balm                          |balm                          |7.3.6               |PROCESS_IM|Manifest: NOSIGNATURE
		Steam_Rails-1.6.4+forge-mc1.20.1.jar  |Create: Steam 'n' Rails       |railways                      |1.6.4+forge-mc1.20.1|PROCESS_IM|Manifest: NOSIGNATURE
		fabric-screen-api-v1-2.0.8+45a670a577.jar         |Fabric Screen API (v1)        |fabric_screen_api_v1          |2.0.8+45a670a577    |PROCESS_IM|Manifest: NOSIGNATURE
		terrestria-6.0.13$terrestria-worldgen-6.0.13_mappe|Terrestria: World Generation  |terrestria_worldgen           |6.0.13              |PROCESS_IM|Manifest: NOSIGNATURE
		FpsReducer2-forge-1.20-2.5.jar           |FPS Reducer                   |fpsreducer                    |1.20-2.5            |PROCESS_IM|Manifest: NOSIGNATURE
		cloth-config-11.1.118-forge.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.118            |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-api-0.92.2+1.11.8+1.20.1.jar               |Forgified Fabric API          |fabric_api                    |0.92.2+1.11.8+1.20.1|PROCESS_IM|Manifest: NOSIGNATURE
		modmenu-bridge-1.11.2+1.20.1.jar                  |Connector Extras ModMenu Bridg|connectorextras_modmenu_bridge|1.11.2+1.20.1       |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-content-registries-v0-4.0.11+a670df1e77.jar|Fabric Content Registries (v0)|fabric_content_registries_v0  |4.0.11+a670df1e77   |PROCESS_IM|Manifest: NOSIGNATURE
		embeddium-0.3.28+mc1.20.1.jar                     |Embeddium                     |embeddium                     |0.3.28+mc1.20.1     |PROCESS_IM|Manifest: NOSIGNATURE
		terrablender-bridge-1.11.2+1.20.1.jar             |Connector Extras Terrablender |connectorextras_terrablender_b|1.11.2+1.20.1       |PROCESS_IM|Manifest: NOSIGNATURE
		terrestria-6.0.13$terraform-shapes-api-v1-7.0.3_ma|Terraform Shapes API (v1)     |terraform_shapes_api_v1       |7.0.3               |PROCESS_IM|Manifest: NOSIGNATURE
		terrestria-6.0.13$terraform-surfaces-api-v1-7.0.3_|Terraform Surfaces API (v1)   |terraform_surfaces_api_v1     |7.0.3               |PROCESS_IM|Manifest: NOSIGNATURE
		FarmersDelight-1.20.1-1.2.4.jar            |Farmer's Delight              |farmersdelight                |1.20.1-1.2.4        |ERROR     |Manifest: NOSIGNATURE
		fabric-game-rule-api-v1-1.0.40+683d4da877.jar     |Fabric Game Rule API (v1)     |fabric_game_rule_api_v1       |1.0.40+683d4da877   |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-api-lookup-api-v1-1.6.36+67f9824077.jar    |Fabric API Lookup API (v1)    |fabric_api_lookup_api_v1      |1.6.36+67f9824077   |PROCESS_IM|Manifest: NOSIGNATURE
		reach-entity-attributes-2.4.0.jar                 |Reach Entity Attributes       |reach_entity_attributes       |2.4.0               |PROCESS_IM|Manifest: NOSIGNATURE
		architectury-bridge-1.11.2+1.20.1.jar             |Connector Extras Architectury |connectorextras_architectury_b|1.11.2+1.20.1       |PROCESS_IM|Manifest: NOSIGNATURE
		Patchouli-1.20.1-84-FORGE.jar             |Patchouli                     |patchouli                     |1.20.1-84-FORGE     |PROCESS_IM|Manifest: NOSIGNATURE
		oculus-mc1.20.1-1.7.0.jar                         |Oculus                        |oculus                        |1.7.0               |PROCESS_IM|Manifest: NOSIGNATURE
		Connector-1.0.0-beta.45+1.20.1-mod.jar            |Connector                     |connectormod                  |1.0.0-beta.45+1.20.1|PROCESS_IM|Manifest: NOSIGNATURE
		fabric-entity-events-v1-1.6.0+6274ab9d77.jar      |Fabric Entity Events (v1)     |fabric_entity_events_v1       |1.6.0+6274ab9d77    |PROCESS_IM|Manifest: NOSIGNATURE
		InventoryProfilesNext-forge-1.20-1.10|Inventory Profiles Next       |inventoryprofilesnext         |1.10.10             |PROCESS_IM|Manifest: NOSIGNATURE
		architectury-9.2.14-forge.jar                     |Architectury                  |architectury                  |9.2.14              |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-loot-api-v2-1.2.1+eb28f93e77.jar           |Fabric Loot API (v2)          |fabric_loot_api_v2            |1.2.1+eb28f93e77    |PROCESS_IM|Manifest: NOSIGNATURE
		ConnectorExtras-1.11.2+1.20.1.jar                 |Connector Extras              |connectorextras               |1.11.2+1.20.1       |PROCESS_IM|Manifest: NOSIGNATURE
		terrestria-6.0.13$terrestria-client-6.0.13_mapped_|Terrestria: Client            |terrestria_client             |6.0.13              |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-rendering-data-attachment-v1-0.3.37+a6081af|Fabric Rendering Data Attachme|fabric_rendering_data_attachme|0.3.37+a6081afc77   |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-networking-api-v1-1.3.11+503a202477.jar    |Fabric Networking API (v1)    |fabric_networking_api_v1      |1.3.11+503a202477   |PROCESS_IM|Manifest: NOSIGNATURE
		JadeAddons-1.20.1-Forge-5.3.0.jar                 |Jade Addons                   |jadeaddons                    |5.3.0+forge         |PROCESS_IM|Manifest: NOSIGNATURE
		probejs-7.0.1-forge.jar                           |ProbeJS                       |probejs                       |7.0.1               |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-lifecycle-events-v1-2.2.22+afab492177.jar  |Fabric Lifecycle Events (v1)  |fabric_lifecycle_events_v1    |2.2.22+afab492177   |PROCESS_IM|Manifest: NOSIGNATURE
		terrestria-6.0.13$terraform-biome-remapper-api-v1-|Terraform Biome Remapper API (|terraform_biome_remapper_api_v|7.0.3               |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-key-binding-api-v1-1.0.37+561530ec77.jar   |Fabric Key Binding API (v1)   |fabric_key_binding_api_v1     |1.0.37+561530ec77   |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-client-tags-api-v1-1.1.2+5d6761b877.jar    |Fabric Client Tags            |fabric_client_tags_api_v1     |1.1.2+5d6761b877    |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-transfer-api-v1-3.3.5+631c9cd677.jar       |Fabric Transfer API (v1)      |fabric_transfer_api_v1        |3.3.5+631c9cd677    |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-dimensions-v1-2.1.54+8005d10d77.jar        |Fabric Dimensions API (v1)    |fabric_dimensions_v1          |2.1.54+8005d10d77   |PROCESS_IM|Manifest: NOSIGNATURE
		terrestria-6.0.13_mapped_srg_1.20.1.jar           |Terrestria                    |terrestria                    |6.0.13              |PROCESS_IM|Manifest: NOSIGNATURE
		[犀牛] rhino-forge-2001.2.2-build.18.jar            |Rhino                         |rhino                         |2001.2.2-build.18   |PROCESS_IM|Manifest: NOSIGNATURE
		kubejs-forge-2001.6.5-build.14.jar                |KubeJS                        |kubejs                        |2001.6.5-build.14   |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-model-loading-api-v1-1.0.3+6274ab9d77.jar  |Fabric Model Loading API (v1) |fabric_model_loading_api_v1   |1.0.3+6274ab9d77    |PROCESS_IM|Manifest: NOSIGNATURE
		pehkui-bridge-1.11.2+1.20.1.jar                   |Connector Extras Pehkui Bridge|connectorextras_pehkui_bridge |1.11.2+1.20.1       |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-screen-handler-api-v1-1.3.30+561530ec77.jar|Fabric Screen Handler API (v1)|fabric_screen_handler_api_v1  |1.3.30+561530ec77   |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-resource-loader-v0-0.11.10+bcd08ed377.jar  |Fabric Resource Loader (v0)   |fabric_resource_loader_v0     |0.11.10+bcd08ed377  |PROCESS_IM|Manifest: NOSIGNATURE
		CreateHeatJS-1.20.1-0.0.2.jar                     |CreateHeatJS                  |create_heat_js                |1.20.1-0.0.2        |PROCESS_IM|Manifest: NOSIGNATURE
		terrestria-6.0.13$terraform-config-api-v1-7.0.3_ma|Terraform Config API (v1)     |terraform_config_api_v1       |7.0.3               |PROCESS_IM|Manifest: NOSIGNATURE
		terrestria-6.0.13$terraform-wood-api-v1-7.0.3_mapp|Terraform Wood API (v1)       |terraform_wood_api_v1         |7.0.3               |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-rendering-v1-3.0.8+66e9a48f77.jar          |Fabric Rendering (v1)         |fabric_rendering_v1           |3.0.8+66e9a48f77    |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-renderer-indigo-1.5.2+b5b2da4177.jar       |Fabric Renderer - Indigo      |fabric_renderer_indigo        |1.5.2+b5b2da4177    |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-mining-level-api-v1-2.1.50+561530ec77.jar  |Fabric Mining Level API (v1)  |fabric_mining_level_api_v1    |2.1.50+561530ec77   |PROCESS_IM|Manifest: NOSIGNATURE
		SereneSeasons-1.20.1-9.0.0.46.jar       |Serene Seasons                |sereneseasons                 |9.0.0.46            |PROCESS_IM|Manifest: NOSIGNATURE
		geckolib-fabric-compat-1.11.2+1.20.1.jar          |Connector Extras Geckolib-Fabr|connectorextras_geckolib_fabri|1.11.2+1.20.1       |PROCESS_IM|Manifest: NOSIGNATURE
		gtceu-1.20.1-1.3.1-build_938.jar                  |GregTech                      |gtceu                         |1.3.1-build_938     |PROCESS_IM|Manifest: NOSIGNATURE
		MTR-forge-4.0.0-beta-8+1.20.1.jar        |Minecraft Transit Railway     |mtr                           |4.0.0-beta-8        |PROCESS_IM|Manifest: NOSIGNATURE
		PineappleDelight-Forge-1.20-1.0.8-Fix2.jar |Pineapple Delight             |pineapple_delight             |1.0.8               |PROCESS_IM|Manifest: NOSIGNATURE
		energy-bridge-1.11.2+1.20.1.jar                   |Connector Extras Energy Bridge|connectorextras_energy_bridge |1.11.2+1.20.1       |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-particles-v1-1.1.2+78e1ecb877.jar          |Fabric Particles (v1)         |fabric_particles_v1           |1.1.2+78e1ecb877    |PROCESS_IM|Manifest: NOSIGNATURE
		forge-1.20.1-47.3.5-universal.jar                 |Forge                         |forge                         |47.3.5              |ERROR     |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		fabric-transitive-access-wideners-v1-4.3.1+1880499|Fabric Transitive Access Widen|fabric_transitive_access_widen|4.3.1+1880499877    |PROCESS_IM|Manifest: NOSIGNATURE
		tectonic-forge-1.19.3-2.3.5a.jar                  |Tectonic                      |tectonic                      |2.3.5a              |PROCESS_IM|Manifest: NOSIGNATURE
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |PROCESS_IM|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		emi-1.1.10+1.20.1+forge.jar                       |EMI                           |emi                           |1.1.10+1.20.1+forge |PROCESS_IM|Manifest: NOSIGNATURE
		libIPN-forge-1.20-4.0.2.jar                       |libIPN                        |libipn                        |4.0.2               |PROCESS_IM|Manifest: NOSIGNATURE
		theoneprobe-1.20.1-10.0.2.jar                     |The One Probe                 |theoneprobe                   |1.20.1-10.0.2       |ERROR     |Manifest: NOSIGNATURE
		fabric-api-base-0.4.31+ef105b4977.jar             |Fabric API Base               |fabric_api_base               |0.4.31+ef105b4977   |PROCESS_IM|Manifest: NOSIGNATURE
		configuration-forge-1.20.1-2.2.0.jar              |Configuration                 |configuration                 |2.2.0               |PROCESS_IM|Manifest: NOSIGNATURE
		mysterious_mountain_lib-1.4.7-1.20.1.jar          |Mysterious Mountain Lib       |mysterious_mountain_lib       |1.4.7-1.20.1        |PROCESS_IM|Manifest: NOSIGNATURE
		corn_delight-1.0.4-1.20.1.jar              |Corn Delight                  |corn_delight                  |1.0.4-1.20.1        |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-blockrenderlayer-v1-1.1.41+1d0da21e77.jar  |Fabric BlockRenderLayer Regist|fabric_blockrenderlayer_v1    |1.1.41+1d0da21e77   |PROCESS_IM|Manifest: NOSIGNATURE
		Jade-1.20.1-forge-11.9.4.jar               |Jade                          |jade                          |11.9.4+forge        |PROCESS_IM|Manifest: NOSIGNATURE
		amecsapi-1.5.3+mc1.20-pre1.jar                    |Amecs API                     |amecsapi                      |1.5.3+mc1.20-pre1   |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-block-api-v1-1.0.11+0e6cb7f777.jar         |Fabric Block API (v1)         |fabric_block_api_v1           |1.0.11+0e6cb7f777   |PROCESS_IM|Manifest: NOSIGNATURE
		jei-bridge-1.11.2+1.20.1.jar                      |Connector Extras JEI Bridge   |connectorextras_jei_bridge    |1.11.2+1.20.1       |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-resource-conditions-api-v1-2.3.8+9ad825cd77|Fabric Resource Conditions API|fabric_resource_conditions_api|2.3.8+9ad825cd77    |PROCESS_IM|Manifest: NOSIGNATURE
		forgeconfigapiport-1.11.2+1.20.1.jar              |Forge Config API Port (Connect|forgeconfigapiport            |8.0.0               |PROCESS_IM|Manifest: NOSIGNATURE
		kffmod-4.11.0.jar                                 |Kotlin For Forge              |kotlinforforge                |4.11.0              |PROCESS_IM|Manifest: NOSIGNATURE
		flywheel-forge-1.20.1-0.6.10-7.jar                |Flywheel                      |flywheel                      |0.6.10-7            |PROCESS_IM|Manifest: NOSIGNATURE
		oculus-flywheel-compat-forge1.20.1+1.1.1.jar      |Oculus Flywheel Compat        |irisflw                       |1.1.1               |PROCESS_IM|Manifest: NOSIGNATURE
		create-1.20.1-0.5.1.f.jar                  |Create                        |create                        |0.5.1.f             |PROCESS_IM|Manifest: NOSIGNATURE
		create_central_kitchen-1.20.1-for-crea|Create: Central Kitchen       |create_central_kitchen        |1.3.12              |ERROR     |Manifest: NOSIGNATURE
		createoreexcavation-1.20-1.5.0.jar    |Create Ore Excavation         |createoreexcavation           |1.5.0               |PROCESS_IM|Manifest: NOSIGNATURE
		Xaeros_Minimap_24.2.0_Forge_1.20.jar  |Xaero's Minimap               |xaerominimap                  |24.2.0              |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-item-group-api-v1-4.0.12+c9161c2d77.jar    |Fabric Item Group API (v1)    |fabric_item_group_api_v1      |4.0.12+c9161c2d77   |PROCESS_IM|Manifest: NOSIGNATURE
		jecharacters-1.20.1-forge-4.5.11.jar     |Just Enough Characters        |jecharacters                  |4.5.11              |PROCESS_IM|Manifest: NOSIGNATURE
		ToughAsNails-1.20.1-9.0.0.96.jar           |Tough As Nails                |toughasnails                  |0.0NONE             |PROCESS_IM|Manifest: NOSIGNATURE
		 entityculling-forge-1.6.6-mc1.20.1.jar |EntityCulling                 |entityculling                 |1.6.6               |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-biome-api-v1-13.0.13+dc36698e77.jar        |Fabric Biome API (v1)         |fabric_biome_api_v1           |13.0.13+dc36698e77  |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-registry-sync-v0-2.3.3+1c0ea72177.jar      |Fabric Registry Sync (v0)     |fabric_registry_sync_v0       |2.3.3+1c0ea72177    |PROCESS_IM|Manifest: NOSIGNATURE
		kubejs-create-forge-2001.2.5-build.2.jar          |KubeJS Create                 |kubejs_create                 |2001.2.5-build.2    |PROCESS_IM|Manifest: NOSIGNATURE
		appleskin-forge-mc1.20.1-2.5.1.jar          |AppleSkin                     |appleskin                     |2.5.1+mc1.20.1      |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-recipe-api-v1-1.0.21+514a076577.jar        |Fabric Recipe API (v1)        |fabric_recipe_api_v1          |1.0.21+514a076577   |PROCESS_IM|Manifest: NOSIGNATURE
		 ferritecore-6.0.1-forge.jar               |Ferrite Core                  |ferritecore                   |6.0.1               |PROCESS_IM|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		fabric-object-builder-api-v1-11.1.3+2174fc8477.jar|Fabric Object Builder API (v1)|fabric_object_builder_api_v1  |11.1.3+2174fc8477   |PROCESS_IM|Manifest: NOSIGNATURE
		rubidium-extra-0.5.4.3+mc1.20.1-build.121|Embeddium Extra               |embeddium_extra               |0.5.4.3+mc1.20.1-bui|PROCESS_IM|Manifest: NOSIGNATURE
		terrestria-6.0.13$terraform-dirt-api-v1-7.0.3_mapp|Terraform Dirt API (v1)       |terraform_dirt_api_v1         |7.0.3               |PROCESS_IM|Manifest: NOSIGNATURE
		ModernUI-Forge-1.20.1-3.10.1.4-universal.|Modern UI                     |modernui                      |3.10.1.4            |PROCESS_IM|Manifest: 01:c4:52:25:b1:6e:5f:ac:fe:88:35:7e:cf:65:2f:69:1d:56:db:2b:93:f8:dd:7c:93:47:04:8c:e4:22:13:91
		fabric-sound-api-v1-1.0.13+4f23bd8477.jar         |Fabric Sound API (v1)         |fabric_sound_api_v1           |1.0.13+4f23bd8477   |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-message-api-v1-5.1.9+52cc178c77.jar        |Fabric Message API (v1)       |fabric_message_api_v1         |5.1.9+52cc178c77    |PROCESS_IM|Manifest: NOSIGNATURE
		emi-bridge-1.11.2+1.20.1.jar                      |Connector Extras EMI Bridge   |connectorextras_emi_bridge    |1.11.2+1.20.1       |PROCESS_IM|Manifest: NOSIGNATURE
		create_enchantment_industry-1.20.1-for|Create Enchantment Industry   |create_enchantment_industry   |1.2.9.d             |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-data-generation-api-v1-12.3.4+369cb3a477.ja|Fabric Data Generation API (v1|fabric_data_generation_api_v1 |12.3.4+369cb3a477   |PROCESS_IM|Manifest: NOSIGNATURE
		fabric-events-interaction-v0-0.6.2+0d0bd5a777.jar |Fabric Events Interaction (v0)|fabric_events_interaction_v0  |0.6.2+0d0bd5a777    |PROCESS_IM|Manifest: NOSIGNATURE
		createaddition-1.20.1-1.2.4d.jar                  |Create Crafts & Additions     |createaddition                |1.20.1-1.2.4d       |PROCESS_IM|Manifest: NOSIGNATURE

### Expected Behavior

I enter a world.

### Actual Behavior

Game crushed.

### Steps to Reproduce

Add mods, start game, enter a world.

### Additional Information

[crash-2024-08-09_18.08.48-server.txt](https://github.com/user-attachments/files/16559891/crash-2024-08-09_18.08.48-server.txt)

**Comment by screret** [comment]
latest.log please?

**Comment by Water-Gate-King** [comment]
[latest.log](https://github.com/user-attachments/files/16560067/latest.log)

**Comment by screret** [comment]
`gtceu.js#53: Could not create ID from 'gtceu:block/machines/electric_furnace)'!: Non [a-z0-9/._-] character in path of location: gtceu:block/machines/electric_furnace)`
one of your scripts has an error. the `)` at the end of a path.

**Comment by screret** [comment]
also, one of your machine overlays is erroring.

**Comment by Water-Gate-King** [comment]
OK, I have solved it. Thank you!
