### ISSUE TITLE
Solar boilers not working in void dimension

### ISSUE THREAD

**Issue by lunzbunz** [GregTechCEu/GregTechCEu-1.19#1682]
### Checked for existing issues

- [x] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.3.1

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer and Open to LAN

### Cross-Mod Interaction

Yes

### Other Installed Mods

Monifactory (hard mode)

### Expected Behavior

Solar boilers produce steam in other dimension (specifically the void dimension) when it is day and show that it is day 

### Actual Behavior

Solar boilers don't produces steam and show that it is night

### Steps to Reproduce

Join a world in Monifactory hard mode 
Enter the void world
Set time to day
Place solar boiler

**Comment by JuiceyBeans** [comment]
Can be closed (#1736)
