### ISSUE TITLE
! not properly inverting tags

### ISSUE THREAD

**Issue by Redderpears** [GregTechCEu/GregTechCEu-1.19#1685]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.3.1-build_940

### Minecraft Version

1.20.1

### Recipe Viewer Installed

No Recipe Viewer

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

GregTech modern

### Expected Behavior

Putting a ! in front of a tag in an oredict tag should invert its setting, e.g. !*gold* should allow everything that does not have "gold" in its tags, but prevent any gold items from going through.

### Actual Behavior

Putting a ! in front of a tag in an oredict tag instead bugs and allows everything through, e.g. !*gold* lets everything through the filter, including items with gold in the tag. 

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/a093d917-0590-4d99-902a-ed7149a5491c)
![image](https://github.com/user-attachments/assets/db0e4928-3f7e-463c-a87f-557868e682bd)

Put a conveyor on an item pipe and set it to import, put an item tag filter in the conveyor, set filter as shown, and put a gold and non-gold item in the imported chest.

### Additional Information

![image](https://github.com/user-attachments/assets/465090de-c534-44e7-a530-626b8d72dc6a)
Side note, this example is wrong since G and D should be lowercase. !*Double* and !*double* also exhibit this bug but also weirdly don't let item or fluid pipes through. I know the tags I've provided should work since I initially found the bug on Monifactory but I have tested on a pure install and found the bug persisted.

**Comment by Spicierspace153** [comment]
fixed in #2220
