### ISSUE TITLE
Not compatible with jei

### ISSUE THREAD

**Issue by FHfenghuo** [GregTechCEu/GregTechCEu-1.19#1692]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.0.20.b

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

I installed jei, but found that the content of jei cannot be displayed normally

### Expected Behavior

I installed the latest version of the jei module in fabric1.20.1 and found that the jei content could not be loaded normally, but this module loaded normally

### Actual Behavior

I installed the latest version of the jei module in fabric1.20.1 and found that the jei content could not be loaded normally, but this module loaded normally

### Steps to Reproduce

Install jei and GregTechCEu Modern separately in fabric1.20.1

**Comment by screret** [comment]
fabric is unsupported.
