### ISSUE TITLE
Missing Lang for Gearboxes

### ISSUE THREAD

**Issue by ThePansmith** [GregTechCEu/GregTechCEu-1.19#1698]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

Latest

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

SP

### Cross-Mod Interaction

No

### Other Installed Mods

Monifactory, Create

### Expected Behavior

For there to be lang files for the electric gearboxes

### Actual Behavior

There are not lang files for the electric gearboxes

### Steps to Reproduce

1. Hover over an electric gearbox

**Comment by YoungOnionMC** [comment]
fixed in #1744
