### ISSUE TITLE
JEI cannot accurately display the multiblock page.

### ISSUE THREAD

**Issue by nutant233** [GregTechCEu/GregTechCEu-1.19#1705]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.3.1-build_947

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

kjs

### Expected Behavior

JEI will accurately bring up the corresponding multiblock page.

### Actual Behavior

It always brings up the wooden tank page.

### Steps to Reproduce

Press U on any main block.

**Comment by nutant233** [comment]
The ore processing page cannot be displayed either.
![d7243822c92df2f4673b712ba5c63ecc](https://github.com/user-attachments/assets/c7208994-7f9e-4b1b-9280-ddce139bd546)

**Comment by Pumpkin7266** [comment]
can confirmed, still bugged as of 1.4.0. for both issues reported here

**Comment by HydrogenC** [comment]
> The ore processing page cannot be displayed either. ![d7243822c92df2f4673b712ba5c63ecc](https://private-user-images.githubusercontent.com/65939836/358118493-c7208994-7f9e-4b1b-9280-ddce139bd546.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0ODUyMDEsIm5iZiI6MTcyNDQ4NDkwMSwicGF0aCI6Ii82NTkzOTgzNi8zNTgxMTg0OTMtYzcyMDg5OTQtN2Y5ZS00YjFiLTkyODAtZGRjZTEzOWJkNTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDA3MzUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjMzYxYzI3MDBmMTU0OWFkMzA5Zjk3Y2RhYTViZDFlMWRmN2MyOWFlMDEwNzFlYTdlMjE2YTg5NGQ5M2ZhNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mjm62ZWBARKt4yLLG3-8L8CubbL26UXllTnbmZvO5-Y)

I can reproduce this.

**Comment by 300f20t** [comment]
I had the same bug when switching to GTm 1.4.0 and updating JEI.
