### ISSUE TITLE
Visual bug with multiblock visualization and EMI

### ISSUE THREAD

**Issue by jaaaco-j** [GregTechCEu/GregTechCEu-1.19#1709]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.3.1-build_950

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

First encountered in Monifactory, but managed to replicate with just EMI installed

tested with latest 1.20.1 version of EMI as of now which is 1.1.12

### Expected Behavior

ingredients, possible components for given block and the multiblock controlers GUIs and the visualization not overlapping each other
![2024-08-12_22 04 29](https://github.com/user-attachments/assets/0c2756e9-0371-4a86-a0c8-a8e17f083870)
this is with JEI instead of EMI

### Actual Behavior

![2024-08-12_22 00 38](https://github.com/user-attachments/assets/e8c989af-2aa3-4219-be33-3dca966e5c29)

the case in monifactory is even worse since the ingredients decided to be entirely cut off by another GUI
![image](https://github.com/user-attachments/assets/31bcbbf0-cdbb-481e-af8d-f3fa697a6a16)

### Steps to Reproduce

1) Download EMI
2) Right click any multiblock controller in the recipe browser or press U on the item in the inventory
3) Click on the multiblock visualization tab

### Additional Information

Not sure if this is an EMI or GTM issue, im trying here first. will repost to EMI github if this isn't caused by GTM

**Comment by screret** [comment]
We can't fix this, sadly.
