### ISSUE TITLE
Crash When try to search item

### ISSUE THREAD

**Issue by pen787** [GregTechCEu/GregTechCEu-1.19#171]
### GregTech CEu Version

1.0.6-build_53

### Recipe Viewer Installed

REI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

Normal Item Render In Inventory and REI and not crashing.

### Actual Behavior

Search in inventory:
[crash-2023-07-16_11.56.44-client.txt](https://github.com/GregTechCEu/GregTechCEu-1.19/files/12063320/crash-2023-07-16_11.56.44-client.txt)
Search in REI:
[crash-2023-07-16_11.58.16-client.txt](https://github.com/GregTechCEu/GregTechCEu-1.19/files/12063321/crash-2023-07-16_11.58.16-client.txt)

### Steps to Reproduce

1. I search miner in inventory

### Additional Information

I thing something that has name "miner" make me crash or something.

**Comment by pen787** [comment]
It's got fix in 1.0.6-build_54 build for some reason

**Comment by Yefancy** [comment]
its still a bug

**Comment by Yefancy** [comment]
fixed
