### ISSUE TITLE
The game crashed while loading the world

### ISSUE THREAD

**Issue by nutant233** [GregTechCEu/GregTechCEu-1.19#1717]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.3.1-build_955

### Minecraft Version

1.20.1

### Recipe Viewer Installed

None

### Environment

Singleplayer,

### Cross-Mod Interaction

Yes

### Other Installed Mods

jei

### Expected Behavior

The game is loading normally.

### Actual Behavior

The game crashed.

### Steps to Reproduce

[minecraft-exported-crash-info-2024-08-14T19-30-22.zip](https://github.com/user-attachments/files/16612231/minecraft-exported-crash-info-2024-08-14T19-30-22.zip)

**Comment by screret** [comment]
already fixed.

**Comment by screret** [comment]
wait, no, why'd you attach multiple completely different crash reports?

**Comment by screret** [comment]
try enabling the forge `removeErroringBlockEntities` config, and then break & replace your fluid drills?

**Comment by nutant233** [comment]
The drill has been reinstalled in the latest.
