### ISSUE TITLE
Chloroethylene and dichloroethane recipe conflict

### ISSUE THREAD

**Issue by nutant233** [GregTechCEu/GregTechCEu-1.19#1719]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.3.1-build_955

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

jei

### Expected Behavior

Recipe is normal

### Actual Behavior

When making dichloroethane, it turns into Chloroethylene.

### Steps to Reproduce

None

**Comment by screret** [comment]
chloroethylene doesn't exist in vanilla GT.

**Comment by nutant233** [comment]
![9d067a3d9b51c0805b3bbdc1470df040](https://github.com/user-attachments/assets/c7862ade-e74e-4909-b9cb-b57d6333ba4f)
![f16dd2c9b3b7992944added5693a2d89](https://github.com/user-attachments/assets/eb3df208-4623-4f9a-b2e0-b7b83b19105b)
My description was incorrect.

**Comment by nutant233** [comment]
The magnetized recipe also has problems.
![64c46119bf694c7f1cea574d6d7e2daf](https://github.com/user-attachments/assets/a57cb802-9bb7-46a7-a8e9-2adafc5dfe8a)

**Comment by screret** [comment]
what's the issue with the polarizer recipe?

**Comment by nutant233** [comment]
The tier should be one grade lower.
