### ISSUE TITLE
Steam input hatches/buses Z-fighting

### ISSUE THREAD

**Issue by jaaaco-j** [GregTechCEu/GregTechCEu-1.19#1723]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.3.1-build_957

### Minecraft Version

1.20.1

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

None

### Expected Behavior

hatch/bus graphic looking the same as with other multiblocks that dont use the steam variant.

### Actual Behavior

That graphic Z fighting
![2024-08-14_17 50 10](https://github.com/user-attachments/assets/ed093c2e-882d-487d-883d-ad4a35a954fe)
![2024-08-14_17 55 54](https://github.com/user-attachments/assets/9fcef268-ab03-4aaa-9c49-af04971eaff4)
![2024-08-14_17 56 11](https://github.com/user-attachments/assets/a62bca4c-0401-4e53-a913-41c8338cbcda)

### Steps to Reproduce

1) Make a steam multiblock, grinder or oven, boiler does not work as it uses the "electric" variants
2) add input/output bus/hatch
3) move the camera around and see the graphics flickering

### Additional Information

probably related to #1511

**Comment by bongcloudenjoyer** [comment]
bronze firebox casing also have this issue when alloy smelter is working

**Comment by DannyDan4** [comment]
can confirm, this is definitely the same issue between both #1511 & this, with it occurring on my steam machines in monifactory both before and after the update to GTCEuM 1.4.

**Comment by Ignus3** [comment]
I have written a fix for this particular bug, I just need to get it into a pull request.

**Comment by Ignus3** [comment]
So to be technically complete, it solves this problem with the fan showing, but I am still getting z-fighting issues on the flame effect, only on this block. But this specific part is fixed.

**Comment by screret** [comment]
I'm currently figuring out a fix for the firebox renderer on parts.

**Comment by screret** [comment]
Might've just solved it
