### ISSUE TITLE
AE2 blocking mode and hidden programming circuit slot conflict

### ISSUE THREAD

**Issue by xinxinsuried** [GregTechCEu/GregTechCEu-1.19#1769]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.0

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Open to LAN

### Cross-Mod Interaction

Yes

### Other Installed Mods

AE2，ExtendedAe

### Expected Behavior

The AE2 template provider can supply (materials and corresponding programmed circuits) to the same machine (such as Wirrell) to produce items with different circuits

### Actual Behavior

After activating the blocking mode of the template provider, the machine still retains the programmed circuit from the last input, causing AE to misjudge that there is still material in the container

### Steps to Reproduce

1. Power supply to AE, sample supply (attached to MV Wirrell, enable blocking mode), MV Wirrell
2. Write two templates
a.(3x copper ingot + 3x programmed  circuit mode1 -> 6x copper_single_wire)
b.(6x copper ingot + 6x programmed circuit mode3 -> 48x fine_copper_wire)
3.First, request Copper_Sngle wire, which is working normally at this time
3.Then request fine_comper-wire, at which point the cable rolling mill still retains 3x programmed circuit mode1, but cannot function properly due to incorrect (presumably) identification of the blocking mode

IMAGE
![image](https://github.com/user-attachments/assets/cc23dfbc-656b-4dbb-a542-6def2a484959)
![image](https://github.com/user-attachments/assets/ef83b322-d322-4f67-9676-16e4411c385d)
![image](https://github.com/user-attachments/assets/4e033296-e919-44d4-9c0d-28cc01d5d5d6)
![image](https://github.com/user-attachments/assets/f4a739cc-15ba-4393-9e29-b74f27bb1bc2)
![image](https://github.com/user-attachments/assets/65d4649c-64ee-401d-a750-229a05ee3918)

### Additional Information

![image](https://github.com/user-attachments/assets/c9f11114-5df9-489e-a369-8feb9b5fa873)
![image](https://github.com/user-attachments/assets/002ef87d-710e-498e-8f63-eb64efd22637)
Is there an invisible programmed circuit slot? And it was not destroyed in a timely manner after the work was completed

**Comment by xinxinsuried** [comment]
![image](https://github.com/user-attachments/assets/9352e0ea-5f87-486e-a825-0bb92cfd2f88)
Blocking mod

**Comment by screret** [comment]
don't insert circuits in patterns. make separate machines for different circuit configurations.

**Comment by xinxinsuried** [comment]
😫this ban the way to make different programmed recipe with only one machine

**Comment by Pumpkin7266** [comment]
You gotta make multiple machines one for each circuit

**Comment by screret** [comment]
correct!

**Comment by xinxinsuried** [comment]
👍

**Comment by Pumpkin7266** [comment]
btw above i said pattern but i meant circuit (editted but just in case you didn't see)

**Comment by xinxinsuried** [comment]
😫 I was planning to be a little stingy on the machine
