### ISSUE TITLE
Tooltips rendering behind EMI buttons and other recipes

### ISSUE THREAD

**Issue by Abbie5** [GregTechCEu/GregTechCEu-1.19#177]
### GregTech CEu Version

1.0.7a

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

Tooltips render above all other UI elements

### Actual Behavior

Tooltips render behind EMI buttons and other recipes

### Steps to Reproduce

1. View the uses of the autoclave
2. Hover over the energium crystal

### Additional Information

Screenshot demonstrating the issue

![2023-07-20_10 12 44](https://github.com/GregTechCEu/GregTech-Modern/assets/43531981/53b2d3aa-6bc0-48c4-83aa-12a33d1e3739)

**Comment by Abbie5** [comment]
Forgot to add, this was on Fabric. I haven't tested on Forge.

**Comment by NeveHanter** [comment]
I have the same issue on Forge with HEI, additionally in the machine GUI item counts overlap the mouse tooltips.

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/3267401/f79d0337-ee18-4cf8-a283-cc9979b5ae98)
