### ISSUE TITLE
What's wrong with this since I cahnge the version to 1.4.0-snapshot

### ISSUE THREAD

**Issue by dustiit** [GregTechCEu/GregTechCEu-1.19#1770]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.0-SNAPSHOT

### Minecraft Version

1.20.1

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Mods uesd to develope GTM

### Expected Behavior

the game should run

### Actual Behavior

the game should run

### Steps to Reproduce

I'v change the version of KJS but it still dosen;t work

### Additional Information

<img width="1097" alt="屏幕截图 2024-08-19 003023" src="https://github.com/user-attachments/assets/cb250b2b-22e7-4953-9cc3-838493e7650a">
As I change the version of  GTM (1.3.1 -> 1.4.0-snapshot) in my addon dependence, it shows these errors

**Comment by screret** [comment]
full log, please.

**Comment by dustiit** [comment]
umm the thing is down maybe? I change the ldlib to 1.0.26.b then everythng is ok

**Comment by screret** [comment]
there is no ldlib 1.0.26.c if that's what you're looking for.

**Comment by dustiit** [comment]
> there is no ldlib 1.0.26.c if that's what you're looking 
At the beginning it show the version of ldlib is low so I change the higher one then it work
