### ISSUE TITLE
kinetic output box bug

### ISSUE THREAD

**Issue by Water-Gate-King** [GregTechCEu/GregTechCEu-1.19#1782]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.4.0

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

![image](https://github.com/user-attachments/assets/76af74f3-d808-49ed-bede-cb8adafe61eb)
![image](https://github.com/user-attachments/assets/40723630-ad2e-402e-8993-fe3c65149fb1)
![image](https://github.com/user-attachments/assets/d8e07e64-fecd-4743-8c28-439ecc819b5e)

### Expected Behavior

 The kinetic output box works

### Actual Behavior

https://github.com/user-attachments/assets/2d58ac60-d522-4718-9d28-7ebb3cef1ce8

### Steps to Reproduce

GTCEuStartupEvents.registry('gtceu:recipe_type', e => {
 
        e.create('lv_generator')
        .setEUIO('out')
        .setMaxIOSize(1, 0, 1, 1)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.TURBINE)

});

GTCEuStartupEvents.registry('gtceu:machine', e => {
        let l = e.create('lv_generator', 'multiblock');
    l.rotationState(RotationState.NON_Y_AXIS)
    l.pattern(
            def => FactoryBlockPattern.start() 
                .aisle('BBB', 'BCB', 'BBB')
                .aisle('AAA', 'ADA', 'AAA')
                .aisle('AAA', 'ADA', 'AAA')
                .aisle('BBB', 'B#B', 'BBB')
                .where('#', Predicates.controller(Predicates.blocks(def.get())))
                .where('C', Predicates.blocks('gtceu:lv_kinetic_output_box'))
                .where('A', Predicates.blocks('gtceu:copper_coil'))
                .where('B', Predicates.blocks('gtceu:solid_machine_casing')
                    .or(Predicates.autoAbilities(def.recipeTypes))
            )
                .where('D', Predicates.air())
                .build() 
        )
        .workableCasingRenderer('gtceu:block/casings/steam/steel/side', 'gtceu:block/multiblock/electric_blast_furnace', false)
        .generator(true)
        .recipeTypes(GTRecipeTypes.get('lv_generator'))
})

ServerEvents.recipes(event => {
event.recipes.gtceu.lv_generator('generator1')            
.duration(4)
.outputStress(512)
.circuit(1)
})

**Comment by screret** [comment]
your video is broken.

**Comment by Water-Gate-King** [comment]
https://github.com/user-attachments/assets/5b1f3f0f-9558-4e39-9e9b-78acc0da669e
