### ISSUE TITLE
Tools have negative mining speeds

### ISSUE THREAD

**Issue by Strubbelkopp** [GregTechCEu/GregTechCEu-1.19#1795]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.0

### Minecraft Version

1.21.1

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

JEI

### Expected Behavior

Every tool should have the correct mining speed

### Actual Behavior

When either crafting a tool or using the /give command to get them, they at first show the correct mining speed on the tooltip (6.0 for the iron pickaxe for example), but as soon as I take the tool in my hand the mining speed becomes negative with a different value (-2.8 for the iron pickaxe). When I get the tool from the creative menu, this doesn't happen.
This makes it impossible to mine anything with the tools.

### Steps to Reproduce

1. Craft or use /give to get a tool (iron pickaxe for example) and make sure it lands in a slot that is not your active hand
2. Look at Mining Speed
3. Switch your hand to the tool and look at the Mining Speed again, impossible to mine anything with it

### Additional Information

The same problem also occured in 1.3.1

**Comment by GraxMonzo** [comment]
I think it's critical bug that prevents further gameplay

**Comment by GraxMonzo** [comment]
Fixed in 1.4.1 version
@Strubbelkopp I think we can close this issue
