### ISSUE TITLE
[1.21] GregTech requesting incorrect JEI version

### ISSUE THREAD

**Issue by Periam** [GregTechCEu/GregTechCEu-1.19#1796]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-1.21.1-1.4.0

### Minecraft Version

1.21

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

jei-1.21-neoforge-19.8.2.99
configuration-neoforge-1.21-3.0.0

### Expected Behavior

Launch the game normally

### Actual Behavior

The game after launching is requesting an incorrect Jei verion
![image](https://github.com/user-attachments/assets/ca1c2f51-6d33-4a1e-a5eb-bb5020d642c9)

### Steps to Reproduce

1 Install Mod latest version for MC 1.21
2 Install Jei Latest version for MC 1.21

### Additional Information

[crash-2024-08-20_09.54.23-fml.txt](https://github.com/user-attachments/files/16676037/crash-2024-08-20_09.54.23-fml.txt)

**Comment by screret** [comment]
just do 1.21.1.

**Comment by screret** [comment]
all 1.20.0 mods work on 1.21.1

**Comment by Periam** [comment]
Not all the mods are yet in 1.21.1, And I guest yours works in 1.21 but it is requesting a newer version of jei..

**Comment by screret** [comment]
neoforge has specifically marked 1.21.1 as always working with 1.21.0 mods. just install them anyway.
