### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by Drackion** [GregTechCEu/GregTechCEu-1.19#180]
### GregTech CEu Version

1.0.7

### Recipe Viewer Installed

REI

### Environment

Singleplayer Forge

### Cross-Mod Interaction

No

### Expected Behavior

For textures to be shown.

### Actual Behavior

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/64641342/af4a7f52-ada3-4daf-a015-48316e222837)

### Steps to Reproduce

download gtceu 1.0.7 forge

**Comment by MaxNeedsSnacks** [comment]
Reproducible on Fabric with build 1.0.7b, seems to affect quite a few GT fluids (and most, if not all AE2 facades using GT blocks)

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/12750501/e1889b5e-307b-4acd-85e3-a19730e5a061)

**Comment by screret** [comment]
NOT AGAIN AAAAAAAAAAAAA

**Comment by screret** [comment]
THIS WILL BE THE 5TH TIME IM FIXING THIS
I TESTED IT. IT WORKED. ON BOTH PLATFORMS. where **the fuck** did that commit go? Who ate it? The gitmonster?

**Comment by Yefancy** [comment]
is a bug in1.20.1? if so, probably bc I move setFluidTexture to other mixins. but teh current blockbakery deoesnt work as we expect in the 1.19. we might look at it later

**Comment by Drackion** [comment]
this is in 1.19.2

**Comment by Drackion** [comment]
more missing textures to add:
this time its mining hammers
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/64641342/8b953df6-4598-4836-ba3a-438d90c26637)
