### ISSUE TITLE
allow HV + macerators to void bonus products

### ISSUE THREAD

**Issue by tinyzooseven** [GregTechCEu/GregTechCEu-1.19#1811]
### Feature Description

id like GT macerators at HV tier or higher to be able to void bonus outputs using a programmed circuit such as configuration 1, similar to how ore washers have a faster version of the recepie that doesnt give bonus products

**Comment by a-a-GiTHuB-a-a** [comment]
It would be interesting to see a middle-ground between the forge hammer and macerator with oreproc.
However, I don't think this will be implemented. At worst, just void the bonus stuff.
