### ISSUE TITLE
Jetpack uses energy whenever player is not touching ground

### ISSUE THREAD

**Issue by noobcoconut** [GregTechCEu/GregTechCEu-1.19#1812]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [x] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.0

### Minecraft Version

1.20.1

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

None

### Expected Behavior

Jetpack should not consume energy when you are not actively using it

### Actual Behavior

Jetpack consumes energy whenever you are not touching the ground like when falling, swimming, stuck in cobweb, sleeping in bed

### Steps to Reproduce

equip electric jetpack
enable engines
fall through cobwebs just don't stand on any block

**Comment by Wyrmlet** [comment]
This still seems to be an issue as of 1.5.2 on minecraft 1.20.1; Even more apparent when a jetpack is used together with a glider of some sort
