### ISSUE TITLE
ME-pattern-buffer cant isolation circuit

### ISSUE THREAD

**Issue by Artina-atina** [GregTechCEu/GregTechCEu-1.19#1815]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-1.20.1-1.4.0

### Minecraft Version

1.20.1

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

gregtech leisure

### Expected Behavior

make sulphuric acid hydrochloric acid at the same time on the large chemical reactor
can get right product

### Actual Behavior

ME-pattern-buffer cant isolation circuit

### Steps to Reproduce

just use large chemical reactor and use circuit:1 with circuit:24
than make sulphuric acid hydrochloric acid at the same time
it can only get hydrogen sulfide

### Additional Information

thank you
your mod is cool
love from china

**Comment by screret** [comment]
1) have you tried enabling distinct buses in the buffers?
2) GTL uses a custom version of GTM they've forked from us, which we will not support.

**Comment by Artina-atina** [comment]
1.i actually used two diffrent buffer
2.thank you,i will ask GTL author
