### ISSUE TITLE
Game crashes on launch

### ISSUE THREAD

**Issue by ghost** [GregTechCEu/GregTechCEu-1.19#1819]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.40.0

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Advancment Plaques, Alex's Mobs, Almost Unified, Amendments, Appleskin, AE2, Architectury API, Athena, Attribute Fix, bad packets, BetterF3, Botarium, Chipped, Citadel, Cloth Config API, Clumps, CoFH Core, Comforts, Configuration, Cosmetic Armor Reworked, Create, Create: New Age, Dynamic FPS, EMI, EMI Enchants, EMI Loot, EMI Trades, EMIffect, Embeddium, Embeddium(Rubidium) Extra, Entity Culling, FTB Chunks, FTB Library, FTB Teams, Farmer's Delight, Fast Leaf Decay, FastFurnace, FastSuite, FastWorkbench, FerriteCore, Framework, Goblin Traders, Iceberg, ImmediatelyFast, Item Highlighter, Jade Addons, Jade, Kotlin for Forge, KubeJS, KubeJS Additions, KubeJS Create, KubeJS Thermal, LDLib, Legendary Tooltips, Let Me Despawn, Lootr, Memory Leak Fix, Model Gap Fix, ModernFix, Moonlight Lib, Mouse Tweaks, Necrocomicon API, Not Enough Animations, Oculus, Placebo, Polymorph, Prism, Quark, Resourceful Lib, Rhino, Saturn, Searchables, Sophisticated Backpacks, Sophisticated Core, Sound Physics Remastered, spark, Starlight, Thermal (Cultivation, Dynamics, Endergy, Expansion, Extra, Foundation, Innovation), Twigs, You Shall Not Spawn, Zeta

### Expected Behavior

Game launches

### Actual Behavior

Game crashes

### Steps to Reproduce

I wrote code in KubeJS that includes GTCEu chemicals, it launched the couple of times but I don't know what happened but it doesn't launch now. I asked CurseForge Discord and they said to post it , game crashes on every version

### Additional Information

It launched the first couple of times but I don't know what happened but it doesn't launch now. I asked CurseForge Discord and they said to post it. Game crashes on every version I had to check that box or else I couldn't have posted it.

**Comment by screret** [comment]
I need a log to be able to tell you what's wrong
send latest.log.

**Comment by ghost** [comment]
[latest.log](https://github.com/user-attachments/files/16740827/latest.log)

**Comment by screret** [comment]
oh, you're trying to check if a material has a property in the material registration event. don't do that.
do it in `GTCEuStartupEvents.materialModification` instead, that fires after all materials are registered.

**Comment by ghost** [comment]
how do i do that?

**Comment by screret** [comment]
use the event I mentioned to do modifications to materials instead of `GTCEuStartupEvents.registry('gtceu:material'`.

**Comment by ghost** [comment]
oh ok

**Comment by ghost** [comment]
i dont understand
