### ISSUE TITLE
game crashes when i put a oak log in coke oven

### ISSUE THREAD

**Issue by Sinkis290** [GregTechCEu/GregTechCEu-1.19#1820]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.4.0

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayers

### Cross-Mod Interaction

No

### Other Installed Mods

- ad_astra 1.15.18
	- ad_astra_giselle_addon 6.14
	- aiimprovements 0.5.2
	- alexsdelight 1.5
	- alexsmobs 1.22.8
	- ambientsounds 6.0.5
	- appleskin 2.5.1+mc1.20.1
	- architectury 9.2.14
	- athena 3.1.2
	- bakery 1.1.15
	- bdlib 1.27.0.8
	- bellsandwhistles 0.4.3-1.20.x
	- betteradvancements 0.4.2.10
	- bettercombat 1.8.6+1.20.1
	- betterdeserttemples 1.20-Forge-3.0.3
	- betterdungeons 1.20-Forge-4.0.4
	- betterendisland 1.20-Forge-2.0.6
	- betterf3 1.0
	- betterfortresses 1.20-Forge-2.0.6
	- betterfpsdist 1.20.1-4.4
	- betterjungletemples 1.20-Forge-2.0.5
	- bettermineshafts 1.20-Forge-4.0.4
	- betteroceanmonuments 1.20-Forge-3.0.4
	- betterstrongholds 1.20-Forge-4.0.3
	- betterthirdperson 1.9.0
	- betterwitchhuts 1.20-Forge-3.0.3
	- biggerreactors 0.6.0-beta.10.4
	- bigreactors 1.20.1-2.0.84
	- biomesoplenty 18.0.0.598
	- blockui 1.20.1-1.0.156-RELEASE
	- botarium 2.3.4
	- brandonscore 3.2.1.302
	- brewery 1.1.9
	- buildinggadgets2 1.0.7
	- caelus 3.2.0+1.20.1
	- carbonconfig 1.20-1.2.6
	- chipped 3.0.6
	- chunkpregen 1.20-4.4.4
	- citadel 2.6.0
	- cloth_config 11.1.118
	- clumps 12.0.0.4
	- codechickenlib 4.4.0.512
	- cofh_core 11.0.2
	- collective 7.84
	- commongroovylibrary 0.3.3
	- configuration 2.2.1
	- configured 2.2.3
	- controlling 12.0.2
	- corpse 1.20.1-1.0.12
	- create 0.5.1.f
		\-- flywheel 0.6.10-7
	- create_new_age 1.1.2
	- create_sa 2.0.4.
	- createaddition 1.20.1-1.2.4e
	- createbigcannons 5.5.1+mc.1.20.1-forge
		\-- ritchiesprojectilelib 2.0.0-dev+mc.1.20.1-forge-build.182
	- createdeco 2.0.2-1.20.1-forge
	- createdieselgenerators 1.20.1-1.2i
	- createoreexcavation 1.5.0
	- creativecore 2.11.37
	- cristellib 1.1.5
	- cupboard 1.20.1-2.7
	- curios 5.9.1+1.20.1
	- design_decor 0.4.0b
	- doapi 1.2.15
		\-- terraform 7.0.1
	- domum_ornamentum 1.20.1-1.0.186-RELEASE
	- draconicevolution 3.1.2.588
	- drawerstooltip 8.0.0
	- durabilitytooltip 1.1.5
	- eatinganimation 5.1.0
	- elytraslot 6.4.3+1.20.1
		\-- mixinsquared 0.1.2-beta.6
	- embeddium 0.3.30+mc1.20.1
		\-- rubidium 0.7.1
	- embeddiumplus 1.2.13
	- emi 1.1.12+1.20.1+forge
	- enderio 6.1.8-beta
	- enderstorage 2.11.0.188
	- entityculling 1.6.7
	- extendedgears 2.1.1-1.20.1-0.5.1.f-forge
	- fallingtree 4.3.4
	- farmersdelight 1.20.1-1.2.4
	- fastload 3.4.0
	- ferritecore 6.0.1
	- fluxnetworks 7.2.1.15
	- forge 47.3.6
	- ftblibrary 2001.2.4
	- ftbquests 2001.4.8
	- ftbteams 2001.3.0
	- fusion 1.1.1
	- gml 4.0.9
	- gtceu 1.4.0
	- hangglider 8.0.1
	- iceberg 1.1.21
	- immediatelyfast 1.2.20+1.20.4
	- immersive_aircraft 1.0.1+1.20.1
	- immersive_armors 1.6.1+1.20.1
	- immersiveengineering 1.20.1-10.1.0-171
	- industrialforegoing 3.5.19
	- infinitybuttons 1.20.1-4.0.4
	- interiors 0.5.4+forge-mc1.20.1
	- inventoryprofilesnext 1.10.10
	- itemfilters 2001.1.0-build.59
	- kotlinforforge 4.11.0
	- ldlib 1.0.27.a
	- legendarytooltips 1.4.5
	- letmedespawn 1.2.1
	- libipn 4.0.2
	- magistuarmory 9.8
	- mcjtylib 1.20-8.0.6
	- mcwbridges 3.0.0
	- mcwdoors 1.1.1
	- mcwfences 1.1.2
	- mcwfurnitures 3.3.0
	- mcwlights 1.1.0
	- mcwpaths 1.0.5
	- mcwroofs 2.3.1
	- mcwtrpdoors 1.1.3
	- mcwwindows 2.3.0
	- mekanism 10.4.8
	- mekanismadditions 10.4.8
	- mekanismgenerators 10.4.8
	- mekanismtools 10.4.8
	- minecolonies 1.20.1-1.1.603-RELEASE
	- minecraft 1.20.1
	- modernfix 5.19.1+mc1.20.1
	- moonlight 1.20-2.12.16
		\-- mixinextras 0.3.6
	- moremekanismprocessing 4.0
	- mousetweaks 2.25.1
	- multipiston 1.20-1.2.43-RELEASE
	- patchouli 1.20.1-84-FORGE
	- phosphophyllite 0.7.0-alpha.0.1
	- pipez 1.20.1-1.2.16
	- playeranimator 1.0.2-rc1+1.20
	- pneumaticcraft 6.0.16+mc1.20.1
	- powah 5.0.7
	- prism 1.0.5
	- puzzleslib 8.1.21
		\-- puzzlesaccessapi 8.0.7
	- quartz 0.2.0-alpha.0.1
	- railways 1.6.4+forge-mc1.20.1
	- rechiseled 1.1.6
	- rechiseledcreate 1.0.2
	- refinedstorage 1.12.4
	- resourcefulconfig 2.1.2
	- resourcefullib 2.1.28
	- rftoolsbase 1.20-5.0.5
	- rftoolsbuilder 1.20-6.0.5
	- rftoolscontrol 1.20-7.0.2
	- rftoolspower 1.20-6.0.2
	- rftoolsstorage 1.20-5.0.3
	- rftoolsutility 1.20-6.0.6
	- saturn 0.1.3
	- scannable 1.7.12+18ccb75
	- searchables 1.0.3
	- sereneseasons 9.0.0.46
	- sliceanddice 3.2.1
	- solarpanels 1.5.9
	- sophisticatedbackpacks 3.20.5.1044
	- sophisticatedcore 0.6.22.611
	- sound_physics_remastered 1.20.1-1.4.5
	- starlight 1.1.2+forge.1cda73c
	- steampowered 1.20.1-3.0.1
	- storagedrawers 12.5.2
	- structurize 1.20.1-1.0.742-RELEASE
	- supermartijn642configlib 1.1.8
	- supermartijn642corelib 1.1.17
	- supplementaries 1.20-2.8.17
	- systeams 1.7.1
	- t_and_t 0.0NONE
	- terrablender 3.0.1.7
	- tfmg 0.9.1b-1.20.1
	- theoneprobe 1.20.1-10.0.2
	- thermal_cultivation 11.0.1
	- thermal_dynamics 11.0.1
	- thermal_expansion 11.0.1
	- thermal_extra 3.1.3-1.20.1
	- thermal_foundation 11.0.6
		\-- thermal 11.0.6
	- thermal_innovation 11.0.1
	- thermal_integration 11.0.1
	- thermal_locomotion 11.0.1
	- titanium 3.8.32
	- toolbelt 1.20.01
	- towntalk 1.1.0
	- vinery 1.4.28
	- weaponmaster_ydm 4.2.3
	- xaerominimap 24.3.0
	- xaeroworldmap 1.39.0
	- xnet 1.20-6.1.4
	- xnetgases 5.1.3
	- yungsapi 1.20-Forge-4.0.5
	- yungsbridges 1.20-Forge-4.0.3
	- yungsextras 1.20-Forge-4.0.3
	- zerocore 1.20.1-2.1.45

### Expected Behavior

either nothing should happen or the oak log will turn into coal

### Actual Behavior

the game is crashing with 'the connecting is lost'
![error2024-08-25](https://github.com/user-attachments/assets/e14053d5-18d9-4aa7-b75d-f8bc2dfcc057)

### Steps to Reproduce

1. im building coke oven 2. im putting the oak log in the coke oven 3. game crashes

### Additional Information

maybe this happening because i have trouble with mcjty lib or java20

**Comment by JuiceyBeans** [comment]
Attach crash log

**Comment by Sinkis290** [comment]
> Attach crash log

all okay thank you. the trouble was with mod 'The One Probe'. i installed jade and everything worked okay.
