### ISSUE TITLE
Prospector and JourneyMap integration

### ISSUE THREAD

**Issue by jshilmover** [GregTechCEu/GregTechCEu-1.19#1821]
### Cross-mod Integration

JourneyMap

### Feature Description

In GTCEu you can click on an ore chunk in the prospector and it will mark it on JourneyMap via waypoint. It's a little unwieldy to use as is in modern with having to open and close the prospector a few times to see where you're at

**Comment by screret** [comment]
in 1.12 that's an addon.

**Comment by screret** [comment]
just fyi

**Comment by jshilmover** [comment]
Did not realize that, should I close this?

**Comment by screret** [comment]
Nah

**Comment by YoungOnionMC** [comment]
implemented in #1944
