### ISSUE TITLE
Wiki for adding electrical machine using KubeJS not presently accurate

### ISSUE THREAD

**Issue by vinni57** [GregTechCEu/GregTechCEu-1.19#1822]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.0-build_1029-SNAPSHOT

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

N/A

### Expected Behavior

Wiki shows requirement for pollution production parameter in `event.create()`.

Eg. 
```
GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('test_electric', 'simple', **pollution_integer**, GTValues.LV, GTValues.MV, GTValues.HV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('test_recipe_type')
        .tankScalingFunction(tier => tier * 3200)
})
```

### Actual Behavior

Wiki does not show such a requirement, instead having the following line:
```
event.create('test_electric', 'simple', GTValues.LV, GTValues.MV, GTValues.HV)
```

Following this results in the machine not generating a variant for the first GT power tier passed in.

### Steps to Reproduce

Copied the example script for the production of a generator in startup scripts:

```
event.create('bio_generator', 'generator', GTValues.LV, GTValues.MV)
        .recipeTypes(['bio_generator'])
        .tankScalingFunction(tier => tier * 3200)
```

Here is the matching bio_generator recipe type:

```
event.create('bio_generator')
        .category('generator')
        .setEUIO('out')
        .setMaxIOSize(1, 0, 1, 0)
        .setSound(GTSoundEntries.CHEMICAL)
```

The resulting machine does not have an LV variant. Adding a 0 between 'generator' and GTValues.LV results in it working correctly, however

**Comment by YoungOnionMC** [comment]
can you reopen this issue on the gtm wiki repo?
https://gregtechceu.github.io/gtceu-modern-docs/

**Comment by vinni57** [comment]
> can you reopen this issue on the gtm wiki repo? https://gregtechceu.github.io/gtceu-modern-docs/

Done :)
