### ISSUE TITLE
GTCEu clashing with JEI

### ISSUE THREAD

**Issue by ghost** [GregTechCEu/GregTechCEu-1.19#1823]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.0

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Sİngleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

![image](https://github.com/user-attachments/assets/9346ad82-007b-4b3d-89fe-c4f5020918e5)

### Expected Behavior

Game launches with JEI and GTCEu installed simultaneously

### Actual Behavior

Game refuses to launch when JEI and GTCEu is installed simultaneously

### Steps to Reproduce

Install JEI and GTCEu

### Additional Information

I need JEI because Create recipes aren't visible without it and I cant uninstall GTCEu either because my modpack is centered around GTCEu and Create.

**Comment by ghost** [comment]
This happens on older versions too

**Comment by Pumpkin7266** [comment]
update jei to 15.12.3.54

**Comment by ghost** [comment]
works
