### ISSUE TITLE
Marble ores incorrectly named

### ISSUE THREAD

**Issue by Ix-risor** [GregTechCEu/GregTechCEu-1.19#1837]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.3.1

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

SIngleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Gregtech community pack

### Expected Behavior

Marble ores are named "Marble X Ore"

### Actual Behavior

Marble ores are instead named "Red Granite X Ore"

### Steps to Reproduce

View any kind of marble ore either in JEI, in-world, or after harvesting with silk touch.

**Comment by screret** [comment]
you aren't on latest. this is already fixed.
