### ISSUE TITLE
Forge hammer and Raw ore Block issue

### ISSUE THREAD

**Issue by Midao133** [GregTechCEu/GregTechCEu-1.19#1845]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-1.20.1-1.4.0

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Dedicated server

### Cross-Mod Interaction

No

### Other Installed Mods

Monifactory

### Expected Behavior

Recipy for block of raw ore (raw diamond ore block, etc) for the forge hammer is supposed to give back the 9 items
![image](https://github.com/user-attachments/assets/ad3b7e92-87f5-497e-872d-d5561a7a3d33)

### Actual Behavior

recipy doesnt start
![image](https://github.com/user-attachments/assets/534542af-edc7-4160-8695-f9b83231d4f4)
![image](https://github.com/user-attachments/assets/b3f4a1b8-7948-40a6-998d-9add096b2ac6)

### Steps to Reproduce

have a powered forge hammer of any tier
put any raw ore block
nothing happens

### Additional Information

This is especially bad since in harder mode of monifactory they remove the crafting table way of compressing and decompressing ores

**Comment by screret** [comment]
can the forge hammer vent?

**Comment by Midao133** [comment]
its lv in the ss

**Comment by screret** [comment]
oh, oops

**Comment by Midao133** [comment]
ive tried with all kind of forge hammer but it doesnt seems to work, also my monifactory version is 0.8.1

**Comment by MatthiasMann** [comment]
there seems to be a general issue with recipes - I was also unable to make a maintenance hatch in an LV assembler (circuit 1, LV machine hull) - using gtceu-1.20.1-1.4.0-build_1035-SNAPSHOT.

**Comment by screret** [comment]
it.... wants circuit 2?

**Comment by screret** [comment]
wtf
