### ISSUE TITLE
EBF doesn't overclock aluminium ingots on HV power

### ISSUE THREAD

**Issue by MatthiasMann** [GregTechCEu/GregTechCEu-1.19#1870]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-1.20.1-1.4.0-build_1043-SNAPSHOT

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Sky Greg modpack without FastSuite

### Expected Behavior

The HV powered EBF (2x MV energy hatch) should process an aluminium ingot in ~15s as shown in the recipe viewer using circuit 2 with nitrogen

### Actual Behavior

it takes 30s as it did with the MV powered one (2x LV energy hatch)

### Steps to Reproduce

- build an EBF with 2x MV energy hatches, 1 input hatch, 1 output bus, 1 input bus and cupronickle coils
- check that the UI says "overclock tier HV", Max EU/t: 512 (HV) and Max recipe tier: HV
- select circuit 2
- insert nitrogen
- insert aluminium dust

### Additional Information

Looking at the Jade overlay and at my 4 MV gas turbines - the EBF actually uses only 120EU and not the 480EU it should when overclocked.

**Comment by screret** [comment]
might be fixed with #1863

**Comment by MatthiasMann** [comment]
As it's not wasting power I'm fine with waiting until the fix lands (otherwise I would probably build a 2nd one using only MV input power to not waste my fuel).

I'm impressed with how quick you guy fix these bugs.

**Comment by MatthiasMann** [comment]
sadly this issues was not fixed with gtceu-1.20.1-1.4.0-build_1052-SNAPSHOT
