### ISSUE TITLE
Machines don't respect the minimum power tier for recipes

### ISSUE THREAD

**Issue by MatthiasMann** [GregTechCEu/GregTechCEu-1.19#1876]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-1.20.1-1.4.0-build_1052-SNAPSHOT

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Sky Greg without FastSuite

### Expected Behavior

Machines should not perform recipes which have a higher power tier than their recipe tier (power tier in single blocks).

### Actual Behavior

a) the LV extractor will extract 18mb of liquid aluminium from an aluminium bolt and then break (need to pick up the machine and place it down again)

b) The MV assembler consumes ~7900 EU/t (IV power level) and immediate empties it's energy buffer and can't craft.
reducing the overclocking setting doesn't help.

### Steps to Reproduce

a)
1. place an LV extractor
2. insert an aluminium bolt
3. the extractor will extract 18mb of liquid aluminium and then break (need to pick up the machine and place it down again)

b) Alternate approach (the original topic for this bug report before I associated it with the above issue I noticed previously):

This is a conflict with the following kubejs recipe:
```event.remove ({ output: 'advgenerators:iron_frame'})
event.recipes.gtceu.assembler('kubejs:assembler/iron_frame')
.itemInputs('4x #forge:rods/long/iron')
.itemOutputs('1x advgenerators:iron_frame')
.duration(50)
.EUt(IV)
```

1. place MV assembler and connect to power
5. insert 4+ long iron rods
6. the assembler starts to craft but can't finish

**Comment by YoungOnionMC** [comment]
fixed in #1878
