### ISSUE TITLE
Small dust recipes are the same as tiny dust ones

### ISSUE THREAD

**Issue by NeveHanter** [GregTechCEu/GregTechCEu-1.19#188]
### GregTech CEu Version

(1.19.2) 1.0.7.b-build_87

### Recipe Viewer Installed

REI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

I can craft tiny dusts.

### Actual Behavior

I cannot craft tiny dusts due to conflicting pattern in the recipes:
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/3267401/84468d8b-78e8-4172-a9c4-9d912a1c9b9c)

### Steps to Reproduce

Try the craft ;)

**Comment by MaxNeedsSnacks** [comment]
Same as #187
