### ISSUE TITLE
Primitive blast furnace no longer works

### ISSUE THREAD

**Issue by MatthiasMann** [GregTechCEu/GregTechCEu-1.19#1882]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-1.20.1-1.4.0-build_1058-SNAPSHOT

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Sky Greg without FastSuite

### Expected Behavior

64 wrought iron ingots + 64 coke should produce 64 steel ingots

### Actual Behavior

Nothing - the machine doesn't do anything (replacing the controller didn't fix it either)

### Steps to Reproduce

1. build a primitive blast furnace
2. insert 1 or more wrought iron ingots
3. insert 1 or more coke

### Additional Information

The coke oven doesn't burn coal either - might be related to the steam boilers not burning fuel too.

**Comment by YoungOnionMC** [comment]
are you able to reply more often on the ceu discord, for faster feedback?
