### ISSUE TITLE
Pattern buffers are a valid part ability for assemblylines

### ISSUE THREAD

**Issue by kolan4ick** [GregTechCEu/GregTechCEu-1.19#1891]
### Cross-mod Integration

AE2

### Feature Description

I want the PatternBuffer to insert the items in the order they are listed in the pattern to automate the AssemblyLine, because it is quite difficult to do this now, especially if the craft needs more than 64 items.

**Note**: **this is my first issue here, so I apologize if I've done something wrong in the design or description.**

**Comment by Ghostipedia** [comment]
Pattern buffers aren't meant to be compatible with assembly lines

**Comment by kolan4ick** [comment]
Will pattern buffers be compatible with assembly lines in the future?

**Comment by Ghostipedia** [comment]
> Will pattern buffers be compatible with assembly lines in the future?

They never will be compatible. Pattern buffers and extensible machines like the assembly line are mutually exclusive.

**Comment by kolan4ick** [comment]
> > Will pattern buffers be compatible with assembly lines in the future?
> 
> They never will be compatible. Pattern buffers and extensible machines like the assembly line are mutually exclusive.

Okay, thanks for the answer.
