### ISSUE TITLE
Empty Tag: forge:small_springs/platinum

### ISSUE THREAD

**Issue by 300f20t** [GregTechCEu/GregTechCEu-1.19#1892]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.0

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

Dedicated Server or Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

AE2, JEI.

### Expected Behavior

The empty tag is missing

### Actual Behavior

empty tag

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/f9ba0868-0650-45b0-baed-066c246cf541)
![image](https://github.com/user-attachments/assets/d3315bc5-7833-41be-be56-7599f19adc11)
![image](https://github.com/user-attachments/assets/44f9bca8-20c3-467d-9496-5ce44153b73a)

**Comment by YoungOnionMC** [comment]
fixed in #1908
