### ISSUE TITLE
Most mixer recipes not working

### ISSUE THREAD

**Issue by Atticool** [GregTechCEu/GregTechCEu-1.19#1897]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.4.0

### Minecraft Version

1.21.1

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Configuration, JEI, LDLib

### Expected Behavior

Expected every Mixer recipe to work

### Actual Behavior

Most mixer recipes are broken, such as Bronze Dust, Potin Dust, Kanthal Dust, etc.

### Steps to Reproduce

1. Create a new instance on 1.21.1 with the latest Neoforge version
2. Install latest version (1.4.0) of GTCEU Modern
3. Install JEI
4. Look at Mixer uses in JEI, or any of the aforementioned dust recipes.

### Additional Information

Turning on debug mode, the debug.log file doesn't seem to show any errors with the mixing recipes specifically. The broken recipes do not show up in the dumped recipe folder either. The order in gtceu/data/recipe/serialized/chemistry/MixerRecipes.java doesn't seem to matter either, since gunpowder recipes are added but bronze dust is not.

**Comment by Atticool** [comment]
I forgot to attach an image to show the problem. As you can see, there are only 66 working recipes (in JEI), although there should be a lot more

<img width="501" alt="Screenshot 2024-09-06 at 3 34 46 AM" src="https://github.com/user-attachments/assets/88d94aac-cede-48fd-9837-9a47317f4c88">

**Comment by YoungOnionMC** [comment]
fixed in #1918
