### ISSUE TITLE
Unable to wash impure dusts/crushed ores in the cauldron

### ISSUE THREAD

**Issue by NeveHanter** [GregTechCEu/GregTechCEu-1.19#190]
### GregTech CEu Version

(1.19.2) 1.0.7.b-build_87

### Recipe Viewer Installed

REI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

I can wash impure dusts & crushed ores in the cauldron.

### Actual Behavior

Nothing happens after throwing item/stack inside the cauldron.

### Steps to Reproduce

1. Take your precious ore,
2. pulverise it to dust,
3. see the impurities,
4. steal the cauldron from the nearby village's leatherworker, poor guy,
5. bring the cauldron to your base and fill it with water ("where did I put that bucket again?"),
6. throw the impure dusts inside the cauldron,
7. no effect

**Comment by ChromaPIE** [comment]
yo so it's a confirmed bug right?

**Comment by ccpemily** [comment]
This bug will cause significant lack of sulphur in the early game stage, because I cannot wash impure sulphur dust before crafting an ore-washing plant, unless directly smelt sulphur ores.

**Comment by screret** [comment]
less a bug, more a NYI feature
