### ISSUE TITLE
Server crashes while dismantle ulv input buses

### ISSUE THREAD

**Issue by MoXuanSun** [GregTechCEu/GregTechCEu-1.19#1904]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.0

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

Dedicated Server

### Cross-Mod Interaction

Unsure

### Other Installed Mods

we use a mod pack:

https://github.com/nutant233/GregTech-Leisure

### Expected Behavior

should drop item or someting

### Actual Behavior

server crashed 

### Steps to Reproduce

1. put a ulv input bus 
2. use a wrench to dismantle it in survive mode 

### Additional Information

those are the crash reps, we tested 3 times in survive mode 

[crash-2024-09-07_15.03.04-server.txt](https://github.com/user-attachments/files/16915234/crash-2024-09-07_15.03.04-server.txt)
[crash-2024-09-07_14.48.43-server.txt](https://github.com/user-attachments/files/16915235/crash-2024-09-07_14.48.43-server.txt)
[crash-2024-09-07_14.58.50-server.txt](https://github.com/user-attachments/files/16915237/crash-2024-09-07_14.58.50-server.txt)

**Comment by screret** [comment]
GTL has their own fork of GTM, which we do not support.
