### ISSUE TITLE
QoL updates around voltage levels in the recipe viewers

### ISSUE THREAD

**Issue by NeveHanter** [GregTechCEu/GregTechCEu-1.19#191]
### Cross-mod Integration

JEI/HEI/REI, etc.

### Feature Description

GTNH has a nifty feature in its forked recipe viewer that:

- allows filtering recipes by the <= voltage tier (you can click the arrow in the machine's GUI or select the machine on the left in the recipe browser),
- shows lower voltage levels' recipes OC'ed to the selected voltage level (all the stats are properly calculated for the selected voltage level),
- sorts the recipes by voltage level so you know when to stop scrolling.

These are pretty nice features that by themselves would be a great addition to GTCEu, but maybe they could be improved by adding better voltage level filtering.
I.e. there could be selectable list on the right or additional column on the left similar to the machine list where you can select each voltage level you're interested in (i.e. everthing, only MV or all below MV).
There could also be a global filter for the whole tree, so I can toggle each voltage level to declutter whole tree, i.e. I'm in LV, I don't want to see Aluminium things in the tree when I search for the ingots.

Also note that AFAIK GTNH doesn't have tiered chances so that's something that could be also implemented here when you view OC'ed recipes (both int the tooltip and a numbers next to the item).

I'm not sure if these kind of features are possible with these recipe viewers' API alone, but maybe that's something that could be suggested as an addition to these APIs.

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/3267401/91163ea9-952f-4df9-a9c1-5e81c2749eab)
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/3267401/3bebc76e-fe53-4b89-8b6e-f6f83d6ef7d8)
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/3267401/541f9120-aee3-4b7d-95c3-4436d7aab993)
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/3267401/4c85fad3-9b6f-4e59-83df-6d661f4a5f47)

**Comment by screret** [comment]
can't without cluttering the recipe viewer a lot, sadly.
