### ISSUE TITLE
Charcoal igniter has no visual indication that it's running

### ISSUE THREAD

**Issue by MatthiasMann** [GregTechCEu/GregTechCEu-1.19#1916]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-1.20.1-1.4.0-build_1073-SNAPSHOT

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

SkyGreg modpack

### Expected Behavior

The charcoal igniter should emote smoke particles (maybe some sparks too?) while it's burning (similar to  the macerator or steam boilers)

### Actual Behavior

without having JADE installed it's not possible to see if the charcoal igniter is working or not

### Steps to Reproduce

1. build a charcoal igniter pile (3x3, bricks, logs dirt etc)
2. ignite the igniter
3. wait and hope that you build it correctly (or look at JADE)

**Comment by YoungOnionMC** [comment]
fixed in #1923
