### ISSUE TITLE
No chance based outputs on atleast macerator, ore washer and thermal centrifuge

### ISSUE THREAD

**Issue by MatthiasMann** [GregTechCEu/GregTechCEu-1.19#1917]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-1.20.1-1.4.0-build_1073-SNAPSHOT

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

SkyGreg

### Expected Behavior

Bonus / chance based outputs should be generated

### Actual Behavior

No chance based outputs from HV macerator, MV ore washer or LV thermal centrifuge (not even stone dust)

### Steps to Reproduce

1. place a HV macerator insert 1 stack of ore
2. place an ore washer and put the crushed ore in
3. place a thermal centrifuge and insert the purified ore

**Comment by YoungOnionMC** [comment]
fixed in #1920
