### ISSUE TITLE
Crash when Entering World

### ISSUE THREAD

**Issue by Phoupraw** [GregTechCEu/GregTechCEu-1.19#194]
### GregTech CEu Version

1.0.7.b

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

No crash.

### Actual Behavior

Crash when entering the world.

### Steps to Reproduce

1. Create a world.
2. Enter the world.
3. Crash.

### Additional Information

[minecraft-exported-crash-info-2023-07-24T17-41-18.zip](https://github.com/GregTechCEu/GregTech-Modern/files/12144283/minecraft-exported-crash-info-2023-07-24T17-41-18.zip)
[minecraft-exported-crash-info-2023-07-24T17-45-34.zip](https://github.com/GregTechCEu/GregTech-Modern/files/12144287/minecraft-exported-crash-info-2023-07-24T17-45-34.zip)

**Comment by Yefancy** [comment]
@screret related to 1.20,1 ore gen
