### ISSUE TITLE
Builder option for weighted outputs

### ISSUE THREAD

**Issue by JuiceyBeans** [GregTechCEu/GregTechCEu-1.19#1942]
### Cross-mod Integration

No

### Feature Description

A builder option that lets you add weighted outputs for recipes

``.weightedOutput(ingredient, weight)``

The ability to add bonus rolls, while not necessary, would be useful to have

**Example:**
```java
ASSEMBLER_RECIPES.recipeBuilder("test_recipe")
                .inputItems(Items.DIRT)
                .weightedOutput(Items.SAND, 9)
                .weightedOutput(Items.DIAMOND, 1)
                .circuitMeta(1)
                .duration(200).EUt(VA[LV]).save(provider);
```
Would generate a recipe with 90% chance to output dirt and 10% chance to output a diamond

**Comment by screret** [comment]
wait this *is* actually possible sorry

**Comment by JuiceyBeans** [comment]
bro

**Comment by screret** [comment]
do `.chancedItemOutputLogic(ChanceLogic.XOR)` and then add the outputs as normal

**Comment by JuiceyBeans** [comment]
Do it support weights?
