### ISSUE TITLE
Facade Covers do not work on Optical Fiber Cables

### ISSUE THREAD

**Issue by Pumpkin7266** [GregTechCEu/GregTechCEu-1.19#1951]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

Latest (1.4.1patch2)

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

SinglePlayer

### Cross-Mod Interaction

No

### Other Installed Mods

JEI

### Expected Behavior

Able to place facade covers on Optical Fiber Cables

### Actual Behavior

Not able to place facade covers on Optical Fiber Cables

### Steps to Reproduce

Place optical fiber
Try to place facade
Fail and cry

**Comment by krossgg** [comment]
Fixed with #1953
