### ISSUE TITLE
Chance cannot be less or equal to 0 or more than 10000. Actual: 0.

### ISSUE THREAD

**Issue by skohlhepp** [GregTechCEu/GregTechCEu-1.19#1958]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

GregTechCEu 1.20.1-1.4.0

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

Dedicated Server

### Cross-Mod Interaction

Unsure

### Other Installed Mods

ATM9 v 0.3.2
This error seems like it involves an interaction with KubeJS version: kubejs-forge-2001.6.5-build.14.jar

### Expected Behavior

Game is playable normally with GregTech stuff.

### Actual Behavior

I am running an ATM 9 Server on v 0.3.2 and I am having an issue with a GregTech error spamming during startup. The server boots and runs fine but after I interact with the inventory of any GregTech block once then basically get desynced from server and cant open any chests and when I exit the game the server crashes. I just need some help narrowing down where the issue could be.

[Here](https://paste.ubuntu.com/p/4twSgg7FFR/) is the error that spams during startup. 

The game is playable with no issues until someone opens the inventory of or interacts with any GTCEu block. Once you do this you can not interact or open any other block in the game this [error](https://paste.ubuntu.com/p/gpTWVrtScX/) comes up. 

### Steps to Reproduce

Run ATM 9 0.3.2 - This issue also occurred in 0.3.0.

I am not sure if this is entirely a Gregtech issue but any guidance would be appreciated.

**Comment by YoungOnionMC** [comment]
this is an issue regarding atm9 scripts, ask them
