### ISSUE TITLE
Brick doesn't macerate into dust

### ISSUE THREAD

**Issue by theMegaTech** [GregTechCEu/GregTechCEu-1.19#1964]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.1

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

none

### Expected Behavior

Expected to macerate bricks (the items)

### Actual Behavior

Only bricks (the block) are maceratable, not items

### Steps to Reproduce

1) check the recipe and EMI
2) see there's none

**Comment by Vextin** [comment]
I'll be tackling this tonight :)

**Comment by Vextin** [comment]
This is fixed in dev (and I don't know why)
