### ISSUE TITLE
nothing

### ISSUE THREAD

**Issue by Pumpkin7266** [GregTechCEu/GregTechCEu-1.19#1978]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.1

### Minecraft Version

1.21.1

### Recipe Viewer Installed

JEI

### Environment

SinglePlayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Jei

### Expected Behavior

Gregtech to launch with latest JEI

### Actual Behavior

Gregtech requires a too high/ non existent version of JEI for 1.21.1

### Steps to Reproduce

add greg and jei to modpack in 1.21

**Comment by Pumpkin7266** [comment]
![image](https://github.com/user-attachments/assets/82aaa0f4-8dd7-4b8b-8cc0-e7b376a0a4c3)

**Comment by YoungOnionMC** [comment]
https://www.curseforge.com/minecraft/mc-mods/jei/files/5708550 ?

**Comment by Pumpkin7266** [comment]
wtf curseforge app moment?

**Comment by Pumpkin7266** [comment]
fuck it was not checking for beta versions nvm
