### ISSUE TITLE
Filling/emptying drums with a bucket moves the bucket

### ISSUE THREAD

**Issue by a-a-GiTHuB-a-a** [GregTechCEu/GregTechCEu-1.19#1979]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.1

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

singleplayer (doesn't matter)

### Cross-Mod Interaction

No

### Other Installed Mods

botania, some random irrelevant stuff, AE2, Fireproof Boats, AppleSkin, Jade, KubeJS and addons, a freecam mod, etc.

they're all irrelevant afaik

### Expected Behavior

When I fill my bronze drum with lava, the bucket stays in the 9th hotbar slot where it belongs.

### Actual Behavior

The bucket slides over to the 8th slot (which is empty) when filling the drum. Drawing a bucket of fluid also moves the bucket.

### Steps to Reproduce

1. put bucket in hotbar slot that is to the right of at least one empty slot
2. acquire drum
3. fill bucket
4. deposit fluid to drum
5. bucket slides over
6. put it back
7. take the fluid back from drum
8. it slides over _again_

### Additional Information

If I had to guess, this issue comes from the fact that the filled bucket is a different item from the empty one. It gives the filled/empty bucket item to the player without taking the slot into account.

**Comment by YoungOnionMC** [comment]
fixed in #2422
