### ISSUE TITLE
prospector shows ores that aren't in range

### ISSUE THREAD

**Issue by velzie** [GregTechCEu/GregTechCEu-1.19#1985]
Playing on latest monifactory (1.20.1, gtceu 1.40), prospector shows iron even though it isn't in range
![image](https://github.com/user-attachments/assets/dbfc827c-d7ab-468c-b86c-a31df92c20d1)

**Comment by Ghostipedia** [comment]
Please Verify this occurs on the latest version of GTModern first, as 1.4.0 is outdated now.
If Monifactory is still outdated that is on the pack itself to resolve.

**Comment by velzie** [comment]
issue is unrelated, moving elsewhere
