### ISSUE TITLE
Move NC tag to top-left corner of Programmed Circuit

### ISSUE THREAD

**Issue by Caerglad** [GregTechCEu/GregTechCEu-1.19#1989]
### Feature Description

Programmed circuits no.7 with NC tag can be confused as no.1
![image](https://github.com/user-attachments/assets/67b71630-4336-4a9f-ad99-be72c2d1bf68)
Moving this tag to top left corner should fix this, as circuit numbers go up to around 30

**Comment by Ghostipedia** [comment]
These are not the default textures included with GTCEu Modern. Please Take it up with the resource pack author instead.
Most Recipe overlays (NonConsume, Range, %, Weight, etc) are all on the right to accommodate for Numbers. As well as NonConsume doesn't just apply to programmable circuits, it would affect any non consumable.
Changing only one of them isn't something we plan to do.
