### ISSUE TITLE
Showing usages of multiblock controllers shows all multiblocks in the Multiblock Info

### ISSUE THREAD

**Issue by Fuyukai** [GregTechCEu/GregTechCEu-1.19#200]
### GregTech CEu Version

1.0.8

### Recipe Viewer Installed

EMI

### Environment

singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

The multiblock info should only show the selected multiblock.

### Actual Behavior

The multiblock info shows the first one, and then all other multiblocks.

### Steps to Reproduce

1) Use usages on a mutliblock controller (e.g. the LCR block)
2) Go to the Multiblock Info tab.
3) Large Bronze Boiler jumpscare.

**Comment by Yefancy** [comment]
This seems to be a problem with EMI?

**Comment by Fuyukai** [comment]
Possibly? I don't know how EMI works or your EMI integration. This is just what happens.
