### ISSUE TITLE
Crush

### ISSUE THREAD

**Issue by AngryUnp** [GregTechCEu/GregTechCEu-1.19#2002]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.1 patch.2

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

-

### Cross-Mod Interaction

Yes

### Other Installed Mods

https://www.curseforge.com/minecraft/modpacks/gregtech-new-beginnings
ver: 0.3.3, but the mod was updated

### Expected Behavior

...Loading?

### Actual Behavior

![image](https://github.com/user-attachments/assets/11c626c1-5bb1-4b33-bf73-20333fbee42a)

### Steps to Reproduce

1) players did not launch on the mod version 0.4.0, it gave an error as if different versions (configs, etc. were deleted)
2) decided to update the mod (and the library, respectively)
3) after the update, no one's launcher starts, but the server started and works

### Additional Information

[startup.log](https://github.com/user-attachments/files/17090171/startup.log)

**Comment by screret** [comment]
this is on the pack to fix when they update GT. don't just update mods in packs willy nilly.
