### ISSUE TITLE
Config to disable harder Hatch/Bus recipes

### ISSUE THREAD

**Issue by Xefyr0** [GregTechCEu/GregTechCEu-1.19#2013]
### Feature Description

1.4.1 introduced harder hatch/bus recipes.
There is a sizeable constituent of the Monifactory discord that would like to see the change reverted.

If this is not planned, that is OK - KJs exists, after all

**Comment by YoungOnionMC** [comment]
the hatch recipes that come from 1.12 had a lot of balancing and thought put behind those specific recipes in the base mod, if a pack needs to make them harder or easier, kube is always available
