### ISSUE TITLE
2 energy hatches don't increase max recipe tier

### ISSUE THREAD

**Issue by DmitryScaletta** [GregTechCEu/GregTechCEu-1.19#2017]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.4.2

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

ATM9

### Expected Behavior

Multiblocks increase their max recipe tier if 2 energy hatches installed.

### Actual Behavior

Multiblocks don't increase their max recipe tier if 2 energy hatches installed.

![2024-09-24_13 24 54](https://github.com/user-attachments/assets/0090d55b-b52b-4927-9170-7c4f77f49edf)
![2024-09-24_13 25 11](https://github.com/user-attachments/assets/ac3f198e-5d62-4eb2-be3d-6fea773b006b)

### Steps to Reproduce

1. Build an LCR with 2 IV energy hatches
2. See in the GUI that max recipe tier is still IV.

### Additional Information

It worked fine in GregTechCEu 1.20.1-1.4.1+patch.2
Same issue with regular 2A energy hatches or 4A energy hatches

P.S. Also ME Output Hatch is in the Inputs section (see screenshot)

**Comment by Pumpkin7266** [comment]
![image](https://github.com/user-attachments/assets/b12d926d-4c3a-4a50-a342-9f19c21b4404)
for reference, issue is something diferent because 1 iv hatch causes this

**Comment by DmitryScaletta** [comment]
Looks like there is also something wrong with the recipe durations.
I have 4 LCRs with 2 4A IV energy hatches each.
GUI says it can only run at IV.
But WAILA says the actual recipe runs at LuV.
And the recipe takes only 5 ticks but JEI says it should take 2 seconds at LuV.
Maybe it's because I wallshare 4 LCRs with stocking hatches/buses, I don't know.

UPD. It works as expected. JEI just doesn't show that LCR overclocks recipes 4:4 instead of 4:2. 

![2024-09-24_14 00 40](https://github.com/user-attachments/assets/4b72e760-4a2c-43a9-97d8-cf93e3c0c50b)
![2024-09-24_14 01 23](https://github.com/user-attachments/assets/e4822e4a-d752-44d5-aa03-d08ec42aae04)

**Comment by DmitryScaletta** [comment]
Just installed gtceu-1.20.1-1.4.3-build_1131-SNAPSHOT.jar
Can confirm that the issue is fixed in https://github.com/GregTechCEu/GregTech-Modern/pull/2019

**Comment by kaitlynia** [comment]
This affects Gregicality multiblocks

Shown: Centrifuge set to Thermal, running in EV
<img width="1229" height="681" alt="Image" src="https://github.com/user-attachments/assets/5c0fa0d8-f7ab-4eda-8ecb-137280973bfc" />

Shown: Unused EV Energy Hatch. Above this is another EV Energy Hatch which is being used. There is definitely enough amperage available on the wire.
<img width="605" height="681" alt="Image" src="https://github.com/user-attachments/assets/fc31f5a3-2257-4e39-80a7-4c54623bd997" />

**Comment by DilithiumThoride** [comment]
> This affects Gregicality multiblocks
> 
> Shown: Centrifuge set to Thermal, running in EV 

Note that the machine is also running 4 Parallels. It is not overclocking to IV, because it is using that power to perform 4 parallel recipes at EV. This is expected behavior.
Were it handed a recipe that _required_ IV, it would run that recipe at IV rather than running Parallels.
