### ISSUE TITLE
Missing recipe for Diamond Screwdriver (LV)

### ISSUE THREAD

**Issue by Cyphall** [GregTechCEu/GregTechCEu-1.19#2021]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.1+patch.2

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

Modpack: GregTech Community Pack Modern

### Expected Behavior

The Diamond Screwdriver (LV) has a recipe.

### Actual Behavior

The Diamond Screwdriver (LV) does not have a recipe.

### Steps to Reproduce

Left click on the Diamond Screwdriver (LV) in JEI.

### Additional Information

JEI also does not find any item called "Diamond Screwdriver Tip" that would be required for this recipe.

**Comment by YoungOnionMC** [comment]
![image](https://github.com/user-attachments/assets/fb7af7d4-5b65-46b7-b379-cc8aaebbae87)
?

**Comment by YoungOnionMC** [comment]
oh wait, reading comprehension moment

**Comment by Cyphall** [comment]
Yeah I'm talking about the electric one :wink:

**Comment by YoungOnionMC** [comment]
fixed in #2024

**Comment by screret** [comment]
onion you can't close issues before the fix is merged
