### ISSUE TITLE
Wood barrels don't respect fluid temperature and gaseousness rules

### ISSUE THREAD

**Issue by Vextin** [GregTechCEu/GregTechCEu-1.19#2028]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.4.4 (dev env)

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Dev environment

### Expected Behavior

Wooden barrels do not accept gasses or hot liquids.

### Actual Behavior

Wooden Barrel BLOCKS do not accept gasses or hot liquids. 

Wooden Barrel ITEMS can pick up gasses and hot liquids:
1. through GUIs, such as the fluid slot of a machine
2. through right-clicking on another drum

### Steps to Reproduce

1. procure a Steel Drum full of Steam
2. put a wood barrel in your hand
3. right-click on the Steel Drum and note that the wood barrel picks up the steam (part 1)
4. Deposit some steam into a machine's fluid slot.
5. use the wood barrel item to pick up that fluid from the slot (part 2)

### Additional Information

Seems like drums as FluidHandlerItemStacks don't check the validity of the fluid before filling... FluidHanderItemStack#isFluidValid always returns true.

**Comment by YoungOnionMC** [comment]
fixed in #2128
