### ISSUE TITLE
[1.21.1] Latest Mod Version Crash Game

### ISSUE THREAD

**Issue by Periam** [GregTechCEu/GregTechCEu-1.19#2038]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-1.21.1-1.4.4

### Minecraft Version

1.21.1

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

JEI
Configuration

### Expected Behavior

To be able to run the game

### Actual Behavior

The game crash with an error

### Steps to Reproduce

1-Install Mod
2-Launch game

### Additional Information

[crash-2024-09-26_11.10.23-client.txt](https://github.com/user-attachments/files/17150021/crash-2024-09-26_11.10.23-client.txt)
[latest.log](https://github.com/user-attachments/files/17150023/latest.log)

**Comment by Pumpkin7266** [comment]
Use ldlib 27.b for now

**Comment by Periam** [comment]
ok, thanks for the replay
