### ISSUE TITLE
New upgraded batteries for HV+ look worse

### ISSUE THREAD

**Issue by Wyrmlet** [GregTechCEu/GregTechCEu-1.19#2042]
### Feature Description

ZedTech textures for upgraded batteries (energium crystals, lapotrons, etc.) that were used previously fit the current art style of the mod better than the ones currently present, especially from IV onward. Perhaps it's worth it to revert those?

**Comment by Wyrmlet** [comment]
Alternatively this could be an integrated resource pack, like what Create does with legacy copper.

**Comment by Ignus3** [comment]
This is definitely personal preference, so I'm in favor of a texture pack for it. Personally I adore the new high tier battery graphics, I hated the zedtech ones.
