### ISSUE TITLE
Empty Tag gtceu:treated_logs

### ISSUE THREAD

**Issue by Cosmoros-git** [GregTechCEu/GregTechCEu-1.19#2044]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.4

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

SP

### Cross-Mod Interaction

Yes

### Other Installed Mods

Monicraft modpack

### Expected Behavior

Missing tag. 
![image](https://github.com/user-attachments/assets/7a826c2d-db02-4fd1-b2b2-3e0b7e1f9268)

### Actual Behavior

Missing recipe not missing. 

### Steps to Reproduce

Look into EMI in the treated logs recipes. 

### Additional Information

Wasn't a thing in 1.4.3

**Comment by JuiceyBeans** [comment]
Fixed in #2045
