### ISSUE TITLE
Creating Custom Recipe on Custom Machine

### ISSUE THREAD

**Issue by KCtops6** [GregTechCEu/GregTechCEu-1.19#2050]
Hello,

After referring to the documentation, I am confused on how to create a custom recipe for a custom machine I made.  For example:
event.recipes.gtceu.assembler('test')
What should "assembler" be replaced with?

Additionally, is there a place I can find a list of constants such as "GTSoundEntries.COOLING" found in the documentation?

Thank you for your time and hard work on this mod.

**Comment by JuiceyBeans** [comment]
Example for creating new recipe types: https://github.com/ThePansmith/Monifactory/blob/main/kubejs/startup_scripts/Singleblock_Registry.js

Your recipe would use `event.recipes.gtecu.(whatever you put in your event.create(recipe_type))`

Sound entries: https://github.com/GregTechCEu/GregTech-Modern/blob/1.20.1/src/main/java/com/gregtechceu/gtceu/common/data/GTSoundEntries.java

**Comment by JuiceyBeans** [comment]
Issue can be closed. Additionally for future reference, you should ask this on the Discord in `#modern-support` instead of making an issue

**Comment by KCtops6** [comment]
Thank you for the reference and your time.  I got it to work.  I will note about the Discord in the future.
