### ISSUE TITLE
Research stations often cannot conduct scheduled research

### ISSUE THREAD

**Issue by LiN-lN** [GregTechCEu/GregTechCEu-1.19#2051]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.4

### Minecraft Version

1.20.1

### Recipe Viewer Installed

None

### Environment

单人游戏

### Cross-Mod Interaction

Unsure

### Other Installed Mods

[GregTech-Leisure-1.4.2.0.zip](https://github.com/user-attachments/files/17173584/GregTech-Leisure-1.4.2.0.zip)
![image](https://github.com/user-attachments/assets/1bdd936e-66f3-40ea-9bdf-020b6d28b431)
该整合包和图片所示mod

### Expected Behavior

A方块在已成型研究站物品支架内和数据模块在UEV级别的电压下通过256C/tick的算力支持下经过一定时间产出B方块的数据模块用于装配线合成B方块

### Actual Behavior

A方块及数据模块并未消耗，B方块的数据模块也未产出，在所以条件满足的情况下研究站多方块不进行工作，但可以进行UEV以下所以电压等级的工作

### Steps to Reproduce

在安装上述整合包和私货MOD后建造UEV电压等级工作的研究站并提供256C/tick以上算力  随意挑选一个UEV等级的研究配方  如：太空组装模块+数据模块生成超时空装配线

**Comment by screret** [comment]
...we can't read chinese

**Comment by LiN-lN** [comment]
> ...我们看不懂中文
https://github.com/GregTechCEu/GregTech-Modern/issues/2052
