### ISSUE TITLE
Auto-Smelting enchantment xp drop is not working on gregtech ores.

### ISSUE THREAD

**Issue by Cosmoros-git** [GregTechCEu/GregTechCEu-1.19#2066]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.4

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

SP

### Cross-Mod Interaction

Yes

### Other Installed Mods

Monifactory modpack

### Expected Behavior

Mine ore, get XP. 

### Actual Behavior

On mining ores, XP is not being dropped even though EMI says it should provide XP. Also, a lot of recipes don't provide smelting XP at all. 

### Steps to Reproduce

Hammer with Auto-Smelting enchant.
Break ore.
No XP. 
Mending = sad.

**Comment by krossgg** [comment]
Issue with whatever mod adds auto smelting. Not dropping xp for raw resources is vanilla behavior. You get the xp when you smelt it in a furnace.
