### ISSUE TITLE
Coke Ovens can't wallshare Hathces Output

### ISSUE THREAD

**Issue by FabricioTrude** [GregTechCEu/GregTechCEu-1.19#2068]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.4

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

The modpack is called Monifactory

### Expected Behavior

I'm trying to make wallshared coke ovens, the bototm ones do form, but when I put the top ones they won't because of the hatches

### Actual Behavior

instead of wallsharing hatches they dont form

### Steps to Reproduce

![coke_oven](https://github.com/user-attachments/assets/5a8a109d-a2bb-4484-9d3e-754d78afdf01)

### Additional Information

I dont know if its only for coke oven or other multi :(

**Comment by screret** [comment]
this is intended.

**Comment by screret** [comment]
coke oven hatches cannot be shared.
