### ISSUE TITLE
dual hatch and MEPatternBuffer did not distinct properly

### ISSUE THREAD

**Issue by Heng-ws** [GregTechCEu/GregTechCEu-1.19#2069]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.4

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

SinglePlayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

NONE

### Expected Behavior

those parts should distinct fluids from items

### Actual Behavior

Actually, those parts just distinct items from items, fluids from fluids

### Steps to Reproduce

Name the dual hatch in the first picture "1", Name the dual hatch in the second picture "2". While I put 800mb gaseous chlorine and one sodium powder into “1”，and put 317mb gaseous chlorine into ”2“, they didn't react. But after i put another bucket of gaseous chlorine into "2", they did react. In other word, one sodium powder and 800mb gaseous chlorine   in "1" and 200mb gaseous chlorine in "2" will not react, but one sodium powder in "1" and 1000mb gaseous chlorine in "2" will react.
![Screenshot from 2024-10-01 01-52-27](https://github.com/user-attachments/assets/10986d7e-bdd0-4a69-8ff2-04cbb545305e)
![Screenshot from 2024-10-01 01-52-38](https://github.com/user-attachments/assets/6b67e3ad-90a4-49ba-bd09-00101feb3b71)

**Comment by krossgg** [comment]
Known issue. Unfortunately a very complicated issue and is not being fixed for the foreseeable future.
