### ISSUE TITLE
Extreme FPS drop in-world

### ISSUE THREAD

**Issue by TheAlaskanPhysicist** [GregTechCEu/GregTechCEu-1.19#207]
### GregTech CEu Version

1.19.2 Most Recent Update

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

FPS should be about normal. I tested it with Forge and Fabric with none of the mods.

### Actual Behavior

The FPS is extremely low in the development in IntelliJ.
For both Forge and Fabric, the fps is ~2.

### Steps to Reproduce

Download the most recent from 1.19.2
Run Data for the platform
Run client for the platform
Enter any world.

### Additional Information

I'll guess since this has only recently started happening, it's EMI, but I can't be sure.

**Comment by TheAlaskanPhysicist** [comment]
Just ran it today on Forge/Fabric with REI, and it still has the same effect.

**Comment by TheAlaskanPhysicist** [comment]
After about 2 minutes, the FPS drop subsides unless one of the following occurs:

1. Game quality changes (Fast -> Fancy -> Fabulous!)
2. `F3+T` Reloading Textures
3. A world is loaded into

**Comment by Yefancy** [comment]
if it just happens in the dev env, actullay I cant reproduce it? try to rebuild your project and allocate more memory? also have you tried other JVM? 

try to revert to the commit when it was working, and see if there's still this problem?

**Comment by Yefancy** [comment]
I want to close this issue because it doesn't seem to be a gtceu issue, but I'm not sure. Let's wait and see if anyone else is in the same boat.

**Comment by TheAlaskanPhysicist** [comment]
Sounds good
