### ISSUE TITLE
Flour has no use, bread recipe uses wheat

### ISSUE THREAD

**Issue by Pumpkin7266** [GregTechCEu/GregTechCEu-1.19#2070]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.4

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

single

### Cross-Mod Interaction

No

### Other Installed Mods

Jei

### Expected Behavior

Maybe bread recipe should use flour or flour be made into dough then baked into bread (although in this case probably hardmode configs only)

### Actual Behavior

Flour no use, bread made with wheat even on hard mode

### Steps to Reproduce

open jei, check recipe

**Comment by Pumpkin7266** [comment]
i guess the bigger problem here is hard mode configs make it so hay bale cannot go back to wheat, only to flour

**Comment by YoungOnionMC** [comment]
fixed in #2147
