### ISSUE TITLE
Lighter + shovel issues

### ISSUE THREAD

**Issue by JuiceyBeans** [GregTechCEu/GregTechCEu-1.19#2071]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.5-SNAPSHOT

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Dev env

### Expected Behavior

- Using a GT shovel on a campfire extinguishes it
- Shift + right clicking a lighter anywhere, including if you're looking at a block opens it
- Using a lighter on a campfire lights the campfire

### Actual Behavior

- Campfires can't be extinguished using GT shovels
- You cant open lighters if you're looking at a block
- Using a lighter on a campfire places a fire block above the campfire

### Steps to Reproduce

- Right click campfire with shovel
- Attempt to open lighter while looking at a block
- Use lighter on campfire

**Comment by Astral-Haze** [comment]
Lighters also cannot be used to light candles.
Also, when used for crafting in kubejs with .damageIngredient(..., 4), it consumes the whole item whereas other tools like hammer or flint & steel would be used with durability consumed
