### ISSUE TITLE
UHV+ Circuits

### ISSUE THREAD

**Issue by ghost** [GregTechCEu/GregTechCEu-1.19#2081]
### Feature Description

There should be UHV+ Circuits they don't exist atleast for me.

**Comment by JuiceyBeans** [comment]
Works as intended. GTCEu only goes upto UV content, anything past that point is upto pack and addon devs to implement

**Comment by ghost** [comment]
I see so I gotta make it myself then with custom mod.

**Comment by JuiceyBeans** [comment]
Or KubeJS, yes
