### ISSUE TITLE
Slabs of Stone types dont have recipe in GT Cutter. which is very odd

### ISSUE THREAD

**Issue by FabricioTrude** [GregTechCEu/GregTechCEu-1.19#2085]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.4

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Monifactory

### Expected Behavior

since you can put oak plank in cutter to get oak slab, you should be able to put sandstone or stone or other blocks and get their slab variants in cutter

### Actual Behavior

no recipe :(

### Steps to Reproduce

Add recipes to all blocks that have slabs variant

### Additional Information

that's about it

**Comment by JuiceyBeans** [comment]
Known issue, being worked on
