### ISSUE TITLE
add compat to XTone mod and make them craftable in assembler?

### ISSUE THREAD

**Issue by FabricioTrude** [GregTechCEu/GregTechCEu-1.19#2086]
### Cross-mod Integration

XTone

### Feature Description

XTone is a mod that adds many variants to some blocks, like you can make Myst, and Myst 1 , 2, 3, up to 15,
Make it be craftable in assembler by just changing its circuit, so Circuit 0/no circuit is default Myst block, circuit 5 is Myst 5, and that for all XTone blocks :D

**Comment by screret** [comment]
just do it yourself with KubeJS or the like?

**Comment by JuiceyBeans** [comment]
Recipe Gregification for other mods aren't included with the base mod

**Comment by krossgg** [comment]
Check out our [community pack](https://github.com/GregTechCEu/GregTech-Modern-Community-Pack/tree/main/kubejs/server_scripts/building) for examples, where our wonderful pack dev mina has created recipes similar to what you're asking for. You can always add more on your own too. KubeJS is pretty powerful!

Closing as not planned.
