### ISSUE TITLE
EIO conduits cannot extract power from converters in EU -> FE mode

### ISSUE THREAD

**Issue by EnsignEvident** [GregTechCEu/GregTechCEu-1.19#2089]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.4

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Monifactory

### Expected Behavior

Expected to be able to extract power from a converter to put into conduit network. Works with all other forms of FE power transfer.

### Actual Behavior

No power is transfered

### Steps to Reproduce

Change converter to FE production mode -> Plug a converter into a source of EU energy -> connect conduit to output of converter -> Connect conduit to FE sink -> Observe no power transfer.
![2024-10-04_15 42 11](https://github.com/user-attachments/assets/82975488-50fb-4164-956f-8bcd3fabb28c)
![2024-10-04_15 29 48](https://github.com/user-attachments/assets/48d02dde-715d-46be-9255-fd12f023bc7a)

**Comment by krossgg** [comment]
Known issue with Moni's custom conduits.
