### ISSUE TITLE
[Crash] Generating Chunks

### ISSUE THREAD

**Issue by Phoupraw** [GregTechCEu/GregTechCEu-1.19#209]
### GregTech CEu Version

1.20.1-1.0.8

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

No crash.

### Actual Behavior

Crash.

### Steps to Reproduce

1. Create a new world, or enter a existing world and move to where you have never been.
2. It possibly crashes. If it doesn't crash, repeat step 1.

### Additional Information

AE2 seems increase the probability to trigger the crash, but without AE2 there is still a certain probability to crash.
This crash might prevent server from saving. Crash reports might not be generated, neither.
[crash-2023-07-27_00.17.06-server.txt](https://github.com/GregTechCEu/GregTech-Modern/files/12175006/crash-2023-07-27_00.17.06-server.txt)
[crash-2023-07-27_00.18.50-server.txt](https://github.com/GregTechCEu/GregTech-Modern/files/12175008/crash-2023-07-27_00.18.50-server.txt)
[crash-2023-07-27_00.20.35-server.txt](https://github.com/GregTechCEu/GregTech-Modern/files/12175009/crash-2023-07-27_00.20.35-server.txt)
[crash-2023-07-27_00.22.28-server.txt](https://github.com/GregTechCEu/GregTech-Modern/files/12175005/crash-2023-07-27_00.22.28-server.txt)

**Comment by screret** [comment]
~~actually no ide~~ wait is this the rubber tree trying to generate wtf

**Comment by screret** [comment]
It's added tho only those biomes
Then it tests if it's in those biomes to spawn i think? Or the spawn chance boost
Then it cycles to itself and dies
