### ISSUE TITLE
bug? if I put a fluid filter in between 2 pipes  (a nonuple pipe with 2 liquids and a normal pipe) it doesnt filters.

### ISSUE THREAD

**Issue by FabricioTrude** [GregTechCEu/GregTechCEu-1.19#2116]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.4

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Monifactory

### Expected Behavior

I expected Naphtha to enter on the pipe with the fluid filter, but steam ended up in it.
Tried using naphtha in whitelist and Steam in blacklist, both passed steeam to the small pipe.

### Actual Behavior

Steam entering the small pipe not mattering what I use it

### Steps to Reproduce

Have a nonuple or quad pipe, put 2 fluids, and hook up it into another pipe.
I imagine that the first fluid you put gets priority, so Steam > Naphtha enters whatever you put

**Comment by krossgg** [comment]
Next time, please add a screenshot for more context.

This is a known issue. Filters on the pipe blocks themselves do not work. Use a drum or super tank as a buffer block.

**Comment by YoungOnionMC** [comment]
fixed in #2126
