### ISSUE TITLE
Assembly line input order reversed when built in some orientations

### ISSUE THREAD

**Issue by aevns** [GregTechCEu/GregTechCEu-1.19#2118]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.4.4

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Monifactor (Harder) [modpack]

### Expected Behavior

When the mod is configured to require assembly line ingredient ordering, recipes should complete when inputs are given in order, from the controller's end to the output end.

### Actual Behavior

When constructed with the controller face-down and input side (normally the bottom) facing east, recipes will complete only if recipes inputs are provided in reverse order as shown. This was the only orientation tested, though it most likely happens in other configurations.
![image](https://github.com/user-attachments/assets/5aa617cc-372b-49c0-93b3-dd8d0d9a6e91)

### Steps to Reproduce

With ordering required, construct an assembly line as described (controller face-down, start of line to the south, end to the north, inputs to the east). Try inputting a recipe's ingredients in the normal order; the recipe will not process. Put them in reverse order and it will.

**Comment by krossgg** [comment]
Fixed by #2119
