### ISSUE TITLE
Cable auto-connect system is "wired" backwards. UPDATE: Im a complete idiot and I misunderstood cables

### ISSUE THREAD

**Issue by ShoobFloof22** [GregTechCEu/GregTechCEu-1.19#212]
### GregTech CEu Version

Modern 1.0.8 1.19.2

### Recipe Viewer Installed

JEI

### Environment

Singleplayer, Creative Mode

### Cross-Mod Interaction

Unsure

### Expected Behavior

Cables (Not fluid pipes though, just cables) should, like in the 1.12.2 version, have all sides disconnected by default, requiring you to use the Wire Cutter tool to link them to other cables. Also, placing cables against other cables (by right clicking on the other cable block) should automatically open a connection between the two cables. Enabling a connection manually with the Wire Cutters should also cause the adjacent cable (the one being connected to) to open it's connection as well, completing the link. 

As mentioned, the existing fluid pipes do this fine, as expected. Cables on the other hand... well, read on

### Actual Behavior

Cables _actually_ do the exact opposite of that. Placing a cable down enables all neighboring connections by default. When placing a cable against another cable (again, by right clicking on another cable) actually DISABLES the link between the two. Also enabling a link between to cables using the Wire Cutters is a little funky as well. If you open say, the right side of Cable A to link with the left side of Cable B, you'd expect Cable B to open it's left side automatically to meet with Cable A's link. That does not happen however, requiring you to open both connecting sides manually. I've attached some images here showing some of what I mean. 

First image shows what happens when you place a single cable, second one shows what happens when a cable is placed next to it.
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/79608647/f512d917-c4d1-4b9e-b195-eb54f4009deb)
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/79608647/0b5aabbd-cedd-416f-8161-e9331bf9cb59)

### Steps to Reproduce

Reproduction is easy, just use cables as you'd expect them to work and they will do what I described instead XD

### Additional Information

Just realized, through further testing, that the cables themselves actually do not appear to work at all. Not entirely sure of the cause of that, but they do not transfer any power at all. Machines don't transfer power directly between each other either, it seems. You CAN use the Infinite Energy source block in creative mode to power stuff, that will transmit energy. But only directly into Energy Hatches. Cables don't accept power from it. Also that's obviously a creative-only item so like... yeahhhh, not helpful in survival XD

**Comment by Yefancy** [comment]
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/18493855/48cb5320-3f63-40db-a216-aabaa44525d6)
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/18493855/f32d670e-13e1-4340-a9b3-69049cb5caca)
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/18493855/d52793d1-6200-4e6b-95a2-302600a06167)

**Comment by ShoobFloof22** [comment]
OHHH IM AN IDIOT!!! I just got skill-issued so hard
