### ISSUE TITLE
Machines can't perform cleanroom recipes unless cleanroom was built after the machine was already placed

### ISSUE THREAD

**Issue by Niki4tap** [GregTechCEu/GregTechCEu-1.19#2123]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.4

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

All

### Cross-Mod Interaction

No

### Other Installed Mods

EMI

### Expected Behavior

If you place a machine inside of a cleanroom, it should be able to perform recipes that require cleanroom environment.

### Actual Behavior

Machines are unable to perform cleanroom recipes until you break the cleanroom, and rebuild it.

Guessing placing machines in unfinished cleanroom and finishing the cleanroom after placing the machines also works, but I haven't tested that (should be the exact same scenario).

### Steps to Reproduce

1) Build a cleanroom
2) Place machines inside
3) Try to execute a recipe that require a cleanroom environment
4) Machine does nothing until the cleanroom is reformed

**Comment by krossgg** [comment]
Known issue. Current workaround is to open and close your door, which will trigger an update without having to reform your cleanroom.

**Comment by Niki4tap** [comment]
> Known issue.

Is it a duplicate, should I close or keep open to track progress on it? (if it is even planned to be fixed)

>  Current workaround is to open and close your door, which will trigger an update without having to reform your cleanroom.

Doesn't work if the cleanroom is built without a door. And in that case you would still need to rebuild the cleanroom and that stalls automated recipes which doesn't look good

**Comment by krossgg** [comment]
You can keep the issue open. I don't think we have one on GitHub.

Solution: add a door.
