### ISSUE TITLE
Aluminium Cell doesnt shows its fluid

### ISSUE THREAD

**Issue by FabricioTrude** [GregTechCEu/GregTechCEu-1.19#2124]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.4

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Monifactory

### Expected Behavior

if you put water, it should be blue inside, naphtha yellow.

### Actual Behavior

if you fill it, it shows like its empty
![image](https://github.com/user-attachments/assets/0c16b02d-9673-4ec9-83a9-0bb2ce984be7)
![image](https://github.com/user-attachments/assets/4b8c01eb-fda7-4129-a488-10f2d1374473)

### Steps to Reproduce

Fill an aluminium fluid cell

### Additional Information

dontt need to be full, just any amount of any fluid

**Comment by Ignus3** [comment]
+1 from me, I noticed this is only happening with aluminium fluid cell, no other file. Not sure how that got fixed for the others but not alum
