### ISSUE TITLE
Combining 2 of the same greg tools will use 1 durability from both tools and net you a new tool

### ISSUE THREAD

**Issue by PilpohMC** [GregTechCEu/GregTechCEu-1.19#213]
### GregTech CEu Version

gtceu-forge-1.20.1-1.0.8.a

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Expected Behavior

Combining 2 of the same greg tools **must** add both of the tools durability up and return 1 tool with that durability (if more thatn 100% then set to 100%)

### Actual Behavior

Combining 2 of the same greg tools will use 1 durability from both tools and net you a new tool

### Steps to Reproduce

use a hammer once, make another hammer and use it also.
combine both together and you will get a new hammer and keep the 2 old hammers

**Comment by MaxNeedsSnacks** [comment]
Should be noted that in vanilla, this is done by a special crafting recipe (RepairItemRecipe), I think this *might*(?) be an issue with how return items are handled for GT tools?

**Comment by nishokurengecho** [comment]
Farmer's Delight knives when used in a GT recipe just disappear
