### ISSUE TITLE
Primitive Pump has wrong descriptions and PCO can't use coke dust.

### ISSUE THREAD

**Issue by Cosmoros-git** [GregTechCEu/GregTechCEu-1.19#2157]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.4

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

SP

### Cross-Mod Interaction

Yes

### Other Installed Mods

Monifactory

### Expected Behavior

Pump description telling correct data in ticks.

Not sure if PCO is intended.

### Actual Behavior

The pump tells you that it processes 100mb/s when it's per tick.

Primitive coke ovens cannot use coal dust.  

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/705e7a1b-c7a5-4466-8b8e-40e8aa8d39a4)

**Comment by YoungOnionMC** [comment]
Primitive pump correctly shows in terms of per second, that's how the machine works
Coke ovens intentionally don't allow coal->coke dust conversion as that would be too strong for making steel
