### ISSUE TITLE
Miss some recipes

### ISSUE THREAD

**Issue by UraraChiya** [GregTechCEu/GregTechCEu-1.19#216]
### GregTech CEu Version

build_97

### Recipe Viewer Installed

REI

### Environment

Dedicated Server

### Cross-Mod Interaction

Yes

### Expected Behavior

Can craft the following items:

- [ ] All Buzz Saw Blade
- [ ] Energy Input Hatch 16A
- [ ] MV Solar Panel and above

### Actual Behavior

Cannot craft them.

### Steps to Reproduce

Try looking up their recipe with REI.

**Comment by Yefancy** [comment]
we do `MV Solar Panel and above` intentionally
