### ISSUE TITLE
[EMI] Ghost Circuits invisible to EMI Recipe Tree

### ISSUE THREAD

**Issue by riking** [GregTechCEu/GregTechCEu-1.19#2160]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.4

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Monifactory 0.9.5

### Expected Behavior

1.    Establish a Recipe Tree that includes a machine processing step with a programmed circuit as intermediate steps, e.g. the GregTech assembler recipe for Vacuum Tubes as a precursor to basic LV Circuit
2.    Switch the recipe tree to Crafting Mode, so each step shows up in the favorites panel
3.    Hold all inputs to the Assembler recipe in your inventory
4. The recipe output is highlighted in cyan and you can shift-click it to move all recipe inputs into the machine input slots.

### Actual Behavior

4.    Observe that the recipe target (here, the 2x plate) displays as red ("uncraftable") despite all of its inputs being satisfied and removed from the listing

![image](https://github.com/user-attachments/assets/ab6079d0-48fe-493e-ac33-75003cd0f307)

### Steps to Reproduce

see above

### Additional Information

Issue moved from emilyploszaj/emi#751

**Comment by Deepacat** [comment]
it should probably just not add the circuit to trees
