### ISSUE TITLE
Item Tag Filter does not work.

### ISSUE THREAD

**Issue by UraraChiya** [GregTechCEu/GregTechCEu-1.19#218]
### GregTech CEu Version

build_97

### Recipe Viewer Installed

REI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

Item Tag Filter works.

### Actual Behavior

Item Tag Filter does not work.

### Steps to Reproduce

1. Put a Conveyor Module on a Tungsten Steel Crate.
2. Put some items in the Tungsten Steel Crate, it will move items.
3. Insert an Item Tag Filter in the Conveyor Module.
4. Try "forge:dusts/gold", "#forge:dusts/gold", and even "dustGold", it does not move the Gold Dust and other items.

**Comment by Yefancy** [comment]
"dusts"
"dusts/gold"
