### ISSUE TITLE
Steam solar boilers produce so much sound that it takes around 100 of them to make so every other sound breaks around them.

### ISSUE THREAD

**Issue by Cosmoros-git** [GregTechCEu/GregTechCEu-1.19#2187]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.6

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

SP

### Cross-Mod Interaction

Yes

### Other Installed Mods

Monifactory

### Expected Behavior

Boilers of any kind do not overload Minecraft sounds, leading to artificial muffling of all of them.

### Actual Behavior

![image](https://github.com/user-attachments/assets/94ca26fd-d125-4a29-acb8-988e67d92bac)
I have this solar farm; if I get near, sounds stop playing, except for boiler noises. 

### Steps to Reproduce

Make a reasonably sized steam solar boiler farm and get near it. 

### Additional Information

I guess that they all try to play no matter what, causing something similar to a lot of of minecarts collide into a wall that also nukes sound thread.

**Comment by screret** [comment]
that's.. not reasonably sized.

**Comment by screret** [comment]
we can't do anything about this, closing as not planned.
