### ISSUE TITLE
Improve not consumed items in AE2 patterns

### ISSUE THREAD

**Issue by teh-banana** [GregTechCEu/GregTechCEu-1.19#2190]
### Cross-mod Integration

Applied Energistics 2, EMI

### Feature Description

Since #2160 / #2175 was implemented, while using EMI, AE2 does not include the circuit when creating patterns, which helps the tedium of making patterns.

Could this functionality be extended to all not consumed items? Like extruder mold's, fluid solidifier mold's, even random chemical ingredients that don't get used up.

**Comment by HydrogenDeuterium** [comment]
unconsumed items does not add to pattern at one version in 1.12
this feature is good
