### ISSUE TITLE
Some Vanilla Recipes not Pruned when using Hard GT Recipes. 

### ISSUE THREAD

**Issue by StoneLegion** [GregTechCEu/GregTechCEu-1.19#2194]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-1.21.1-1.4.6 & gtceu-1.21.1-1.4.7-SNAPSHOT

### Minecraft Version

1.21.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Modern 1.21.1 Modpack not released yet. (Quark not installed)

### Expected Behavior

Some Vanilla Recipes don't come with 2 recipes vanilla + GT.

### Actual Behavior

Some recipes have both GT / Vanilla Recipes.

### Steps to Reproduce

Armor Stand
![image](https://github.com/user-attachments/assets/51e9b136-d263-4b0c-8cea-3d03711bb59a)

Bee Hive
![image](https://github.com/user-attachments/assets/3b069c92-c38a-4005-a636-0e814dbe2aa1)

Beacon:
![image](https://github.com/user-attachments/assets/0b5f2e44-8645-4ab4-8c05-3145dee815f1)

Blast Furnce:
![image](https://github.com/user-attachments/assets/34a26794-e7ff-406b-a243-d6c52c57ba57)

Brewing Stand
![image](https://github.com/user-attachments/assets/efaeba34-d8cd-420d-b56e-a751047c9905)

Cartography Table:
![image](https://github.com/user-attachments/assets/c19ae55f-21d4-44c6-b6d0-49d2a1cd7c3d)

Composter:
![image](https://github.com/user-attachments/assets/c6445e2f-bb22-477e-ae4b-2b7a091621d2)

Crafting Table
![image](https://github.com/user-attachments/assets/5f952852-cd2e-42eb-b19c-5f8445574ef3)

Enchanting Table:
![image](https://github.com/user-attachments/assets/0b560a29-5406-4df8-9545-8e12449dac04)

Fletching Table:
![image](https://github.com/user-attachments/assets/f9a531de-57bd-46c2-b84f-46623805b951)

Flower Pot 
![image](https://github.com/user-attachments/assets/5a6d2dcd-41db-4f17-aec1-7d2e9e93f179)

Furnace:
![image](https://github.com/user-attachments/assets/6ca7dd0c-9391-4e19-b9c9-4d82286a78ee)

Grindstone:
![image](https://github.com/user-attachments/assets/fa05e0db-7d4e-457d-87fa-8571bc111fb7)

Jack o'Lantern:
![image](https://github.com/user-attachments/assets/8b6b3cd1-e52f-4553-bff3-396af0451e05)

Jukebox:
![image](https://github.com/user-attachments/assets/3e892998-0c13-47ae-a847-f751cf87a3e4)

Latern:
![image](https://github.com/user-attachments/assets/fe00df1f-28d2-4bb0-abb3-dabf71f06cfa)

Lectern
![image](https://github.com/user-attachments/assets/579538c5-e372-44ef-8e49-b55f31fda3fc)

Lightening Rod:
![image](https://github.com/user-attachments/assets/5f802843-0c9c-4b27-829f-1093a33cb9e4)

Loom:
![image](https://github.com/user-attachments/assets/c999e11c-13fa-48d8-818a-e56d41f79b03)

Note Block:
![image](https://github.com/user-attachments/assets/b672a8ec-5158-41b2-b1c7-ea3907077164)

Scaffolding:
![image](https://github.com/user-attachments/assets/39b6cc17-8f23-4952-b36b-76456f2495ae)

Stonecutter:
![image](https://github.com/user-attachments/assets/0272ad7e-b775-4cd7-bd91-1af15277495c)

Smithing Table:
![image](https://github.com/user-attachments/assets/677fe39d-58f9-410f-ab0e-0d44d0523d9e)

Smoker:
![image](https://github.com/user-attachments/assets/0f50f476-5650-4507-b3e2-1b3eeb327cb3)

Should Have a Hard Recipe???
Decorated Pot (File in Center?)
![image](https://github.com/user-attachments/assets/289c18dd-7288-4e55-a3f1-d64f6be434a6)

**Comment by JuiceyBeans** [comment]
Uh oh

**Comment by StoneLegion** [comment]
Hi there, Piston might be missing unless you fixed it yourself.

**Comment by AveryAndCompany** [comment]
piston still missing afaik
