### ISSUE TITLE
Extreme Combustion Engine, Liquid Oxygen consumption

### ISSUE THREAD

**Issue by notnexi** [GregTechCEu/GregTechCEu-1.19#2200]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.20.1-1.4.6

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

Nomifactory 0.9.7

### Expected Behavior

80 mb/s Liquid Oxygen consumption during load.

### Actual Behavior

As you can see in the attached video, consumption goes up several times the expected amount for a brief moment.

https://github.com/user-attachments/assets/36701b0d-2ec6-412c-9098-72f1418bb755

### Steps to Reproduce

Run the engine with High Octane Gasoline, Lubricant, and Liquid Oxygen.

**Comment by YoungOnionMC** [comment]
fixed in #2211
