### ISSUE TITLE
Batch mode

### ISSUE THREAD

**Issue by KePiadina** [GregTechCEu/GregTechCEu-1.19#2201]
### Feature Description

As recipes cannot be faster than 0.05s due to tickrate, make recipes overclocked past it use double/quadruple the inputs (when possible) for double/quadruple the output, akin to parallelization.

Example: EV Distillery can turn 24mB Creosote into 12mB Lubricant. Any higher tier cannot produce it any faster without using a multiblock, and even then it gets bottlenecked by the tickrate. With Batch mode on it would be able, at IV and higher, to use 48/96mB Creosote to produce 24/48mB Lubricant per tick

**Comment by Pumpkin7266** [comment]
this kind of exists. it's called subtick parallels

**Comment by screret** [comment]
Already happens

**Comment by screret** [comment]
only on multiblocks, though.
