### ISSUE TITLE
Large Bronze Boiler HUD/GUI not displaying correctly

### ISSUE THREAD

**Issue by KOSmekKosmik** [GregTechCEu/GregTechCEu-1.19#2203]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.4.6

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

The Gregtech CEu Modern modpack mods

### Expected Behavior

The hud/gui should display correctly

### Actual Behavior

The hud/gui just shows like ~7 top pixels

### Steps to Reproduce

I opened the large bronze boiler.

**Comment by Phantom914** [comment]
Also having the same issue on Monifactory 0.9.7

**Comment by JuiceyBeans** [comment]
Known issue

**Comment by Phoupraw** [comment]
It's also present in `1.21.1-7.1.0-SNAPSHOT+2b820fb`

(Thanks to #2223. It's very easy to fix it.)
