### ISSUE TITLE
Two Recipes for obsidian dust

### ISSUE THREAD

**Issue by mblz90** [GregTechCEu/GregTechCEu-1.19#2204]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.6

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

GTCEu Community Pack Modern

### Expected Behavior

One Recipe for obsidian dust in the macerator

### Actual Behavior

Two Recipes for obsidian dust in the macerator

### Steps to Reproduce

Lookup the uses (hotkey U) for obsidian (the block) in JEI and navigate to the macerator tab.

### Additional Information

![issue](https://github.com/user-attachments/assets/7a717ba1-c25e-478b-92d5-ab17bc7d1148)

**Comment by screret** [comment]
GCP issue
