### ISSUE TITLE
Item consumption in tagged ingredients is wonky

### ISSUE THREAD

**Issue by YoungOnionMC** [GregTechCEu/GregTechCEu-1.19#2214]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.6

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

dev

### Cross-Mod Interaction

No

### Other Installed Mods

ae2

### Expected Behavior

only the required amount of your tag ingredient gets consumed

### Actual Behavior

it consumes everything

### Steps to Reproduce

example script
![image](https://github.com/user-attachments/assets/4b08d7d9-7f73-4eee-9a22-a1abfe44c3ad)

produces
![image](https://github.com/user-attachments/assets/f4076d4a-19ab-4a76-af42-eabe0dde3d51)

what actually happens
![java_GJtA3SwrPM](https://github.com/user-attachments/assets/c6380648-6a41-4783-98a1-70d4f6be602b)

**Comment by krossgg** [comment]
Fixed by #2246
