### ISSUE TITLE
Incompatible with Continuity

### ISSUE THREAD

**Issue by Paper-wand** [GregTechCEu/GregTechCEu-1.19#222]
### GregTech CEu Version

1.0.8.a

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

GregTech-Modern works well with continuity

### Actual Behavior

The game crashed.
[crash-2023-07-29_15.18.10-client.txt](https://github.com/GregTechCEu/GregTech-Modern/files/12206528/crash-2023-07-29_15.18.10-client.txt)

### Steps to Reproduce

1) Download Minecraft
2) Put continuity-3.0.0-beta.3+1.20.1.jar, gtceu-fabric-1.20.1-1.0.8.a.jar and fabric-api-0.86.1+1.20.1.jar in the mods folder
3) Launch the game

**Comment by Yefancy** [comment]
report to continuity
