### ISSUE TITLE
cleanrooms should block copper block weathering

### ISSUE THREAD

**Issue by riking** [GregTechCEu/GregTechCEu-1.19#2224]
### Cross-mod Integration

vanilla

### Feature Description

Cleanrooms should block copper block weathering

Why: Lore

**Comment by krossgg** [comment]
Do it yourself.

**Comment by Ghostipedia** [comment]
Clean-rooms are not Oxygen free. 
Oxidization still occurs in them unless the environment is evacuated with an intert gas like Argon or Nitrogen and we do not have this as a feature for the clean-room. Closing this as while it seems like a cool idea, doesn't really make sense and honey waxing exists.
