### ISSUE TITLE
Add ability to limit inventory sizes in machine outputs to not store a stack of items everywhere.

### ISSUE THREAD

**Issue by Cosmoros-git** [GregTechCEu/GregTechCEu-1.19#2228]
### Cross-mod Integration

Modern Industrialization slot locking and limits

### Feature Description

From what I've been told, there is apparently a messy way to limit machines to holding just a few items they process. But the issue is that it's a mess and makes no sense. Why can't you limit the inventory size of the machine? 

For example, in assemblers, in many situations, you are forced to manually disable the machine because it will work until it's full. Even if you need the smallest items, it's a stack at least. It's not an issue when you are making something cheap and just passing it, but the moment you are limited on materials because they are next tier or just not passive yet, you are manually limiting them or suffering.

**Comment by Cosmoros-git** [comment]
Also, it's not cross-mod integration. I just saw an example textbox and thought it meant I could give an example of a mod with such a feature.

**Comment by screret** [comment]
slot locking is not a feature we're considering, and likely ever won't.
