### ISSUE TITLE
Format Error Conveyor cover settings

### ISSUE THREAD

**Issue by JesseDeLoore** [GregTechCEu/GregTechCEu-1.19#2237]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.6

### Minecraft Version

1.20.1

### Recipe Viewer Installed

None

### Environment

Dedicatedd server

### Cross-Mod Interaction

Yes

### Other Installed Mods

Monifactory 0.9.10

### Expected Behavior

See Conveyor/pump cover text

### Actual Behavior

![image](https://github.com/user-attachments/assets/d7014093-80e3-4a55-8daf-377f58f2b3d1)
![image](https://github.com/user-attachments/assets/1d379cc7-d077-4c6a-a1c3-fe28642e7867)

### Steps to Reproduce

Add cover on pipe and inspect with screwdriver

**Comment by Spicierspace153** [comment]
are you playing in turkish perchance?

**Comment by JesseDeLoore** [comment]
No, just plain old English.
________________________________

**Comment by Spicierspace153** [comment]
weird.
it seems to be localized only to your instance
whats you gui scale?
have you updated monifactory to latest?

**Comment by JesseDeLoore** [comment]
Gui scale is 2x
Monifactory is 0.9.10, the issue is there since I started playing at 0.9.3.

Any logs I can provide to help narrow down the bug?
________________________________
