### ISSUE TITLE
Change to RTM alloy cable for coil blocks not mirrored in other machines' heating elements

### ISSUE THREAD

**Issue by Xefyr0** [GregTechCEu/GregTechCEu-1.19#2238]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.6

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

EMI

### Expected Behavior

if you look at the wires that go into each EBF coil, you may notice that the material they're made of corresponds to the wires that are used in the electric furnace recipe.
Cupronickel wires are used in MV electric furnaces,
Kanthal wires are used in HV electric furnaces, 
Nichrome wires are used in EV electric furnaces.
This pattern applies for nearly every tier, and in this report I argue that it should be consistent across all tiers.

The use of Coil blocks' material in recipes also applies to the Alloy Smelter, Extruder, Fluid Heater, and Thermal Centrifuge of each tier as much as it does the Electic Furnace - it seems that these wires are intended to represent these machines' heating elements.

### Actual Behavior

The first exception to the pattern described above are the RTM alloy cables, as seen in the RTM coils.
They are *not* in the IV electric furnace recipe, nor are they in the Alloy Smelter, Extruder, Fluid Heater, or Thermal Centrifuge.
Instead, those machines use *Tungstensteel cables*, a remnant from when the Tungstensteel coil existed.

It's likely that the RTM coil block was made and used to replace the Tungstensteel coil block without also changing the recipe for the IV machines that used Tungstensteel for their heating elements.

### Steps to Reproduce

1. Make a new world
2. Open EMI and look at the recipes

### Additional Information

There is only one other exception to this pattern: UV uses Naquadah Alloy wires for its machines' heating elements despite the presence of the Tritanium coil. Unlike with RTM alloy and Tungstensteel, however, it's less easily to attribute to a change that wasn't applied as thoroughly as it could have been.

**Comment by a-a-GiTHuB-a-a** [comment]
should this issue be closed now, since my PR was merged?
