### ISSUE TITLE
Error coil temperature string formating in Chinese

### ISSUE THREAD

**Issue by ChenHaoYan1234** [GregTechCEu/GregTechCEu-1.19#224]
### GregTech CEu Version

v1.0.9

### Recipe Viewer Installed

REI

### Environment

single player

### Cross-Mod Interaction

No

### Expected Behavior

Has a norma ltemperature display

### Actual Behavior

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/79736203/a7212cc2-68d3-434f-b25e-1df255996966)
The temperature display doesn't normal

### Steps to Reproduce

1.Start game 
2.Change language into Chinese

**Comment by MCTian-mi** [comment]
感谢反馈！已在paratranz项目中修复，将在下次汉化更新时一并修复。
汉化相关问题可于[此处](https://paratranz.cn/projects/7760/issues)提出。

**Comment by ChenHaoYan1234** [comment]
It has same issues in English
