### ISSUE TITLE
Game crashing on world loading Fabric 1.20.1 v1.0.9

### ISSUE THREAD

**Issue by GoodGameInfinity** [GregTechCEu/GregTechCEu-1.19#225]
### GregTech CEu Version

"gtceu-fabric-1.20.1-1.0.9" downloaded from Modrinth

### Recipe Viewer Installed

REI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Expected Behavior

Load the world without any issues

### Actual Behavior

Crashing the game

### Steps to Reproduce

1. Load up Minecraft 1.20.1 Fabric with "gtceu-fabric-1.20.1-1.0.9" version of Gregtech-Modern
2. Try to create/load a world

### Additional Information

Logs when loading an empty superflat world: [link](https://mclo.gs/78yCGmp)
Logs when loading a typical survival world: [link](https://mclo.gs/CPVBPY7)

**Comment by Yefancy** [comment]
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/18493855/0a48036c-7561-4c2a-ba69-57ddede93bc3)
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/18493855/083f23b0-393f-4864-a7c4-14bdd8681262)

**Comment by Yefancy** [comment]
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/18493855/1b1b33f6-9ec2-43a7-b1f9-8f69c9fe36e9)
@screret

**Comment by GoodGameInfinity** [comment]
For further context i should probably specify that "gtceu-fabric-1.20.1-1.0.8.a" works perfectly fine.
