### ISSUE TITLE
Axes start from the top of the tree instead of the bottom

### ISSUE THREAD

**Issue by Wyrmlet** [GregTechCEu/GregTechCEu-1.19#2266]
### Feature Description

Floating trees drive me mad, and an axe breaking halfway through chopping a tree does exactly that. While manageable with vanilla trees, massive modded ones (like those from biomes o' plenty or oh the biomes we've gone) can cause quite a bit of trouble.
I propose to make axes chop down the topmost logs first, if possible. In previous versions there was a bug that didn't stop the tree felling process if the axe broke, which would work just fine too, but it would probably be pretty cheaty if used in a clever way.

**Comment by YoungOnionMC** [comment]
axes already chop from the top to the bottom since #2218
