### ISSUE TITLE
Pointing an Me Export Bus into a Gregtech Multiblock 'Me Input Bus' crashes the Game

### ISSUE THREAD

**Issue by mustermann-max** [GregTechCEu/GregTechCEu-1.19#2277]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.6

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Monifactory pack

### Expected Behavior

Game does not crash

### Actual Behavior

Game chrashes

### Steps to Reproduce

1. build ebf (gegtech multiblock) and use Me Input Bus as part of the ebf (offline, unconfigured)
2. setup ae2 storage system disk drives/storage bus
3. point export bus into me input bus, set item to be exported
4. put item into ae2 storage

**Comment by Spicierspace153** [comment]
Fixed in #2246
