### ISSUE TITLE
Steam turbines causing pollution.. from steam?

### ISSUE THREAD

**Issue by trofdev** [GregTechCEu/GregTechCEu-1.19#2290]
### Cross-mod Integration

Nuclearcraft

### Feature Description

Nuclearcraft makes steam, and steam is then used in turbines to generate power.
But steam causing CO pollution makes no sense, its just water vapor. Pollution should be created when we burn things in boilers or furnaces/etc. It makes no sense for turbines to have the muffler hatch and make carbon pollution from steam

**Comment by Valdevon** [comment]
This was already done for the small steam turbines: https://github.com/GregTechCEu/GregTech-Modern/pull/1528

**Comment by Valdevon** [comment]
So makes sense to modify the large one as well

**Comment by a-a-GiTHuB-a-a** [comment]
It seems like all large turbines have mufflers, based on what I saw in the code.

(does that mean the plasma turbine has one as well???)
