### ISSUE TITLE
Chunk task failing with c2me

### ISSUE THREAD

**Issue by liangmoe** [GregTechCEu/GregTechCEu-1.19#2292]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.6

### Minecraft Version

1.21.1

### Recipe Viewer Installed

None

### Environment

Dedicated Server

### Cross-Mod Interaction

No

### Other Installed Mods

Only Concurrent Chunk Management Engine

### Expected Behavior

Chunk task should be finished

### Actual Behavior

Chunk task failed

### Steps to Reproduce

Install c2me alonside with gtceu, run the server and try pregen the world, command used `chunky start minecraft:overworld circle 0 0 1024 1024`, run it and wait untill the task failed

### Additional Information

latest.log: https://mclo.gs/jXpqW96 and i do not use sinytra, c2me's modpage: https://modrinth.com/mod/c2me-neoforge

**Comment by screret** [comment]
we do not support C2ME.
