### ISSUE TITLE
Make RTM Alloy coils cheaper

### ISSUE THREAD

**Issue by Xefyr0** [GregTechCEu/GregTechCEu-1.19#2296]
### Feature Description

It's known that RTM Alloy coils are intentionally used instead of Tungstensteel coils to [force players to use](https://discord.com/channels/701354865217110096/1089296351906504835/1298537986803109980) [platline in EV](https://discord.com/channels/701354865217110096/1089296351906504835/1297299814345736212).
However, this leads to a bit of a progression stumbling block since Ruthenium is [quite hard to get in the amounts needed for RTM Alloy coils](https://discord.com/channels/701354865217110096/1089296351906504835/1297298436302966905).
Therefore, an actionable solution that can alleviate this difficulty without major changes would be to change the composition of RTM Alloy itself, reducing the Ruthenium portion of the alloy from 4 dusts out of 7 to 2 out of 5, or even 1 out of 4.
This shouldn't have much in the way of consequences outside of making players have to re-pattern or reconfigure their ABSes since RTM alloy is almost useless outside of the coils, and would ease the burden on EV players' budding platline.

**Comment by YoungOnionMC** [comment]
The balance of RTM Alloy was deliberate around making platline in EV, and proven to be well enough in 1.12. If a pack wants to change its composition they are free to
