### ISSUE TITLE
Energy converter not working

### ISSUE THREAD

**Issue by Migmag789** [GregTechCEu/GregTechCEu-1.19#230]
### GregTech CEu Version

1.19.2-1.0.8

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

The energy converter should have accepted the FE (I tried multiple cables) and then should have outputted the EU it converted in the output side.

### Actual Behavior

It did not accept any energy so it didn't convert any.

### Steps to Reproduce

Place an energy converter and try to make it work, and it won't (at least for me).

### Additional Information

I've asked multiple friends to help me and it looks like it's not working either.
Thanks for updating this mod in 1.19, it's still a lot of fun!

**Comment by Migmag789** [comment]
I've figured out I had done something wrong on my part from the start. I'm very sorry for the inconvenience and I'm really hyped to check the next updates of the mod. Still, thanks for making the mod!

**Comment by luluxiaoyu** [comment]
May I ask what the problem is?

**Comment by Migmag789** [comment]
I tried multiple times the soft wallet on the machine to change the convertor (from EU to FE and FE to EU) without really knowing what I had to do, though after messing enough with it I finally made it work

**Comment by luluxiaoyu** [comment]
I asked on Discord and they said it was a bug😂
