### ISSUE TITLE
Ability to lock input slot based on side of machine

### ISSUE THREAD

**Issue by mechobree** [GregTechCEu/GregTechCEu-1.19#2302]
### Feature Description

I'm not sure if there's already a feature that solves this issue, and if so it is not very apparent, but as of now when you want a passive process of say.. Bronze in the alloy smelter for example, you will eventually run into the issue where one metal ends up filling both slots if they aren't both being inserted at the same time, which breaks passive factories where both materials aren't produced at the same speed.

I think a really helpful feature would be able to lock an input side of a machine to a specific input slot, either using conveyor hatches or some other hatch, or by fleshing out the machine input/export tab. 

Or an even simpler solution would be to make a side only able to fill one slot, however, this would bring up an issue for chemical reactors because they have recipes that can have all inputs needed with two types of outputs, which is more sides than the machine has.

**Comment by Zorbatron** [comment]
You can do this with a robot arm set to keep exact and an item filter with the amount of items you want to keep in the machine.

**Comment by mechobree** [comment]
> You can do this with a robot arm set to keep exact and an item filter with the amount of items you want to keep in the machine.

Oh awesome! Did not know they had that functionality, thank you!
