### ISSUE TITLE
1.5.0 Crashes on Dedicated Server (1.20.1)

### ISSUE THREAD

**Issue by HexFlareheart** [GregTechCEu/GregTechCEu-1.19#2329]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.5.0

### Minecraft Version

1.20.1

### Recipe Viewer Installed

No Recipe Viewer

### Environment

Dedicated Server

### Cross-Mod Interaction

No

### Other Installed Mods

This was initially found on a 300-mod-ish custom modpack, but has been confirmed to happen with ONLY GTCEu Modern installed.

### Expected Behavior

Expected the game to start up properly? I don't really know what to say here, this one's fairly simple.

### Actual Behavior

Game crashes out on startup, but only on dedicated server. This crash does not happen on clientside.
[crash-2024-11-13_13.26.10-fml.txt](https://github.com/user-attachments/files/17737512/crash-2024-11-13_13.26.10-fml.txt)

### Steps to Reproduce

Install GTCEu on a dedicated server installation and attempt to start the server.

### Additional Information

The log specifically calls out the class "net/minecraft/client/multiplayer/MultiPlayerGameMode" as being invalid to be loaded in this context; is this a clientside class for multiplayer functions being incorrectly called? (This also did not occur on previous versions of GTCEu Modern.)

**Comment by screret** [comment]
latest.log please

**Comment by HexFlareheart** [comment]
[latest.log](https://github.com/user-attachments/files/17737988/latest.log)
