### ISSUE TITLE
Furnaces duplicating items & only processing a single recipe

### ISSUE THREAD

**Issue by mikerooni** [GregTechCEu/GregTechCEu-1.19#233]
### GregTech CEu Version

1.19.2 branch, latest commit (current HEAD revision is afc22aa)

### Recipe Viewer Installed

None

### Environment

Singleplayer, Forge (not yet tested with Fabric)

### Cross-Mod Interaction

No

### Expected Behavior

When using a steam or electric furnace, it should consume and smelt the input item.

### Actual Behavior

As soon as the first placed furnace has enough steam / power, as well as an input item, it will:
- not consume that item
- produce infinite items of that type, even after the input item is removed or even changed entirely

This only applies when the input is a specific single item. It does **not** happen when the recipe uses a tag as its input.

Additionally, all furnaces placed after the first one, will not produce any results other than the output of the first furnace's "active" recipe.

### Steps to Reproduce

Tested in both an existing world without any running furnaces, as well as directly after creating a new world:

1. Place a furnace and supply enough power
2. Put an item (matching the criteria described above, e.g. raw iron) into its input slot
4. The furnace will produce infinite amounts of the according recipe's output
5. Place a second furnace and supply enough power
6. Do **NOT** put an item into its input slot
7. The second furnace will **also** produce infinite amounts of that recipe's output
8. Put an item into the second furnace's input. It will be ignored.

### Additional Information

The input item stack for the recipe seems to resolve to an empty item at `com.gregtechceu.gtceu.api.recipe.GTRecipe#handleRecipeIO`
<details><summary>Debugger Output</summary>
<p>

```
inputs.values().iterator().next().get(0).content = {Ingredient@40609}
 values = {Ingredient$Value[1]@40610}
  0 = {Ingredient$ItemValue@40611}
   item = {ItemStack@40612} "0 air"
    delegate = {Holder$Reference@40614} "Reference{ResourceKey[minecraft:item / minecraft:raw_iron]=raw_iron}"
    capNBT = null
    count = 0
    popTime = 0
    item = {Item@40615} "raw_iron"
    tag = null
    emptyCacheFlag = true
    entityRepresentation = null
    adventureBreakCheck = null
    adventurePlaceCheck = null
    baseClass = {Class@12023} "class net.minecraft.world.item.ItemStack"
    capabilities = null
    valid = true
    isLazy = true
    lazyParentSupplier = {ItemStack$lambda@40616}
    lazyData = null
    initialized = false
``` 

</p>
</details>

**Comment by Drackion** [comment]
Tested it for myself on gtceu 1.0.9 downloaded from CF and i have managed to replicate it

**Comment by mikerooni** [comment]
Potential problem source (at least for inputs not being consumed):
`com/gregtechceu/gtceu/api/machine/trait/NotifiableItemStackHandler.java:97` - stack size is modified

**Comment by mikerooni** [comment]
Debug Insights:

- `com/gregtechceu/gtceu/api/machine/trait/NotifiableItemStackHandler.java:94` - ingredientStack is always the same instance for the cases where the bug occurs, but a new instance every time in other machines
- Same location - Ingredient for other recipes is instance of `SizedIngredientImpl`, but `Ingredient` for affected recipes

**Comment by Yefancy** [comment]
its a bug of my fast ingrdient copy. I might fix it when I work on recipe mathcing later
