### ISSUE TITLE
Rocket Scanner bugged out

### ISSUE THREAD

**Issue by Cyphecx** [GregTechCEu/GregTechCEu-1.19#2336]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.6

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

SIngleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

Monifactory modpack

### Expected Behavior

Rocket scanner works like normal

### Actual Behavior

Rocket scanner has a messed up interface and duplicates items.
![image](https://github.com/user-attachments/assets/e15ea67e-94cc-47b0-82f5-046819636092)
Placing a chip in the UI slot will cause the item to be duped every time you close the scanner UI
![image](https://github.com/user-attachments/assets/15f75580-6478-4ea0-8368-3b95eb6ca57f)

### Steps to Reproduce

place down rocket scanner
open UI

**Comment by Deepacat** [comment]
1. This is from an addon
2. This version is outdated

**Comment by Cyphecx** [comment]
My bad, will post on the addon's page instead.
