### ISSUE TITLE
Rubber Trees do not naturally generate [1.19.2 Forge]

### ISSUE THREAD

**Issue by Burchard36** [GregTechCEu/GregTechCEu-1.19#234]
### GregTech CEu Version

1.0.9

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Expected Behavior

Rubber trees should be generating in the world

### Actual Behavior

None generate in the world, they do work when using the `/place` command though.

### Steps to Reproduce

Simply build the jar from github and place it in your mods folder, create a new world and fly around for a few, I've tried a few different worlds by now flying around in creative for over an hour now, looked in every biome imaginable including swamps as recommended when I raised awareness about this issue in the discord

### Additional Information

This bug effects all 1.19.2 versions of forge, I've tried a few from 43.2.0 - 43.2.21 and none generate rubber trees, ore vein generation does work though, I tried this within a modpack I'm working on & with only GTCEU installed and the bug persists

**Comment by Burchard36** [comment]
Here is the latest.log: https://hastebin.com/share/izixovolut.yaml

No errors related to rubber trees, but might be useful when looking into

**Comment by in1t1a1** [comment]
The same goes for fabric

**Comment by screret** [comment]
fixed when #235 merges
