### ISSUE TITLE
Minecraft 1.20.1 Fabric Server crash, keeps crashing as it finishes booting the world up, NoClassDefFoundError

### ISSUE THREAD

**Issue by TheFoolStruck** [GregTechCEu/GregTechCEu-1.19#2352]
### GregTech CEu Version

1.0.20.b

### Minecraft Version

1.20.1

### Recipe Viewer Installed

None

### Cross-Mod Interaction

Unsure

[crash-2024-11-14_13.43.42-server.txt](https://github.com/user-attachments/files/17756825/crash-2024-11-14_13.43.42-server.txt)

I've been trying to get this server working from scratch, not hosted by another website, at the moment I'm struggling with crash due to "java.lang.NoClassDefFoundError: net/minecraft/class_1074"

If I were to look at it's "Caused by" it says "Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1074"

Rest of the information can be found in the crash file report

**Comment by Deepacat** [comment]
Fabric is no longer supported, and quite frankly shouldn't be used unless you're forking and fixing things yourself. This version is ancient and very buggy

**Comment by TheFoolStruck** [comment]
Ooooooh, okay, that's unfortunate

Thank you so much though 👍

**Comment by Deepacat** [comment]
If you're developing a pack I'd recommend switching to forge 1.20.1, if you're insistent on fabric check out modern industrialization which is a somewhat similar tech mod for fabric on that version

**Comment by TheFoolStruck** [comment]
Ahh! Thank you so much for the assistance and recommendations!

**Comment by ManKingProxx9** [comment]
Hello @Deepacat, I have the same problem and I want to solve that issue for my server and I dont know what is the error root. Can you explain why it happens and, if its a code problem, can I fix?

**Comment by Deepacat** [comment]
I am unsure of why it happens, fabric is unsupported now and I would not recommend using this version of gregtech.

**Comment by WetABQ** [comment]
I fixed it, and here is a compiled version: https://file.io/YvY05o8y8zKV

Note: Use it with `PacketFixer`, and **without** `Krypton`

**Comment by krossgg** [comment]
Please do not post links to filesharing sites with recompiled versions of our source code. You can fork and share your modifications directly. We no longer officially support Fabric.
