### ISSUE TITLE
Vein related crash issue

### ISSUE THREAD

**Issue by ThePansmith** [GregTechCEu/GregTechCEu-1.19#2364]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.5.1

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

SP

### Cross-Mod Interaction

No

### Other Installed Mods

Moni 0.10.1

### Expected Behavior

For game to not crash

### Actual Behavior

It crashed :(

### Steps to Reproduce

1. I dunno, i just tabbed back into the game
2. Crashed due to something related to oreveins.

[Moni's custom oreviens](https://github.com/ThePansmith/Monifactory/blob/main/kubejs/server_scripts/worldgen/oreVeins.js), if it helps

### Additional Information

Possibly related to VP?
https://bytebin.lucko.me/PYbegzKALR

**Comment by Deepacat** [comment]
Have had this happen 3 times to me, still present on 1.5.3 
[My veins ](https://github.com/Deepacat/Worldshaper/blob/main/minecraft/kubejs/server_scripts/gtceu/standardOreVein.js)

**Comment by Deepacat** [comment]
Seems to be caused when pausing and or opening ui's

**Comment by Deepacat** [comment]
Seems to only happen after a reload, with custom ore veins, then when something specific happens UI related

**Comment by IamKahina** [comment]
I had the same issue, and luckily my logs contain a crash report. I will send them here
[latest.log](https://github.com/user-attachments/files/17923094/latest.log)
