### ISSUE TITLE
[1.21.1] Unable to Insert Coal into Solid Steam Boilers

### ISSUE THREAD

**Issue by Azraeel** [GregTechCEu/GregTechCEu-1.19#2372]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.5.1

### Minecraft Version

1.21.1

### Recipe Viewer Installed

None

### Environment

Dedicated Server

### Cross-Mod Interaction

Yes

### Other Installed Mods

LDLID & Configuration

### Expected Behavior

Low Pressure Bronze Solid Steam Boiler allows me to put coal in it

### Actual Behavior

Low Pressure Bronze Solid Steam Boiler does NOT allow me to put coal in it, GUI Breaks and errors completely 

See LOG Below for full LOG
[2024-11-08-4.log](https://github.com/user-attachments/files/17773415/2024-11-08-4.log)

Other issue is that it seems to be related to LDLib, I have tested without any mods except the ones required for Gregtech. I have tested Community Pack as well on 1.20.1 still has the issue for me. LDLib when init on server loads client side stuff that breaks it breaking certain UI Elements of GregTech (essentially all) 

### Steps to Reproduce

Put on Dedicate Server
[GT, Configuration, LDLib]

Load to see errors.

**Comment by monworlig** [comment]
Hello,

I came across your closed issue (#2372) regarding the "Attempted to load class ... ScreenEvent for invalid dist DEDICATED_SERVER" error on a dedicated server when using GTCEU. I am experiencing the exact same problem with the following setup:

Minecraft version: 1.21.1

NeoForge version:21.1.113

GTCEU version:1.4.6

I noticed you closed the issue yourself. If you managed to find a solution or workaround, could you please share it? Any information on how you resolved this would be greatly appreciated. I have already tried updating/downgrading GTCEU, removing ldlib, and testing different NeoForge versions, but the issue persists.

Thank you for your time and any help you can provide.
