### ISSUE TITLE
Random crash while using prospector.

### ISSUE THREAD

**Issue by tomprince** [GregTechCEu/GregTechCEu-1.19#2375]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.5.2

### Minecraft Version

1.20.1

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Monifactory  0.10.1 hard mode, slightly tweaked

I think the only possibly relevant tweak is https://github.com/ThePansmith/Monifactory/pull/1121/files

### Expected Behavior

The game not to crash.

### Actual Behavior

The game to crash.

### Steps to Reproduce

Unsure. I had updated GT to 1.5.2 and left the game running overnight. Then, when I got back, I was using the prospector to find somwhere to mine when the game crashed. I *think* I was mousing over the prospector, though I may have unintentionally clicked.

### Additional Information

[crash-2024-11-15_07.14.13-server.txt](https://github.com/user-attachments/files/17776849/crash-2024-11-15_07.14.13-server.txt)

**Comment by screret** [comment]
I believe this is fixed on latest.
