### ISSUE TITLE
Compass error?

### ISSUE THREAD

**Issue by kienerxyzzy** [GregTechCEu/GregTechCEu-1.19#2379]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.4.5

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

Singlaplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

Create, AE2, Create C&A, Create Applied Kinetics. However, bug appears before installing any of those.

### Expected Behavior

There should be a way to access the compass, but I have found none. (The Terminal does not work.)

### Actual Behavior

^
|
look above

### Steps to Reproduce

1. Get the terminal
2. Use it
3. It does nothing

### Additional Information

This could be a me-only issue, I have seen other people use it just fine

**Comment by Pumpkin7266** [comment]
it's behind a config

**Comment by screret** [comment]
enable the config. it's too broken so we disabled it.

**Comment by kienerxyzzy** [comment]
oh
