### ISSUE TITLE
enablePlatformConverters does not sync correctly between Client and Server

### ISSUE THREAD

**Issue by HexFlareheart** [GregTechCEu/GregTechCEu-1.19#2393]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.5.3

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

Dedicated Server

### Cross-Mod Interaction

No

### Other Installed Mods

As with other issues I've logged, this was initially observed on a larger modset, but has been confirmed to occur with ONLY GTCEu Modern 1.5.3 and the latest version of JEI.

### Expected Behavior

The enablePlatformConverters config setting should be synced to the clientside regardless of what the client's config is set to; if server has it set to TRUE, the converters should be visible and recipes available in JEI, and if server has it set to FALSE, the converters and their recipes should NOT be visible in JEI.

### Actual Behavior

Whatever enablePlatformConverters is set to on serverside DOES NOT appear to be synced to the client correctly; this doesn't affect recipe visibility, since this is entirely controlled by the server, but it does mean that if the server is set to TRUE and the client is set to FALSE, the client does not display the converters in JEI even though it should. The inverse is also the case.

### Steps to Reproduce

1. Create a dedicated server, and set enablePlatformConverters in gtceu.yaml to either TRUE or FALSE
2. Set the client instance's enablePlatformConverters to whatever the server's ISN'T (so TRUE if server is FALSE or FALSE if server is TRUE)
3. Connect into the server and look up converters in JEI

### Additional Information

Fortunately unlike the previous issues I've reported here, this one is an instance of inconvenient behavior that can very readily be worked around, as opposed to game-breaking bugs. Practically speaking this is, in fact, barely an issue at all, as the solution is just "make sure client and server have the same configs"; the only reason I even found this problem in the first place is because I wanted to turn on converters without needing end users to update their configs manually.

**Comment by screret** [comment]
> make sure client and server have the same configs

that's what you're supposed to do. just do that.
