### ISSUE TITLE
Game bricker: typing a filter in converyor with item tag filter bricks game.

### ISSUE THREAD

**Issue by PhoenixtheII** [GregTechCEu/GregTechCEu-1.19#2398]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

monifactory version

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

monifactory

### Cross-Mod Interaction

Yes

### Other Installed Mods

monifactory pack

### Expected Behavior

Not brick the game

### Actual Behavior

Bricking the game

### Steps to Reproduce

From the monifactory discord:

D3v0id
OP
 — 11/17/24, 5:14 PM
Editing a tag item filter within a conveyor bricked my save had to reload a backup.  I was holding backspace deleting a long line of code when this happened

Phoenix the II — Yesterday at 7:48 PM
And I added a "|" behind "dust*" made mine crash & brick

**Comment by YoungOnionMC** [comment]
crash report?

**Comment by Magespire** [comment]
I'm not the original poster but I had the same crash, here's my report:

[crash-2024-11-18_23.20.08-server.txt](https://github.com/user-attachments/files/17810673/crash-2024-11-18_23.20.08-server.txt)

Conditions were almost identical to the above, I added a | after *dust* in a tag filter on an MV conveyor, crashing the game and also making the game crash when the world is loaded.

Was having some issues with regular item filters not being able to have filters set through EMI items immediately prior, probably unrelated though.

This is on Moni version 0.10.2

**Comment by PhoenixtheII** [comment]
[crash-2024-11-18_19.40.44-server.txt](https://github.com/user-attachments/files/17816100/crash-2024-11-18_19.40.44-server.txt)

Crash report after typing the "|"

**Comment by PhoenixtheII** [comment]
[crash-2024-11-18_19.45.05-server.txt](https://github.com/user-attachments/files/17816108/crash-2024-11-18_19.45.05-server.txt)

Crash on loading the world after the initial crash

**Comment by Seyves** [comment]
Yeah, I have the same issue. I play GregTech Community Pack Modern and downgrading to 1.11.3 version of modpack version fixes it, not sure about specific GregTech version

**Comment by Deepacat** [comment]
I cannot replicate on community pack 1.12.1, GT 1.5.3
