### ISSUE TITLE
[1.0.9][1.19.2] "GregTech (gtceu) has failed to load correctly"

### ISSUE THREAD

**Issue by Rosethorns** [GregTechCEu/GregTechCEu-1.19#241]
### GregTech CEu Version

1.0.9

### Recipe Viewer Installed

EMI

### Environment

launch

### Cross-Mod Interaction

Unsure

### Expected Behavior

For Minecraft to finish loading to the main menu

### Actual Behavior

Rarely Minecraft will crash with the stated title 

### Steps to Reproduce

This error is not always reproducable and seems to be roughly 1:10 on launch

### Additional Information

Crash log: [https://pastebin.com/gW3H1ein](https://pastebin.com/gW3H1ein)

**Comment by Yefancy** [comment]
really weird!

**Comment by screret** [comment]
going to assume whatever this is doesn't happen anymore, as seemingly it is out of our control anyway. Will reopen if it occurs again.
