### ISSUE TITLE
Crash when viewing TOP information

### ISSUE THREAD

**Issue by zk00790** [GregTechCEu/GregTechCEu-1.19#2411]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.5.3

### Minecraft Version

1.20.1

### Recipe Viewer Installed

REI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

TheOneProbe

### Expected Behavior

![屏幕截图 2024-11-21 140538](https://github.com/user-attachments/assets/ca73a2a6-3caf-403b-84bd-f2072c8797ec)

### Actual Behavior

Crash when viewing TOP information

### Steps to Reproduce

Cursor pointing to electrolyzer with infinite water cover installed

The same problem occurs with many other devices and multi-box structures

**Comment by omergunr100** [comment]
can you add the crash log?

**Comment by zk00790** [comment]
[latest.log](https://github.com/user-attachments/files/17850870/latest.log)

**Comment by omergunr100** [comment]
this crash log doesn't match the error in your screenshot, are you sure you sent the right one?

**Comment by zk00790** [comment]
Only this one file
![屏幕截图 2024-11-22 041036](https://github.com/user-attachments/assets/901eb489-b4b1-4216-8648-f42eb7401c2b)

**Comment by omergunr100** [comment]
yeah, but latest gets overwritten every time you run the game.
I managed to replicate the issue, so I'll see what I can do.

**Comment by zk00790** [comment]
Thanks, I can provide an example if needed
