### ISSUE TITLE
Issues associated with merged PRs aren't closed

### ISSUE THREAD

**Issue by a-a-GiTHuB-a-a** [GregTechCEu/GregTechCEu-1.19#2415]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

null

### Minecraft Version

null

### Recipe Viewer Installed

None

### Environment

GitHub

### Cross-Mod Interaction

Unsure

### Other Installed Mods

none

### Expected Behavior

When a PR addressing an issue is merged, the associated issue is closed.

### Actual Behavior

The issues remain open and clog up the actual unaddressed issues.

### Steps to Reproduce

1. go to [this page](https://github.com/GregTechCEu/GregTech-Modern/issues)
2. find an issue like #2238 or #2399
3. see that they have a merged PR associated, but they're still open???
4. no indication if there are still bugs that weren't addressed in the first PR

### Additional Information

issue authors ghosted us :<

**Comment by Pumpkin7266** [comment]
that's because the pr descriptions aren't triggering the github auto issue closer 
![image](https://github.com/user-attachments/assets/e8ffe576-9706-44ae-aa03-2709d609658a)

**Comment by a-a-GiTHuB-a-a** [comment]
oh.
so what will?

**Comment by screret** [comment]
the PR's creator just used the wrong keyword, that's all. we have to close them manually when that happens.
