### ISSUE TITLE
[1.0.9][1.19.2]

### ISSUE THREAD

**Issue by Rosethorns** [GregTechCEu/GregTechCEu-1.19#243]
### GregTech CEu Version

1.0.9

### Recipe Viewer Installed

EMI

### Environment

Launch

### Cross-Mod Interaction

Unsure

### Expected Behavior

For Minecraft to launch normally

### Actual Behavior

rare startup crash involving gtceu:flowing_aluminium

### Steps to Reproduce

Not readily reproducible, random startup crash roughly 1:10

### Additional Information

Crash Log: [https://mclo.gs/Cy7zp3A](https://mclo.gs/Cy7zp3A)

**Comment by screret** [comment]
create crashed, not our fault.
