### ISSUE TITLE
Suggestion: Integration of more recent Minecraft content, particularly Netherite

### ISSUE THREAD

**Issue by Taschenmogul** [GregTechCEu/GregTechCEu-1.19#2441]
### Cross-mod Integration

Vanilla Minecraft

### Feature Description

I hope it is ok to just casually ask this question here, or make this suggestion, respectively. A quick search for "Netherite" at least didn't bring up a similar topic.

So I have been wondering if there has been an internal discussion about integrating some of the more recent features of vanilla Minecraft, in particular Netherite as a high-end material, but also possibly Echo Shards or other content pertaining to the Deep Dark.
I suppose it is part of GregTech's current identity to rather focus on real-world chemical elements and alloys, but I was still astonished when I saw that at least the 1.20.1 version does seem to have no use for Netherite at all.
I for one would love to see GregTech move more towards giving a greater focus to and working with vanilla Minecraft materials, but I guess that this might not be what GT-afficionados want for their mod.
However I feel like at least Netherite should be supported as a material in some way.

Any statements or opinions on this?

**Comment by Ghostipedia** [comment]
Netherite will most likely never end up being the high end fantasy material people want.
It's basically a golden flavor of steel,and we already have several materials that slot in use cases there. It will most likely not be more than a valid tool material in the future.

There are arguments to be made on sculk related content. But that sort of discussion is unlikely to occur until progression is overhauled across 1.12 CEU and GT:Modern. As major content changes from 1.12 are usually priority which is currently being focused on.

**Comment by Taschenmogul** [comment]
> Netherite will most likely never end up being the high end fantasy material people want. It's basically a golden flavor of steel,and we already have several materials that slot in use cases there. It will most likely not be more than a valid tool material in the future.
> 
> There are arguments to be made on sculk related content. But that sort of discussion is unlikely to occur until progression is overhauled across 1.12 CEU and GT:Modern. As major content changes from 1.12 are usually priority which is currently being focused on.

Interesting. I didn't know that you guys are aiming for feature parity with 1.12!
But yes, compared with the advanced materials in GregTech, Netherite is certainly not high end. But it is one of the rarest resources in vanilla Minecraft, so it offers an opportunity to use it as a component in advanced recipes.
But of course that might necessitate more thorough changes to the machine progression, so if that's not something you're already considering, I guess I should have no hope for it happening any time soon.

**Comment by a-a-GiTHuB-a-a** [comment]
I know packs like Monifactory and such overhaul netherite recipes and such, so it'll probably just be a "put it in your modpack however you want" type of thing.

**Comment by Taschenmogul** [comment]
> I know packs like Monifactory and such overhaul netherite recipes and such, so it'll probably just be a "put it in your modpack however you want" type of thing.

Yeah, I already thought about just making my own recipes, but then again that's not really what I was hoping for. It's rather that by staying its course, GregTech's paradigm and vanilla Minecraft's paradigm are slowly drifting apart, and I wished that GT would rather try to integrate with the evolving vanilla paradigm.
Even if some of Mojang's decisions might admittedly seem a bit bizarre at times.

**Comment by Ghostipedia** [comment]
Even in earlier versions of GT, GT and Vanilla have always had different perspectives on resource usage/production etc. It's pretty expected.

For future issues so I can reference back to this(as this type of issue has been opened several times now). GT as a whole is still a heavily in development mod, and more modern materials will be the lowest on the list to implement vs 1.12 Content modifications

There will be an eventual branch in the timeline where Content on 1.12 and Modern has matured enough that modern can 'branch off' and do its own thing, but until then a lot of modern MC materials or themes may be left dormant in favor of using our own original systems.

Don't expect anything anytime soon, this could easily take months or years and/or change if a large majority of the dev team changes.

**Comment by Taschenmogul** [comment]
Yeah, absolutely, it is a sensible decision, even though I might have hoped for a different answer. There's only so much time and attention to spend on a project.
