### ISSUE TITLE
Quartz sand has 2 macerator recipes, 2nd recipe is not true.

### ISSUE THREAD

**Issue by Jollahs** [GregTechCEu/GregTechCEu-1.19#2443]
### Checked for existing issues

- [x] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.5.3

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Monifactory

### Expected Behavior

Expected recipe to produce quartz sand can happen in any tier macerator, but there is an HV specific recipe that uses 1 HV amp and takes 1 tick. 

### Actual Behavior

When making quartz sand in an HV macerator, it takes 0.35 seconds, and uses 32 EU/t. Not 512 EU/t and 0.05 seconds.

### Steps to Reproduce

Place sand in an HV macerator, and supply with power to make quartz sand. The recipe that uses 32 eu/t is chosen, despite emi saying there is another HV specific recipe.
![image](https://github.com/user-attachments/assets/b808803e-7212-4a56-a9b5-320997e8dacd)

**Comment by Vextin** [comment]
The extra recipe does not exist in vanilla GT Modern. Looks like a Monifactory issue, unless Pansmith disagrees.

**Comment by YoungOnionMC** [comment]
this recipe does not exist in base gtm
