### ISSUE TITLE
Add External Tick Accelerator Support

### ISSUE THREAD

**Issue by vinni57** [GregTechCEu/GregTechCEu-1.19#2450]
### Cross-mod Integration

ProjectE, Watch of Flowing Time Standalone, etc.

### Feature Description

Presently, GTM doesn't support external tick acceleration methods. When attempting to use them (eg. watch of flowing time from ProjectE), different blocks have different behavior. Eg. wires aren't affected while some machines are.

Please add consistent tick acceleration from external sources for all GT blocks such that they work the same as in-mod tick accelerators.

Optionally, incorporate the same wire behavior as GTCEU 1.12 where if the amperage * acceleration rate > wire amp limit, it burns. This is a central mechanic I made use of in a 1.12 GT modpack I would love to port to modern.

Thanks!

**Comment by screret** [comment]
Thank you for your feature suggestion. We've considered it thoroughly and have come to the conclusion we will not be going through with this currently.
