### ISSUE TITLE
Energy converters cannot be crafted

### ISSUE THREAD

**Issue by GooeyGungan** [GregTechCEu/GregTechCEu-1.19#2451]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.5.4

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Dedicated Server

### Cross-Mod Interaction

Yes

### Other Installed Mods

Monifactory 0.10.4

### Expected Behavior

Energy converter recipes should be shown when I search for them and the items should be craftable.

### Actual Behavior

Energy converters cannot be crafted and their recipes cannot be searched for.

### Steps to Reproduce

- Search for Energy converter recipe
- Notice it does not appear

**Comment by teh-banana** [comment]
I tested this on a new installation of both client and server, both had energy converters available and craftable.

![image](https://github.com/user-attachments/assets/370d0c57-6ccf-466b-b9c2-087583b739f3)

I believe Pansmith released the 0.10.4 update with the configs for the main gtceu.yaml being wrong initially, and updated it a few hours later. [See this commit for details](https://github.com/ThePansmith/Monifactory/commit/3c5f37a5e37e145719055bd83225b98d1668c8bd). It seems like you need to have your config updated.

**Comment by screret** [comment]
monifactory issue, wait for pansmith to fix the config or do it yourself.
