### ISSUE TITLE
Large Chemical Reactor, Structure incomplete

### ISSUE THREAD

**Issue by kersjan14** [GregTechCEu/GregTechCEu-1.19#2458]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.5.4

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

ATM9 Latest 0.3.5

### Expected Behavior

Expected a working Large Chemical Reactor

### Actual Behavior

Structure found incomplete.

### Steps to Reproduce

- I followed the JEI and online guides to building the Reactor, all those options didn't work.
- I tried with only one input and output of each
- I tried different tiers

And I build the following structure with PFTE middle bottom and top, the center is the tube variant.
![2024-11-30_19 57 13](https://github.com/user-attachments/assets/1268faa1-abdb-4d94-9a11-8b1c23a03a56)
Front
![2024-11-30_19 57 18](https://github.com/user-attachments/assets/f888c688-557c-4fae-a325-0c1a649fda4c)
Left
![2024-11-30_19 57 23](https://github.com/user-attachments/assets/1b2578a8-c8f8-4ded-a752-dfbc677aeb2b)
Back
![2024-11-30_19 57 25](https://github.com/user-attachments/assets/ce21cd65-54d5-4e52-8d22-8ce966bbc579)
Right

I Can't find any reason or solution for the problem.

**Comment by Deepacat** [comment]
Requires specifically cupronickel coil. Ask in a discord for easier responses btw, git issues can be slow

**Comment by screret** [comment]
use cupronickel coils. the LCR allowing any coil to be used is an unported feature from 1.12.

**Comment by kersjan14** [comment]
Thank you for the quick answer, cupronickel did fix it indeed
