### ISSUE TITLE
worldgen fail in mining dimension

### ISSUE THREAD

**Issue by Castanea43** [GregTechCEu/GregTechCEu-1.19#2459]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.5.4

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Dedicated Server

### Cross-Mod Interaction

Yes

### Other Installed Mods

a lot : 

Mods:
  [✔] [+食品}_随意乐事casualness_delight-1.20.1-0.4n
  [✔] [forge]ctov-3.4.10
  [✔] 1.20.1-create_oppenheimered-1.0.4
  [✔] AE2-Things-1.2.1
  [✔] ae2alchemistryaddon-1.20.1-0.0.2
  [✔] AE2NetworkAnalyzer-1.20-1.0.6-forge
  [✔] alchemistry-1.20.1-2.3.4
  [✔] alchemylib-1.20.1-1.0.30
  [✔] alltheleaks-0.1.0-beta+1.20.1-forge
  [✔] almostunified-forge-1.20.1-0.9.4
  [✔] alternate_current-mc1.20-1.7.0
  [✔] amendments-1.20-1.2.12
  [✔] Apotheosis-1.20.1-7.4.3
  [✔] ApotheoticAdditionsV2.0.2
  [✔] ApothicAttributes-1.20.1-1.3.7
  [✔] appleskin-forge-mc1.20.1-2.5.1
  [✔] Applied-Mekanistics-1.4.2
  [✔] appliedenergistics2-forge-15.2.13
  [✔] aquaculture_delight_1.0.0_forge_1.20.1
  [✔] Aquaculture-1.20.1-2.5.3
  [✔] aquadelight-1.0.2-1.20.1
  [✔] architectury-9.2.14-forge
  [✔] ars_additions-1.20.1-1.6.7
  [✔] ars_elemental-1.20.1-0.6.7.7
  [✔] ars_nouveau-1.20.1-4.12.6-all
  [✔] ars_ocultas-1.20.1-1.2.2-all
  [✔] ars_technica-1.20.1-1.1.4
  [✔] arsdelight-1.1.2
  [✔] arseng-1.2.0
  [✔] athena-forge-1.20.1-3.1.2
  [✔] ati_structures(1.20)_v1.1.0_FORGE
  [✔] attributizer-2.1
  [✔] BadOptimizations-2.2.0-1.20.1
  [✔] balm-forge-1.20.1-7.3.9-all
  [✔] BambooEverything-forge-3.0.3+mc1.20.1
  [✔] berries_and_cherries-1.0.9-hotfix
  [✔] betterfpsdist-1.20.1-6.0
  [✔] BetterFusionReactor-1.20.1-1.4.8
  [✔] betterp2p-1.4.3-forge
  [✔] bettervillage-forge-1.20.1-3.2.0
  [✔] blockui-1.20.1-1.0.186-beta
  [✔] bloodmagic-1.20.1-3.3.3-45
  [✔] bobberdetector-0.1.9-1.20.1
  [✔] Bookshelf-Forge-1.20.1-20.2.13
  [✔] BotanyPots-Forge-1.20.1-13.0.39
  [✔] BotanyPotsTiers-Forge-1.20.1-6.0.1
  [✔] BotanyTrees-Forge-1.20.1-9.0.17
  [✔] botarium-forge-1.20.1-2.3.4
  [✔] BrandonsCore-1.20.1-3.2.1.302-universal
  [✔] Butchersdelight beta 1.20.1 2.1.0
  [✔] Butchersdelight Foods beta 1.20.1 1.0.3
  [✔] cable_facades-1.20.1-Forge-1.1.3
  [✔] CacaoUnofficial-Forge-1.20.1-1.0.0
  [✔] car-forge-1.20.1-1.0.33
  [✔] carryon-forge-1.20.1-2.1.2.7
  [✔] cataclysm_ut-33 - 1.20.1
  [✔] chefs-delight-1.0.3-forge-1.20.1
  [✔] chemlib-1.20.1-2.0.19
  [✔] chipped-forge-1.20.1-3.0.7
  [✔] citadel-2.6.0-1.20.1
  [✔] clienttweaks-forge-1.20-11.1.0
  [✔] cloth-config-11.1.136-forge
  [✔] cluttered-2.1-1.20.1
  [✔] cobweb-forge-1.20.1-1.0.0
  [✔] CodeChickenLib-1.20.1-4.4.0.516-universal
  [✔] cofh_core-1.20.1-11.0.2.56
  [✔] collective-1.20.1-7.87
  [✔] commandkeys-forge-2.3.2+1.20.1
  [✔] configured-forge-1.20.1-2.2.3
  [✔] connectivity-1.20.1-6.0
  [✔] constructionwand-1.20.1-2.11
  [✔] Controlling-forge-1.20.1-12.0.2
  [✔] copycats-2.1.4+mc.1.20.1-forge
  [✔] craftingstation-1.20.1-1.2.3
  [✔] craftingtweaks-forge-1.20.1-18.2.5
  [✔] Create Sweets And Treats 1.1.1
  [✔] create_central_kitchen-1.20.1-for-create-0.5.1.f-1.3.12
  [✔] create_connected-0.9.2-mc1.20.1-all
  [✔] create_deepfried-1.20.1-0.1.1
  [✔] create_enchantment_industry-1.20.1-for-create-0.5.1.f-1.2.9.d
  [✔] create_factory-0.4b-1.20.1
  [✔] create_optical-0.2.1
  [✔] create_structures_arise-139.12.11-forge-1.20.1
  [✔] create_vibrant_vaults-0.2.0+1.20.1
  [✔] create-1.20.1-0.5.1.j
  [✔] create-confectionery1.20.1_v1.1.0
  [✔] Create-DnDesire-1.20.1-0.1b.Release-Early-Dev
  [✔] create-food-1.20.1-1.1.5-forge
  [✔] Create-Guardian-Beam-Defense-1.3.0b-1.20.1
  [✔] create-new-age-forge-1.20.1-1.1.2
  [✔] create-structures-0.1.1-1.20.1-FORGE
  [✔] create-stuff-additions1.20.1_v2.0.5
  [✔] createaddition-1.20.1-1.2.4e
  [✔] createarmoryv0.6.1n
  [✔] createbicbit-1.20.1-0.0.86
  [✔] createbigcannons-5.6.0-mc.1.20.1-forge
  [✔] createcafe-1.2.4-1.20.1
  [✔] createdeco-2.0.2-1.20.1-forge
  [✔] createdieselgenerators-1.20.1-1.2i
  [✔] croptopia_and_create-1.0.6-1.20.1
  [✔] Croptopia-1.20.1-FORGE-3.0.4
  [✔] CroptopiaAdditions-1.20.1-FORGE-2.4
  [✔] CroptopiaDelight-1.20.1_1.2.2-forge
  [✔] ctov-chefs-delight-compat-2.0
  [✔] ctov-create-structures-1.0
  [✔] ctov-croptopia-compat-2.2
  [✔] ctov-farmers-delight-compat-2.1
  [✔] ctov-floralis-compat-1.0
  [✔] cuisinedelight-1.1.16
  [✔] cupboard-1.20.1-2.7
  [✔] curios-forge-5.11.0+1.20.1
  [✔] Delightful-1.20.1-3.6
  [✔] delightfulburgers-1.20.1
  [✔] delightfulsandwich-1.20.1
  [✔] design_decor-0.4.0b-1.20.1
  [✔] displaydelight-1.1.0
  [✔] domum_ornamentum-1.20.1-1.0.282-snapshot-universal
  [✔] Draconic-Additions-1.20.1-2.4.0.4-universal
  [✔] Draconic-Evolution-1.20.1-3.1.2.598-universal
  [✔] EggDelight-v1.2-1.20.1
  [✔] elevatorid-1.20.1-lex-1.9
  [✔] embeddium-0.3.31+mc1.20.1
  [✔] embeddiumplus-1.20.1-v1.2.13
  [✔] emi_enchanting-0.1.2+1.20.1+forge
  [✔] emi_loot-0.7.4+1.20.1+forge
  [✔] emi-1.1.18+1.20.1+forge
  [✔] EnchantmentDescriptions-Forge-1.20.1-17.1.19
  [✔] endersdelight-1.20.1-1.0.3
  [✔] EpheroLib-1.20.1-FORGE-1.2.0
  [✔] ExtendedAE-1.20-1.2.1-forge
  [✔] farmers_croptopia-1.20.1-1.1.0
  [✔] FarmersDelight-1.20.1-1.2.5
  [✔] FarmersStructures-1.0.3-1.20
  [✔] farsight-1.20.1-3.7
  [✔] FasterLadderClimbing-1.20.1-0.2.10
  [✔] FastFurnace-1.20.1-8.0.2
  [✔] FastSuite-1.20.1-5.0.1
  [✔] FastWorkbench-1.20.1-8.0.4
  [✔] ferritecore-6.0.1-forge
  [✔] floralis-1.20.1-10.6.0
  [✔] FramedBlocks-9.3.1
  [✔] framework-forge-1.20.1-0.7.12
  [✔] fruitsdelight-1.0.12
  [✔] ftb-essentials-forge-2001.2.2
  [✔] ftb-library-forge-2001.2.6
  [✔] ftb-ultimine-forge-2001.1.5
  [✔] functionalstorage-1.20.1-1.2.12
  [✔] fusion-1.1.1-forge-mc1.20.1
  [✔] fzzy_config-0.5.8+1.20.1+forge
  [✔] garnished_additions-beta-0.7.0-forge
  [✔] garnished-2.0.2+1.20.1-neoforged
  [✔] garnished-botany-pots-forge-2.2.0
  [✔] geckolib-forge-1.20.1-4.4.9
  [✔] geode_plus-forge-1.2.5-1.20.1
  [✔] glassential-renewed-forge-1.20.1-2.4.2
  [✔] GlitchCore-forge-1.20.1-0.0.1.1
  [✔] Glodium-1.20-1.5-forge
  [✔] gourmet-0.1.1b-1.20.1
  [✔] gtb-1.20.1-1.0.0
  [✔] gtceu-1.20.1-1.5.4
  [✔] gtec-1.20.1-0.2.1
  [✔] gtnn-1.1.6
  [✔] harvest-with-ease-forge-1.20.1-9.3.0
  [✔] honeydelight-1.0.2.1-1.20.1
  [✔] ImmediatelyFast-Forge-1.3.2+1.20.4
  [✔] Incendium_1.20.x_v5.3.5
  [✔] incontrol-1.20-9.2.11
  [✔] industrial-foregoing-1.20.1-3.5.19
  [✔] industrial-foregoing-souls-1.20.1-1.0.9
  [✔] ingredientsdelight-1.0.1-1.20.1
  [✔] instant_classic_houses-1.0.0-forge-1.20.1
  [✔] inventoryessentials-forge-1.20.1-8.2.6
  [✔] invtweaks-1.20.1-1.1.0
  [✔] Jade-1.20.1-Forge-11.12.2
  [✔] JadeAddons-1.20.1-Forge-5.3.1
  [✔] JAOPCA-1.20.1-4.4.12.22
  [✔] jei-1.20.1-forge-15.20.0.105
  [✔] JustEnoughMekanismMultiblocks-1.20.1-4.6
  [✔] JustEnoughResources-1.20.1-1.4.0.247
  [✔] kitchen_grow-0.1-1.20.1
  [✔] Kiwi-1.20.1-Forge-11.8.20
  [✔] kotlinforforge-4.11.0-all
  [✔] KryptonReforged-0.2.3
  [✔] kubejs-forge-2001.6.5-build.16
  [✔] L_Enders_Cataclysm-2.27 - 1.20.1
  [✔] largemeals-1.20.1-1.3.0
  [✔] letsdo-addon-compat-forge-1.4.2
  [✔] letsdo-API-forge-1.2.15-forge
  [✔] letsdo-bakery-forge-2.0.3
  [✔] letsdo-farm_and_charm-forge-1.0.4
  [✔] letsdo-vinery-forge-1.4.28
  [✔] libraryferret-forge-1.20.1-4.0.0
  [✔] LibX-1.20.1-5.0.14
  [✔] lionfishapi-2.4-Fix
  [✔] lithostitched-forge-1.20.1-1.3.8
  [✔] lootr-forge-1.20-0.7.34.89
  [✔] mae2-1.4.4
  [✔] mcjtylib-1.20-8.0.6
  [✔] mcw-bridges-3.0.0-mc1.20.1forge
  [✔] mcw-doors-1.1.1forge-mc1.20.1
  [✔] mcw-fences-1.1.2-mc1.20.1forge
  [✔] mcw-furniture-3.3.0-mc1.20.1forge
  [✔] mcw-lights-1.1.0-mc1.20.1forge
  [✔] mcw-paths-1.0.5-1.20.1forge
  [✔] mcw-roofs-2.3.1-mc1.20.1forge
  [✔] mcw-trapdoors-1.1.3-mc1.20.1forge
  [✔] mcw-windows-2.3.0-mc1.20.1forge
  [✔] megacells-forge-2.4.5-1.20.1
  [✔] mekanism_extras-1.20.1-1.3.5
  [✔] mekanism_lasers-1.0.10
  [✔] mekanism_turrets-1.2.1
  [✔] Mekanism-1.20.1-10.4.10.66
  [✔] MekanismAdditions-1.20.1-10.4.10.66
  [✔] mekanismcardboardtooltip-forge-1.20.1-1.4.0
  [✔] MekanismGenerators-1.20.1-10.4.10.66
  [✔] MekanismTools-1.20.1-10.4.10.66
  [✔] MekanismWeapons-1.20.1-1.5
  [✔] memoryleakfix-forge-1.17+-1.1.5
  [✔] merequester-forge-1.20.1-1.1.5
  [✔] mighty_mail-forge-1.20.1-1.1.2
  [✔] MineColonies_Compatibility-1.20.1-2.45
  [✔] MineColonies_LetsDo-1.20.1-1.7
  [✔] MineColonies_Tweaks-1.20.1-2.38
  [✔] minecolonies-1.20.1-1.1.756-snapshot
  [✔] miners_delight-1.20.1-1.2.3
  [✔] mining-dimension-forge-1.20.1-1.1.0
  [✔] modernfix-forge-5.19.5+mc1.20.1
  [✔] modonomicon-1.20.1-forge-1.77.3
  [✔] moonlight-1.20-2.13.30-forge
  [✔] moredelight-24.11.06-1.20-forge
  [✔] morered-1.20.1-4.0.0.4
  [✔] MouseTweaks-forge-mc1.20.1-2.25.1
  [✔] MTR-forge-4.0.0-beta.12+1.20.1
  [✔] multipiston-1.20-1.2.43-RELEASE
  [✔] nether-s-exoticism-1.20.1-1.2.9
  [✔] netherportalfix-forge-1.20-13.0.1
  [✔] nethersdelight-1.20.1-4.0
  [✔] nightvision 1.20.1-0.0.2
  [✔] no_nv_flash-1.20.1-1.6.0.4
  [✔] Not Enough Recipe Book-FORGE-0.4.1+1.20.1
  [✔] NuclearCraft-1.20.1-1.1.1
  [✔] occultism-1.20.1-1.140.2
  [✔] oceansdelight-1.0.2-1.20
  [✔] OctoLib-FORGE-0.4.2+1.20.1
  [✔] oculus-mc1.20.1-1.7.0
  [✔] OverflowingBars-v8.0.1-1.20.1-Forge
  [✔] PackagedAuto-1.20.1-3.4.9.27
  [✔] Patchouli-1.20.1-84-FORGE
  [✔] Pehkui-3.8.2+1.20.1-forge
  [✔] pipez-forge-1.20.1-1.2.16
  [✔] Placebo-1.20.1-8.6.2
  [✔] polyeng-forge-0.1.1-1.20.1
  [✔] polymorph-forge-0.49.5+1.20.1
  [✔] ppfluids-1.20.1-2.0.1
  [✔] PrettyPipes-1.15.0-all
  [✔] productivebees-1.20.1-12.6.0
  [✔] productivetrees-1.20.1-0.2.6
  [✔] protection_pixel-1.0.9-forge-1.20.1
  [✔] PuzzlesLib-v8.1.25-1.20.1-Forge
  [✔] radium-mc1.20.1-0.12.4+git.26c9d8e
  [✔] realisticbees-1.20.1-4.0
  [✔] rechiseled_chipped-1.1
  [✔] rechiseled-1.1.6-forge-mc1.20
  [✔] rechiseledcreate-1.0.2-forge-mc1.20
  [✔] reevesfurniture-1.2811-forge-1.20.1
  [✔] repurposed_structures-7.1.15+1.20.1-forge
  [✔] resourcefullib-forge-1.20.1-2.1.29
  [✔] rftoolsbase-1.20-5.0.5
  [✔] rftoolsbuilder-1.20-6.0.8
  [✔] rhino-forge-2001.2.3-build.6
  [✔] rusticdelight-forge-1.20.1-1.3.0
  [✔] rusticpancakes-forge-1.20.1-1.0.0
  [✔] salt-1.20.1-1.2.6
  [✔] Searchables-forge-1.20.1-1.0.3
  [✔] SeedDelight-NeoorForge-1.20.1-1.0.1 (1)
  [✔] SereneSeasons-forge-1.20.1-9.1.0.0
  [✔] sereneseasonsfix-1.20.2-1.1.0.1
  [✔] simplylight-1.20.1-1.4.6-build.50
  [✔] sliceanddice-forge-3.3.0
  [✔] SmartBrainLib-forge-1.20.1-1.15
  [✔] SnowRealMagic-1.20.1-Forge-10.5.2
  [✔] sodiumdynamiclights-forge-1.0.9-1.20.1
  [✔] sodiumoptionsapi-forge-1.0.8-1.20.1
  [✔] solcarrot-1.20.1-1.15.1
  [✔] sophisticatedbackpacks-1.20.1-3.20.17.1150
  [✔] sophisticatedcore-1.20.1-0.7.11.799
  [✔] sophisticatedstorage-1.20.1-0.10.50.955
  [✔] Steam_Rails-1.6.7+forge-mc1.20.1
  [✔] steamadditions-1.3
  [✔] Stellarity-v2-0e
  [✔] structureessentials-1.20.1-3.4
  [✔] structurize-1.20.1-1.0.760-snapshot
  [✔] stylecolonies-1.11-1.20.1
  [✔] sunflowerdelight-1.20.1-1.0.4
  [✔] supermartijn642configlib-1.1.8-forge-mc1.20
  [✔] supermartijn642corelib-1.1.17a-forge-mc1.20.1
  [✔] supplementaries-1.20-3.1.9
  [✔] suppsquared-1.20-1.1.18
  [✔] tectonic-forge-1.20.1-2.4.1
  [✔] tfmg-0.9.3-1.20.1
  [✔] thermal_cultivation-1.20.1-11.0.1.24
  [✔] thermal_dynamics-1.20.1-11.0.1.23
  [✔] thermal_expansion-1.20.1-11.0.1.29
  [✔] thermal_foundation-1.20.1-11.0.6.70
  [✔] thermal_innovation-1.20.1-11.0.1.23
  [✔] thermal_integration-1.20.1-11.0.1.27
  [✔] thermal_locomotion-1.20.1-11.0.1.19
  [✔] thermalendergy-1.20.1-1.0.0
  [✔] ThermalExtra-3.2.0-1.20.1
  [✔] THT-Forge-1.20.1-6.2.11.3
  [✔] tinymobfarm-1.4-1.20.1-forge
  [✔] titanium-1.20.1-3.8.32
  [✔] ToastControl-1.20.1-8.0.3
  [✔] tomeofblood-1.20.1-0.4.4-all
  [✔] towntalk-1.20.1-1.1.0
  [✔] trafficcraft-forge-1.20.1-1.1.0
  [✔] trashcans-1.0.18b-forge-mc1.20
  [✔] TravelAnchors-1.20.1-5.0.1
  [✔] ubesdelight-forge-1.20.1-0.2.3
  [✔] uilib-0.3.5-forge
  [✔] UniversalEnchants-v8.0.0-1.20.1-Forge
  [✔] vintagedelight-0.1.6
  [✔] wfc-1.4.1-1.20.1-forge
  [✔] WWOO-FABRIC+FORGE+QUILT-2.0.0
  [✔] Xaeros_Minimap_24.6.1_Forge_1.20
  [✔] XaerosWorldMap_1.39.0_Forge_1.20
  [✔] xnet-1.20-6.1.6
  [✔] xnetgases-1.20.1-5.1.4
  [✔] ydms_autorun-forge-1.20.1-1.0.0``

### Expected Behavior

worldgen problem or something change ?

### Actual Behavior

no oregen on mining dimension 

example of kubejs code, this code was ok on GTCEU 1.4.6, but not on 1.5.4

(https://pastebin.com/d10SftsN)

### Steps to Reproduce

change version of GTCEU modern to 1.4.6 > 1.5.4

### Additional Information

Latest gtceu modern version 1.5.4

Test on a minimal instance with gtceu, advanced dimension mining, kubejs, emi), and same result

**Comment by screret** [comment]
try enabling the config to allow ores in superflat worlds, we made this change recently.

**Comment by Castanea43** [comment]
Thanks its ok with this !
