### ISSUE TITLE
Arc Furnace / Macerator recycling recipes do not update outputs when a recipe is altered or removed

### ISSUE THREAD

**Issue by Electrolyte220** [GregTechCEu/GregTechCEu-1.19#2479]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.5.4

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

KubeJS (2001.6.5-build.16)

### Expected Behavior

If the recipe was removed and replaced with a different one, the recycling recipes should reflect the new inputs.
If the recipe was removed and no recipe was added, it should remove the recycling recipes.

### Actual Behavior

The old outputs for the recycling recipes remain the same, regardless of if the recipe was removed and a new recipe was added.

### Steps to Reproduce

1. Remove a recipe for a machine (ex. Wooden multiblock tank) 
2. Add a new recipe for the machine using different materials (ex. steel rings instead of copper rings)
3. Reload kube scripts and check the uses on the tank to see the recycling recipes using the original materials as outputs

**Comment by Spicierspace153** [comment]
can i see your Kubejs script your using?

**Comment by Electrolyte220** [comment]
```
ServerEvents.recipes(event => {
	event.remove({id: 'gtceu:shaped/wood_multiblock_tank'})
})
```

**Comment by Spicierspace153** [comment]
what about the recipe that adds a new recipe

**Comment by Spicierspace153** [comment]
Can you please send the kube script your using to add the new recipe in

**Comment by Electrolyte220** [comment]
```
event.shaped(Item.of('gtceu:wooden_multiblock_tank'),
		[
			'RPS',
			'OTD',
			'FPF'
		],
		{
			S: 'gtceu:wrought_iron_screw',
			R: 'gtceu:wrought_iron_ring',
			D: '#forge:tools/screwdrivers',
			T: 'gtceu:treated_wood_planks',
			P: 'gtceu:wood_large_fluid_pipe',
			F: 'gtceu:treated_wood_frame',
			O: 'gtceu:wrought_iron_rotor'
		})
```

**Comment by Spicierspace153** [comment]
you need to edit the unification data for the block to properly change recipe data using the chemical helper method in kubejs.
