### ISSUE TITLE
To Do In Game Compass Guide

### ISSUE THREAD

**Issue by Drackion** [GregTechCEu/GregTechCEu-1.19#248]
### To Do
- [x] Gtceu power system 
- [ ] Overclocking 
- [ ] Individual Cover Functions // In Progress Drack
   - [x] Pump
   - [x] Conveyor
   - [ ] Robot Arm
   - [ ] Item Filter
   - [ ] Item Tag Filter
   - [ ] Fluid Filter
   - [ ] Fluid Tag Filter
   - [ ] Machine Controller
   - [ ] Activity Detector
   - [ ] Advanced Activity Detector
   - [ ] Fluid Detector
   - [ ] Advanced Fluid Detector
   - [ ] Item Detector
   - [ ] Advanced Item Detector
   - [ ] Energy Detector
   - [ ] Advanced Energy Detector
   - [ ] Maintenance Detector
   - [ ] Computer Monitor
   - [ ] Crafting Table
   - [ ] Shutter Module
   - [ ] Infinity Water
   - [ ] Ender Fluid Link
   - [ ] Fluid Voiding
   - [ ] Advanced Fluid Voiding
   - [ ] Item Voiding
   - [ ] Advanced Item Voiding
   - [ ] Facade
- [ ] Tool functions
- [ ] Machine Functions

**Comment by Yefancy** [comment]
any luck? can we merge the finished contents first ^_^

**Comment by Yefancy** [comment]
also refer to the #523
