### ISSUE TITLE
Magnetic Ingots make non-magnetic products

### ISSUE THREAD

**Issue by RashunB** [GregTechCEu/GregTechCEu-1.19#2492]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.5.4

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Monifactory v0.10.5

### Expected Behavior

Previous behavior of magnetic ingot makes magnetic product. IE magnetic steel ingot makes magnetic steel rods.

### Actual Behavior

Magnetic steel ingot made non-magnetic steel rods
![2024-12-03_09 18 12](https://github.com/user-attachments/assets/afe47f6f-3b69-4c0d-bc84-f041fe0ed995)
![2024-12-03_10 17 26](https://github.com/user-attachments/assets/fd361b74-3055-494f-a3d5-34da746c0b32)

### Steps to Reproduce

1) Magnetize steel ingots in polarizer
2) Put magnetized steel ingots in lathe
3) View output

**Comment by krossgg** [comment]
This is intended. Ferromagnetic materials tend lose their magnetization when subject to high forces or temperatures. You now need to machine, then magnetize.

**Comment by RashunB** [comment]
Okay, as long as its intentional. I thought something went wrong, reasoning aligns with what gregtech intends to be anyway. Thank you. This can be closed.
