### ISSUE TITLE
Something with GTCeuM and LDlib is crashing during world creation.

### ISSUE THREAD

**Issue by levicc00123** [GregTechCEu/GregTechCEu-1.19#2493]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.5.4

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

- AdvancedAE
- Advanced Peripherals
- AE Additions
- AE2 Import Export Card
- AE2 MEGA Things
- Ae2 Things
- Ae2 Crafting Tree
- AEInfinityBooster
- AntiBlockReChiseled
- Applied Energistics 2
- Applied Energistics Wireless Terminals
- Applied Flux
- Architectury API
- BadMeteoroid
- Bigger AE2
- Bookshelf
- Botany Pots
- Botany Trees
- Caged Mobs
- CC:Tweaked
- Cloth Config API
- Construction Wand
- Controlling
- CreativeCore
- Curios
- Embeddium
- ExtendedAE
- Fast Leaf Decay
- FerriteCore
- FramedBlocks
- Framework
- FTB Backups 2
- FTB Chunks
- FTB Essentials
- FTB Library
- FTB Teams
- FTB Ultimine
- Fusion
- GeckoLib
- Glodium
- Gregtech Rocketry
- Gregtech Steam Additions
- GT Community Additions
- GT--
- GTMThings
- JEI
- Just Enough Resources
- Kotlin for Forge
- LDLib
- MEGA Cells
- ME Requester
- Modern AE2 Addons
- Modern Online Picture Frame
- ModernFix
- More Peripherals
- Mouse Tweaks
- MrCrayFish Furniture Mod: Refurbished
- NeonDeco
- Oculus
- PolyLib
- Programmed Circuit Card
- Rechiseled
- Rechiseled AE2
- Resourceful Lib
- Scalable Cat's Force
- Searchables
- Simple Neon Lights
- Simply Light
- SuperMartijn642's Config Lib
- SuperMartijn642's Core Lib
- The One Probe
- Tom's Peripherals
- Xtones
- Zoe Isn't Cyberpunk

### Expected Behavior

I'm able to create a world.

### Actual Behavior

Game crashes before the world creation dialog opens.

### Steps to Reproduce

1. Create a fresh instance with all the mods I mentioned and GregTechCEu Modern
2. launch the instance and wait for it to boot.
3. Create a new world, this is where the crash happens.

### Additional Information

[crash-2024-12-03_16.56.45-client.txt](https://github.com/user-attachments/files/18001053/crash-2024-12-03_16.56.45-client.txt)
[latest.log](https://github.com/user-attachments/files/18001065/latest.log)

**Comment by krossgg** [comment]
This happens because GT Community Addons has not updated to match our API changes introduced in 1.5.0. Please take this issue to them, or downgrade your GTM version. Thank you.

**Comment by levicc00123** [comment]
Removing GT Community Additions fixed the issue! Thank you, and have a fantastic day!
