### ISSUE TITLE
Gregtech machine guis lag

### ISSUE THREAD

**Issue by Faked4075** [GregTechCEu/GregTechCEu-1.19#2504]
### Checked for existing issues

- [ ] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

V2.5.4

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

dedicated server

### Cross-Mod Interaction

No

### Other Installed Mods

Embeddium

### Expected Behavior

Nope

### Actual Behavior

I expected that there would be no lag

### Steps to Reproduce

Nope

### Additional Information

also the mechanisms themselves, which are in the inventory, lag (3D texture of the mechanism block in the inventory)

**Comment by Faked4075** [comment]
https://github.com/user-attachments/assets/c71b5e60-1755-4a57-a2c7-84ff1bddc0a2

You can see the lag

**Comment by Pumpkin7266** [comment]
you mean 1.5.5?

**Comment by Faked4075** [comment]
> you mean 1.5.5?

oh sorry, the version was 1.5.4

**Comment by Faked4075** [comment]
I also checked on 1.5.5, the interfaces still lag

**Comment by Faked4075** [comment]
but on version 1.4.6 1.21.1, there are no lags.
but there the mechanisms in the inventory lag even more

**Comment by Spicierspace153** [comment]
Currently this is because of our library mod for guis which we are planning to switch off of fairly soon. This will alleviate this issue.
