### ISSUE TITLE
When spray painting AE2 cables, it should stop at any face that has a cable part.

### ISSUE THREAD

**Issue by tomprince** [GregTechCEu/GregTechCEu-1.19#2518]
### Cross-mod Integration

AE2

### Feature Description

In particular, it should stop at a ME P2P tunnel or quartz fiber, but also pattern provider/interface pair or the like. It should also stop when the original color of the cable changes.

I'm using different color cable to differentiate between cables carrying P2P and those after the P2P, and it would be nice to be able to spray a length of cable and know that it will stop when it gets to a different section of the network.

It probably similarly makes sense to check connectivity (or covers) when painting GT cables/pipes.

**Comment by omergunr100** [comment]
what do you mean?
the spray can is a per block thing, isn't it?

**Comment by tomprince** [comment]
> what do you mean? the spray can is a per block thing, isn't it?

If you sneak click with the spray can, it will do a whole line in the direction you are facing (added in #1025).
