### ISSUE TITLE
Raw crystall chip in Crystallization Chamber

### ISSUE THREAD

**Issue by Alehopper** [GregTechCEu/GregTechCEu-1.19#2534]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.5.4

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Multiplayer (Server)

### Cross-Mod Interaction

Unsure

### Other Installed Mods

Monifactory

### Expected Behavior

only works with cleaning hatch
![Screenshot 2024-12-13 022413](https://github.com/user-attachments/assets/0f1e764c-f18f-4161-835d-347adc9f4d5c)

### Actual Behavior

works without one
![2024-12-13_02 21 53](https://github.com/user-attachments/assets/369f8bef-ba70-41ff-b1b5-7a86176d8b65)

### Steps to Reproduce

just drag and drop

**Comment by teh-banana** [comment]
Did you previously have a Cleaning Maintenance Hatch on the Large Crystallization Chamber?

I was able to reproduce this bug with just GT (1.5.4) (and EMI, Jade, AE2) installed, but to get it to happen it needed to have started running with a Cleaning Maintenance Hatch previously.

**Comment by Alehopper** [comment]
At First only Auto maintanance, than Mate switched to cleaning for this recipe, but wantet an extra atoclaive for this BC to slow, so i stopped it, die some other Prozesses with this machine and than this again, but forgot to Switch hatches in this machine.
So yes previosly threre was a cleaning hatch.

**Comment by a-a-GiTHuB-a-a** [comment]
It might be a config thing—check if `cleanMultiblocks` is set to `true`. Otherwise, this comment is useless and can be ignored.

**Comment by Alehopper** [comment]
Set to false, but for whatever reason, ist works fine after a second round of Chips without cleaning in a while, maybe bc of /reload or something
