### ISSUE TITLE
Crash while generating chunks with Chunk-pregenerator, null pointer GTceu

### ISSUE THREAD

**Issue by PaxtelR** [GregTechCEu/GregTechCEu-1.19#2538]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.5.4

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

Dedicated Server

### Cross-Mod Interaction

Yes

### Other Installed Mods

ALot, see at crash log

### Expected Behavior

Not Crash

### Actual Behavior

Crash while generate chunks with Chunk-Pregenerator 4.4.4

### Steps to Reproduce

- Open server
- Enter server
- Start generate task with chunk-pregenerator (300 radius)
- Quit server
- Wait until crash

### Additional Information

[crash-2024-12-13_11.54.37-server.txt](https://github.com/user-attachments/files/18128109/crash-2024-12-13_11.54.37-server.txt)
[latest.log](https://github.com/user-attachments/files/18128116/latest.log)

```
Description: Exception in server tick loop

java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?] {}
	at java.util.HashMap$KeyIterator.next(HashMap.java:1620) ~[?:?] {}
	at com.gregtechceu.gtceu.integration.map.cache.DimensionCache.toNBT(DimensionCache.java:39) ~[gtceu-1.20.1-1.5.4.jar%23275!/:1.5.4] {re:classloading}
	at com.gregtechceu.gtceu.integration.map.cache.server.ServerCacheSavedData.m_7176_(ServerCacheSavedData.java:55) ~[gtceu-1.20.1-1.5.4.jar%23275!/:1.5.4] {re:classloading}
	at net.minecraft.world.level.saveddata.SavedData.m_77757_(SavedData.java:36) ~[server-1.20.1-20230612.114412-srg.jar%23339!/:?] {re:mixin,re:classloading}
```

**Comment by ThePuzzlemaker** [comment]
I experienced this issue with regular chunk generation on a dedicated server.

[crash-2024-12-15_00.30.18-server.txt](https://github.com/user-attachments/files/18139168/crash-2024-12-15_00.30.18-server.txt)
I can provide more info if needed, I just don't want to have to go through the slog of redacting my entire latest.log/debug.log if it's not necessary.

**Comment by krossgg** [comment]
@ThePuzzlemaker @PaxtelR Hello, assuming you can recreate the issue, would either of you be able to test the jar in the `build output` zip [here](https://github.com/GregTechCEu/GregTech-Modern/actions/runs/12363211444?pr=2565)? I am testing #2565

**Comment by PaxtelR** [comment]
@krossgg I tried to reproduce the error in the version you mentioned, and apparently it is resolved. I couldn't reproduce the error. So, I believe the issue has been fixed.

**Comment by krossgg** [comment]
Cool, thank you
