### ISSUE TITLE
[build] Include better version numbers in github built artifacts.

### ISSUE THREAD

**Issue by tomprince** [GregTechCEu/GregTechCEu-1.19#2539]
### Feature Description

- I was asked to test #2535. When I downloaded the artifacts from it, they had version 1.5.5. It should have some indication that those artifacts are not from a release. Bonus points if the version includes the PR number and commit (at least the short form).
- I have been running various incarnations of https://github.com/GregTechCEu/GregTech-Modern/releases/tag/latest-1.20.1. The version that (currently) reports as is 1.5.5-SNAPSHOT. However, as that tag changes, and I've run multiple versions of it, it can be hard to identify what precise version I'm running. The version should include some indication of what specific snapshot it is. The tag includes a commit date, so that seems sensible to include in the version number. It could also be helpful to include the commit as well.
  Since that tag changes, it might also be helpful to create a tag for snapshots that don't change, so people can easily go back and see what a specific snapshot is (and possibly make it easier to revert to an earlier snapshot if there are issues with a later one). Extra bonus points for using identical bonus points for using the same artifacts for the stable and `latest-1.20.1` tags.

**Comment by jtuc** [comment]
Resolved by #2588?
