### ISSUE TITLE
Crash at the Distillation Tower

### ISSUE THREAD

**Issue by gagu58** [GregTechCEu/GregTechCEu-1.19#2541]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.5.4

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

None

### Expected Behavior

Nothing should happen.

### Actual Behavior

The game crashed and I couldn't load the world.

### Steps to Reproduce

1. Build a Distillation Tower. No output hatch will be placed.
2. Running.
3. Game crashed.

**Comment by Spicierspace153** [comment]
fixed in #2452
