### ISSUE TITLE
Missing liquids' textures

### ISSUE THREAD

**Issue by GoodGameInfinity** [GregTechCEu/GregTechCEu-1.19#255]
### GregTech CEu Version

"gtceu-fabric-1.20.1-1.0.10" downloaded from Modrinth

### Recipe Viewer Installed

REI

### Environment

Singleplayer (but it doesn't make any difference)

### Cross-Mod Interaction

No

### Expected Behavior

All liquids having textures

### Actual Behavior

Some of the liquids don't have textures

### Steps to Reproduce

Here are all the steps up from creating a new instance (I use PrismLauncher):

1. Create a new Fabric 1.20.1 instance
2. Download Gregtech-Modern with it's dependencies (from Modrinth)
3. Download Roughly Enough Items with it's dependencies (from Modrinth)
4. Launch up the game
5. Get access to REI menu
6. Get to liquids page in REI

### Additional Information

Screenshots of this bug:
![Screenshot_20230802_160338](https://github.com/GregTechCEu/GregTech-Modern/assets/81247214/139964da-ca7f-4635-b927-81c0f7e86bb4)
![Screenshot_20230802_160417](https://github.com/GregTechCEu/GregTech-Modern/assets/81247214/5a83e73e-d223-448a-977f-2dba68eaa661)
[Instance packaged as mrpack](https://cdn.discordapp.com/attachments/1136288922553557014/1136289211926978742/Gregtech_Minimal_Instance.mrpack)
[Instance packaged as MultiMC-compatable ZIP](https://cdn.discordapp.com/attachments/1136288922553557014/1136289212308668416/Gregtech_Minimal_Instance.zip) with all mod JARs and player data removed

P.s. Sorry if the links to instances don't work.

**Comment by Phoupraw** [comment]
Me, too. Fluids in AE2 terminal miss texture.
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/50520903/7a2375b2-cede-4b07-8217-f8461bf03d18)
