### ISSUE TITLE
Missing Macerator/Arc Furnace breakdown recipes for some machines

### ISSUE THREAD

**Issue by loving2** [GregTechCEu/GregTechCEu-1.19#256]
### GregTech CEu Version

gtceu-forge-1.20.1-1.0.8.a

### Recipe Viewer Installed

JEI

### Environment

Dedicated Server

### Cross-Mod Interaction

No

### Expected Behavior

Insert Alloy Smelter into a Macerator
Macerator processes the Alloy Smelter
Get some dust out

### Actual Behavior

Insert Alloy Smelter into a Macerator
Macerator does nothing

### Steps to Reproduce

1) Load into a world or make a new one
2) Check the uses of the Basic Alloy Smelter with JEI
3) Notice it has no recipe for breaking down in the Macerator

### Additional Information

I've noticed this is the case for the following machines:
 - Basic to Ultimate Alloy Smelter
 - Basic to Ultimate Electrolyzer
 - All Voltage Transformers
 - All Energy Converters
 - All Battery Buffers
 - All Turbo Chargers
 - All Kinetic Mixers
 - ULV to UHV Input Hatches
 - ULV to UHV Output Hatches
 - ULV to UHV Input Bus
 - ULV to UHV Output Bus
 - LV to UV Item Passthrough Hatches (except the EV Item Passthrough Hatch)
 - LV to UV Fluid Passthrough Hatches (except the EV Fluid Passthrough Hatch)

**Comment by Paupertatis** [comment]
It also happens with the fuel of boilers. You just cannot burn any wood planks (or wools) in boilers, unless quit a world and join another one, then join back to the first one.

**Comment by screret** [comment]
that's a completely separate issue.

**Comment by RainPumpkin** [comment]
update as of latest, only the following are mixing:
-energy converters
-ULV to UHV Input Hatches
-ULV to UHV Output Hatches
-ULV to UHV Input Bus
-ULV to UHV Output Bus
-LV to UV Item Passthrough Hatches (except the EV Item Passthrough Hatch)
-LV to UV Fluid Passthrough Hatches (except the EV Fluid Passthrough Hatch)

did not check:
-kinetic mixers

**Comment by Pumpkin7266** [comment]
update as of latest, only the following are missing:
-energy converters
-ULV to UHV Input Hatches
-ULV to UHV Output Hatches
-ULV to UHV Input Bus
-ULV to UHV Output Bus
-LV to UV Item Passthrough Hatches (except the EV Item Passthrough Hatch)
-LV to UV Fluid Passthrough Hatches (except the EV Fluid Passthrough Hatch)

did not check:
-kinetic mixers
