### ISSUE TITLE
Have a separate "Recycling" recipe type for arc furnace, etc

### ISSUE THREAD

**Issue by ashy1227** [GregTechCEu/GregTechCEu-1.19#2567]
### Feature Description

Currently, recycling recipes are lumped in with actual crafting recipes in EMI (probably other recipes viewers?), which makes it really difficult to tell how you're actually supposed to make certain materials, since you might have to sort through 100s of pages to find the recipe you want. For example, annealed copper:

![Screenshot from 2024-12-16 19-07-50](https://github.com/user-attachments/assets/f249a315-8e7f-4da2-9513-ac9ff313bf30)

(I'm playing TerraFirmaGreg, but I think this is an issue natively. Sorry if it's not.)

I think a good solution would to be to move recipes that turn machines and stuff back into their component parts into a separate category called "Arc Furnace Recycling" or something (and Macerator Recycling. Macerators have a similar problem, might be other machines too.)

**Comment by krossgg** [comment]
This is already a thing on the latest release version of GTM.

**Comment by ashy1227** [comment]
> This is already a thing on the latest release version of GTM.

Thank you. Edit: What's GTM?

**Comment by screret** [comment]
...this mod is GTM?

**Comment by Deepacat** [comment]
> > This is already a thing on the latest release version of GTM.
> 
> Thank you. Edit: What's GTM?

gregtech modern. the mod. this mod^

**Comment by Deepacat** [comment]
terrafirmagreg is on an older version of the mod

**Comment by ashy1227** [comment]
> ...this mod is GTM?

Thank you and sorry I just didn't realize what it stood for before, since I'm new to gregtech

**Comment by omergunr100** [comment]
Thanks for taking the time to fill out the bug report, but when you find a bug please try to see if it's fixed on the latest version before reporting it

**Comment by ashy1227** [comment]
> Thanks for taking the time to fill out the bug report, but when you find a bug please try to see if it's fixed on the latest version before reporting it

Sorry, I know. I just didn't see any issues listed for it, so I assumed you guys didn't know about it.
