### ISSUE TITLE
Have a larger hitbox when using sneak-click with an empty hand on covers.

### ISSUE THREAD

**Issue by tomprince** [GregTechCEu/GregTechCEu-1.19#2571]
### Feature Description

When you sneak click with a screwdriver to access the cover GUI, the hitbox extends to be the full block. However, when you use an empty hand, you need to click in the appropriate sector *and* on face pointing in the correct direction. This is particularly relevant for covers on pipes.

You can see in the middle image, I'm still in the region of the bounding box for the bottom cover, but since I'm point at the
top surface of the cover (rather than the edge of the cover or the side of the pipe) I can't access the cover GUI.
![image](https://github.com/user-attachments/assets/de770a24-92aa-4ec1-9ffd-b4bb12bbc173)
![image](https://github.com/user-attachments/assets/c251988c-813d-47b6-baed-8612dfebcde4)
![image](https://github.com/user-attachments/assets/9fe0cff6-e08e-4204-9185-2a26eae80696)

**Comment by omergunr100** [comment]
nice catch, but it shouldn't be a screwdriver - empty hand diff issue, the same problem happened with enderio conduits too.
the direction returned from `BlockHitResult.getDirection()` returns the face of the section of the block you're looking at, this means that if you look at the pipe section (as you do in the third image) or the correct side of the cover itself (as you do in the first image) it'll give you the correct facing side of the pipe, but if you look at an incorrect side of the cover as you do in the second image where you look at the "top" of the cover section of the pipe it'll return "top" as the hit face.

**Comment by tomprince** [comment]
I am aware of what is going on with `BlockHitResult.getDirection()` (at least in practice). The difference between empty hand and with a screwdriver is, that when you are holding the appropriate tool and looking at a GT pipe, the bounding box  of the pipe is changed to be a full block.

**Comment by omergunr100** [comment]
that does sound like a better solution than guessing the side if that's the case, do you want to pr it or should I?

**Comment by tomprince** [comment]
> that does sound like a better solution than guessing the side if that's the case, do you want to pr it or should I?

I'll happily let you.
