### ISSUE TITLE
Scythes do not consume the seeds that would otherwise be required to replant a particular crop.

### ISSUE THREAD

**Issue by TheDogOfChaos** [GregTechCEu/GregTechCEu-1.19#2581]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech Modern Version

v1.5.4

### Minecraft Version

v1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

```groovy
dependencies {
    // Minecraft & Forge
    minecraft "com.mojang:minecraft:$project.minecraft_version"
    forge "net.minecraftforge:forge:$project.minecraft_version-$project.forge_version"
    
    // layered mappings - Mojmap names, parchment and QM docs and parameters
    mappings loom.layered {
        it.mappings("org.quiltmc:quilt-mappings:$project.minecraft_version+build.$project.quilt_mappings:intermediary-v2")
        it.parchment("org.parchmentmc.data:parchment-$project.minecraft_version:$project.parchment_mappings@zip")
        it.officialMojangMappings { nameSyntheticMembers = false }
    }

    // JEI (Version 15.20.0.105) & EMI (Version 1.1.18)
    modCompileOnly("mezz.jei:jei-$project.minecraft_version-forge-api:$project.jei_version") { transitive = false }
    modCompileOnly("mezz.jei:jei-$project.minecraft_version-common-api:$project.jei_version") { transitive = false }
    modRuntimeOnly("mezz.jei:jei-$project.minecraft_version-forge:$project.jei_version") { transitive = false }
    modRuntimeOnly("dev.emi:emi-forge:$project.emi_version+$project.minecraft_version")

    // GT, LdLib, Registrate
    modImplementation("com.gregtechceu.gtceu:gtceu-$project.minecraft_version:$project.gtceu_version") { transitive = false }
    modRuntimeOnly("com.lowdragmc.ldlib:ldlib-forge-$project.minecraft_version:$project.ldlib_version") { transitive = false } // Version 1.0.33.b
    modRuntimeOnly("com.tterrag.registrate:Registrate:$project.registrate_version") // Version MC1.20-1.3.11

    // KubeJS
    modImplementation("dev.latvian.mods:kubejs-forge:$project.kubejs_version") // Version 2001.6.5-build.16

    // Configuration (by Toma1O6)
    modRuntimeOnly("dev.toma.configuration:configuration-forge-$project.minecraft_version:$project.configuration_version") // Version 2.2.0

    // Jade
    modRuntimeOnly("curse.maven:jade-324717:5390389") // Version 11.9.3

    // Mixin Extras (Version 0.2.0)
    implementation(annotationProcessor("io.github.llamalad7:mixinextras-common:$project.mixinextras_version"))
    implementation(include("io.github.llamalad7:mixinextras-forge:$project.mixinextras_version"))

    // Lombok
    compileOnly 'org.projectlombok:lombok:1.18.36'
    annotationProcessor 'org.projectlombok:lombok:1.18.36'
}
```

### Expected Behavior

I have a crop with the following loot table:
[magnetite_crop.json](https://github.com/user-attachments/files/18183688/magnetite_crop.json) (ignore the iron nugget entry, it's just a test)

The loot table is configured such that breaking the crop block will only ever drop ONE seed, no matter if the crop is fully grown or not.

I expected that scythes would consume a number of seeds (equal to the number of crops to be replanted) from the amount of seeds that get dropped overall.

### Actual Behavior

https://github.com/user-attachments/assets/857f8a15-5d2a-4367-8a0a-d7255f72f51a

The scythe effectively duplicates the seeds.

### Steps to Reproduce

1) Plant any crop's seed (especially a crop that drops a fixed amount of seeds if broken when fully grown)
2) Wait for the crop to grow.
3) Right the crop with a scythe in hand to use the scythe's harvesting ability.
4) The crops will be replanted, but you will get the normal amount of seeds that would drop from that crop.

**Comment by omergunr100** [comment]
I don't have a plant that always drops exactly 1 seed to test a fix with, do you know how to pull a pr branch and compile the mod?

**Comment by TheDogOfChaos** [comment]
yes

**Comment by omergunr100** [comment]
look at the pr above this message and tell me if that solves it for you

**Comment by TheDogOfChaos** [comment]
https://github.com/user-attachments/assets/304ab772-9c42-4c09-81ed-39ec2b78397f

it works

(the data file i [hotloaded](https://github.com/user-attachments/assets/c4b75702-51ee-48e2-912f-ded8fdadf742) onto gt for this video test: [wheat.json](https://github.com/user-attachments/files/18187672/wheat.json))

**Comment by omergunr100** [comment]
good, I'll undraft it
