### ISSUE TITLE
Recipe category icon for multiblock machines changed.

### ISSUE THREAD

**Issue by tomprince** [GregTechCEu/GregTechCEu-1.19#2607]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.6.0

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Monifactory

### Expected Behavior

I expect the recipe category for machines that are all multiblocks to use the base machine. I also expect the list of machine icons along the bottom of the recipe page be in increasing complexity.

### Actual Behavior

For the "Electic Blast Furnace" recipe category, the icon is the "Rotary Hearth Furnace", and the list of machines is RHF then EBF. Also, the RHF is before the EBF in EMI's list of blocks.

Similarily, the Bulk Blast Chiller is used as icon, and is the first machine. Also, the "Large Frationating Distillery" is listed frst.

### Steps to Reproduce

Look at EMI in 1.6.

**Comment by Faked4075** [comment]
[crash-2024-12-21_12.35.20-client.txt](https://github.com/user-attachments/files/18217549/crash-2024-12-21_12.35.20-client.txt)
I found out that this only happens with gtceu installed, nothing else, the crash occurs when I break the primitive blast furnace block.

**Comment by omergunr100** [comment]
> [crash-2024-12-21_12.35.20-client.txt](https://github.com/user-attachments/files/18217549/crash-2024-12-21_12.35.20-client.txt) I found out that this only happens with gtceu installed, nothing else, the crash occurs when I break the primitive blast furnace block.

The issue you're describing is unrelated to this issue and solved by #2609

**Comment by Faked4075** [comment]
> > [crash-2024-12-21_12.35.20-client.txt](https://github.com/user-attachments/files/18217549/crash-2024-12-21_12.35.20-client.txt) Я обнаружил, что это происходит только при установленном gtceu, больше ничего, сбой происходит, когда я ломаю примитивный блок доменной печи.
> 
> Проблема, которую вы описываете, не связана с этой проблемой и решена с помощью #2609

should i wait for the next version of the mod? or what?

**Comment by screret** [comment]
Yes.
