### ISSUE TITLE
1.6.0 crash with embeddium

### ISSUE THREAD

**Issue by Faked4075** [GregTechCEu/GregTechCEu-1.19#2608]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

V1.6.0

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Embeddium

### Expected Behavior

I expected it to work the same as 1.5.4

### Actual Behavior

Launch game with 1.6.0 version

### Steps to Reproduce

Launching

### Additional Information

[crash-2024-12-21_10.50.04-client.txt](https://github.com/user-attachments/files/18217263/crash-2024-12-21_10.50.04-client.txt)

**Comment by krossgg** [comment]
Fixed by #2615

**Comment by Faked4075** [comment]
Perfect
