### ISSUE TITLE
rubber ring recipe issue

### ISSUE THREAD

**Issue by fuunylmz** [GregTechCEu/GregTechCEu-1.19#2624]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.6.0

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

REI

### Environment

Multiplayer - Dedicated Server

### Cross-Mod Interaction

Yes

### Other Installed Mods

Ae2,ad_astra

### Expected Behavior

When using a knife to make a rubber ring, the knife will not disappear directly, but its durability will be deducted.

### Actual Behavior

When using a knife to make a rubber ring, the knife will disappear directly

### Steps to Reproduce

just crafting gtceu:rubber_ring or gtceu:styrene_butadiene_rubber_ring

**Comment by screret** [comment]
What knife?

**Comment by fuunylmz** [comment]
> What knife?

gtceu:iron_knife

**Comment by fuunylmz** [comment]
![1](https://github.com/user-attachments/assets/5fbf7a7d-1947-401b-b6f7-c48ccca32489)
this recipe

**Comment by MatthiasMann** [comment]
is this a flint knife or an iron knife? the flint one has basically no durability

**Comment by fuunylmz** [comment]
> is this a flint knife or an iron knife? the flint one has basically no durability

**Comment by fuunylmz** [comment]
i use other mod knife not GregTech-Modern,my issue
