### ISSUE TITLE
Create world menu crash

### ISSUE THREAD

**Issue by this-text-is-disappeared1435** [GregTechCEu/GregTechCEu-1.19#2635]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.6.1

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

**### list from log**
delightfulburgers-1.20.1.jar |Delightful Burgers |delightfulburgers |1.20.1 |DONE |Manifest: NOSIGNATURE
nethersdelight-1.20.1-4.0.jar |Nether's Delight |nethersdelight |1.20.1-4.0 |DONE |Manifest: NOSIGNATURE
garnished-2.0.2+1.20.1-neoforged.jar |Create: Garnished |garnished |2.0.2 |DONE |Manifest: NOSIGNATURE
EnderIO-1.20.1-6.2.5-beta-all.jar |Ender IO |enderio |6.2.5-beta |DONE |Manifest: NOSIGNATURE
kffmod-4.11.0.jar |Kotlin For Forge |kotlinforforge |4.11.0 |DONE |Manifest: NOSIGNATURE
Iceberg-1.20.1-forge-1.1.25.jar |Iceberg |iceberg |1.1.25 |DONE |Manifest: NOSIGNATURE
flywheel-forge-1.20.1-0.6.11-13.jar |Flywheel |flywheel |0.6.11-13 |DONE |Manifest: NOSIGNATURE
create-1.20.1-0.5.1.j.jar |Create |create |0.5.1.j |DONE |Manifest: NOSIGNATURE
Create-DnDesire-1.20.1-0.1b.Release-Early-Dev.jar |Create: Dreams & Desires |create_dd |0.1b.Release-Early-D|DONE |Manifest: NOSIGNATURE
Crystal-Clear-2.1-Beta-forge.jar |Create: Crystal Clear |crystal_clear |2.1-Beta |DONE |Manifest: NOSIGNATURE
create-structures-0.1.1-1.20.1-FORGE.jar |Create: Structures |create_structures |0.1.1 |DONE |Manifest: NOSIGNATURE
create_central_kitchen-1.20.1-for-create-0.5.1.f-1|Create: Central Kitchen |create_central_kitchen |1.3.12 |DONE |Manifest: NOSIGNATURE
CreateCasing-1.20.1-1.6.2-fix1.jar |Create : Encased |createcasing |1.20.1-1.6.2-fix1 |DONE |Manifest: NOSIGNATURE
create_mechanical_extruder-1.20.1-1.6.3.j-55.jar |Create Mechanical Extruder |create_mechanical_extruder |1.20.1-1.6.3.j-55 |DONE |Manifest: NOSIGNATURE
creategoggles-1.20.1-0.5.5.g-[FORGE].jar |Create Goggles |creategoggles |0.5.5.g |DONE |Manifest: NOSIGNATURE
greate-0.0.34.jar |Greate |greate |0.0.34 |DONE |Manifest: NOSIGNATURE
create_mechanical_spawner-1.20.1-0.1.0.j-55.jar |Create Mechanical Spawner |create_mechanical_spawner |1.20.1-0.1.0.j-55 |DONE |Manifest: NOSIGNATURE
createoreexcavation-1.20-1.5.3.jar |Create Ore Excavation |createoreexcavation |1.5.3 |DONE |Manifest: NOSIGNATURE
entityculling-forge-1.7.2-mc1.20.1.jar |EntityCulling |entityculling |1.7.2 |DONE |Manifest: NOSIGNATURE
Applied-Botanics-forge-1.5.0.jar |Applied Botanics |appbot |1.5.0 |DONE |Manifest: NOSIGNATURE
megacells-forge-2.4.5-1.20.1.jar |MEGA Cells |megacells |2.4.5-1.20.1 |DONE |Manifest: NOSIGNATURE
mekanismcardboardtooltip-forge-1.20.1-1.4.0.jar |Mekanism Cardboard Tooltip |mekanismcardboardtooltip |1.4.0 |DONE |Manifest: NOSIGNATURE
ae2qolrecipes-forge-1.18.x-1.20.x-1.2.0.jar |AE2 QoL Recipes |ae2qolrecipes |1.2.0 |DONE |Manifest: NOSIGNATURE
modonomicon-1.20.1-forge-1.77.3.jar |Modonomicon |modonomicon |1.77.3 |DONE |Manifest: NOSIGNATURE
oceansdelight-1.0.2-1.20.jar |Ocean's Delight |oceansdelight |1.0.2-1.20 |DONE |Manifest: NOSIGNATURE
appleskin-forge-mc1.20.1-2.5.1.jar |AppleSkin |appleskin |2.5.1+mc1.20.1 |DONE |Manifest: NOSIGNATURE
ferritecore-6.0.1-forge.jar |Ferrite Core |ferritecore |6.0.1 |DONE |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
betterp2p-1.5.0-forge.jar |Better P2P |betterp2p |1.5.0 |DONE |Manifest: NOSIGNATURE
occultism-1.20.1-1.140.2.jar |Occultism |occultism |1.140.2 |DONE |Manifest: NOSIGNATURE
ubesdelight-forge-1.20.1-0.2.3.jar |Ube's Delight |ubesdelight |0.2.3 |DONE |Manifest: NOSIGNATURE
create_power_loader-1.5.0-mc1.20.1.jar |Create: Power Loader |create_power_loader |1.5.0-mc1.20.1 |DONE |Manifest: NOSIGNATURE
BetterF3-7.0.2-Forge-1.20.1.jar |BetterF3 |betterf3 |7.0.2 |DONE |Manifest: NOSIGNATURE
CrabbersDelight-1.20.1-1.1.7d.jar |Crabber's Delight |crabbersdelight |1.1.7d |DONE |Manifest: NOSIGNATURE
BadOptimizations-2.2.1-1.20.1.jar |BadOptimizations |badoptimizations |2.2.1 |DONE |Manifest: NOSIGNATURE
Delightful-1.20.1-3.6.1.jar |Delightful |delightful |3.6.1 |DONE |Manifest: NOSIGNATURE
create_enchantment_industry-1.20.1-for-create-0.5.|Create Enchantment Industry |create_enchantment_industry |1.2.9.d |DONE |Manifest: NOSIGNATURE
BotanyPotsOrePlanting-Forge-7.22.0+1.20.1.jar |Botany Pots Ore Planting |botany_pots_ore_planting |7.22.0 |DONE |Manifest: NOSIGNATURE
createaddition-1.20.1-1.2.4e.jar |Create Crafts & Additions |createaddition |1.20.1-1.2.4e |DONE |Manifest: NOSIGNATURE
ad_astra-forge-1.20.1-1.15.19.jar |Ad Astra |ad_astra |1.15.19 |DONE |Manifest: NOSIGNATURE_
sooo full list can looked in log
[crash-2024-12-24_15.58.36-client.txt](https://github.com/user-attachments/files/18239779/crash-2024-12-24_15.58.36-client.txt)

### Expected Behavior

i expected world creating menu

### Actual Behavior

if click create world game crash with error mouseClicked event handler

### Steps to Reproduce

1)load a game
2)click singleplayer
3.1)if you havent no worlds its start creating automatically and game crash
3.2)click create new world and game crash

### Additional Information

in crash report i found this error
(this error on russian because i play on russian language)
net.minecraftforge.fml.ModLoadingException: В GregTech (gtceu) обнаружена ошибка во время фазы события done
just translate

**Comment by screret** [comment]
gregified integrations isn't updated to latest GTM.

**Comment by this-text-is-disappeared1435** [comment]
> gregified integrations isn't updated to latest GTM.

i created modpack with gregified integrations and other greg mods and it work normal but no recipes in jei and if install old version of gregtech crashes dont fix
