### ISSUE TITLE
Trying to fill a tank with a bucket consumes/voids the bucket if there isn't enough space left in the machine tank

### ISSUE THREAD

**Issue by MatthiasMann** [GregTechCEu/GregTechCEu-1.19#2638]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.6.1

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

GT Community pack Modern

### Expected Behavior

Trying to empty the bucket fails without consuming the bucket

### Actual Behavior

The bucket including the fluid inside is gone but you hear the emptying sound.

### Steps to Reproduce

1. Have a machine with a tank (I used an LV arc furnace)
2. have it's internal tank nearly full (mine was at 7392mB)
3. Have a bucket with oxygen in your inventory
4. Try to empty that bucket into the arc furnace by clicking on the tank in the UI

**Comment by Natanaelel** [comment]
1. Does bucket variant matter? Does it also void the small fluid cell?
2. Does it play the emptying sound?
3. I'll take a deep look tomorrow.

**Comment by MatthiasMann** [comment]
I only tested a bucket
it did play the emptying sound - afterwards the bucket was gone
I checked every inventory slot as sometimes items moved differently between client and server can become invisible in the inventory - the bucket was gone.
