### ISSUE TITLE
Steam Oven voids ongoing recipe when rejoining world

### ISSUE THREAD

**Issue by a-a-GiTHuB-a-a** [GregTechCEu/GregTechCEu-1.19#2645]
### GregTech CEu Version

1.6.1

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

none

### Expected Behavior

The Steam Oven would continue to process the recipe it was running before I left the world.

### Actual Behavior

It forgets it was running a recipe, deleting whatever items it was going to output and refusing to return the items it had previously eaten.

### Steps to Reproduce

1. set up steam oven
2. run recipe
3. leave while running
4. come back
5. less stuff!

### Additional Information

I recorded a video, but the file is apparently too big. Welp.

**Comment by jtuc** [comment]
Can confirm - when the input bus was empty on rejoining the world, the recipe got "stuck" at 5% progress:
![2024-12-26_12 56 35](https://github.com/user-attachments/assets/fc1d07d2-66b6-4d67-aa79-054699acce19)
Inserting more ingredients into the input bus then started a new recipe processing, voiding the "stuck" recipe's output.

I did also test a parallel hatch in an arc smelter to see if it was a generic parallel issue, but only the steam oven voided items.

**Comment by a-a-GiTHuB-a-a** [comment]
I never tried it with an empty input bus. Interesting.

The steam grinder works perfectly fine for some reason. It's _just the oven_.

**Comment by jtuc** [comment]
Can confirm that #2657 fixes this - and also explains why it was just furnace recipes.
