### ISSUE TITLE
Unformable Clean Room

### ISSUE THREAD

**Issue by zjh790** [GregTechCEu/GregTechCEu-1.19#2665]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.6.1

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

atm9(Has been reproduced in the newly created game)

### Expected Behavior

a can using clear room 

### Actual Behavior

**in atm9:**
<img width="1280" alt="屏幕截图 2024-12-28 153631" src="https://github.com/user-attachments/assets/0c92b74b-ee3c-4ec1-bfbc-0d13532014f7" />

**in the new game(GTCeu only):**

![image](https://github.com/user-attachments/assets/beb05d64-9b72-43a6-8b0b-c5f0988e1150)
![image](https://github.com/user-attachments/assets/9fb4dd63-e27c-40b9-8a43-2e77abc675f9)

(All Clean Room walls and floors are made of Cleanroom Glass and plascrete.)

### Steps to Reproduce

make a clean room(don't use Terminal)
when i use Terminal to make a clean room,  it worked
So I think you need make clean room by yourself

**Comment by krossgg** [comment]
This was fixed by #2654. For a temporary fix, you can put an elevator block in the floor directly below the cleanroom controller. This should allow it to form.
