### ISSUE TITLE
Fluid and Item pipe restrictions by using wrench.

### ISSUE THREAD

**Issue by Praetorian6478** [GregTechCEu/GregTechCEu-1.19#267]
### Feature Description

Restricting the fluid/item movement in the pipes by adding restricting "rings" on the pipes.

**Comment by TheAlaskanPhysicist** [comment]
While it would be interesting, I don't think that is in the design of the pipes. They're supposed to move things from one place to another, and sorting can be done at the endpoints.

**Comment by Praetorian6478** [comment]
> While it would be interesting, I don't think that is in the design of the pipes. They're supposed to move things from one place to another, and sorting can be done at the endpoints.

The thing is, that the movement of the fluid and items in the pipes can be chaotic, due to the mechanic of the pipes. Restricting the movement will reduce the lag a bit, and several mechanics will, I think, be quite useful, such as not alowing stuff go back to the "input".
