### ISSUE TITLE
New Muffler that is permitted in Cleanrooms

### ISSUE THREAD

**Issue by Lukeb28** [GregTechCEu/GregTechCEu-1.19#2676]
### Feature Description

Create a new muffler that can be used in place of any other muffler and call it a "HEPA filtered muffler". It consumes a "HEPA Filter" and provides some number of crafts before needing to be replaced. It could also prevent carbon monoxide from being generated.

"HEPA filter" could be crafted using Borosilicate Glass Fibers, a Rotor, a motor, and a frame of some tier for balance. Maybe add in a high tier way of cleaning the filters that is unlocked after the filter.

**Comment by Spicierspace153** [comment]
Not currently planned.
