### ISSUE TITLE
Can't Lookup Usage or Recipe by Slot Widget in Multiblock Category

### ISSUE THREAD

**Issue by Phoupraw** [GregTechCEu/GregTechCEu-1.19#269]
### GregTech CEu Version

fabric-1.20.1-1.0.10-build_132

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

Hovering over a slot and left clicking should lead to its recipe and right clicking should lead to its usage.

### Actual Behavior

Hovering over a slot and clicking has no effect.

### Steps to Reproduce

1. Find treated wood frame.
2. Check its usage.
3. Find the multiblock category.
4. Click the slots and nothing happens.

### Additional Information

Slot widgets:
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/50520903/b1c933c0-69ee-4cea-a0c4-0ab4b1b60b9c)

**Comment by screret** [comment]
you can click the "view recipe" button (by default `R`) to open the recipe, no?

**Comment by Phoupraw** [comment]
> you can click the "view recipe" button (by default `R`) to open the recipe, no?

Oh, OK, that works.
