### ISSUE TITLE
Can't Change Number Config

### ISSUE THREAD

**Issue by Phoupraw** [GregTechCEu/GregTechCEu-1.19#270]
### GregTech CEu Version

fabric-1.20.1-1.0.10-build_132

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

Click the text field and it should become editable.

### Actual Behavior

Clicking the text field has no effect.

### Steps to Reproduce

1. Install modmenu.
2. Open gtceu config.
3. Open worldgen category.
4. Click the text field.
5. It is still non-editable.

### Additional Information

Number config entry text field:
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/50520903/33d554ea-4bb3-4532-bbf0-14e949a29ec2)

**Comment by screret** [comment]
can't you edit the config file?
this is likely a bug in the config library we use or modmenu, nothing of our control

**Comment by Phoupraw** [comment]
> can't you edit the config file? this is likely a bug in the config library we use or modmenu, nothing of our control

I can. I quit the config screen, edit the config file externally, then reopen the config screen, and the changes I just made are reflected on the config screen.

**Comment by screret** [comment]
yeah, nothing in our control
