### ISSUE TITLE
Can't Quick Swap Items in Inventory and Hotbar in Machine GUI

### ISSUE THREAD

**Issue by Phoupraw** [GregTechCEu/GregTechCEu-1.19#271]
### GregTech CEu Version

fabric-1.20.1-1.0.10-build_132

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

In vanilla GUI: hovering over a slot and pressing horbar/offhand hotkey (default 1~9 and f) will swap the items in them.

### Actual Behavior

In GT machine GUI: hovering over a slot and pressing horbar/offhand hotkey has no effect.

### Steps to Reproduce

1. Put an item in your inventory.
2. Place a low pressure steam alloy smelter.
1. Open its GUI.
1. Hover over the slot that has item.
2. Press horbar/offhand hotkey.
3. Nothing happened.

### Additional Information

Can't swap the two slots.
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/50520903/0d665e57-6617-440e-b798-b3d1389121de)

**Comment by mikerooni** [comment]
Possibly related:  
Can't use the pick block button in creative mode, as long as any GT inventory is opened.
