### ISSUE TITLE
Hopper Extracts From Ingredient Slot

### ISSUE THREAD

**Issue by Phoupraw** [GregTechCEu/GregTechCEu-1.19#273]
### GregTech CEu Version

fabric-1.20.1-1.0.10-build_132

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

Hopper can only extract items from result slots

### Actual Behavior

Hopper extracts items from ingredient slot.

### Steps to Reproduce

1. Place a low pressure steam macerator.
2. Provide steam power.
3. Put some ingredients into its ingredient slot.
4. Place a hopper beneath it.
5. The hopper is extracting items from its ingredient slot.

### Additional Information

Ingredient slot:
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/50520903/c5f6bda6-743b-4427-ae7d-a3b7661eb1ea)

**Comment by Phoupraw** [comment]
I fixed it by mixin:
```java
@Pseudo
@Mixin(targets = "com/lowdragmc/lowdraglib/side/item/fabric/ItemTransferHelperImpl$2")
abstract class MItemTransferHelperImpl_2 extends SingleStackStorage {

    @Shadow
    @Final
    IItemTransfer val$itemTransfer;

    @Shadow
    @Final
    int val$slot;

    @Override
    protected boolean canInsert(ItemVariant itemVariant) {
        return this.val$itemTransfer.insertItem(this.val$slot, itemVariant.toStack(), true).isEmpty();
    }

    @Override
    protected boolean canExtract(ItemVariant itemVariant) {
        return !this.val$itemTransfer.extractItem(this.val$slot, Integer.MAX_VALUE, true).isEmpty();
    }

}
```

**Comment by screret** [comment]
this doesn't happen for me at all.
feel free to reopen if the issue occurs with only GT.
