### ISSUE TITLE
The energy converter is unable to convert FE energy into EU energy

### ISSUE THREAD

**Issue by luluxiaoyu** [GregTechCEu/GregTechCEu-1.19#276]
### GregTech CEu Version

V1.0.10

### Recipe Viewer Installed

JEI

### Environment

Singleplayer/Multiplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

Convert FE energy into EU energy

### Actual Behavior

Unable to convert energy

### Steps to Reproduce

1. Build an energy converter

2. Switch to FE to EU mode

3. Connecting wires, unable to output EU energy normally

### Additional Information

[![pPAFANF.png](https://s1.ax1x.com/2023/08/05/pPAFANF.png)](https://imgse.com/i/pPAFANF)
[![pPAFe39.png](https://s1.ax1x.com/2023/08/05/pPAFe39.png)](https://imgse.com/i/pPAFe39)  
[![pPAFmcR.png](https://s1.ax1x.com/2023/08/05/pPAFmcR.png)](https://imgse.com/i/pPAFmcR)  
I have already sought help in Discord, and the contributor said this is broken

**Comment by screret** [comment]
https://imgur.com/OzxOJFS
works just fine for me. you sure you don't have it rotated wrong?

**Comment by luluxiaoyu** [comment]
> https://imgur.com/OzxOJFS works just fine for me. you sure you don't have it rotated wrong?

[![pPVTrzF.png](https://s1.ax1x.com/2023/08/08/pPVTrzF.png)](https://imgse.com/i/pPVTrzF)  
Am I supposed to have connected correctly? The pipeline used is pipez (Powah's pipeline has also been tried)  
The mode has also been switched to FE to EU

**Comment by screret** [comment]
likely some kind of mod incompat with pipez/powah/whatever cables.

**Comment by luluxiaoyu** [comment]
> likely some kind of mod incompat with pipez/powah/whatever cables.

I have a try, the flux network mod can be connected
