### ISSUE TITLE
Blocks become invisible when installed with sodium

### ISSUE THREAD

**Issue by NoElcDfb** [GregTechCEu/GregTechCEu-1.19#279]
### GregTech CEu Version

gtceu-fabric-1.20.1-1.0.10

### Recipe Viewer Installed

REI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

It should be use with Sodium to support shaders.

### Actual Behavior

![2023-08-07_18 11 20](https://github.com/GregTechCEu/GregTech-Modern/assets/119948820/5ea0ebec-2901-43f9-9695-7662766f389c)
---

Every block of GTm gets invisible when installed with Sodium.
Iris Shader seems haven't this issue.

---

game Ver: 1.20.1
Sodium Ver: sodium-fabric-mc1.20.1-0.5.0
iris Shader Ver: iris-mc1.20.1-1.6.5

### Steps to Reproduce

just install Sodium can reproduce this bug.

**Comment by Yefancy** [comment]
You have to install Indium to make sodium compatible with fabric rendering api
