### ISSUE TITLE
Error between the GTCEu machine and the Create smart chute

### ISSUE THREAD

**Issue by in1t1a1** [GregTechCEu/GregTechCEu-1.19#283]
### GregTech CEu Version

fabric-1.19.2-1.0.10-build_134

### Recipe Viewer Installed

REI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

Items are correctly transferred to the machine

### Actual Behavior

Items are copied or appear out of thin air

### Steps to Reproduce

1.Put 'create:smart_chute' under 'gtceu:lv_ore_washer'
2.Edit circuit settings
3.The corresponding gtceu:programmed_circuit' drops

### Additional Information

https://cdn.discordapp.com/attachments/1086528220356161546/1138132166606327860/1_x264.mp4

**Comment by mikerooni** [comment]
This might actually be an issue with our item transfer handling on fabric in general.

I managed to reproduce it even with a vanilla hopper (reliably for the ghost circuit extraction, and semi-reliably for non-stackable item insertion). Stackable items seem to be inserted 5 times.
