### ISSUE TITLE
Right click on barrel with bucket consumes bucket and 1B fluid

### ISSUE THREAD

**Issue by klugemonkey** [GregTechCEu/GregTechCEu-1.19#290]
### GregTech CEu Version

1.0.10

### Recipe Viewer Installed

None

### Environment

Multiplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

Either return the bucket to player with fluid or do not allow bucket to interact

### Actual Behavior

Iron bucket was consumed and 1B of fluid (creosote) was subtracted from barrel, player was not given bucket of creosote.

### Steps to Reproduce

Make Coke Oven with hatch output, make barrel, connect with copper pipe, smelt wood into charcoal, creating creosote, creosote fills the barrel, right click on the barrel with empty iron bucket in hand.

**Comment by klugemonkey** [comment]
Also, Create is installed, but bucket consumption happens irregardless of whether Create is installed or not

**Comment by Yefancy** [comment]
version? 1.19?1.20?fabric?forge? I cant reproduce it in the fabric 1.19

**Comment by BobVonBob** [comment]
I can reproduce this and add a bit more info. (1.20.1 GT1.0.11a Forge)

Affects both drums and super tanks.

Inserting fluid into a tank using buckets is fine. Extracting fluid with buckets is also fine _unless_ doing so would empty the drum/tank, then the fluid and the bucket get deleted.

The same thing happens with handheld tanks that contain more than one bucket of fluid, the final bit of fluid empties the drum/tank and deletes the held item.
