### ISSUE TITLE
Some tooltips are duplicated in the recipe viewer

### ISSUE THREAD

**Issue by Fuyukai** [GregTechCEu/GregTechCEu-1.19#293]
### GregTech CEu Version

1.0.11-build_141

### Recipe Viewer Installed

EMI

### Environment

singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

hovering over tooltips shows one tooltip

### Actual Behavior

hovering over tooltips shows two tooltips (twotips?)

### Steps to Reproduce

1) show usages for electric blast furnace 
2) hover over the actual EBF block in either the multiblock usages page, or the macerator page (for the invar dust recipe)
3) duplicate tooltip jumpscare

### Additional Information

screenshot on a clean instance:

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/8783751/f1b24840-93c2-4302-a201-7d06b08a9c7a)

on another instance, it shows up above it instead.

**Comment by Yefancy** [comment]
fixed in the 1.0.11 release

**Comment by Fuyukai** [comment]
... but this is the 1.0.11 release. the latest tagged build.

**Comment by Yefancy** [comment]
I mean modrinth + cf release
