### ISSUE TITLE
Fails to load with Continuity. Removing either loads normally.

### ISSUE THREAD

**Issue by RamielV** [GregTechCEu/GregTechCEu-1.19#295]
### GregTech CEu Version

1.20.1-1.0.11-fabric

### Recipe Viewer Installed

None

### Environment

singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

Normal launch

### Actual Behavior

Game crashes on startup

### Steps to Reproduce

Install continuity, fabricAPI and gregtech
[crash-2023-08-13_19.31.43-client.txt](https://github.com/GregTechCEu/GregTech-Modern/files/12329938/crash-2023-08-13_19.31.43-client.txt)
[latest.log](https://github.com/GregTechCEu/GregTech-Modern/files/12329940/latest.log)

**Comment by Fuyukai** [comment]
#222
