### ISSUE TITLE
Broken Block Breaking Animation

### ISSUE THREAD

**Issue by whatthedrunk** [GregTechCEu/GregTechCEu-1.19#299]
### GregTech CEu Version

gtceu-forge-1.20.1-1.0.11

### Recipe Viewer Installed

JEI

### Environment

All

### Cross-Mod Interaction

Unsure

### Expected Behavior

When breaking blocks in minecraft there is a breaking animation overlay.

### Actual Behavior

The animation does not happen but the blocks still break fine. 

### Steps to Reproduce

Download 0.0.51 of ATM9 and update Gregtech to the newest version. 
gtceu-forge-1.20.1-1.0.8.a - Works as expected.
gtceu-forge-1.20.1-1.0.11 - Does not work as expected.

### Additional Information

I tried removing Rubidium and Oculus to see if that would fix it and it was still broken.

**Comment by screret** [comment]
I feel like this is a case of incompat with some other mod and the veinmining display mixin

**Comment by aAndrew3030** [comment]
Would this be caused by the LDlib not being installed in this pack (if it is required?) Most of us are not installing the mod because it is not listed as a dependency anywhere
https://github.com/GregTechCEu/GregTech-Modern/issues/300
Whatthedrunk, maybe you could test with ldlib installed to see it is fixes the problems with various animations?

**Comment by screret** [comment]
> Would this be caused by the LDlib not being installed in this pack (if it is required?) Most of us are not installing the mod because it is not listed as a dependency anywhere #300 Whatthedrunk, maybe you could test with ldlib installed to see it is fixes the problems with various animations?

LDLib is bundled in gt, and a required dependency.

**Comment by loving2** [comment]
The blocks from GT show the block breaking animation just fine, but the other blocks from various mods and vanilla I've tried do not have the breaking animation.

**Comment by aAndrew3030** [comment]
Sorry, I was confused since it is also a separate mod

**Comment by LuminaSapphira** [comment]
This only occurs on Forge, and occurs even when GTCEu Modern is the only mod installed. The issue starts with 1.0.9, and 1.0.8a is unaffected.
