### ISSUE TITLE
Possible "A feature cycle was found" when generating world

### ISSUE THREAD

**Issue by ChromaPIE** [GregTechCEu/GregTechCEu-1.19#301]
### GregTech CEu Version

1.0.11, Fabric 1.20.1

### Recipe Viewer Installed

REI

### Environment

Singleplayer. Tried server-side but somehow the server's never bothered by it while generating new worlds.

### Cross-Mod Interaction

Yes

### Expected Behavior

World generation causes no crash nor freeze.

### Actual Behavior

See Additional Information for log and crash report.

World generation **sometimes**, not everytime, causes crash or freeze. Possibly caused by conflicts among GTCEu and one or more mods while generating features.

### Steps to Reproduce

All mods in the modlist shown in the log that generates stuff in the world are suspected.

1) Having these mods installed
2) Launch the game, try to create a new world
3) Boom

### Additional Information

Log: https://mclo.gs/uhsJ60q

CR: https://mclo.gs/K8uTOuA

I use [Cyanide](https://modrinth.com/mod/cyanide) that might help with the diagnosis.

**Comment by screret** [comment]
does this still happen?

**Comment by ChromaPIE** [comment]
I've been playing in multiplayer since then so no idea. I'll try creating couple new worlds later today to see how it goes tho.

**Comment by ChromaPIE** [comment]
yea still here unfortunately. my first try was okay, got into the world, walked around a bit until the voice in my brain forced me to try one more time. boom. frozen game.

Log: https://mclo.gs/OPyUfDh

**Comment by ChromaPIE** [comment]
Dunno if the latest update was to fix this issue but yes this issue still happens with the latest GTCEu 1.0.12.
CR this time: https://mclo.gs/jnEO1Io

**Comment by ChromaPIE** [comment]
1.0.12.b reproduced
