### ISSUE TITLE
Wafer Synthesis Problems in Advanced Integrated Circuit

### ISSUE THREAD

**Issue by huanledoudizhu** [GregTechCEu/GregTechCEu-1.19#303]
### GregTech CEu Version

gtceu-forge-1.20.1-1.0.10

### Recipe Viewer Installed

JEI

### Environment

Dedicated Serc

### Cross-Mod Interaction

Yes

### Expected Behavior

If it is really a synthetic formula issue, please check if there is a bug.

### Actual Behavior

When I was trying to synthesize the mv circuit assembler, I found that in this synthesis table, the Ilc chip and ram chip of the advanced integrated circuit needed to be synthesized, which required the use of ilc wafer and ram wafer. However, the synthesis of ilc wafer and ram wafer required red glass lens and green glass lens, which required the use of hv chemical bath. However, the production of it also required the use of advanced integrated circuit, resulting in a dead cycle.
![1](https://github.com/GregTechCEu/GregTech-Modern/assets/32981977/765b1604-12ed-4dc3-bcbc-c638945e76a1)
![2](https://github.com/GregTechCEu/GregTech-Modern/assets/32981977/2c05d280-ab30-44a5-8172-9a90c4fcc56d)
![3](https://github.com/GregTechCEu/GregTech-Modern/assets/32981977/c200eb06-7313-43a3-bbb7-5416ea7cc62f)
![4](https://github.com/GregTechCEu/GregTech-Modern/assets/32981977/7827a471-581d-4314-8c25-1e9e6bb66891)
![5](https://github.com/GregTechCEu/GregTech-Modern/assets/32981977/b08bf251-2992-45ce-b1a5-679205ebd395)
![6](https://github.com/GregTechCEu/GregTech-Modern/assets/32981977/2540b228-e503-4086-a352-6d1eb45098a0)

### Steps to Reproduce

This is a recipe issue.

### Additional Information

None

**Comment by Yefancy** [comment]
it got fixed.

**Comment by huanledoudizhu** [comment]
Is it in the gtceu orge-1.20.1-1.0.10 version or in subsequent versions? How can I download the repaired version.

**Comment by Yefancy** [comment]
1.0.11+, but 1.0.11 has a serious bug. we are preparing for 1.0.11.a. it will be released today

**Comment by huanledoudizhu** [comment]
OK.Thank you very much for your answer.
:)
