### ISSUE TITLE
Game crashes loading a world

### ISSUE THREAD

**Issue by NepJr** [GregTechCEu/GregTechCEu-1.19#306]
### GregTech CEu Version

1.19.2-1.0.11a-fabric

### Recipe Viewer Installed

No Recipe Viewer

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Expected Behavior

The game loads the world

### Actual Behavior

The game crashes

### Steps to Reproduce

Load the fabric version of the mod and load a world

### Additional Information

Crash log of the game: https://pastebin.com/ZUWn4BZn

**Comment by Yefancy** [comment]
its really weird, it seems that forge_port_lib is incompatible with the fabric rendering api. could you try to use fabric loader0.14.21 and fabric api 0.76.0 to see if it works? 
At first glance, its not a bug of gtceu, but of the forge port lib.
