### ISSUE TITLE
Crash, when looking at Multiblock Info in JEI

### ISSUE THREAD

**Issue by sreny1** [GregTechCEu/GregTechCEu-1.19#317]
### GregTech CEu Version

1.0.11.a

### Recipe Viewer Installed

JEI

### Environment

Dedicated Server

### Cross-Mod Interaction

Unsure

### Expected Behavior

Not Crash

### Actual Behavior

Client Crashes when looking at the Multiblock Info and clicking through the different Shapes of the Multiblock (P:0 Button) or just clicking the blocks to see what blocks can go in that position.

Note: it happens alot faster with Rubidium + addon mods
without Rubidium that Tab is smoother and takes alot more clicks to crash

### Steps to Reproduce

1. Open the Multiblock Info Tab in JEI
2. Click on different blocks until the client freezes for a second and then crashes

### Additional Information

Crash log with Rubidium:
https://mclo.gs/3daCLDh

Crash log without Rubidium:
https://mclo.gs/MdzqpXQ

**Comment by screret** [comment]
#313
