### ISSUE TITLE
All item/fluid passthrough hatches (besides EV) have no recipes

### ISSUE THREAD

**Issue by Arochio** [GregTechCEu/GregTechCEu-1.19#319]
### GregTech CEu Version

1.0.11

### Recipe Viewer Installed

JEI

### Environment

Dedicated Server

### Cross-Mod Interaction

Yes

### Expected Behavior

Expected passthrough hatches to have recipes in JEI

### Actual Behavior

no recipes in JEI

### Steps to Reproduce

1) search passthrough hatches in jei
2) no recipes (besides EV)

**Comment by screret** [comment]
...I _think_ only the HV one is supposed to exist at all...

**Comment by screret** [comment]
noting here: don't not register the other ones in case a pack dev wants to add recipes for those.

**Comment by screret** [comment]
> noting here: don't not register the other ones in case a pack dev wants to add recipes for those.

ok cancel that, removing them.
