### ISSUE TITLE
Incompatibility with KubeJS 2001.6.2-build.8

### ISSUE THREAD

**Issue by Afrocntrik** [GregTechCEu/GregTechCEu-1.19#320]
### GregTech CEu Version

1.0.11.a

### Recipe Viewer Installed

REI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

Be able to create a singleplayer game.

### Actual Behavior

When trying to go to the create world screen or singleplayer screen the game crashes.

### Steps to Reproduce

Launch Minecraft
Go to Singleplayer Screen
Game Crashes

KubeJS-2001.6.2-build.8 & Rhino 2001.2.2-build.4

### Additional Information

https://gist.github.com/Afrocntrik/e292241690341962659e4ea525b483e8
[latest.log](https://github.com/KubeJS-Mods/KubeJS/files/12444323/latest.log)

**Comment by screret** [comment]
KJS isn't even out yet...

**Comment by Afrocntrik** [comment]
Bug Post 
https://github.com/KubeJS-Mods/KubeJS/issues/691
Dev Builds
https://kubejs.com/downloads/dev-builds

**Comment by Afrocntrik** [comment]
> KJS isn't even out yet...

Dev Builds
https://kubejs.com/downloads/dev-builds

Bug Post 
https://github.com/KubeJS-Mods/KubeJS/issues/691
Specific Comment from a Main Contributor
https://github.com/KubeJS-Mods/KubeJS/issues/691#issuecomment-1694101212

**Comment by in1t1a1** [comment]
On NeoForge, stop at dispatching CONSTRUCT while loading the game

**Comment by whyareyoulookingatthis** [comment]
[crash-2023-09-03_13.57.36-client.txt](https://github.com/GregTechCEu/GregTech-Modern/files/12507613/crash-2023-09-03_13.57.36-client.txt)
Still happens on KubeJS Build 18 and Rhino Build 6.
On fabric the game will crash when clicking 'singleplayer' for the first time, but on quilt the game crashes during startup.

**Comment by screret** [comment]
#323 would fix this IF SOMEONE MERGED IT
