### ISSUE TITLE
steam boilers arent Producing Steam

### ISSUE THREAD

**Issue by FunkyPotao** [GregTechCEu/GregTechCEu-1.19#321]
### GregTech CEu Version

 1.0.11.a-build_153 (forge)

### Recipe Viewer Installed

JEI

### Environment

Singleplayer, Superflat

### Cross-Mod Interaction

No

### Expected Behavior

I expect steam boilers to consume Fuel in order to produce Steam

### Actual Behavior

The Steam Boilers consumed Fuel without any output

![2023-08-26_09 29 27](https://github.com/GregTechCEu/GregTech-Modern/assets/108956899/3a03a409-a641-4ce5-bda5-757b299ec76c)

![2023-08-26_09 33 42](https://github.com/GregTechCEu/GregTech-Modern/assets/108956899/03462d64-c14e-4b51-8f2b-0db9174a075b)

### Steps to Reproduce

Get any steam boiler then power it with its needed fuel

### Additional Information

even Jei shows that Steam boilers produce nothing

**Comment by Schrubbls** [comment]
See the red bar? On the right hand side?

It gonna heat up first to a certain temperature to produce steam or does not not produce steam after heating up?
Also do you provide it with water?

**Comment by Yefancy** [comment]
as schrubbls said, you need water and wait for heating up. besides, the highter heat it has the highter prouction rate you get.  you can reopen it if it still doesn;t work.

**Comment by FunkyPotao** [comment]
omfg im such an idiot thanks for telling me
