### ISSUE TITLE
Stone Maceration outputs 9 Stone Dust, while Cobblestone Maceration outputs 1.

### ISSUE THREAD

**Issue by Praetorian6478** [GregTechCEu/GregTechCEu-1.19#322]
### GregTech CEu Version

gtceu-forge-1.20.1-1.0.11.a.jar

### Recipe Viewer Installed

JEI

### Environment

Dedicated Server and Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

Both Recepies are supposed to output 1 Stone Dust. 

### Actual Behavior

Stone maceration also takes 44.10 seconds to finish.

![a1](https://github.com/GregTechCEu/GregTech-Modern/assets/140976294/f56550d9-8ff8-4fbc-8d1d-7bca2f3d6875)
![a2](https://github.com/GregTechCEu/GregTech-Modern/assets/140976294/b97c3fa7-ca49-499d-85a9-558de2988684)

### Steps to Reproduce

1. Place any tier of Macerator
2. Put Stone block inside
3. Macerator makes 9 dust.

### Additional Information

Is this supposed to be so, or is this a bug?

**Comment by screret** [comment]
this is definetly a bug

**Comment by KP2048** [comment]
i mean stone duping isn't exactly unheard of in minecraft lol, but should probably be fixed
