### ISSUE TITLE
Bucketing fluids into tanks deletes bucket

### ISSUE THREAD

**Issue by aAndrew3030** [GregTechCEu/GregTechCEu-1.19#327]
### GregTech CEu Version

1.0.11.a

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Expected Behavior

In a test world, while trying to figure out this issue
https://github.com/AllTheMods/ATM-9/issues/299
I found that buckets are deleted when adding fluid to a tank (super tank 1 in this case)

### Actual Behavior

-

### Steps to Reproduce

-

**Comment by mikerooni** [comment]
Related to #290, probably the same cause

**Comment by Yefancy** [comment]
fixed in dev
