### ISSUE TITLE
Gregtech 5u-like Replicators and UU-matter

### ISSUE THREAD

**Issue by Praetorian6478** [GregTechCEu/GregTechCEu-1.19#346]
### Feature Description

Adding Replication Chains, and UU-matter Recipe.

There was an interesting system you could've set up for getting plasma, in the past-mid-game. Replicating Beryllium(which is realtively cheap), and getting it fused with Deuterium made Nitrogen Plasma, which was a pretty decent Plasma Turbine Fuel. Replication in general was a pleasing technological milestone, which can boost progression in the near-endgame.

**Comment by screret** [comment]
i believe UU-matter isn't happening.
someone may (ask to) reopen this issue if/when that statement changes.
