### ISSUE TITLE
GT 1.20 crashes on loading world

### ISSUE THREAD

**Issue by whyareyoulookingatthis** [GregTechCEu/GregTechCEu-1.19#347]
### GregTech CEu Version

1.0.11.a-build_158

### Recipe Viewer Installed

No Recipe Viewer

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Expected Behavior

Expected to be able to create a new world in singleplayer.

### Actual Behavior

The game crashes before opening the world setting page.

### Steps to Reproduce

1) Install GregTechCEu build 1.0.11.a-build_158
2) Launch Minecraft
3) Click Singleplayer

The game will crash before loading the world settings page

### Additional Information

This issue acts the exact same as the KubeJS incompatibility did in previous 1.20 builds.
You can't load an existing world either; minecraft asks you to use the 'safe mode' datapack and then declares the world as corrupted when it isn't.

Using Fabric API 0.88.1+1.20.1 and Fabric Loader 0.14.22

**Comment by in1t1a1** [comment]
https://mclo.gs/YOeEY9O
