### ISSUE TITLE
Hermetic Casing II; no recipe?

### ISSUE THREAD

**Issue by 34486** [GregTechCEu/GregTechCEu-1.19#356]
### GregTech CEu Version

1.0.11b-166

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

I expected "gtceu:mv_hermetic_casing"/Hermetic Casing II to have recipe. 

### Actual Behavior

I go to check the recipe for the casing, and nothing shows up. I do not know recipe so I also do not know if it can currently be crafted, I would assume not though..? 

### Steps to Reproduce

Check recipe of the Hermetic Casing II with JEI, nothing shows.

### Additional Information

thx

**Comment by 34486** [comment]
Passthrough hatches except for EV ones are also missing their recipe, is this just still undetermined/wip/changed stuff?

**Comment by screret** [comment]
only HV passthrough hatch should exist i believe...

**Comment by 34486** [comment]
o idk all of them show up, hv does not has recipe tho!1!1

**Comment by screret** [comment]
oh wait sorry the fix is in a branch that has issues
