### ISSUE TITLE
Shift-Click Items into Machines does not start the recipe

### ISSUE THREAD

**Issue by Raccoon2709** [GregTechCEu/GregTechCEu-1.19#357]
### GregTech CEu Version

GregTechCEu 1.19.2-1.0.11.b-forge

### Recipe Viewer Installed

REI

### Environment

SP

### Cross-Mod Interaction

No

### Expected Behavior

After feeding the machine with its required items to fullfill the recipe it starts.

### Actual Behavior

When shift-click feeding the machine with its items it does not start and you have to drag & drop the item again to "update" it.

### Steps to Reproduce

It does not always work but when unloading the chunk and join the chunk and interact with the machine and shift click ingredients it does not start up even if full powered.

### Additional Information

secret said it might be that the machine does not update when shift clicking the ingredients

**Comment by Yefancy** [comment]
~its a ldlib bug since I reworked the transport system few weeks ago, I will fix it latter~

**Comment by Yefancy** [comment]
could you send me a vid?

**Comment by Phoupraw** [comment]
So this bug happens both on forge and fabric, REI and EMI.
