### ISSUE TITLE
NullPointerException when accessing MachineDefinition.asStack() in GTCreativeModeTabs

### ISSUE THREAD

**Issue by pen787** [GregTechCEu/GregTechCEu-1.19#358]
### GregTech CEu Version

1.0.1.1.b-build_171

### Recipe Viewer Installed

REI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

Not Crash.

### Actual Behavior

Crash when open the gregtech machine creative tab.

### Steps to Reproduce

1. Open the gregtech machine creative tabs.

### Additional Information

[Crash log](https://crashy.net/e069065d-1e6f-49f6-b3b9-738a36a0add5)

**Comment by magcicada** [comment]
this issue will happen on all latest versions

**Comment by magcicada** [comment]
Just change https://github.com/GregTechCEu/GregTech-Modern/blob/b75fec610ff6489cbcd51ae9aabcdee2f478a7c6/common/src/main/java/com/gregtechceu/gtceu/common/data/GTCreativeModeTabs.java#L24 this line to
public static LDLItemGroup MACHINE = new LDLItemGroup(GTCEu.MOD_ID, "machine", () -> GTMachines.ELECTROLYZER[LV].asStack());

**Comment by screret** [comment]
I knew i missed something when doing that change.
closed by #359 (once i commit the fix)

**Comment by screret** [comment]
sorry i attached the closing to the wrong PR, actual fix coming soon

**Comment by magcicada** [comment]
Still get this crash when https://github.com/GregTechCEu/GregTech-Modern/pull/359 merged, need put a fix at here:
https://github.com/GregTechCEu/GregTech-Modern/blob/b75fec610ff6489cbcd51ae9aabcdee2f478a7c6/common/src/main/java/com/gregtechceu/gtceu/common/data/GTCreativeModeTabs.java#L24
@screret

**Comment by screret** [comment]
as i said, i did the fix
and then i marked the wrong PR as closing.
