### ISSUE TITLE
[ATM9 - 0.0.67] Crash when attempting to modify fluid pump cover module

### ISSUE THREAD

**Issue by Cattman423** [GregTechCEu/GregTechCEu-1.19#360]
### GregTech CEu Version

1.0.11

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

I was attempting to use a fluid pump cover to pull fluids out of a machine. I attempted to use both a screwdriver, and the machine's own GUI, both had the same effect

### Actual Behavior

Instead of being able to adjust the fluid pump's settings, the game crashed

### Steps to Reproduce

The first two times experienced this crash the pump was on a bronze fluid pipe, the third time I was using the cover settings GUI on a Super Tank 1. I attempted to recreate the crash with a conveyer module, however that worked as intended. The fourth crash was attempting to adjust an MV pump cover module on an MV ore washer via the ore washer's GUI. I have not tried anything else at this time.

Crash report 1;
[crash-2023-09-10_14.11.33-server.txt](https://github.com/AllTheMods/ATM-9/files/12570845/crash-2023-09-10_14.11.33-server.txt)

Crash report 2;
[crash-2023-09-10_14.40.09-server.txt](https://github.com/AllTheMods/ATM-9/files/12570847/crash-2023-09-10_14.40.09-server.txt)

Crash report 3;
[crash-2023-09-10_15.01.17-client.txt](https://github.com/AllTheMods/ATM-9/files/12570848/crash-2023-09-10_15.01.17-client.txt)

Crash report 4;
[crash-2023-09-10_15.06.53-client.txt](https://github.com/AllTheMods/ATM-9/files/12570849/crash-2023-09-10_15.06.53-client.txt)

### Additional Information

I sent a copy of this bug report to the ATM9 dev team.

Crash report 1;
[crash-2023-09-10_14.11.33-server.txt](https://github.com/GregTechCEu/GregTech-Modern/files/12570873/crash-2023-09-10_14.11.33-server.txt)

Crash report 2;
[crash-2023-09-10_14.40.09-server.txt](https://github.com/GregTechCEu/GregTech-Modern/files/12570874/crash-2023-09-10_14.40.09-server.txt)

Crash report 3;
[crash-2023-09-10_15.01.17-client.txt](https://github.com/GregTechCEu/GregTech-Modern/files/12570875/crash-2023-09-10_15.01.17-client.txt)

Crash report 4;
[crash-2023-09-10_15.06.53-client.txt](https://github.com/GregTechCEu/GregTech-Modern/files/12570876/crash-2023-09-10_15.06.53-client.txt)

**Comment by Yefancy** [comment]
it got fixed in the latest gtm, ask ATM to bump it up
