### ISSUE TITLE
Fluid pipes cannot be correctly broke by wrenches when require GTCEu tool config is true.

### ISSUE THREAD

**Issue by ccpemily** [GregTechCEu/GregTechCEu-1.19#362]
### GregTech CEu Version

1.20.1-1.0.11b

### Recipe Viewer Installed

JEI

### Environment

SSP/Open to LAN

### Cross-Mod Interaction

No

### Expected Behavior

Bronze fluid pipes should be able to break using bronze wrench.

### Actual Behavior

Any GTCEu tools cannot accelerate breaking bronze fluid pipe, and TOP indicates that they are not the suitable tool at all.

### Steps to Reproduce

1) enter survival mode
2) place a bronze fluid pipe
3) try to break it with a wrench

### Additional Information

As I discovered many issues about tools (such as the pickaxe level of GTCEu tools is not correct, even HSS-E pickaxe cannot break diamond ore), this issue is highly related to commonly bug in current tool's implementations.

**Comment by screret** [comment]
does this still happen?

**Comment by ccpemily** [comment]
It now works well in version 1.0.12f. Thanks for fixing that
