### ISSUE TITLE
Remove making new TagPrefix in KubeJS

### ISSUE THREAD

**Issue by TheAlaskanPhysicist** [GregTechCEu/GregTechCEu-1.19#377]
### Feature Description

It makes the code almost unreadable and much slower than if it was done explicitly.
If someone wants to make a new TagPrefix, they should make an addon for GT, not KubeJS it.

**Comment by screret** [comment]
Wtf.

**Comment by screret** [comment]
y' know, I didn't want to force everyone to make an addon in order to add new stonetypes for GT ores.
so I added that feature.
what part of it is "almost unreadable" to you?

**Comment by TheAlaskanPhysicist** [comment]
The for loop over the tag prefixes and then the hidden if conditions everywhere, in my opinion, is not good for comprehension. It would still be possible for making new stonetypes, but for things where an entirely new TagPrefix is made that's an item, it would have to be initialized by the user, because otherwise the code for it is a pain in the ass.

**Comment by mikerooni** [comment]
Got a before/after example for this?
