### ISSUE TITLE
Processing Arrays all stuck on gtceu.dummy machine mode

### ISSUE THREAD

**Issue by loving2** [GregTechCEu/GregTechCEu-1.19#378]
### GregTech CEu Version

gtceu-forge-1.20.1-1.0.12

### Recipe Viewer Installed

JEI

### Environment

Dedicated Server

### Cross-Mod Interaction

No

### Expected Behavior

Inserting a machine into a PA should set the machine mode to that machine, as it did in prior versions

### Actual Behavior

The PA stays on machine mode gtceu.dummy as if nothing were in the controller

### Steps to Reproduce

Build a PA
Insert any machine into it
Notice that the machine mode stays 'gtceu.dummy' and cannot process any recipe

**Comment by screret** [comment]
did you try selecting a mode in the new widget? that might now be required
the image for it is a robot arm

**Comment by loving2** [comment]
I do not see a widget for that
![2023-09-16 09_40_48-Window](https://github.com/GregTechCEu/GregTech-Modern/assets/26778483/44c0195d-fe8a-40de-b4db-eb60db5dc87f)
