### ISSUE TITLE
Block changes direction when connecting directly to same other block???

### ISSUE THREAD

**Issue by 34486** [GregTechCEu/GregTechCEu-1.19#380]
### GregTech CEu Version

176

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

No rotation of block????????

### Actual Behavior

So I placed two or more of the same combustion generator next to each other and the top texture rotated on its own but the function is no different. I don't know if this is something that COULD cause issues in the future or not, but just figured it was strange. If I place two of different tier combustion generators together, it will not do that. 

### Steps to Reproduce

Place generators next to each other, then apart. See difference. 

### Additional Information

![2023-09-16_18 40 38](https://github.com/GregTechCEu/GregTech-Modern/assets/19638851/26c66d87-c8e4-4cb8-9af8-7de2b54bb0fe)
![2023-09-16_18 40 48](https://github.com/GregTechCEu/GregTech-Modern/assets/19638851/0ba46fa9-4a45-4074-80f7-0ad92142bc4c)
![2023-09-16_18 40 50](https://github.com/GregTechCEu/GregTech-Modern/assets/19638851/1a0a03aa-0484-4fb7-99ee-a789f41f2a15)

I don't think this is a severe issue but I hope it can not lead to other issues later down so I feel maybe investigate?

**Comment by screret** [comment]
narrator:
> it, in fact, has lead to another issue down the line.
