### ISSUE TITLE
After updating mining hammer is not working

### ISSUE THREAD

**Issue by adumbrali** [GregTechCEu/GregTechCEu-1.19#391]
### GregTech CEu Version

1.19.2-1.0.12.c-fabric

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Expected Behavior

Mining hammer mines a 3x3 area.

### Actual Behavior

Mining hammer is no longer a mining tool. (And if a block cracks, it will crash.)

### Steps to Reproduce

Update from 1.19.2-1.0.12.b to 1.19.2-1.0.12.c

**Comment by screret** [comment]
does this still happen?

**Comment by adumbrali** [comment]
fixed
