### ISSUE TITLE
Fluid Solidifier slot order inverted

### ISSUE THREAD

**Issue by Leclowndu93150** [GregTechCEu/GregTechCEu-1.19#399]
### GregTech CEu Version

all of them

### Recipe Viewer Installed

REI

### Environment

sp

### Cross-Mod Interaction

No

### Expected Behavior

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/73310949/2bb4805d-5af9-475b-8789-c9c631a00d33)

### Actual Behavior

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/73310949/da024ec6-af3f-48fc-bb9f-7de66292f6d9)

### Steps to Reproduce

no need to reproduce it

**Comment by screret** [comment]
does this really matter tho?

**Comment by Leclowndu93150** [comment]
> does this really matter tho?

normally you will put the fluid into the mold then it solidifies, like the arrow says  and not put the mold into the fluid 💀

**Comment by screret** [comment]
If you really need a custom UI for **this**, then make it.
