### ISSUE TITLE
[Fabric] [1.19.2] Adding CraftTweaker will generate endless logs.

### ISSUE THREAD

**Issue by adumbrali** [GregTechCEu/GregTechCEu-1.19#413]
### GregTech CEu Version

1.19.2-1.0.12.e-fabric

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

The mod should load successfully.

### Actual Behavior

It generates endless logs and affects the entire game.

### Steps to Reproduce

1. Add CraftTweaker, Ingredient Extension API(required), GregTechCEu to the Mods folder and start Minecraft.
2. You get endless logs when you create a world.

### Additional Information

What actually having trouble with is the Ingredient Extension API and GregTechCEu.
The game never crashes.
However, this bug may cause the machine to lose functionality.
In my environment, the item liquid energy inside the machine was lost every time I entered the world.

Since a crash report is not created, the latest.log is attached.
[latest.log](https://github.com/GregTechCEu/GregTech-Modern/files/12707419/latest.log)

**Comment by NemEzanevem** [comment]
Please dont use Crafttweaker its not supported and it wont be...
If you want to modify recipes use Kubejs

**Comment by adumbrali** [comment]
thank you
