### ISSUE TITLE
Large Steam Boilers do not work correctly.

### ISSUE THREAD

**Issue by ccpemily** [GregTechCEu/GregTechCEu-1.19#414]
### GregTech CEu Version

1.20.1-1.0.12e

### Recipe Viewer Installed

JEI

### Environment

SSP/Open to LAN

### Cross-Mod Interaction

No

### Expected Behavior

Large Boilers should consume water or distilled water and fuel then output steam.

### Actual Behavior

Boilers only consume fuel and output dusts in Shuffling chamber, no water consuming or steam output anywhere, the same in JEI's recipes. The max temperature of boilers also not correct, as they all reach 200000+ degrees.

### Steps to Reproduce

Build a large steam boiler of any tier, then put some fuel into its input hatch.

**Comment by mikerooni** [comment]
Wait, don't close this one yet please. I didn't get to fix the temperature yet in my last PR ^^
