### ISSUE TITLE
EMI+JEI cannot work properly on 1.20.1-neoforge.

### ISSUE THREAD

**Issue by Arborsm** [GregTechCEu/GregTechCEu-1.19#415]
### GregTech CEu Version

gtceu-forge-1.20.1-1.0.12.e

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

When I press R/U/mouse button on an item in the EMI, it should point to the corresponding recipe.

### Actual Behavior

Nothing.

### Steps to Reproduce

1) Installing JEI+EMI+GTM.
2) You get it.

### Additional Information

This might be caused by the EMI integration, I compiled a version without JEI integration and still got this error, on the contrary, without EMI integration, it could not display properly but did not have this problem. On 1.19.2, this problem dont occur either.

**Comment by MasterSparkInYourFace** [comment]
if you run /reload, the GTCEu recipe plugin should run and register everything properly. I have no clue why this is happening as it _should_ just load when first entering the world.

I actually had this issue with both EMI and REI on forge and 1.20.1 running GT 1.0.12e.

**Comment by Arborsm** [comment]
> if you run /reload, the GTCEu recipe plugin should run and register everything properly. I have no clue why this is happening as it _should_ just load when first entering the world.
> 
> I actually had this issue with both EMI and REI on forge and 1.20.1 running GT 1.0.12e.

I tried,but it seems not work for me?

**Comment by MasterSparkInYourFace** [comment]
which version of forge are you running? switching to 47.2.0 seemed to fix things for me.

I suppose it should also be noted that in my case, GTCEu failed to register any recipes at all until I ran /reload (nothing showed up in `/recipe give @s` under `gtceu:`).

I'll update here if I run into more issues

**Comment by Arborsm** [comment]
> which version of forge are you running? switching to 47.2.0 seemed to fix things for me.
> 
> I suppose it should also be noted that in my case, GTCEu failed to register any recipes at all until I ran /reload (nothing showed up in `/recipe give @s` under `gtceu:`).
> 
> I'll update here if I run into more issues

Still,and maybe you dont have the same problem as me,my game has items and recipes,but I cannot use the shortcut key to go to the recipe corresponding to an item when I install both EMI and JEI.Additionally,installing only EMI/REI/JEI will not cause any problems

**Comment by Arborsm** [comment]
> which version of forge are you running? switching to 47.2.0 seemed to fix things for me.
> 
> I suppose it should also be noted that in my case, GTCEu failed to register any recipes at all until I ran /reload (nothing showed up in `/recipe give @s` under `gtceu:`).
> 
> I'll update here if I run into more issues

I want to install EMI and JEI at the same time because there are fewer compatible recipes in ForgeEmi, and I need to install JEI to make up for the missing recipes.

**Comment by TacoMonkey11** [comment]
Can reproduce this issue on 1.20.1 fabric

edit: removing JEI fixes the issue, allowing EMI to display the recipes
