### ISSUE TITLE
Crash on load with create-1.20.1-0.5.1.e.jar installed

### ISSUE THREAD

**Issue by skybix** [GregTechCEu/GregTechCEu-1.19#423]
### GregTech CEu Version

gtceu-forge-1.20.1-1.0.12.f.jar

### Recipe Viewer Installed

JEI

### Environment

singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

Load the game.

### Actual Behavior

game crashes

### Steps to Reproduce

update create to create-1.20.1-0.5.1.e.jar 
run game
crash

### Additional Information

crash report: https://pastebin.com/C8WShMjg
latest log: https://pastebin.com/Rw0eY2km

**Comment by screret** [comment]
this isn't GT, this is create addition's fault
