### ISSUE TITLE
Machine controller cover only seems to work with vanilla redstone signal

### ISSUE THREAD

**Issue by hgjensen** [GregTechCEu/GregTechCEu-1.19#425]
### GregTech CEu Version

1.0.12.f

### Recipe Viewer Installed

JEI

### Environment

ATM9 server (private / only me)

### Cross-Mod Interaction

Yes

### Expected Behavior

Machine controller cover set to inverted mode, with threshold of 1, should turn the machine on when receiving any redstone signal.

### Actual Behavior

The machine persistently says "Working Disabled".

### Steps to Reproduce

1. Attach machine controller cover to any GT machine
2. Set cover set to inverted mode with threshold of 1 (default). I.e. "redstone on, machine on".
3. a) Attach AE2 level emitter pointing straight into the cover. Make level emitter emit signal.
    b) Place a LaserIO node with redstone card directly on the face of the GT machine with the controller cover, and make it emit a signal
    c) Place a Modular Router with a "Detector Module" pointing into the cover. Make the router emit a signal
4. The machine persistently says "Working Disabled".

When using a vanilla redstone dust between 3a/b/c and the cover, the machine works as expected.
When placing a vanilla lever on the cover, the machine works as expected.

**Comment by mikerooni** [comment]
That's odd. Probably something to do with weak and strong signals if I had to make a guess.

Not to myself:  
Test with different directions for vanilla levers, redstone pen & computercraft.

**Comment by hgjensen** [comment]
> That's odd. Probably something to do with weak and strong signals if I had to make a guess.
> 
> Not to myself: Test with different directions for vanilla levers, redstone pen & computercraft.

I tried both weak and strong signals, in both LaserIO and Modular Routers. Didn't make a difference.
