### ISSUE TITLE
Duplicated HSLA-Steel dust recipe (supposed to be watertightsteel)

### ISSUE THREAD

**Issue by Bosspc1234** [GregTechCEu/GregTechCEu-1.19#429]
### GregTech CEu Version

1.0.12.f

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Expected Behavior

There is no mixer recipe for watertightsteel dust. Due to it being duplicated of HSLA-Steel recipe.

### Actual Behavior

The lower recipe should result in watertightsteel dust

![2023-09-28_20 12 17-2](https://github.com/GregTechCEu/GregTech-Modern/assets/128601014/f5f3f279-8983-4e8b-83f0-c461f4610f01)

### Steps to Reproduce

None

**Comment by screret** [comment]
will be fixed very soon
