### ISSUE TITLE
(GTM_1.0.12f_1.19.2)The custom GTorevein previously created with kubejs is invalid in the new version

### ISSUE THREAD

**Issue by tsubfak13** [GregTechCEu/GregTechCEu-1.19#432]
### GregTech CEu Version

1.0.12f

### Recipe Viewer Installed

JEI

### Environment

sp

### Cross-Mod Interaction

Yes

### Expected Behavior

Generate GT-style veins in world.

### Actual Behavior

No custom ore veins are generated

### Steps to Reproduce

[orevein.txt](https://github.com/GregTechCEu/GregTech-Modern/files/12774526/orevein.txt)
**This is a kjs serverscript file, please change the file suffix to js**

**Comment by screret** [comment]
your script works fine for me?
