### ISSUE TITLE
Greg tech ceu crashes when nuclear craft is present

### ISSUE THREAD

**Issue by Imadethisaccformodadvice** [GregTechCEu/GregTechCEu-1.19#433]
### GregTech CEu Version

2.7.3

### Recipe Viewer Installed

JEI

### Environment

singleplayer / multiplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

launching normally

### Actual Behavior

---- Minecraft Crash Report ----

WARNING: coremods are present:
  GregTechLoadingPlugin (gregtech-1.12.2-2.6.0-beta.jar)
  LittlePatchingLoader (LittleTiles_v1.5.82_mc1.12.2.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.9.6-core.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  SignPictureCorePlugin (SignPicture-1.12.1-2.8.1-universal.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.78-core.jar)
  SecurityCraftLoadingPlugin ([1.12.2] SecurityCraft v1.9.7.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-2.0.0-17.jar)
  CreativePatchingLoader (CreativeCore_v1.10.71_mc1.12.2.jar)
  DCASMPlugin (HeatAndClimateLib_1.12.2-3.9.3.jar)
  ratscore (rats-3.2.14-1.12.2.jar)
  AE2ELCore (appliedenergistics2-rv6-stable-7-extended_life-v0.55.22.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 9/30/23 7:01 PM
Description: Initializing game

java.lang.NoClassDefFoundError: gregtech/api/recipes/CountableIngredient
	at nc.integration.gtce.GTCERecipeHelper.recipeMatches(GTCERecipeHelper.java:292)
	at nc.integration.gtce.GTCERecipeHelper.findByInputs(GTCERecipeHelper.java:283)
	at nc.integration.gtce.GTCERecipeHelper.findRecipe(GTCERecipeHelper.java:258)
	at nc.integration.gtce.GTCERecipeHelper.addGTCERecipe(GTCERecipeHelper.java:152)
	at nc.recipe.ProcessorRecipeHandler.addRecipe(ProcessorRecipeHandler.java:60)
	at nc.recipe.processor.ManufactoryRecipes.addRecipes(ManufactoryRecipes.java:30)
	at nc.recipe.ProcessorRecipeHandler.<init>(ProcessorRecipeHandler.java:36)
	at nc.recipe.ProcessorRecipeHandler.<init>(ProcessorRecipeHandler.java:26)
	at nc.recipe.processor.ManufactoryRecipes.<init>(ManufactoryRecipes.java:25)
	at nc.recipe.NCRecipes.registerRecipes(NCRecipes.java:84)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1242_NCRecipes_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:636)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: gregtech.api.recipes.CountableIngredient
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at nc.integration.gtce.GTCERecipeHelper.recipeMatches(GTCERecipeHelper.java:292)
	at nc.integration.gtce.GTCERecipeHelper.findByInputs(GTCERecipeHelper.java:283)
	at nc.integration.gtce.GTCERecipeHelper.findRecipe(GTCERecipeHelper.java:258)
	at nc.integration.gtce.GTCERecipeHelper.addGTCERecipe(GTCERecipeHelper.java:152)
	at nc.recipe.ProcessorRecipeHandler.addRecipe(ProcessorRecipeHandler.java:60)
	at nc.recipe.processor.ManufactoryRecipes.addRecipes(ManufactoryRecipes.java:30)
	at nc.recipe.ProcessorRecipeHandler.<init>(ProcessorRecipeHandler.java:36)
	at nc.recipe.ProcessorRecipeHandler.<init>(ProcessorRecipeHandler.java:26)
	at nc.recipe.processor.ManufactoryRecipes.<init>(ManufactoryRecipes.java:25)
	at nc.recipe.NCRecipes.registerRecipes(NCRecipes.java:84)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1242_NCRecipes_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:636)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2172151424 bytes (2071 MB) / 8137474048 bytes (7760 MB) up to 11244929024 bytes (10724 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12064m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_E3 121 mods loaded, 120 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version                             | Source                                                      | Signature                                |
	|:----- |:--------------------------------- |:----------------------------------- |:----------------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                         | 1.12.2                              | minecraft.jar                                               | None                                     |
	| LCH   | mcp                               | 9.42                                | minecraft.jar                                               | None                                     |
	| LCH   | FML                               | 8.0.99.99                           | forge-1.12.2-14.23.5.2860.jar                               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                             | 14.23.5.2860                        | forge-1.12.2-14.23.5.2860.jar                               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | creativecoredummy                 | 1.0.0                               | minecraft.jar                                               | None                                     |
	| LCH   | dcs_asm                           | 2.1.0                               | minecraft.jar                                               | 4cd12b92959105443b7b694fffe0cea9ed004886 |
	| LCH   | littletilescore                   | 1.0.0                               | minecraft.jar                                               | None                                     |
	| LCH   | obfuscate                         | 0.4.2                               | minecraft.jar                                               | None                                     |
	| LCH   | securitycraft                     | v1.9.7                              | [1.12.2] SecurityCraft v1.9.7.jar                           | None                                     |
	| LCH   | actuallyadditions                 | 1.12.2-r152                         | ActuallyAdditions-1.12.2-r152.jar                           | None                                     |
	| LCH   | buildcraftlib                     | 7.99.24.8                           | buildcraft-all-7.99.24.8.jar                                | None                                     |
	| LCH   | buildcraftcore                    | 7.99.24.8                           | buildcraft-all-7.99.24.8.jar                                | None                                     |
	| LCH   | buildcraftfactory                 | 7.99.24.8                           | buildcraft-all-7.99.24.8.jar                                | None                                     |
	| LCH   | buildcrafttransport               | 7.99.24.8                           | buildcraft-all-7.99.24.8.jar                                | None                                     |
	| LCH   | buildcraftsilicon                 | 7.99.24.8                           | buildcraft-all-7.99.24.8.jar                                | None                                     |
	| LCH   | additionalpipes                   | 6.0.0.8                             | additionalpipes-6.0.0.8.jar                                 | None                                     |
	| LCH   | additional_stuff                  | 0.1.1                               | additionalstuff-1.12.2-beta1.1.jar                          | None                                     |
	| LCH   | redstoneflux                      | 2.1.1                               | RedstoneFlux-1.12-2.1.1.1-universal.jar                     | None                                     |
	| LCH   | cofhcore                          | 4.6.6                               | CoFHCore-1.12.2-4.6.6.1-universal.jar                       | None                                     |
	| LCH   | libvulpes                         | 0.4.2.-25                           | LibVulpes-1.12.2-0.4.2-25-universal.jar                     | None                                     |
	| LCH   | advancedrocketry                  | 1.12.2-2.0.0-17                     | AdvancedRocketry-1.12.2-2.0.0-17.jar                        | None                                     |
	| LCH   | ctm                               | MC1.12.2-1.0.2.31                   | CTM-MC1.12.2-1.0.2.31.jar                                   | None                                     |
	| LCH   | appliedenergistics2               | rv6-stable-7-extended_life-v0.55.22 | appliedenergistics2-rv6-stable-7-extended_life-v0.55.22.jar | None                                     |
	| LCH   | aquaculture                       | 1.6.8                               | Aquaculture-1.12.2-1.6.8.jar                                | None                                     |
	| LCH   | dcs_lib                           | 3.9.3                               | HeatAndClimateLib_1.12.2-3.9.3.jar                          | 4cd12b92959105443b7b694fffe0cea9ed004886 |
	| LCH   | jei                               | 4.16.1.301                          | jei_1.12.2-4.16.1.301.jar                                   | None                                     |
	| LCH   | mekanism                          | 1.12.2-9.8.3.390                    | Mekanism-1.12.2-9.8.3.390.jar                               | None                                     |
	| LCH   | mekanismgenerators                | 1.12.2-9.8.3.390                    | MekanismGenerators-1.12.2-9.8.3.390.jar                     | None                                     |
	| LCH   | bfr                               | 1.0.5                               | BetterFusionReactor-1.12.2-1.0.5.jar                        | None                                     |
	| LCH   | bibliocraft                       | 2.4.6                               | BiblioCraft[v2.4.6][MC1.12.2].jar                           | None                                     |
	| LCH   | big_swords                        | 0.9.0                               | Big Swords R-1.12.2-0.9.0.jar                               | None                                     |
	| LCH   | biomesoplenty                     | 7.0.1.2445                          | BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar               | None                                     |
	| LCH   | buildcraftbuilders                | 7.99.24.8                           | buildcraft-all-7.99.24.8.jar                                | None                                     |
	| LCH   | buildcraftcompat                  | 7.99.24.8                           | buildcraft-all-7.99.24.8.jar                                | None                                     |
	| LCH   | buildcraftenergy                  | 7.99.24.8                           | buildcraft-all-7.99.24.8.jar                                | None                                     |
	| LCH   | buildcraftrobotics                | 7.99.24.8                           | buildcraft-all-7.99.24.8.jar                                | None                                     |
	| LCH   | bcfe                              | 1.1                                 | buildcraftfluxified-1.0.0.jar                               | None                                     |
	| LCH   | carryon                           | 1.12.3                              | carryon-1.12.2-1.12.7.23.jar                                | None                                     |
	| LCH   | chisel                            | MC1.12.2-1.0.2.45                   | Chisel-MC1.12.2-1.0.2.45.jar                                | None                                     |
	| LCH   | codechickenlib                    | 3.2.3.358                           | CodeChickenLib-1.12.2-3.2.3.358-universal.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | cofhworld                         | 1.4.0                               | CoFHWorld-1.12.2-1.4.0.1-universal.jar                      | None                                     |
	| LCH   | toughasnails                      | 3.1.0.139                           | ToughAsNails-1.12.2-3.1.0.139-universal.jar                 | None                                     |
	| LCH   | comforts                          | 1.4.1.3                             | comforts-1.12.2-1.4.1.3.jar                                 | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCH   | extendedrenderer                  | v1.0                                | coroutil-1.12.1-1.2.37.jar                                  | None                                     |
	| LCH   | coroutil                          | 1.12.1-1.2.37                       | coroutil-1.12.1-1.2.37.jar                                  | None                                     |
	| LCH   | configmod                         | v1.0                                | coroutil-1.12.1-1.2.37.jar                                  | None                                     |
	| LCH   | corpse                            | 1.12.2-1.0.8                        | corpse-1.12.2-1.0.8.jar                                     | None                                     |
	| LCH   | cosmeticarmorreworked             | 1.12.2-v5a                          | CosmeticArmorReworked-1.12.2-v5a.jar                        | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCH   | craftingex                        | 1.2.0                               | CraftingEX_1.12-v1.2.0.jar                                  | None                                     |
	| LCH   | craftstudioapi                    | 1.0.0                               | CraftStudio-1.0.0.93-mc1.12-alpha.jar                       | None                                     |
	| LCH   | creativecore                      | 1.10.0                              | CreativeCore_v1.10.71_mc1.12.2.jar                          | None                                     |
	| LCH   | cucumber                          | 1.1.3                               | Cucumber-1.12.2-1.1.3.jar                                   | None                                     |
	| LCH   | cyberware                         | 0.2.11.29                           | cyberware-1.12.2-0.2.11.29.jar                              | None                                     |
	| LCH   | patchouli                         | 1.0-23.6                            | Patchouli-1.0-23.6.jar                                      | None                                     |
	| LCH   | deepmoblearning                   | 1.2.1                               | DeepMobEvolution-1.12.2-1.2.1.jar                           | None                                     |
	| LCH   | endercore                         | 1.12.2-0.5.78                       | EnderCore-1.12.2-0.5.78.jar                                 | None                                     |
	| LCH   | thermalfoundation                 | 2.6.7                               | ThermalFoundation-1.12.2-2.6.7.1-universal.jar              | None                                     |
	| LCH   | thermalexpansion                  | 5.5.7                               | ThermalExpansion-1.12.2-5.5.7.1-universal.jar               | None                                     |
	| LCH   | enderio                           | 5.3.72                              | EnderIO-1.12.2-5.3.72.jar                                   | None                                     |
	| LCH   | enderiointegrationtic             | 5.3.72                              | EnderIO-1.12.2-5.3.72.jar                                   | None                                     |
	| LCH   | enderiobase                       | 5.3.72                              | EnderIO-1.12.2-5.3.72.jar                                   | None                                     |
	| LCH   | enderioconduits                   | 5.3.72                              | EnderIO-1.12.2-5.3.72.jar                                   | None                                     |
	| LCH   | enderioconduitsappliedenergistics | 5.3.72                              | EnderIO-1.12.2-5.3.72.jar                                   | None                                     |
	| LCH   | enderioconduitsopencomputers      | 5.3.72                              | EnderIO-1.12.2-5.3.72.jar                                   | None                                     |
	| LCH   | enderioconduitsrefinedstorage     | 5.3.72                              | EnderIO-1.12.2-5.3.72.jar                                   | None                                     |
	| LCH   | enderiointegrationforestry        | 5.3.72                              | EnderIO-1.12.2-5.3.72.jar                                   | None                                     |
	| LCH   | enderiointegrationticlate         | 5.3.72                              | EnderIO-1.12.2-5.3.72.jar                                   | None                                     |
	| LCH   | enderioinvpanel                   | 5.3.72                              | EnderIO-1.12.2-5.3.72.jar                                   | None                                     |
	| LCH   | enderiomachines                   | 5.3.72                              | EnderIO-1.12.2-5.3.72.jar                                   | None                                     |
	| LCH   | enderiopowertools                 | 5.3.72                              | EnderIO-1.12.2-5.3.72.jar                                   | None                                     |
	| LCH   | enderstorage                      | 2.4.6.137                           | EnderStorage-1.12.2-2.4.6.137-universal.jar                 | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | shetiphiancore                    | 3.5.9                               | shetiphiancore-1.12.0-3.5.9.jar                             | None                                     |
	| LCH   | endertanks                        | 1.6.8                               | endertanks-1.12.0-1.6.8.jar                                 | None                                     |
	| LCH   | enderutilities                    | 0.7.15                              | enderutilities-1.12.2-0.7.15.jar                            | 2b03e1423915a189b8094816baa18f239d576dff |
	| LCH   | extrautils2                       | 1.0                                 | extrautils2-1.12-1.9.9.jar                                  | None                                     |
	| LCH   | firstaid                          | 1.6.22                              | firstaid-1.6.22.jar                                         | 7904c4e13947c8a616c5f39b26bdeba796500722 |
	| LCH   | cfm                               | 6.3.0                               | furniture-6.3.2-1.12.2.jar                                  | None                                     |
	| LCH   | grapplemod                        | 1.12.2-v13                          | grappling_hook_mod-1.12.2-v13.jar                           | None                                     |
	| LCH   | ichunutil                         | 7.2.2                               | iChunUtil-1.12.2-7.2.2.jar                                  | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCH   | gravitygun                        | 7.1.0                               | GravityGun-1.12.2-7.1.0.jar                                 | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCH   | gregtech                          | 2.6.0                               | gregtech-1.12.2-2.6.0-beta.jar                              | None                                     |
	| LCH   | gcym                              | 1.2.1                               | GregicalityMultiblocks-1.12.2-1.2.1.jar                     | None                                     |
	| LCH   | gvclib                            | 1.12.2                              | GVCLib__1.12.2__7.1.zip                                     | None                                     |
	| LCH   | gvcr2                             | 1.12.2                              | GVCReversion2__1.12.2__α.6.1.zip                            | None                                     |
	| LCH   | handmadeguns2                     | 1.12.2                              | HandmadeGun's2_1.12.2.9.zip                                 | None                                     |
	| LCH   | handmadevehicle2                  | 1.12.2                              | HandmadeVehicle's2_1.12.2.4.3.zip                           | None                                     |
	| LCH   | dcs_climate                       | 3.9.11                              | HeatAndClimateMod_1.12.2-3.9.11.jar                         | 4cd12b92959105443b7b694fffe0cea9ed004886 |
	| LCH   | iblis_headshots                   | 1.2.6                               | iblis-headshots-1.2.6.jar                                   | None                                     |
	| LCH   | vehicle                           | 0.44.1                              | vehicle-mod-0.44.1-1.12.2.jar                               | None                                     |
	| LCH   | jev                               | 2.0.0                               | jev-1.12.2-2.0.0.jar                                        | None                                     |
	| LCH   | littletiles                       | 1.5.0                               | LittleTiles_v1.5.82_mc1.12.2.jar                            | None                                     |
	| LCH   | manydifferentweapons              | 1.0.0                               | Many Different Weapons-1.12.2-0.0.0.jar                     | None                                     |
	| LCH   | mdi                               | 1.7.8                               | MDI 1.7.8.jar                                               | None                                     |
	| LCH   | mekanismtools                     | 1.12.2-9.8.3.390                    | MekanismTools-1.12.2-9.8.3.390.jar                          | None                                     |
	| LCH   | minerva                           | 1.0.13                              | minerva-library-1.0.13.jar                                  | b851b8b7c7f4d8d0e910ff27618150ba80c026ec |
	| LCH   | minetraps                         | 1.0.4                               | MineTraps-1.12.2-(v.1.0.4).jar                              | None                                     |
	| LCH   | mousetweaks                       | 2.10                                | MouseTweaks-2.10-mc1.12.2.jar                               | None                                     |
	| LCH   | nuclearcraft                      | 2.18y                               | NuclearCraft-2.18y-1.12.2.jar                               | None                                     |
	| LCH   | omlib                             | 3.1.5-256                           | omlib-1.12.2-3.1.5-256.jar                                  | None                                     |
	| LCH   | openmodularturrets                | 3.1.14-382                          | openmodularturrets-1.12.2-3.1.14-382.jar                    | None                                     |
	| LCH   | oreexcavation                     | 1.4.150                             | OreExcavation-1.4.150.jar                                   | None                                     |
	| LCH   | p455w0rdslib                      | 2.3.161                             | p455w0rdslib-1.12.2-2.3.161.jar                             | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCH   | placeableitems                    | 3.3                                 | placeableitems-3.3.jar                                      | None                                     |
	| LCH   | rationcraft                       | 1.0                                 | Rationcraft_B1.0.1_1.12.2.jar                               | None                                     |
	| LCH   | llibrary                          | 1.7.20                              | llibrary-1.7.20-1.12.2.jar                                  | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | rats                              | 3.2.14                              | rats-3.2.14-1.12.2.jar                                      | None                                     |
	| LCH   | signpic                           | 2.8.1                               | SignPicture-1.12.1-2.8.1-universal.jar                      | None                                     |
	| LCH   | snad                              | 1.12.1-1.7.09.16a                   | Snad-1.12.1-1.7.09.16a.jar                                  | None                                     |
	| LCH   | specialmobs                       | 1.0.4_for_mc1.12.2                  | specialmobs-1.0.4_for_mc1.12.2.jar                          | None                                     |
	| LCH   | tektopia                          | 1.1.0                               | tektopia-1.1.0.jar                                          | None                                     |
	| LCH   | thermalcultivation                | 0.3.6                               | ThermalCultivation-1.12.2-0.3.6.1-universal.jar             | None                                     |
	| LCH   | thermalinnovation                 | 0.3.6                               | ThermalInnovation-1.12.2-0.3.6.1-universal.jar              | None                                     |
	| LCH   | tanaddons                         | 3.4.24                              | ToughExpansion-1.12-3.4.24.jar                              | None                                     |
	| LCH   | tpp                               | 1.0.1.1                             | TP+-1.12.2-1.0.1.1.jar                                      | None                                     |
	| LCH   | uteamcore                         | 2.2.5.255                           | u_team_core-1.12.2-2.2.5.255.jar                            | None                                     |
	| LCH   | usefulbackpacks                   | 1.5.4.85                            | useful_backpacks-1.12.2-1.5.4.85.jar                        | None                                     |
	| LCH   | voicechat                         | 1.12.2-2.4.24                       | voicechat-forge-1.12.2-2.4.24.jar                           | None                                     |
	| LCH   | xercamod                          | 1.12.2-1.2                          | xercamod-1.12.2-1.2.jar                                     | None                                     |
	| LCH   | betteranimalsplus                 | 9.0.1                               | betteranimalsplus-1.12.2-9.0.1.jar                          | None                                     |
	| LCH   | thebetweenlands                   | 3.9.6                               | TheBetweenlands-3.9.6-universal.jar                         | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| UD    | advancedrocketrycore              | 1                                   | minecraft.jar                                               | None                                     |

	Loaded coremods (and transformers): 
GregTechLoadingPlugin (gregtech-1.12.2-2.6.0-beta.jar)
  gregtech.asm.GregTechTransformer
LittlePatchingLoader (LittleTiles_v1.5.82_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.9.6-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
SignPictureCorePlugin (SignPicture-1.12.1-2.8.1-universal.jar)
  com.kamesuta.mc.signpic.asm.SignPictureTransformer
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.78-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
SecurityCraftLoadingPlugin ([1.12.2] SecurityCraft v1.9.7.jar)
  
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  shetiphian.asm.ClassTransformer
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-2.0.0-17.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
CreativePatchingLoader (CreativeCore_v1.10.71_mc1.12.2.jar)
  
DCASMPlugin (HeatAndClimateLib_1.12.2-3.9.3.jar)
  defeatedcrow.hac.asm.DCMethodTransformer
ratscore (rats-3.2.14-1.12.2.jar)
  com.github.alexthe666.rats.server.misc.RatsRuntimePatcher
AE2ELCore (appliedenergistics2-rv6-stable-7-extended_life-v0.55.22.jar)
  appeng.core.transformer.AE2ELTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 516.59' Renderer: 'NVIDIA GeForce RTX 3070/PCIe/SSE2'
	AE2 Version: stable rv6-stable-7-extended_life-v0.55.22 for Forge 14.23.5.2847
	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Authlib is : /C:/Users/F%c3%b6hling/curseforge/minecraft/Install/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Patchouli open book context: n/a
	Launched Version: forge-14.23.5.2860
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce RTX 3070/PCIe/SSE2 GL version 4.6.0 NVIDIA 516.59, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: hopefully this isnt copyrighted.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 20x 12th Gen Intel(R) Core(TM) i7-12700K
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 516.59
	OpenGlRenderer: NVIDIA GeForce RTX 3070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 20

### Steps to Reproduce

install gregtech and nuclear craft 
it could be because of other mods in my mod pack but it only crashe when nuclear craft is present

**Comment by screret** [comment]
wrong git. https://github.com/GregTechCEu/GregTech/issues
also this can be fixed by disabling the GTCE integration in nuclearcraft's config.

**Comment by Imadethisaccformodadvice** [comment]
thanks
