### ISSUE TITLE
Add recipes to REI

### ISSUE THREAD

**Issue by Martmists-GH** [GregTechCEu/GregTechCEu-1.19#444]
### Cross-mod Integration

REI

### Feature Description

Currently, no recipes are visible in REI, except for multiblock structures. Being able to see how to craft GregTech items would be a very welcome feature :)

**Comment by screret** [comment]
Wha- we have REI integration

**Comment by Martmists-GH** [comment]
Very strange, none are showing up on my end. Is there a way for me to debug this?

**Comment by mikerooni** [comment]
Which version of GTCEu are you running?

**Comment by Martmists-GH** [comment]
1.0.12.f-build_209

Here's a log: https://mclo.gs/OHHrD9Q

**Comment by mikerooni** [comment]
Can you please try it with 1.0.12.g? It should be fixed there as far as I know.

**Comment by mikerooni** [comment]
Did it work with the newer version? ^^

**Comment by Martmists-GH** [comment]
Yup, no issues whatsoever

**Comment by mikerooni** [comment]
Thanks for confirming! That's great then.
