### ISSUE TITLE
Entering world and creating world crashes after updating mod

### ISSUE THREAD

**Issue by tsubfak13** [GregTechCEu/GregTechCEu-1.19#452]
### GregTech CEu Version

1.0.13

### Recipe Viewer Installed

JEI

### Environment

sp

### Cross-Mod Interaction

Unsure

### Expected Behavior

I don't know, maybe normal entry and world creation?

### Actual Behavior

Entering world and creating world crashes after updating mod

### Steps to Reproduce

https://www.curseforge.com/minecraft/modpacks/gregtronix-revoluton
This is my modpack, but now it crashes when I upgrade gtceu's mod version to .13.

### Additional Information

[crash-2023-10-06_00.23.53-server.txt](https://github.com/GregTechCEu/GregTech-Modern/files/12820847/crash-2023-10-06_00.23.53-server.txt)

**Comment by screret** [comment]
your ProbeJS config file is corrupt.
You sure you didn't update any other mods?

**Comment by tsubfak13** [comment]
> your ProbeJS config file is corrupt. You sure you didn't update any other mods?

yep

**Comment by tsubfak13** [comment]
> your ProbeJS config file is corrupt. You sure you didn't update any other mods?
I'm pretty sure I haven't updated any other mods
