### ISSUE TITLE
Multiblocks crashing client

### ISSUE THREAD

**Issue by sreny1** [GregTechCEu/GregTechCEu-1.19#453]
### GregTech CEu Version

1.0.12.f

### Recipe Viewer Installed

JEI

### Environment

Dedicated Server

### Cross-Mod Interaction

Unsure

### Expected Behavior

The Game doesnt crash randomly when rendering multiblocks

### Actual Behavior

the game crashes at random times quite frequently rendering multiblocks

### Steps to Reproduce

build Multiblocks
look at them and wait for it to crash

happens to me anywhere from 1min to like 15mins with multiple multiblocks in view

### Additional Information

this happend in ATM9 version 0.1.12
it happend with embeddium + addons installed: https://mclo.gs/2C0cHPa
it happend without rendering mods installed: https://mclo.gs/EM3RC4W
There are many more crash reports, each caused by some random block (hatches, casings, cleanroom glas, ..) of any multiblock in view

**Comment by sreny1** [comment]
seems like this issue was fixed in the mean time 👍
no longer getting crashes like this

**Comment by screret** [comment]
oh cool

**Comment by sreny1** [comment]
it was fixed like one or two updates after i opened this.
just closed this now because i realized it was stil open.

since not even i was able to reproduce it in a new world, i guess it was just some weird edge case that i had constructed :)
but happy it got fixed somehow anyways :D
