### ISSUE TITLE
Ore veins containing "Custom Ore 'Stone' Types" will cause the game to crash.

### ISSUE THREAD

**Issue by tsubfak13** [GregTechCEu/GregTechCEu-1.19#456]
### GregTech CEu Version

1.0.13 (1.19)

### Recipe Viewer Installed

JEI

### Environment

sp

### Cross-Mod Interaction

Unsure

### Expected Behavior

Generate veins in other types of stones in other dimensions

### Actual Behavior

The ore vein is generated, but the game will crash after a while

### Steps to Reproduce

[StartJS.txt](https://github.com/GregTechCEu/GregTech-Modern/files/12837393/StartJS.txt)
[orevein.txt](https://github.com/GregTechCEu/GregTech-Modern/files/12837394/orevein.txt)

### Additional Information

I posted this bug on discord yesterday, but at that time I thought that the structure generation of ad astra's moon conflicted with something, causing the game to crash, but today I tried to generate veins in the dimension of the deeper and darker mod. The game will still crash.
But my other vein script generated in vanilla stone in TF runs very well.
[crash-2023-10-07_17.40.31-server.txt](https://github.com/GregTechCEu/GregTech-Modern/files/12837384/crash-2023-10-07_17.40.31-server.txt)
[crash-2023-10-07_16.52.14-server.txt](https://github.com/GregTechCEu/GregTech-Modern/files/12837388/crash-2023-10-07_16.52.14-server.txt)

**Comment by tsubfak13** [comment]
I'm not sure if there is a problem with the two streamlined scripts I uploaded, but in my original script these two veins can be generated and kubejs does not report any errors when entering the game. I used rtp in these dimensions. My veins will be visible for a few seconds, but then the game will crash

**Comment by tsubfak13** [comment]
I just created an ore stone type for Vanilla Dirt and created an overworld vein, but the game still crashes, as if I were just using a custom ore block type and the game would crash

**Comment by screret** [comment]
same as #480.
