### ISSUE TITLE
ATM9 - Gregtech ticking block entity crash.

### ISSUE THREAD

**Issue by Micaxs** [GregTechCEu/GregTechCEu-1.19#458]
### GregTech CEu Version

1.0.12.f

### Recipe Viewer Installed

JEI

### Environment

Dedicated Server

### Cross-Mod Interaction

Yes

### Expected Behavior

Open the inventory without the server crashing with ticking block entity.

### Actual Behavior

Crashes when opening inventory

### Steps to Reproduce

Setup a lv centrifuge and opening inventory randomly causes server to crash.
Similar crash happens when changing outputs as well.

### Additional Information

Crash log: https://mclo.gs/PsB59BB

**Comment by mikerooni** [comment]
That's odd...  
I'm not 100% sure about it and this definitely needs further testing, but the error in your log looks to me like something is messing with the values (specifically `normal`) in `net.minecraft.core.Direction`

**Comment by Micaxs** [comment]
> That's odd... I'm not 100% sure about it and this definitely needs further testing, but the error in your log looks to me like something is messing with the values (specifically `normal`) in `net.minecraft.core.Direction`

Seemed to have happend when changing the input/output of the machine to the side of an pattern provider from applied energistics 2. Might be the indication of what the direction is referencing to?

**Comment by ctallet8** [comment]
I believe I'm having pretty much the same issue. I was trying to change the fluid output on my electrolyzee to a gregtech fluid pipe and it kept crashing anytime I'd open the electrolyzer after that. 

https://mclo.gs/ax5ICeD

**Comment by mikerooni** [comment]
I have now gotten it in my own pack as well for the second time. I still have no idea how to reliably reproduce it, or what's even causing it.  
And it still looks to me like it shouldn't even be able to happen, unfortunately.
