### ISSUE TITLE
Machines stopping after doing one recipe

### ISSUE THREAD

**Issue by Doctor-Duck** [GregTechCEu/GregTechCEu-1.19#467]
### GregTech CEu Version

gtceu-forge-1.20.1-1.0.13.a

### Recipe Viewer Installed

JEI

### Environment

Dedicated Server

### Cross-Mod Interaction

Unsure

### Expected Behavior

Using low-pressure machines will continue to process items. Such as macerating a stack of wood to make wood dust until I either run out of logs or the macerator output slots are full.

### Actual Behavior

Machines will only process an item once, then stop working until breaking the machine and placing it down again. However, the same thing will happen where the machine only processes the item once.

### Steps to Reproduce

1. Placed materials into the input slot.
2. Machine processes the materials into the desired output.
3. Machine stops processing materials until broken and placed down again.
4. Cycle repeats after only processing once.

**Comment by screret** [comment]
Move the steam vent to an open side.
