### ISSUE TITLE
missing recipy "zeron 100 dust"

### ISSUE THREAD

**Issue by minecrafterseppe** [GregTechCEu/GregTechCEu-1.19#469]
### GregTech CEu Version

1.20.1-1.0.13.a

### Recipe Viewer Installed

JEI

### Environment

dedicated server

### Cross-Mod Interaction

Unsure

### Expected Behavior

missing recipy

### Actual Behavior

look at recipy
missing

### Steps to Reproduce

look at recipy 
missing

**Comment by screret** [comment]
Intended.
