### ISSUE TITLE
Crash when the mod loader is creating the mod instance

### ISSUE THREAD

**Issue by NishikiAsumi0** [GregTechCEu/GregTechCEu-1.19#47]
### GregTech CEu Version

1.19.2 Auto Build #8

### Recipe Viewer Installed

No Recipe Viewer

### Environment

Dedicated Server

### Cross-Mod Interaction

No

### Expected Behavior

Server should startup

### Actual Behavior

Failed to start the minecraft server.
Crash when the mod loader is creating the mod instance.

https://pastebin.com/FZL6k7z1

### Steps to Reproduce

Using Forge Modloader with only mods of GTCEu and ldlib

**Comment by screret** [comment]
Paste not available anymore, and afaik most recent build runs on server
