### ISSUE TITLE
distinct bus mode not working with circuits config

### ISSUE THREAD

**Issue by DarkCreeper0131** [GregTechCEu/GregTechCEu-1.19#470]
### GregTech CEu Version

v1.0.13a

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

when putting all input busses in distinct mode and having different circuit configs, the recipe will craft  

### Actual Behavior

the recipe will not craft if distinct mode is turned on in the input bus that has recipe

### Steps to Reproduce

1) build large assembler multiblock
2) have multiple input busses with different circuit configs
3) put a recipe in while distinct bus mode is on 

### Additional Information

seems to only happen to recipes requiring a circuit config to be set

**Comment by sreny1** [comment]
is this issue supposed to be fixed in 1.0.13.b?
if so: it doesn't seem to be fixed :(
