### ISSUE TITLE
Rubber Ring Knife Craft Recipe Deletes Knife

### ISSUE THREAD

**Issue by loving2** [GregTechCEu/GregTechCEu-1.19#473]
### GregTech CEu Version

gtceu-forge-1.20.1-1.0.13.a

### Recipe Viewer Installed

JEI

### Environment

Dedicated Server

### Cross-Mod Interaction

Yes

### Expected Behavior

Another mod's knife durability should go down by 1

### Actual Behavior

The other mod's knife is deleted

### Steps to Reproduce

1) Install another mod that comes with a knife, like Aquaculture 2, Farmer's Delight, or Twilight Forest
2) Make a rubber ring with the other mod knife
3) Note how the knife is yeeted from existence

### Additional Information

Originally reported in ATM9 - https://github.com/AllTheMods/ATM-9/issues/593

**Comment by screret** [comment]
I don't think we can quite _do that?_ or can we?

**Comment by loving2** [comment]
I tried hunting it down, and it looks like it is Forge code that returns hasCraftingRemainingItem() as false which causes the item to just get deleted rather than call getCraftingRemainingItem. I don't know why it returns false...

Might be something to do with how the recipe is generated? Might not either, as I tried deleting the recipe and making a new one with KubeJS which had the same issue.

**Comment by screret** [comment]
it's just that vanilla (or most mods) don't have remainder items, and we had to do some jank to make the combining recipes work as well.
