### ISSUE TITLE
Add Engineer's Wirecutters functionality to GTCEu wire cutters.

### ISSUE THREAD

**Issue by Correlander** [GregTechCEu/GregTechCEu-1.19#474]
### Cross-mod Integration

Immersive Engineering

### Feature Description

The title pretty much says it all. Just make it so right-click with the wirecutters from GTCEu can do the same things as the Engineer's Wirecutters.

**Comment by screret** [comment]
if the engineer's wirecutters use tags, great! this is fixed.
if they use an interface etc. then this is a no-go.

**Comment by Darthsae** [comment]
public static final TagKey<Item> wirecutters = createItemWrapper(rl("tools/wirecutters"));
This is the line in IETags.

**Comment by Correlander** [comment]
I opened this a very long time ago, but if I remember correctly, I suggested this specifically because there was functionality not built in to tags that I could add by just using KubeJS to add a tag to the wrenches. I will try to check myself but I don't have much time recently so if someone wants to check instead to fast track it, please feel free.
