### ISSUE TITLE
AE2 Processing Pattern Encoding Not working on REI

### ISSUE THREAD

**Issue by Drackion** [GregTechCEu/GregTechCEu-1.19#483]
### GregTech CEu Version

1.0.13b

### Recipe Viewer Installed

REI

### Environment

Singleplayer Forge

### Cross-Mod Interaction

Yes

### Expected Behavior

to be able to encode processing pattens with no issues

### Actual Behavior

When REI is use as the Recipe viewer and REI compat is installed any pack with gregtech the encoding of ae2 processing patterns doesn't working as it only encodes only fluid:

### Steps to Reproduce

https://github.com/Low-Drag-MC/LDLib-Architectury/assets/64641342/bf31a73c-6feb-4471-ab8b-97422ccc372d

note you need REI compat installed and a mod that doesn't have REI support like create

### Additional Information

I also talked about the issue on the Kubejs discord and they looked at the LDlib code an atributed the issue to missing annotation is the JEI plugin:

https://github.com/Low-Drag-MC/LDLib-Architectury/blob/1.19.2/common/src/main/java/com/lowdragmc/lowdraglib/jei/JEIPlugin.java#L25

![image](https://github.com/Low-Drag-MC/LDLib-Architectury/assets/64641342/661f08c0-8fcc-43b9-a362-8d0fc65fb6fd)

**Comment by Ghostipedia** [comment]
Closing as the issue was from 1.19.2 - If the issue occurs on **1.20.1** or greater please feel free to reopen
