### ISSUE TITLE
Alloy Blast Smelter create Molten version of Gallium Arsenide instead of Liquid

### ISSUE THREAD

**Issue by Bosspc1234** [GregTechCEu/GregTechCEu-1.19#498]
### GregTech CEu Version

1.0.13.d

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Expected Behavior

Alloy Blast Smelter should create Liquid Gallium Arsenide since it doesn't need cooling.

### Actual Behavior

![2023-10-29_00 11 572](https://github.com/GregTechCEu/GregTech-Modern/assets/128601014/23e71fea-b41c-4272-971e-6096b0973a0f)
This recipe create molten version which doesn't have any use in JEI (except for filling bucket).

### Steps to Reproduce

Only happen in Alloy blast smelter. Extracting Gallium Arsenide Ingot still gives correct liquid version.

**Comment by Bosspc1234** [comment]
I also found more metal recipe that alloy blast smelter create incorrect molten version.
- Sterling Silver
- Rose Gold
- Bismuth Bronze
- Stainless Steel
- Manganese Phosphide
- Black Steel
- Vanadium Steel
- Red Steel
- Blue Steel
- HSLA Steel
Seem like metals that doesn't turn into hot ingot when EBF is all in the list.

**Comment by Rundas01** [comment]
I'll take a look

**Comment by Rundas01** [comment]
@Bosspc1234 I fixed it. will be there in the next release after my PR is merged. thanks for reporting.
