### ISSUE TITLE
Crash when break rubber leaf

### ISSUE THREAD

**Issue by gundami** [GregTechCEu/GregTechCEu-1.19#50]
### GregTech CEu Version

v1.0.2

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

break the block

### Actual Behavior

break the rubber leaf block, then crash
crash log: https://paste.ubuntu.com/p/RSPVNmzbKS/

### Steps to Reproduce

break the block

**Comment by Yefancy** [comment]
can't reproduce it
