### ISSUE TITLE
tag based steam input for steam machines

### ISSUE THREAD

**Issue by Drackion** [GregTechCEu/GregTechCEu-1.19#502]
### Cross-mod Integration

Railcraft

### Feature Description

For steam machines to not be hard coded to use gtceu:steam and instead use a tag so steam from other mods could be used

**Comment by screret** [comment]
Uh 
That's already the case, no?
Looked everywhere, and everywhere tags are used as far as i can see

**Comment by Drackion** [comment]
for turbines it is, but not for steam age machines
