### ISSUE TITLE
Things cannot calculate properly on EMI

### ISSUE THREAD

**Issue by Arborsm** [GregTechCEu/GregTechCEu-1.19#509]
### GregTech CEu Version

*

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

the programming circuit and chanced output calculated properly on EMI

### Actual Behavior

the programming circuit and chanced output cannot be calculated properly on EMI

### Steps to Reproduce

calculate the recipe on EMI

### Additional Information

The latter seems difficult to fix that make it calculated based on machine level. Maybe just calculate with the base chance?

**Comment by screret** [comment]
duplicate of #343 .
