### ISSUE TITLE
AE2 Wrench Is Directly Consumed in Recipes

### ISSUE THREAD

**Issue by Phoupraw** [GregTechCEu/GregTechCEu-1.19#513]
### GregTech CEu Version

fabric-1.20.1-1.0.13.e

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

As AE2 wrenches don't have durability, they should be remained or shouldn't be used in those recipes.

### Actual Behavior

AE2 wrenches are directly consumed.

### Steps to Reproduce

1. Get 2 bricks, 5 bronze plates, 1 furnace and 1 ae2 wrench.
2. Craft a lp steam solid steamer.
3. You lost the ae2 wrench.

![shaped_steam_boiler_coal_bronze](https://github.com/GregTechCEu/GregTech-Modern/assets/50520903/b7997902-8613-4e7c-93f4-b410a2945ea8)

### Additional Information

Mod:
- additionaladditions 6.0.1
  - libgui 8.0.1+1.20
    - jankson 5.0.1+j1.2.2
    - libninepatch 1.2.0
- ae2 15.0.14
  - team_reborn_energy 3.0.0
- ae2-emi-crafting 1.0.1
- ae2wtlib 15.0.1-beta
- amecs 1.3.9+mc.1.20-pre2
  - amecsapi 1.4.0+mc1.20-pre1
- appleskin 2.5.0+mc1.20
- architectury 9.1.12
- ash 2.0.0-rc.2
- attackspeedenchantment 1.3.0.20
- autofish 0.9.10-SNAPSHOT
- badpackets 0.4.3
- bugjump 1.2.0-1.20.1
- can-i-mine-this-block 1.4.0
- carpet 1.4.112+v230608
- carpet-tis-addition 1.48.0
  - conditional-mixin 0.3.2
- chat_heads 0.10.15
- cloth-config 11.1.106
  - cloth-basic-math 0.6.1
- colormeoutlines 1.1.2
- conjuring 1.0.28+1.20
  - lavender 0.1.0-pre.6+1.20
    - lavender-md 0.1.0-pre.3+1.20
    - lavender-md-owo-ui 0.1.0-pre.3+1.20
- creativecore 2.10.23
  - net_minecraftforge_eventbus 6.0.3
- cull-less-leaves 1.3.0
- diggusmaximus 1.5.9-1.20
  - kyrptconfig 1.5.6-1.20
- eatinganimationid 1.20+1.9.5-CMDfix
- elytraslot 6.3.0+1.20.1
- emi 1.0.23+1.20.1+fabric
- emi_loot 0.6.5+1.20.1
- emiffect 1.1.1+mc1.20.1
- emitrades 1.2.0+mc1.20.1
  - org_quiltmc_parsers_json 0.2.1
- enchantinginfuser 8.0.2
- entityculling 1.6.2-mc1.20
- extra-mod-integrations 0.4.1+1.20.1
- fabric-api 0.88.1+1.20.1
  - fabric-api-base 0.4.30+7abfd51577
  - fabric-api-lookup-api-v1 1.6.35+4d8536c977
  - fabric-biome-api-v1 13.0.10+b3afc78b77
  - fabric-block-api-v1 1.0.10+92a0d36777
  - fabric-block-view-api-v2 1.0.0+92a0d36777
  - fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
  - fabric-client-tags-api-v1 1.1.1+97bb207577
  - fabric-command-api-v1 1.2.33+f71b366f77
  - fabric-command-api-v2 2.2.12+b3afc78b77
  - fabric-commands-v0 0.2.50+df3654b377
  - fabric-containers-v0 0.1.63+df3654b377
  - fabric-content-registries-v0 4.0.9+b3afc78b77
  - fabric-convention-tags-v1 1.5.4+a1a980da77
  - fabric-crash-report-info-v1 0.2.18+aeb40ebe77
  - fabric-data-generation-api-v1 12.2.2+1e61dba177
  - fabric-dimensions-v1 2.1.53+8536527b77
  - fabric-entity-events-v1 1.5.22+b3afc78b77
  - fabric-events-interaction-v0 0.6.1+e91849a877
  - fabric-events-lifecycle-v0 0.2.62+df3654b377
  - fabric-game-rule-api-v1 1.0.38+b04edc7a77
  - fabric-item-api-v1 2.1.27+b3afc78b77
  - fabric-item-group-api-v1 4.0.10+23d9108177
  - fabric-key-binding-api-v1 1.0.36+fb8d95da77
  - fabric-keybindings-v0 0.2.34+df3654b377
  - fabric-lifecycle-events-v1 2.2.21+b3afc78b77
  - fabric-loot-api-v2 1.1.39+b3afc78b77
  - fabric-loot-tables-v1 1.1.43+9e7660c677
  - fabric-message-api-v1 5.1.7+3265161977
  - fabric-mining-level-api-v1 2.1.49+b3afc78b77
  - fabric-model-loading-api-v1 1.0.2+709a987177
  - fabric-models-v0 0.4.1+9386d8a777
  - fabric-networking-api-v1 1.3.10+eeb8eb3677
  - fabric-networking-v0 0.3.50+df3654b377
  - fabric-object-builder-api-v1 11.1.1+6beca84877
  - fabric-particles-v1 1.1.1+201a23a077
  - fabric-recipe-api-v1 1.0.20+b3afc78b77
  - fabric-registry-sync-v0 2.3.2+4df89eb277
  - fabric-renderer-api-v1 3.1.3+92a0d36777
  - fabric-renderer-indigo 1.4.3+6bdb2ed077
  - fabric-renderer-registries-v1 3.2.45+df3654b377
  - fabric-rendering-data-attachment-v1 0.3.36+92a0d36777
  - fabric-rendering-fluids-v1 3.0.27+b3afc78b77
  - fabric-rendering-v0 1.1.48+df3654b377
  - fabric-rendering-v1 3.0.7+b3afc78b77
  - fabric-resource-conditions-api-v1 2.3.5+ea08f9d877
  - fabric-resource-loader-v0 0.11.9+132c48c177
  - fabric-screen-api-v1 2.0.7+b3afc78b77
  - fabric-screen-handler-api-v1 1.3.29+b3afc78b77
  - fabric-sound-api-v1 1.0.12+b3afc78b77
  - fabric-transfer-api-v1 3.3.1+195226a777
  - fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
- fabric-language-kotlin 1.10.11+kotlin.1.9.20
  - org_jetbrains_kotlin_kotlin-reflect 1.9.20
  - org_jetbrains_kotlin_kotlin-stdlib 1.9.20
  - org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.20
  - org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.20
  - org_jetbrains_kotlinx_atomicfu-jvm 0.22.0
  - org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.3
  - org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.3
  - org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.1
  - org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.0
  - org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.0
  - org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.0
- fabricloader 0.14.24
- farmersdelight 1.20.1-1.4.2
- ferritecore 6.0.0
- forgeconfigapiport 8.0.0
- gtceu 1.0.13.e
  - configuration 2.2.0
  - ldlib 1.0.20
  - registrate-fabric 1.3.59-MC1.20
    - com_google_code_findbugs_jsr305 3.0.2
    - porting_lib_data 2.1.1021+1.20
      - porting_lib_core 2.1.1021+1.20
      - porting_lib_gametest 2.1.1021+1.20
      - porting_lib_utility 2.1.1021+1.20
    - porting_lib_model_generators 2.1.1021+1.20
      - porting_lib_core 2.1.1021+1.20
      - porting_lib_gametest 2.1.1021+1.20
      - porting_lib_model_materials 2.1.1021+1.20
      - porting_lib_utility 2.1.1021+1.20
      - porting_lib_tags 3.0
         - porting_lib_core 2.1.1021+1.20
         - porting_lib_gametest 2.1.1021+1.20
- iceberg 1.1.15
- identifier_translation 3_1.20-1.20.1
- imblocker 4.0.5
- indium 1.0.21+mc1.20.1
- inventoryprofilesnext 1.10.9
- itemscroller 0.20.0
- java 17
- kiwi 11.1.1
- languagereload 1.5.9+1.20.1
  - com_github_llamalad7_mixinextras 0.2.0-rc.5
- libipn 4.0.0
- litematica 0.15.0
- lmft 1.0.2+1.20
- magiclib 0.7.387+c02a0de-stable
  - magiclib-1_20_1 0.7.387+c02a0de-stable
- malilib 0.16.3
- masa_gadget_mod 3.2.312+d94b097-beta
  - masa_gadget_mod-1_20_1 3.2.312+d94b097-beta
- mcwifipnp 1.6.5
- minecraft 1.20.1
- minihud 0.27.0
- moderate-loading-screen 1.2.1+1.20.1
  - cicada 0.1.2
    - langfiles-plus 1.0.0
- modmenu 7.1.0
- neat 1.20-35-FABRIC
  - fiber 0.23.0-2
- nochatreports 1.20.1-v2.2.1
- ommc-1_20_1 0.5.325+b4f9d2d-beta
- owo 0.11.1+1.20
  - blue_endless_jankson 1.2.2
- passablefoliage 1.20.1-fabric-8.1.0
- passivesearchbar 1.0.0
- pca 0.3.166+0c5bf4c-beta
- puzzleslib 8.1.5
  - puzzlesaccessapi 8.0.7
- really_forge 0.1.1
- sodium 0.4.10+build.27
- stepup 1.20-fabric0.83.0-1.3
  - crowdin-translate 1.4+1.19.3
  - gbfabrictools 1.4+1.20
- travelersbackpack 1.20.1-9.1.2
- trifle 0.10.5
  - mm 2.3
  - org_apache_commons_commons-math3 3.6.1
- trinkets 3.7.1
- tweakermore 3.13.1
  - conditional-mixin 0.3.2
- tweakeroo 0.17.0
- universalenchants 8.0.0
  - cardinal-components-base 5.2.1
  - cardinal-components-entity 5.2.1
  - extensibleenums 7.0.1
- uteamcore 5.1.3.267
- worldedit 7.2.15+6463-5ca4dff
- worldeditcui 1.20+01
- wthit 8.4.1
- xaero_map_addition-1_20_1 0.2.86+85478ec-beta
- xaerominimap 23.4.4
- xaeroworldmap 1.30.4
- xaerozoomout 1.0.0+mc1.20
- yet_another_config_lib_v3 3.2.1+1.20
  - com_twelvemonkeys_common_common-image 3.10.0-SNAPSHOT
  - com_twelvemonkeys_common_common-io 3.10.0-SNAPSHOT
  - com_twelvemonkeys_common_common-lang 3.10.0-SNAPSHOT
  - com_twelvemonkeys_imageio_imageio-core 3.10.0-SNAPSHOT
  - com_twelvemonkeys_imageio_imageio-metadata 3.10.0-SNAPSHOT
  - com_twelvemonkeys_imageio_imageio-webp 3.10.0-SNAPSHOT
  - org_quiltmc_parsers_gson 0.2.1

**Comment by krossgg** [comment]
Fabric is no longer supported.
