### ISSUE TITLE
Compass pages review

### ISSUE THREAD

**Issue by Yefancy** [GregTechCEu/GregTechCEu-1.19#523]
We ported [mcmod's gtceu wiki ](https://www.mcmod.cn/item/list/5343-1.html) to compass. A total of 300+ pages containing descriptions + tests of various machines and items. Since the original page was written in Chinese and based on 1.12, we used online translator to generate the xml automatically.

---

# **We are looking forward to people helping us adjust the layout of the page, grammar issues, and the correctness of modern content.**

### How to improve it?
1. Use command `/compass dev_mode true` to turn on the dev mode for hotswap pages.
2. Give yourself a terminal by `/give @a gtceu:terminal`, use it to open the compass without pressing [C]
3. Copy/Add `sss/xxx.xml` to the `.minecraft/ldlib/assets/gtceu/compass/pages/en_us/sss/xxx.xml` .
4. Modify the page and save. You can check the updated results once you reopen the compass / resize the game window if you are in the dev mode.
5. Make a pr and submit the improved page to the path of `common/src/main/resources/assets/gtceu/compass/pages/en_us/sss/xxx.xml` in the project.

Welcome to submit pr. Please remove the warning from the modification page. Also, if the content is still based on the mcmod port, please keep the source and add your own author credit.

All of the ported pages are listed below which can be found under the `assets/gtceu/compass/pages/en_us/...`:

## circuits 
- [x] circuits/nano_cpu_chip 
- [x] circuits/simple_soc 
- [x] circuits/basic_electronic_circuit 
- [x] circuits/silicon_boule 
- [x] circuits/qubit_cpu_chip 
- [x] circuits/ilc_chip 
- [x] circuits/phosphorus_wafer 
- [x] circuits/smd 
- [x] circuits/resistor 
- [x] circuits/wafer 
- [x] circuits/vacuum_tube 
- [x] circuits/micro_processor_computer 
- [x] circuits/nano_processor_computer 
- [x] circuits/quantum_processor_computer 
- [x] circuits/crystal_processor_computer 
- [x] circuits/wetware_processor_computer 
- [x] circuits/phosphorus_boule 
- [x] circuits/diode 
- [x] circuits/nand_chip 
- [x] circuits/neutronium_wafer 
- [x] circuits/circuit_board 
- [x] circuits/microchip_processor 
- [x] circuits/capacitor 
- [x] circuits/micro_processor_mainframe 
- [x] circuits/nano_processor_mainframe 
- [x] circuits/quantum_processor_mainframe 
- [x] circuits/crystal_processor_mainframe 
- [x] circuits/wetware_processor_mainframe 
- [x] circuits/micro_processor 
- [x] circuits/nano_processor 
- [x] circuits/quantum_processor 
- [x] circuits/crystal_processor 
- [x] circuits/wetware_processor 
- [x] circuits/advanced_integrated_circuit 
- [x] circuits/silicon_wafer 
- [x] circuits/basic_integrated_circuit 
- [x] circuits/good_electronic_circuit 
- [x] circuits/micro_processor_assembly 
- [x] circuits/nano_processor_assembly 
- [x] circuits/quantum_processor_assembly 
- [x] circuits/crystal_processor_assembly 
- [x] circuits/wetware_processor_assembly 
- [x] circuits/inductor 
- [x] circuits/good_integrated_circuit 
- [x] circuits/naquadah_wafer 
- [x] circuits/glass_tube 
- [x] circuits/transistor 

## materials 
- [x] materials/gear 
- [x] materials/dense_plate 
- [x] materials/foil 
- [x] materials/hot_ingot 
- [x] materials/bolt 
- [x] materials/rotor 
- [x] materials/lens 
- [x] materials/nugget 
- [x] materials/screw 
- [x] materials/round 
- [x] materials/small_spring 
- [x] materials/rod 
- [x] materials/dust 
- [x] materials/fine_wire 
- [x] materials/spring 
- [x] materials/wire_and_cable 
- [x] materials/small_dust 
- [x] materials/block 
- [x] materials/turbine_blade 
- [x] materials/crushed_ore 
- [x] materials/ring 
- [x] materials/double_plate 
- [x] materials/ingot 
- [x] materials/tiny_dust 
- [x] materials/gem 
- [x] materials/plate 
- [x] materials/small_gear 

## blocks 
- [ ] blocks/coil_block 

## items 
- [ ] items/wireless_transmitter 
- [ ] items/terminal 
- [ ] items/rubber_wood_boat 
- [ ] items/glass_vial 
- [ ] items/iridium_neutron_reflector 
- [ ] items/duct_tape 
- [ ] items/drill 
- [ ] items/empty_cell 
- [ ] items/debug_scanner 
- [ ] items/match 
- [ ] items/dynamite 
- [ ] items/prospector 
- [ ] items/portable_scanner 

## steam 
- [ ] steam/charcoal_pile_igniter 
- [ ] steam/coke_oven_hatch 
- [ ] steam/steam_solid_fuel_boiler 
- [ ] steam/coke_oven 
- [ ] steam/primitive_blast_furnace 
- [ ] steam/large_boiler 
- [ ] steam/steam_hatch 
- [ ] steam/steam_compressor 
- [ ] steam/steam_liquid_boiler 
- [ ] steam/steam_solar_boiler 
- [ ] steam/steam_macerator 
- [ ] steam/steam_alloy_smelter 
- [ ] steam/steam_extractor 
- [ ] steam/steam_grinder 
- [ ] steam/steam_compressor 
- [ ] steam/steam_oven 
- [ ] steam/steam_extractor 
- [ ] steam/steam_macerator 

## multiblock 
- [ ] multiblock/large_combustion 
- [ ] multiblock/cleanroom 
- [ ] multiblock/cracker 
- [ ] multiblock/processing_array 
- [ ] multiblock/large_chemical_reactor 
- [ ] multiblock/large_turbine 
- [ ] multiblock/assembly_line 
- [ ] multiblock/high_performance_computing_array 
- [ ] multiblock/data_bank 
- [ ] multiblock/distillation_tower 
- [ ] multiblock/research_station 
- [ ] multiblock/large_miner 
- [ ] multiblock/vacuum_freezer 

## machines 
- [ ] machines/lathe 
- [ ] machines/electric_furnace 
- [ ] machines/thermal_centrifuge 
- [ ] machines/fisher 
- [ ] machines/arc_furnace 
- [ ] machines/crate 
- [ ] machines/cutter 
- [ ] machines/infinite_energy 
- [ ] machines/extruder 
- [ ] machines/miner 
- [ ] machines/alloy_smelter 
- [ ] machines/macerator 
- [ ] machines/super_tank 
- [ ] machines/brewery 
- [ ] machines/block_breaker 
- [ ] machines/world_accelerator 
- [ ] machines/autoclave 
- [ ] machines/chemical_reactor 
- [ ] machines/assembler 
- [ ] machines/fluid_heater 
- [ ] machines/centrifuge 
- [ ] machines/gas_turbine 
- [ ] machines/forming_press 
- [ ] machines/gas_collector 
- [ ] machines/electrolyzer 
- [ ] machines/circuit_assembler 
- [ ] machines/transformer 
- [ ] machines/rock_crusher 
- [ ] machines/extractor 
- [ ] machines/fluid_solidifier 
- [ ] machines/sifter 
- [ ] machines/distillery 
- [ ] machines/packer 
- [ ] machines/mixer 
- [ ] machines/polarizer 
- [ ] machines/bender 
- [ ] machines/electromagnetic_separator 
- [ ] machines/ore_washer 
- [ ] machines/compressor 
- [ ] machines/steam_turbine 
- [ ] machines/laser_engraver 
- [ ] machines/scanner 
- [ ] machines/magic_energy_absorber 
- [ ] machines/combustion 
- [ ] machines/item_collector 
- [ ] machines/chemical_bath 
- [ ] machines/machine_hull 
- [ ] machines/wiremill 
- [ ] machines/canner 
- [ ] machines/drum 
- [ ] machines/fermenter 
- [ ] machines/battery_buffer 
- [ ] machines/forge_hammer 

## batteries 
- [ ] batteries/large_vanadium_battery 
- [ ] batteries/lapotronic_energy_orb 
- [ ] batteries/lapotronic_energy_orb_cluster 
- [ ] batteries/ultimate_battery 
- [ ] batteries/tantalum_capacitor 
- [ ] batteries/energy_crystal 
- [ ] batteries/zero_point_module 

## misc 
- [ ] misc/crystal_soc 
- [ ] misc/certificate_of_not_being_a_noob_anymore 
- [ ] misc/gravitation_engine_unit 
- [ ] misc/stem_cells 
- [ ] misc/brick_wooden_form 
- [ ] misc/fertilizer 
- [ ] misc/engraved_lapotron_crystal_chip 
- [ ] misc/gravi_star 
- [ ] misc/power_unit 
- [ ] misc/turbine_rotor 
- [ ] misc/energium_dust 
- [ ] misc/carbon_fiber_plate 
- [ ] misc/extruder_shape 
- [ ] misc/compressed_coke_clay 
- [ ] misc/quantum_eye 
- [ ] misc/plant_ball 
- [ ] misc/raw_crystal_chip_parts 
- [ ] misc/carbon_fiber_mesh 
- [ ] misc/petri_dish 
- [ ] misc/power_thruster 
- [ ] misc/neuro_processing_unit 
- [ ] misc/glass_lens 
- [ ] misc/firebrick 
- [ ] misc/advanced_power_thruster 
- [ ] misc/coke_oven_brick 
- [ ] misc/tungsten_grinding_head 
- [ ] misc/programmed_circuit 
- [ ] misc/mold 
- [ ] misc/battery_hull 
- [ ] misc/diamond_grinding_head 
- [ ] misc/engraved_crystal_chip 
- [ ] misc/empty_mold 
- [ ] misc/credit 
- [ ] misc/raw_carbon_fibers 
- [ ] misc/sticky_resin 
- [ ] misc/crystal_cpu 
- [ ] misc/bio_chaff 
- [ ] misc/compressed_fireclay 
- [ ] misc/raw_crystal_chip 
- [ ] misc/purple_drink 
- [ ] misc/ancient_gold_coin 
- [ ] misc/quantum_star 
- [ ] misc/chemical_dye 
- [ ] misc/blacklight 
- [ ] misc/empty_wooden_form 
- [ ] misc/gelled_toluene 
- [ ] misc/coil 

## tools 
- [x] tools/saw 
- [x] tools/mining_hammer 
- [x] tools/hammer 
- [x] tools/file 
- [x] tools/screwdriver 
- [x] tools/knife 
- [x] tools/wire_cutter 
- [x] tools/mallet 
- [x] tools/crowbar 
- [x] tools/wrench 
- [x] tools/mortar 

## covers 
- [ ] covers/infinite_water_cover 
- [ ] covers/solar_panel 
- [ ] covers/item_tag_filter 
- [ ] covers/crafting_table_cover 
- [ ] covers/ender_fluid_link_cover 
- [ ] covers/machine_controller_cover 

## generation 
- [ ] generation/rubber_sapling 

## parts 
- [ ] parts/auto_maintenance_hatch 
- [ ] parts/fluid_hatch 
- [ ] parts/monitor_screen 
- [ ] parts/data_access_hatch 
- [ ] parts/energy_hatch 
- [ ] parts/item_passthrough_hatch 
- [ ] parts/rotor_holder 
- [ ] parts/maintenance_hatch 
- [ ] parts/fluid_passthrough_hatch 
- [ ] parts/item_bus 
- [ ] parts/me_hatch 

## components 
- [ ] components/data_orb 
- [ ] components/electric_motor 
- [ ] components/data_stick 
- [ ] components/data_module 

## mv 
- [ ] mv/electric_blast_furnace 
- [ ] mv/pyrolyse_oven

**Comment by Yefancy** [comment]
![8653c303d2d04a6bf0d0871e6f0308c3](https://github.com/GregTechCEu/GregTech-Modern/assets/18493855/72bc3a9f-efeb-4c4b-9a57-0c0ecfd438a6)

![5ffc6fcf7084b1c16d9e6594ab77e3f9](https://github.com/GregTechCEu/GregTech-Modern/assets/18493855/5da1c5f9-4b9e-4747-9f2c-5a1e8b46ae65)

**Comment by blackdragon2447** [comment]
The circuits section can be checked off  (#604).
