### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by ChromaPIE** [GregTechCEu/GregTechCEu-1.19#527]
### GregTech CEu Version

gtceu-fabric-1.20.1-1.0.14.a-build_269

### Recipe Viewer Installed

REI

### Environment

Not related

### Cross-Mod Interaction

Unsure

### Expected Behavior

I'm playing the game

### Actual Behavior

I'm typing stuff here due to the crash

### Steps to Reproduce

Start the game

### Additional Information

Crash report: https://mclo.gs/yqd8Bvk
full mod list contained

New mods added after the last successful bootup:
physics-mod-3.0.10-mc-1.20.1-fabric
dimdoors-5.3.0-fabric-beta1
ExtendedDrawers-2.0.7+mc.1.20.1
utilitybelt-1.3.6+1.20.1
Powah-5.0.4 (upgraded)
XaeroPlus-Fabric-1.20.1-64-WM1.36.0-MM23.8.4 (upgraded)

**Comment by screret** [comment]
I take it you tried to do F3+T?

**Comment by screret** [comment]
or well ig not if this is on startup
but, i have noticed the issue already (like 2h ago) and have fixed it.

**Comment by ChromaPIE** [comment]
sweet. wasnt expecting such a fast reply and yea reloading the resourcepack crashes the game too but i cant even start the game this time. can we get a snapshot or smth with that fix?
