### ISSUE TITLE
Datapack registry issue?

### ISSUE THREAD

**Issue by ChromaPIE** [GregTechCEu/GregTechCEu-1.19#528]
### GregTech CEu Version

gtceu-fabric-1.20.1-1.0.14.a-build_269

### Recipe Viewer Installed

REI

### Environment

Both

### Cross-Mod Interaction

Yes

### Expected Behavior

See Additional Information

### Actual Behavior

See Additional Information

### Steps to Reproduce

See Additional Information

### Additional Information

https://github.com/MehVahdJukaar/Supplementaries/issues/778
This issue should be enough to provide useful info
Seems like GT Modern is _messing up with datapack registry_, causing the given issue to happen.

**Comment by screret** [comment]
ok i can't be bothered to write that anymore
