### ISSUE TITLE
Primitive pump multiblock part rendering issue

### ISSUE THREAD

**Issue by DStrand1** [GregTechCEu/GregTechCEu-1.19#53]
### GregTech CEu Version

between 1.0.2 and 1.0.3

### Recipe Viewer Installed

REI

### Environment

Forge

### Cross-Mod Interaction

No

### Expected Behavior

Multiblock parts to render properly with cube_bottom_top model for the parent model

### Actual Behavior

Parent model is rotated incorrectly if part is facing up/down

### Steps to Reproduce

1. Build primitive pump with any size of output hatch
2. Rotate hatch to be facing up or down

**Comment by Yefancy** [comment]
fixed in #92
