### ISSUE TITLE
GTCEu tools are not working correctly

### ISSUE THREAD

**Issue by Exzept1on** [GregTechCEu/GregTechCEu-1.19#549]
### GregTech CEu Version

gtceu-forge-1.20.1-1.0.15.a-build_288.jar

### Recipe Viewer Installed

REI

### Environment

Singleplayer, Multiplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

When you press RBM with an axe in your hand on a log block, it should clear the bark, but this does not happen, the same thing happens with cleaning the block from honey and rust.

Same with shovels and paths.

### Actual Behavior

I have to be able to peel the honey off the copper block, peel the rust off the copper block, and peel the bark off the log block.

### Steps to Reproduce

1) Install GTCEU
2) Enter the world
3) Try make path, or anything else described in the topic

**Comment by Krazyclrug** [comment]
Think the tools are not implemented yet. They don't function well, including axe, shovel, hoe. Enchantments are also kinda weird. Sword accepts efficiency, for example.

**Comment by screret** [comment]
The enchants were fixed lately, the tool usages will be fixed in next version

**Comment by Exzept1on** [comment]
It still doesn't work with grass, trees from TFC. For example, shovels, axes from AE2, work perfectly with TFC grass and turn it into paths, but this does not happen with GTCEU shovels.
