### ISSUE TITLE
Multiblock part z-fighting

### ISSUE THREAD

**Issue by DStrand1** [GregTechCEu/GregTechCEu-1.19#55]
### GregTech CEu Version

between 1.0.2 and 1.0.3

### Recipe Viewer Installed

REI

### Environment

Forge

### Cross-Mod Interaction

No

### Expected Behavior

Multiblock part overlays do not z fight

### Actual Behavior

Multiblock part overlays z fight when in formed multiblocks

### Steps to Reproduce

1. Build a steam oven
2. Observe that the overlay for the input is z-fighting

### Additional Information

![2023-04-04_23 48 32](https://user-images.githubusercontent.com/10861407/229985201-af245bc7-db42-4633-adb2-74fab0a20296.png)

**Comment by lordclips** [comment]
If you can point me towards where the issue might be located, I can probably begin sniffing it out.

Unfortunately not knowing the whole project structure in-and-out makes me chronically stupid

**Comment by screret** [comment]
Might be that overlay models in https://github.com/GregTechCEu/GregTechCEu-1.19/tree/master/common/src/main/resources/assets/gtceu/models/block/machine/part/ etc. Don't have those .002 offsets to the face rendering in code.

**Comment by lordclips** [comment]
Call to:
https://github.com/Low-Drag-MC/LDLib-Architectury/blob/1.19.2/common/src/main/java/com/lowdragmc/lowdraglib/client/bakedpipeline/FaceQuad.java#L27
in:
https://github.com/GregTechCEu/GregTechCEu-1.19/blob/5fe2524ff576ef3aa4f227c17f8a1ce458921108/common/src/main/java/com/gregtechceu/gtceu/client/model/WorkableOverlayModel.java#LL122C1-L122C1

May need to be altered to add an offset to avoid Z-fighting.
