### ISSUE TITLE
GTCEu stone type ores do not have processing and drop (raw ore)

### ISSUE THREAD

**Issue by Exzept1on** [GregTechCEu/GregTechCEu-1.19#550]
### GregTech CEu Version

gtceu-forge-1.20.1-1.0.15.a-build_288.jar

### Recipe Viewer Installed

REI

### Environment

Singleplayer, Multiplayer

### Cross-Mod Interaction

No

### Expected Behavior

When creating ore via stone type, it does not have recipes, does not have the correct drop (just a block of ore falls out, not raw ore), does not have a processing page in JEI, REI, etc. Only the most ordinary ore can boast of this.

### Actual Behavior

When creating ore, it must have recipes, as well as the usual one, have the right drop (raw ore), have a processing page in JEI, REI.

### Steps to Reproduce

Is this really necessary?

**Comment by screret** [comment]
did you try enabling `allUniqueStoneTypes` in the config?

**Comment by Exzept1on** [comment]
JEI Processing page don't work any way
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/52341158/3619010a-90ea-414d-8768-4d2605ef4c8f)

**Comment by Exzept1on** [comment]
OreRecipeHandler.class, line 104
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/52341158/4243c5eb-625e-43b8-97bd-b44e0500cfc7)

I would suggest making the addition of additional dust material more understandable. In order for the user to add it himself, let's say to specify some material. And not to create material by the name of a stonetype, as is done here. Such a system is implemented on 1.12.
