### ISSUE TITLE
Large Mixing Vessel not processing with Distinct Buses On.

### ISSUE THREAD

**Issue by ShadedPL** [GregTechCEu/GregTechCEu-1.19#554]
### GregTech CEu Version

1.0.15.a

### Recipe Viewer Installed

JEI

### Environment

Dedicated Server

### Cross-Mod Interaction

Unsure

### Expected Behavior

When using Distinct Buses - On, the Mixing Vessel should process the recipe just fine when the ingredients are inside of the correct bus, that is set to the specific program.

### Actual Behavior

Only with Distinct Buses disabled the recipe is actually processed, but this introduces the risk that the wrong resource will be produced.
This was working in the previous versions as far as I remember. Playing currently on ATM9.

### Steps to Reproduce

Have any Large Mixing Vessel with more than 1 bus (in my case I have 5, each set to different programs, and all are set to Distinct Buses - On.

### Additional Information

So far I saw this behavior only with Large Mixing Vessel, other blocks like Rotary Heart Furnaces work fine with Distinct Buses enabled.

**Comment by mikerooni** [comment]
Likely related to #512, not 100% sure though

**Comment by ShadedPL** [comment]
I tested if the behavior happens in the Assembling Factory and making coils with programmed buses to 1 and Distinct Buses on works just fine, so that's probably another issue.

**Comment by ShadedPL** [comment]
I tried to enable Distinct Buses again on the Mixing Vessel and it ran now without a problem. Maybe there was another reason why this was not working, could be during a restart it got stuck somehow... Closing for now until I can successfully reproduce. :)

**Comment by ShadedPL** [comment]
Ok, so I can confirm, this happens every time I update the mod (inside of ATM9) but as soon as a reset the distinct buses setting it works again. But it's a pain to have this setup each time I update. Especially because it's happening not only with Mixing Vessels but also Hearth Furnaces and Large Material Press.

**Comment by mikerooni** [comment]
I assume since you reported this as happening on a dedicated server, that you weren't restarting the server unless you had to update. Is this correct?

If so, this will be fixed with the upcoming PR #787 - otherwise, please try to confirm whether your bug is fixed in the next version that will be released (and reopen the issue if necessary).
