### ISSUE TITLE
Pipe connection logic

### ISSUE THREAD

**Issue by serenibyss** [GregTechCEu/GregTechCEu-1.19#56]
### GregTech CEu Version

between 1.0.2 and 1.0.3

### Recipe Viewer Installed

REI

### Environment

Forge

### Cross-Mod Interaction

No

### Expected Behavior

Pipe logic to function like in GTCEu 1.12.2

### Actual Behavior

Pipe logic functions more similarly to GTCE

### Steps to Reproduce

I will take this issue, I am just noting it so I don't forget

**Comment by Yefancy** [comment]
achieved
