### ISSUE TITLE
Parallel Hatch not working properly with ALCR

### ISSUE THREAD

**Issue by ShadedPL** [GregTechCEu/GregTechCEu-1.19#565]
### GregTech CEu Version

1.0.15.a

### Recipe Viewer Installed

JEI

### Environment

Dedicated Server

### Cross-Mod Interaction

Yes

### Expected Behavior

Have the ALCR process all recipes at ones if it has the right ingredients, just like other machines do when they have the parallel upgrade installed.

### Actual Behavior

One crafting job is making Sulfuric Acid 
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/4216212/9fdd4127-3322-4ef1-af85-67aea584d026)
And this is working fine the machine is working.
BUT
As you see below two I'm running additional two recipes but they are currently stuck as the machine is still crafting sulfuric acid but I see the ingredients inside of the machine with the correct proportions, so it should be able to process.
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/4216212/439e76e3-684f-4ae0-b979-564dcbd50d03)

### Steps to Reproduce

Any ALCR with parallel upgrade (in my case Ultimate - 64)
Have 2 or more recipes scheduled at ones, so multiple hatches are occupied with correct ingredients.

### Additional Information

My parallel hatch is set to 64
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/4216212/b5d1313e-0f1b-46e1-857a-c62d38f25e00)
One more thing to note - once the sulfuric acid finished the machine actually seems to have run both of the other ingredients in parallel but still it should have done it during the Acid crafting.
Maybe this has something to do that one was in program 24 and the other without a program?

**Comment by screret** [comment]
it don't work like that tho

**Comment by screret** [comment]
parallel runs a single recipe multiple times in the time of one

**Comment by ShadedPL** [comment]
ahhh I see, yeah just tested 1 vs 256.. significant difference! Thought that actually makes multiple different recipes at once.. Thanks for the prompt help! :)
