### ISSUE TITLE
Some UIs break item renderers

### ISSUE THREAD

**Issue by DStrand1** [GregTechCEu/GregTechCEu-1.19#57]
### GregTech CEu Version

between 1.0.2 and 1.0.3

### Recipe Viewer Installed

REI

### Environment

Forge

### Cross-Mod Interaction

Yes

### Expected Behavior

Item renderers to look normal, like when in creative ui
![2023-04-05_19 08 55](https://user-images.githubusercontent.com/10861407/230240664-25106df1-4067-4cca-baf1-74340abd287e.png)

### Actual Behavior

Item renderers are broken
![2023-04-05_19 08 58](https://user-images.githubusercontent.com/10861407/230240680-d7bc44fb-cd07-4544-97c0-caac25ce2a03.png)

### Steps to Reproduce

Place a machine (Kinetic Mixer used here) and look for more complex renders in REI

### Additional Information

Unknown if this happens to other recipe/item viewer mods like JEI or EMI

**Comment by screret** [comment]
i think this might be caused by LDlib not calling renderBackround() in ModularUIGuiContainer
at least REI whines a whole lot about it on fabric.
