### ISSUE TITLE
Parallel Processing bug list (and some others)

### ISSUE THREAD

**Issue by Arochio** [GregTechCEu/GregTechCEu-1.19#574]
### GregTech CEu Version

1.0.15.a

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

Parallel bugs and some others (1.20.1):

Recipes that wont parallel:
-Ultimate voltage coil

Recipes that take longer with parallel (256 parallel = 256x as long):
-titanium triflouride dust (lcr)
-tons of rotary hearth furnace recipes including but not limited to trinium sulfide recipe, enriched naq sulfate recipe, naquadria sulfate recipe, etc.

Recipes that wont start due to voltage restrictions: (only a bug bc wont start if higher)
(if one of these recipes is queued, but the parallel hatch is set higher, it wont even start bc of the voltage)
(UEV voltage divided by recipe voltage cost per tick)
-liquid neutronium: 56x parallel max
-most fusion reactor recipes

General:
-if the parallel control hatch is changed mid recipe, the next recipe parallels the same as the previous one, and does not change.
-output buses/hatches do not output their full inventory every tick, causing parallel recipes to get backed up
-electric pumps and conveyors dont get any faster after LuV (65536 mb/t and 16 stacks/s)
-distinct buses setting needs to be toggled occasionally before recipes work (usually after server/world restart)
-anything that touches a cleanroom lags upon block updates (mostly machines being charged)
-LuV processing array takes longer when there are more recipes running at once (its legit faster to use a single machine outside of the PA)
-LuV processing array will not always use the highest possible voltage OC for a recipe (it made my NaN at IV voltage)

### Actual Behavior

see above

### Steps to Reproduce

see above

**Comment by screret** [comment]
- parallel issues are actual issues, except fusion & neutronium. 
- parallel hatch issue is real
- hatch issue is real
- they don't get faster because that'd be laggy AF
- hm. weird.
- skull, how does that even happen?? multi pattern checks maybe?
- fuck. HOW
- PA uses the tier of the machines inside. or did you have an UV compressor in there? It might also be capped at the tier of the PA.

**Comment by mikerooni** [comment]
Semi-related: #512

**Comment by Arochio** [comment]
> * PA uses the tier of the machines inside. or did you have an UV compressor in there? It might also be capped at the tier of the PA.

i had a UV machine inside, yeah, but regardless it should have run at LuV not IV

**Comment by loving2** [comment]
If it helps, here's a [spark profile](https://spark.lucko.me/UXKzNPB2T6) where the Large Assembling Factory was sitting idle with a bunch of stuff to make superconducting coils in an input bus & hatch. It seems to cause pretty intense tick lag until the input bus is cleared out enough for it to start running the recipe 4-16 at a time. Specifically, it looks like it gets to [here](https://github.com/GregTechCEu/GregTech-Modern/blob/1.20.1/common/src/main/java/com/gregtechceu/gtceu/api/recipe/GTRecipeType.java#L225) and hangs at recipe lookup I think?

**Comment by screret** [comment]
I think the lag might come from it trying to go over what it's able to parallel, failing, going 1 parallel lower and trying again over and over
