### ISSUE TITLE
Tags not added to generated materials

### ISSUE THREAD

**Issue by Drackion** [GregTechCEu/GregTechCEu-1.19#58]
### GregTech CEu Version

v1.0.2

### Recipe Viewer Installed

JEI

### Environment

Singleplayer Forge

### Cross-Mod Interaction

Yes

### Expected Behavior

When creating a new material with kubejs you should be able to turn the ingot into nuggets and vice versa

### Actual Behavior

you are unable to convert between: blocks, ingots & nuggets. with kubejs generated materials due to the recipes being tagged based and the items are missing the tags
![image](https://user-images.githubusercontent.com/64641342/230802738-d41a6cfc-f86c-4989-8c35-1760c1eae4f0.png)

### Steps to Reproduce

generate new material with kubejs and check the recipes of the ingot/nugget/block

**Comment by DStrand1** [comment]
Closed by #59
