### ISSUE TITLE
EBF tripping with recipes, 2x MV Energy Hatch and Nichrome coils.

### ISSUE THREAD

**Issue by 34486** [GregTechCEu/GregTechCEu-1.19#584]
### GregTech CEu Version

1.0.16 - 308

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

I expected to be able to make my steel ingots when putting iron and oxygen into the EBF, with 2 mv energy hatches that get an amp of MV power each with Nichrome coils. 

### Actual Behavior

The EBF will run, and then start to starve for power and keep tripping on and off.

### Steps to Reproduce

Make EBF with 2x MV Energy hatches, supply them with an amp of MV each, use Nichrome coil blocks and supply Oxygen and Iron to try to make steel, it will trip. 

### Additional Information

I think a while ago I discussed this and it was a discount problem where it multiplied it instead of removing required energy per tick???????? When you look at tooltip it is using 388eu/t at "HV" because its HV capable, but I am using an MV recipe that should only require 120eu/t?

**Comment by blackdragon2447** [comment]
> I think a while ago I discussed this and it was a discount problem where it multiplied it instead of removing required energy per tick???????? When you look at tooltip it is using 388eu/t at "HV" because its HV capable, but I am using an MV recipe that should only require 120eu/t?

It is indeed an MV recipe, but since your EBF is capable of running at HV, it'll overclock the MV recipe to run at HV making it faster but using HV energy. You should be able to limit the overclock in the controllers GUI.

> Make EBF with 2x MV Energy hatches, supply them with an amp of MV each, use Nichrome coil blocks and supply Oxygen and Iron to try to make steel, it will trip.

Each MV Hatch actually takes 2A of MV hower so if you put two the EFB expects to get 4A MV (which equals 1A HV).

**Comment by 34486** [comment]
OH ok I have 16 amps of mv going to it but that doesnt matter because 128+128 is not 388 that it requires to run hv recipe. I am unable to underclock it, it says only [ULV, ULV] are avail and just a small red button... no arrow..? I have /reloaded as well to make sure its not one of the things that might be broken unless you /reload?

**Comment by ghzdude** [comment]
You can only "underclock" the EBF by removing one of the energy hatches, forcing the EBF to run at MV speeds.
By having two MV hatches, the EBF can run HV recipes, and overclockes MV recipes to HV as well, meaning you have to supply around 4 amps of MV to satisfy the energy requirements.

**Comment by 34486** [comment]
Ok I see that now, but still how can I have my 2 mv hatches with 16 amps available to them and it uses a recipe at 388 eu/t, and cannot maintain it. It should maintain it then right? I am supplying plenty of mv amperage to it, steady. I must be flat out missing something. I have tried lossless cables and have had no change, its 4x blue alloy cable I use there. 
![2023-11-28_19 14 33](https://github.com/GregTechCEu/GregTech-Modern/assets/19638851/1226b8cb-7888-425e-9626-43f98dc7fa84)

**Comment by 34486** [comment]
![2023-12-01_18 58 09](https://github.com/GregTechCEu/GregTech-Modern/assets/19638851/a1e34a9e-08d6-4d97-87bf-7e3366a1d911)
This here does work though, so are transformers not correctly working because it should be the same thing if I just hook up the hi amp 4x transformer rather than it plus the normal transformer.... right????

**Comment by Y3llowL1ght** [comment]
[transformer code related to the bug imo](https://github.com/GregTechCEu/GregTech-Modern/blob/1.20.1/src/main/java/com/gregtechceu/gtceu/common/machine/electric/TransformerMachine.java#L78-L91)

multiplication of energy buffer by baseAmp in transformUp mode should fix this as currently all variants of transformer (hi-amp, regular, etc) have the same energy buffer, hi-amp transformers are basically rendered useless and do not work correctly until this is resolved, pls fix :P

**Comment by screret** [comment]
okie thx
