### ISSUE TITLE
Fortune

### ISSUE THREAD

**Issue by grain12** [GregTechCEu/GregTechCEu-1.19#590]
### GregTech CEu Version

1.0.16

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

A pickaxe with luck enchantment 3 increases ore drops

### Actual Behavior

When using a pickaxe on Luck 3, the amount of mined ore does not increase or very little.

### Steps to Reproduce

Mining ore from gregtech with a pickaxe for luck 3

### Additional Information

Perhaps I'm wrong or what I do not know, but when I mine ore from other mods for example thermal foundation, the amount increases when mining, and when I mine ore from gregtech is mainly mined 1 ore and 2 stone dust

**Comment by Drackion** [comment]
This is not a bug, the ability for gtceu ores to be affected by fortune when mining them was removed a few updates ago

**Comment by screret** [comment]
It may come back once we rebalance ores to work with it.

**Comment by grain12** [comment]
I hear you, thanks for the reply
