### ISSUE TITLE
REI recipe move doesn't match correctly

### ISSUE THREAD

**Issue by Phoupraw** [GregTechCEu/GregTechCEu-1.19#593]
### GregTech CEu Version

fabric-1.20.1-1.0.16

### Recipe Viewer Installed

REI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/50520903/85108723-569f-407f-9457-f7ffdcfb878c)
Tools are ready.

### Actual Behavior

Tools aren't considered as ready.

### Steps to Reproduce

1. Get some tools.
2. Check a recipe that uses these tools.
3. Mismatch.

### Additional Information

EMI works fine.
Wasn't tested in forge.

**Comment by FrnkPsycho** [comment]
can confirm the same issue on forge version. The fast slot craft seems not recognizing tools with non-full durability.
