### ISSUE TITLE
LCR OverClocking Issue

### ISSUE THREAD

**Issue by Drackion** [GregTechCEu/GregTechCEu-1.19#6]
### GregTech CEu Version

1.0.0

### Recipe Viewer Installed

REI

### Environment

Singleplayer Forge

### Cross-Mod Interaction

Unsure

### Expected Behavior

The LCR with a 4amp HV hatch should overclock to EV.

### Actual Behavior

The LCR will sometime think its overclocking to IV after completing a craft.
![2023-03-21_20 43 56](https://user-images.githubusercontent.com/64641342/226574353-6f06e024-ce9c-4afd-ae70-9459f4b9059b.png)
![2023-03-21_20 44 02](https://user-images.githubusercontent.com/64641342/226574371-8d823c8c-8849-4659-a70f-10e8407fcc0d.png)
![2023-03-21_20 44 07](https://user-images.githubusercontent.com/64641342/226574375-b56cc3bc-b551-45ff-aefa-c3863b2eac03.png)

### Steps to Reproduce

Steps:
1- set LCR are up with 4amp HV input, 3 fluid inputs, 1 fluid output & 1 item input
2- set ae2 up to autocraft PTFE in the LCR
3- autocraft PTFE
4- check LCR controller if still at EV repeat step 3

### Additional Information

the front of the LCR with ae2 attached
![2023-03-21_21 09 18](https://user-images.githubusercontent.com/64641342/226575303-842a6110-9eea-489a-ba2b-b4762b97ae52.png)

**Comment by Yefancy** [comment]
yeah, fixed.
