### ISSUE TITLE
Ore NBT messing with checking recipe in JEI

### ISSUE THREAD

**Issue by Drackion** [GregTechCEu/GregTechCEu-1.19#61]
### GregTech CEu Version

v1.0.2

### Recipe Viewer Installed

JEI

### Environment

Singleplayer Forge

### Cross-Mod Interaction

No

### Expected Behavior

when checking the uses of GT ores the forge hammer and macerator recipe should pop up

### Actual Behavior

Checking uses:
- endstone ores show the macerator recipe
- red sand ores show the forge hammer recipe
- other ore types show only the furnace recipe

Other Ore type:
![image](https://user-images.githubusercontent.com/64641342/232278068-85591012-19f7-4a46-9bb0-d4b4d2e7d16e.png)

Endstone Ores:
![image](https://user-images.githubusercontent.com/64641342/232278102-81fe4186-3664-43d9-896c-eaacb9ab18a7.png)

Red Sand Ores:
![image](https://user-images.githubusercontent.com/64641342/232278115-c743b736-5416-4fa7-b98c-28703b926dae.png)

### Steps to Reproduce

no steps are needed

**Comment by DStrand1** [comment]
Closed by #59
