### ISSUE TITLE
Loss of surface mineral texture

### ISSUE THREAD

**Issue by Sovina1991** [GregTechCEu/GregTechCEu-1.19#613]
### GregTech CEu Version

gtceu-forge-1.19.2-1.0.17

### Recipe Viewer Installed

None

### Environment

 Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/47661362/05b65596-5e03-4448-b482-a67434de0247)

### Actual Behavior

Loss of surface mineral texture

### Steps to Reproduce

loading a world

**Comment by mikerooni** [comment]
Do you have any rendering mods installed? That doesn't happen by default.

**Comment by screret** [comment]
not enough information.
