### ISSUE TITLE
Stacked wooden brick forms are duplicated in compressed coke clay recipe

### ISSUE THREAD

**Issue by Fastmapler** [GregTechCEu/GregTechCEu-1.19#616]
### GregTech CEu Version

1.10.17

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Expected Behavior

After making compressed coke clay in a crafting table, a stack of wooden brick forms should not be consumed or duplicated

### Actual Behavior

After crafting the stack of wooden forms (> 1 form) in the crafting grid will be duplicated, even over the max stack of 64

### Steps to Reproduce

1) Obtain materials to make compressed coke clay
2) Put the items in the crafting grid, but make sure the form has atleast two in the stack
3) Craft compressed coke clay and the forms should duplicate
<img width="271" alt="Screenshot 2023-12-08 144601" src="https://github.com/GregTechCEu/GregTech-Modern/assets/22627974/27ea3acb-7669-4d53-a4a8-178c06f8ec3c">
<img width="255" alt="Screenshot 2023-12-08 144639" src="https://github.com/GregTechCEu/GregTech-Modern/assets/22627974/c5b89b69-125a-474e-b829-eae512599fd6">

### Additional Information

I am not sure if wooden forms are supposed to be stackable. I also tried using machine recipes with stacked casting and extruder molds but that seemed to work fine.

**Comment by willkel224** [comment]
Also had this issue. Stacks went up to ~4000 in while holding them.

**Comment by a-a-GiTHuB-a-a** [comment]
Random theory:
When crafting a thing, items are consumed. So the wooden form would be eaten when crafting the clay.

This is not good.

So perhaps they double the amount of wooden forms right before one is taken. This works perfectly when there's only one form (2*1-1=1), and it's not that useful to have multiple.
However, when there's more than one (for example, a full stack), 2n-1>>n. It would explain 64 --> 127, at least.
