### ISSUE TITLE
Crash when removed pipe with attached cover

### ISSUE THREAD

**Issue by AKlug1** [GregTechCEu/GregTechCEu-1.19#618]
### GregTech CEu Version

1.0.16

### Recipe Viewer Installed

None

### Environment

Singleplayer and Multiplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

Not crash

### Actual Behavior

Crash

### Steps to Reproduce

Attach cover to pipe
Use wrench to disconnect side of pipe with cover

### Additional Information

Looks like it deletes the connection before removing the cover, so the cover tries to reference a null object
[crash-2023-12-08_20.46.16-server.txt](https://github.com/GregTechCEu/GregTech-Modern/files/13622313/crash-2023-12-08_20.46.16-server.txt)

**Comment by lonevox** [comment]
Just encountered this crash too. It also seemed to put the pipe block in an invalid state, so reopening the world caused the crash to happen again.
