### ISSUE TITLE
Crash when creating a new world

### ISSUE THREAD

**Issue by 08118651** [GregTechCEu/GregTechCEu-1.19#619]
### GregTech CEu Version

forge-1.19.2-1.0.17

### Recipe Viewer Installed

None

### Environment

 Singleplayer

### Cross-Mod Interaction

No

### Expected Behavior

Successfully create the world

### Actual Behavior

crash
[crash-2023-12-10_11.00.31-client.txt](https://github.com/GregTechCEu/GregTech-Modern/files/13626361/crash-2023-12-10_11.00.31-client.txt)

### Steps to Reproduce

Create the world

**Comment by alazeprt** [comment]
I also encountered this problem
[latest.log](https://github.com/GregTechCEu/GregTech-Modern/files/13642093/latest.log)
[crash-2023-12-12_08.02.57-client.txt](https://github.com/GregTechCEu/GregTech-Modern/files/13642094/crash-2023-12-12_08.02.57-client.txt)
After I uninstalled this mod, everything was restored

**Comment by degoz16** [comment]
I found quite similar issue on 1.20.1-1.0.20
[latest.log](https://github.com/GregTechCEu/GregTech-Modern/files/13853189/latest.log)
[crash-2024-01-07_18.16.36-server.txt](https://github.com/GregTechCEu/GregTech-Modern/files/13853188/crash-2024-01-07_18.16.36-server.txt)

**Comment by screret** [comment]
> I found quite similar issue on 1.20.1-1.0.20 [latest.log](https://github.com/GregTechCEu/GregTech-Modern/files/13853189/latest.log) [crash-2024-01-07_18.16.36-server.txt](https://github.com/GregTechCEu/GregTech-Modern/files/13853188/crash-2024-01-07_18.16.36-server.txt)

your issue isn't the same.
