### ISSUE TITLE
Wires as in Immersive Engineering or Create

### ISSUE THREAD

**Issue by Exzept1on** [GregTechCEu/GregTechCEu-1.19#627]
### Feature Description

The wires as a block are outdated, and they are also not convenient. I suggest making relays and wires like coils, which by the way already exist.
I don't see any point in explaining the mechanics, it already exists in IE and Create.
As for the fate of the current wires, I don't know if it makes sense to leave them, but perhaps you can leave only the densest wires for laying some high-voltage power lines.

**Comment by screret** [comment]
nay

**Comment by mikerooni** [comment]
While I don't think this would fit base GT very well, you could absolutely make an addon for this ^^
