### ISSUE TITLE
The robotic arm is not working properly

### ISSUE THREAD

**Issue by hkrt69iruk** [GregTechCEu/GregTechCEu-1.19#629]
### GregTech CEu Version

forge 1.0.17 a_build_343

### Recipe Viewer Installed

JEI

### Environment

Open to LAN

### Cross-Mod Interaction

No

### Expected Behavior

The robotic arm supplies items with precision

### Actual Behavior

The robotic arm tuned to precise replenishment doesn't work,No matter how many items are set, as long as there is an item will be entered
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/36347893/cff6c4e6-9be0-4069-9b61-28abfd62a740)

### Steps to Reproduce

At the time of setting

**Comment by hkrt69iruk** [comment]
ATM9

**Comment by mikerooni** [comment]
I can't reproduce this on the latest version.
