### ISSUE TITLE
Crash when placing/or joining a world where Advanced Combustion Generator II is placed

### ISSUE THREAD

**Issue by LtMost** [GregTechCEu/GregTechCEu-1.19#63]
### GregTech CEu Version

gtceu-1.0.0+gtceu-fabric-1.19.2-fixes

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Expected Behavior

the block gets placed and can be used.

### Actual Behavior

the block gets placed, then the game crashes but saves the world. when trying to join the world after, it crashes when done loading.

### Steps to Reproduce

create a world,
get Advanced Combustion Generator II form Creative inventory,
right click it on the ground.

**Comment by cocona20xx** [comment]
Can't replicate on workflow build e7cb99c with just Quilt Loader + Quilted FAPI + GTCEu + LowDragLib installed. Placing the Advanced Combustion Generator II doesn't crash, nor does reloading the world.
