### ISSUE TITLE
Ore Indicator Problem List

### ISSUE THREAD

**Issue by mikerooni** [GregTechCEu/GregTechCEu-1.19#630]
This is a list of currently known issues with ore indicators.

- [x] Ore Indicators are generated in superflat worlds
- [x] Indicators generate mid-air if the center of the vein generates aboveground
- [x] Indicators generate in empty/void chunks in the end
- [x] Indicators generate even if the vein didn't
- [x] #613

**Comment by MindBrain27** [comment]
I noticed using Ex Deorum I had the Indicators spawning in mid air in a void world in all dimensions but using Skyblock Builder there were no more floating Indicators in any dimensions.

If using Ex Deorum it has a few bugs and I think that's on their side.

**Comment by EntityinArray** [comment]
Ore indicator also spawn midair when ore vein is in the ocean
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/18554021/11417f67-b79d-438d-9a54-8005317aecbd)

**Comment by mikerooni** [comment]
> Ore indicator also spawn midair when ore vein is in the ocean

This will be fixed in the next version ^^
