### ISSUE TITLE
Mixin Conflict with Alloy Forgery

### ISSUE THREAD

**Issue by sleepy-evelyn** [GregTechCEu/GregTechCEu-1.19#638]
### GregTech CEu Version

1.20.1-1.0.18-fabric

### Recipe Viewer Installed

REI

### Environment

N/A

### Cross-Mod Interaction

Yes

### Expected Behavior

Not to crash :3

### Actual Behavior

Crashed

### Steps to Reproduce

Load with Alloy Forge

### Additional Information

Load the mod with Alloy Forgery 2.1.2 installed as well

**Crash Report**: https://gist.github.com/sleepy-evelyn/51ae8df42069d11b6255f910dc7cbcdf

**Comment by screret** [comment]
fabric is deead, fabric is dee-ee-eeaaad

**Comment by sleepy-evelyn** [comment]
Wtf the mod is cross compatible. That doesn’t make any sense.

**Comment by sleepy-evelyn** [comment]
Oh wait never-mind. Y’all gave up on Fabric.

**Comment by screret** [comment]
> Wtf the mod is cross compatible. That doesn’t make any sense.

not anymore, way too much effort to support fabric for the 1% of the userbase

**Comment by sleepy-evelyn** [comment]
> > Wtf the mod is cross compatible. That doesn’t make any sense.
> 
> not anymore, way too much effort to support fabric for the 1% of the userbase

Well no wonder. The mods still in alpha for Fabric. Peeps don’t add alpha mods to mod-packs for obvious reasons.
Not to mention integration with fabric mods was horrendous. Case in point. EMI didn’t work properly either

**Comment by screret** [comment]
people did add the alpha forge version to many packs, though.

**Comment by sleepy-evelyn** [comment]
> people did add the alpha forge version to many packs, though.

Not really. Nearly all the downloads for the mod came exclusively from ATM9: https://legacy.curseforge.com/minecraft/mc-mods/gregtechceu-modern/relations/dependents

Compare this to Alloy Forgery: https://legacy.curseforge.com/minecraft/mc-mods/alloy-forgery/relations/dependents
