### ISSUE TITLE
gt conflicts with kubejs

### ISSUE THREAD

**Issue by Stobine** [GregTechCEu/GregTechCEu-1.19#64]
### GregTech CEu Version

1.19.2 (alpha 1.0.0)

### Recipe Viewer Installed

None

### Environment

singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

minecraft was expected to launch 

### Actual Behavior

eventually crashed (https://paste.ee/p/eG3xS)

### Steps to Reproduce

i started minecraft with mods gt and kube js

**Comment by screret** [comment]
Install kubejs' library mods, this isn't gtceu's fault.
`Mod ID: 'architectury', Requested by: 'kubejs', Expected range: '[6.2.46,)', Actual version: '[MISSING]'
	Mod ID: 'rhino', Requested by: 'kubejs', Expected range: '[1902.2.2-build.263,)', Actual version: '[MISSING]'`

**Comment by Stobine** [comment]
thank you!
