### ISSUE TITLE
Items don't flow through item pipes when inserted by a hopper

### ISSUE THREAD

**Issue by moozilla** [GregTechCEu/GregTechCEu-1.19#647]
### GregTech CEu Version

1.20.1-1.0.18.a

### Recipe Viewer Installed

None

### Environment

Singleplayer, GregTech CEu Modern Community Pack

### Cross-Mod Interaction

No

### Expected Behavior

In the following setup I expect the hopper to push charcoal into the item pipe, which then distributes it to both boilers, filling the bottom first and then the top.

![2023-12-23_12 02 47](https://github.com/GregTechCEu/GregTech-Modern/assets/288266/eee7261b-1486-4aa7-8b0d-838d11d0de28)

### Actual Behavior

Only the bottom boiler gets filled with charcoal. Based on several tests it seems like items pushed by the hopper will only ever travel through a single pipe and only in the direction directly in line with the hopper.

Based on the quest book in the community pack suggesting to use pipes with hoppers I suspect this isn't intended. If all pipes do is extend hopper by one block they are useless until LV.

### Steps to Reproduce

I think these screenshots show the simplest way to reproduce.
* The first setup shows that any pipe longer than 1 block will not transfer items pushed by a hopper
* The second setup shows that a 1 long pipe will only push items to inventory directly in front of it
* The final is the original setup but with an item filter added onto the hopper as a cover. **In this case the setup works as expected.**

![2023-12-23_12 31 26](https://github.com/GregTechCEu/GregTech-Modern/assets/288266/b0fae825-c8a2-4b48-a1ee-b7ce390657ed)

![2023-12-23_12 33 25](https://github.com/GregTechCEu/GregTech-Modern/assets/288266/b5f50c6e-cd27-421c-8f15-15066d93b056)

![2023-12-23_20 28 31](https://github.com/GregTechCEu/GregTech-Modern/assets/288266/f2738dc0-d4e2-4f08-a098-e3629f67f58d)

### Additional Information

Not sure if this is the code responsible, but possibly related: https://github.com/GregTechCEu/GregTech-Modern/blob/1.20.1/common/src/main/java/com/gregtechceu/gtceu/common/pipelike/item/ItemNetHandler.java#L87-L88

That this is doing different logic based on if a cover is present or not is what made me think to try adding an item filter.

**Comment by Sparky1492** [comment]
I have this same issues. 

GregTech CEu Modern Community Pack v1.1.1, Singleplayer

Tested GregTech CEu mod Versions
1.20.1-1.0.18.a
1.20.1-1.0.20
1.20.1-1.20.b-build_401
