### ISSUE TITLE
Ore Vein Information

### ISSUE THREAD

**Issue by a-a-GiTHuB-a-a** [GregTechCEu/GregTechCEu-1.19#657]
### Cross-mod Integration

Just Enough Items or Just Enough Resources

### Feature Description

In Nomi-CEu, JEI had a tab called Ore Spawn Information, which gave important information about ores and their veins. One of the most important features of that was the y-level that the given veins spawned in. Since JER has a built-in system for _vanilla_ ores, what if this mod gave _modded_ ores spawn information instead, since vanilla oregen is (I believe) disabled? It would make the experience more fair, especially with the buggy indicators.

**Comment by screret** [comment]
already done.
