### ISSUE TITLE
Liquid Steam Boiler not accepting Creosote input

### ISSUE THREAD

**Issue by mcphersonsw** [GregTechCEu/GregTechCEu-1.19#662]
### GregTech CEu Version

1.19.2

### Recipe Viewer Installed

JEI

### Environment

Dedicated Server

### Cross-Mod Interaction

Unsure

### Expected Behavior

When clicking a bucket of creosote on the fuel indicator in the liquid steam boiler, expect to load 1 bucket of creosote into boiler. 

### Actual Behavior

No creosote is added and the bucket is unaffected

### Steps to Reproduce

Place a low pressure steam liquid boiler. Obtain bucket of creosote. Left/Right click on any of the columns in the liquid boiler, nothing happens.

**Comment by okamt** [comment]
Already fixed in #655
