### ISSUE TITLE
Crash on startup with Weather2

### ISSUE THREAD

**Issue by salviija** [GregTechCEu/GregTechCEu-1.19#663]
### GregTech CEu Version

1.0.18a

### Recipe Viewer Installed

No Recipe Viewer

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

Successful launch.

### Actual Behavior

Crash on startup.

### Steps to Reproduce

1) Install latest version of forge for 1.20.1
2) Install Gregtech CEu Modern and dependencies
3) Install Weather2 and CoroUtil
4) Launch game in Prism Launcher

### Additional Information

Debug log:
[debug.log](https://github.com/GregTechCEu/GregTech-Modern/files/13794514/debug.log)
Latest log:
[latest.log](https://github.com/GregTechCEu/GregTech-Modern/files/13794516/latest.log)

**Comment by salviija** [comment]
I would have really liked to play with Weather2 in my current modpack. Those who also want to play with Weather2 should install Tempest from modrinth until if/when there is a fix.

**Comment by screret** [comment]
not our fault, try installing https://www.curseforge.com/minecraft/mc-mods/coroutil.

**Comment by salviija** [comment]
> not our fault, try installing https://www.curseforge.com/minecraft/mc-mods/coroutil.
I did that, as you can see in the debug log :)

**Comment by screret** [comment]
try with just weather2? because we can't just magically make the config lib disappear

**Comment by salviija** [comment]
> try with just weather2? because we can't just magically make the config lib disappear

it's a required dependency, again, debug log my friend. but i see your point. the stacktrace is calling it an issue with gtceu itself that i am willing to fix, but you seem to think it's not an issue with gtceu itself, what makes you think so?

**Comment by screret** [comment]
![Screenshot_20231229-195559.jpg](https://github.com/GregTechCEu/GregTech-Modern/assets/68943070/683b1d1a-4cc5-4dfc-a8e9-a81cb2ea0258)

It's because forge reports the WRONG ERROR, my friend pal buddy mate friend
