### ISSUE TITLE
Block selection outline is holdout on GregTech ores

### ISSUE THREAD

**Issue by EntityinArray** [GregTechCEu/GregTechCEu-1.19#665]
### GregTech CEu Version

10.0.18a

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Expected Behavior

Block selection outline should look same as with other blocks

### Actual Behavior

When looking at GT ores, block selection outline is transparent/holdout. Allows you to see through the world
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/18554021/782545b2-11e7-496d-ad0d-f5269d5367cb)
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/18554021/f48a611a-153f-4d81-93e4-48d93fb97192)

### Steps to Reproduce

1) Look at a GT ore
2) Notice that selection outline is transparent/holdout

### Additional Information

Issue occurs without any other mods installed

**Comment by Exzept1on** [comment]
can confirm this

**Comment by EntityinArray** [comment]
Hi, i'm really grateful for the effort, but issue still persists for me
Though I don't know if your PR made it to the latest version yet, if it didn't i'm sorry

https://github.com/GregTechCEu/GregTech-Modern/assets/18554021/2731ac4b-701c-4140-b292-8aa986a7b79c

**Comment by screret** [comment]
you aren't on the latest GT version.

**Comment by EntityinArray** [comment]
> you aren't on the latest GT version.

i see, thank you! when latest version comes out on modrinth?

**Comment by screret** [comment]
uh oh our versioning broke
