### ISSUE TITLE
New update invalidated multiblocks

### ISSUE THREAD

**Issue by MindBrain27** [GregTechCEu/GregTechCEu-1.19#678]
### GregTech CEu Version

1.0.19/1.0.19a

### Recipe Viewer Installed

REI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Expected Behavior

Multiblocks stay functioning after updating.

### Actual Behavior

Some multiblocks were changed to only require an ME Output Hatch, invalidating the Multi Smelter and Refinery multiblocks.

### Steps to Reproduce

Update the mod and try to assemble either multiblock.

**Comment by mikerooni** [comment]
Already fixed in 1.0.19.b
