### ISSUE TITLE
high tier quantum chests storage values integer overflow 

### ISSUE THREAD

**Issue by eldritch-cookie** [GregTechCEu/GregTechCEu-1.19#679]
### GregTech CEu Version

1.0.19

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Expected Behavior

Quantum chests would store as much items as my system memory allows

### Actual Behavior

quantum chests higher than X inclusive have integer overflow in maximum capacity

### Steps to Reproduce

1. enable highTierContent in configuration
2. read the tooltip of a quantum chest of level X or higher 

### Additional Information

reproduced with only gregtech as the mod

**Comment by RainPumpkin** [comment]
still happens on latest

**Comment by Pumpkin7266** [comment]
still happens on latest

**Comment by YoungOnionMC** [comment]
fixed in #2447
