### ISSUE TITLE
GT:Modern Axes do not respect SHIFT

### ISSUE THREAD

**Issue by Ghostipedia** [GregTechCEu/GregTechCEu-1.19#681]
### GregTech CEu Version

1.0.19b

### Recipe Viewer Installed

REI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Expected Behavior

While holding shift the tree-felling functionality of all GTCEU axes should be off/disabled

### Actual Behavior

Presently, while holding shift and mining any log-like block, causes the tree-felling functionality to activate. I discovered this the hard way and now half my house is missing.

### Steps to Reproduce

1. Take Iron axe
2. Place logs
3. SHIFT+BREAK those logs
4. Cry as your built creation turns into drops

**Comment by screret** [comment]
will be fixed with das tool rework™
