### ISSUE TITLE
Missing extra outputs from macerators below HV

### ISSUE THREAD

**Issue by kjukmar2** [GregTechCEu/GregTechCEu-1.19#687]
### GregTech CEu Version

1.0.19.b

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

The extra outputs appear, just as the recipe says they would, whe using any macerator.

### Actual Behavior

Extra outputs appear only when using an HV or above macerator, therefore invalidating early-game macerators.

### Steps to Reproduce

Just try and use any low-tier macerator.

### Additional Information

I have learnt that this is by design, but i still can't comprehend why anyone should invalidate the early-game macerators. And with more processed ore, washed copper ore for instance; this ore doesn't yield any byproducts like gold of cobalt when using the steam-low-med voltage machines. Like, why bother with macerators at all when one can just smelt the ore? I'd be infinitely grateful if someone shared the location of some kind of config file in using which this oversight could be fixed, if such thing exists, of course.

**Comment by screret** [comment]
it's to make the player create more oreprocessing machines than just the macerator, as I told you in the ATM9 issue.
