### ISSUE TITLE
Crash when connecting pipes containing fluids

### ISSUE THREAD

**Issue by GoldenMaster8** [GregTechCEu/GregTechCEu-1.19#690]
### GregTech CEu Version

v.1.0.19a

### Recipe Viewer Installed

JEI

### Environment

Server

### Cross-Mod Interaction

Unsure

### Expected Behavior

Not to crash

### Actual Behavior

The game crashed

### Steps to Reproduce

1. Connect a pipe with a fluid going through it
2. Server crashes

### Additional Information

Crash Report : 
[crash-2024-01-05_02.20.22-server.txt](https://github.com/GregTechCEu/GregTech-Modern/files/13839233/crash-2024-01-05_02.20.22-server.txt)

**Comment by GoldenMaster8** [comment]
the fluid going through the pipe is definitely the issue, if you want a more specific pipe, use a small bronze pipe with steam inside

it also seems to happen when breaking the fluid pipe

Here is the crash report for after i break the pipe:
[crash-2024-01-05_02.29.19-server.txt](https://github.com/GregTechCEu/GregTech-Modern/files/13839269/crash-2024-01-05_02.29.19-server.txt)

**Comment by GoldenMaster8** [comment]
This crash still happens in version 1.0.20a

**Comment by GoldenMaster8** [comment]
This crash still happens in the newest version (1.0.20b)

**Comment by BardSk** [comment]
[latest.log](https://github.com/GregTechCEu/GregTech-Modern/files/13939682/latest.log)

**Comment by Magamelin** [comment]
Me to. Fix it with change world\serverconfig\forge-server.toml "removeErroringEntities" and "removeErroringBlockEntities" to true. After that delete all information in .dat file world\data\gtcue_fluid_pipe_net.dat (Backup that file) like was: https://i.imgur.com/qtnL6lW.png result: https://i.imgur.com/etkrd3t.png

Then, start game and break all the problems pipes, then restart and return parameters above to false, like it was. .dat file also restore from copy.

My crash report with details below
[crash-2024-01-28_23.27.07-server.txt](https://github.com/GregTechCEu/GregTech-Modern/files/14077647/crash-2024-01-28_23.27.07-server.txt)

**Comment by GoldenMaster8** [comment]
Will pipes work afterwords? Or do i have to use alternative mods to pipe fluids?

**Comment by screret** [comment]
Should be fixed in the next version whenever that actually releases
