### ISSUE TITLE
Broken loot in pre-generated chests

### ISSUE THREAD

**Issue by StrangestAce** [GregTechCEu/GregTechCEu-1.19#716]
### GregTech CEu Version

1.0.20.a

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Expected Behavior

Creating a new world would generate whole world normally step by step and there would be loot in pre-generated chests.

### Actual Behavior

After new world was created and generated absolutely all pre-generated chests are empty. Via Jade it says "inventory is not generated". I can assume somehow loot tables are broken.

### Steps to Reproduce

1. Create new world
2. Find pre-generated chest
3. Try to open
4. Find it's empty

### Additional Information

Forge 1.19.2 43.3.7

On GT ECu Modern 1.0.19.b world generation works perfectly

**Comment by mcphersonsw** [comment]
Breaking the chest keeps the loot intact.

**Comment by mcphersonsw** [comment]
This was fixed in the most recent release, @StrangestAce
