### ISSUE TITLE
[Fabric 1.19.2] Black screen flickering on startup

### ISSUE THREAD

**Issue by S1mpleM0use** [GregTechCEu/GregTechCEu-1.19#722]
### GregTech CEu Version

1.19.2-1.0.20.b

### Recipe Viewer Installed

No Recipe Viewer

### Environment

Startup

### Cross-Mod Interaction

No

### Expected Behavior

Launching the game without flickering

### Actual Behavior

After "Mojang" logo the game itself tries to load something, but all I can see is black screen. I can see the rainbow background of minecraft with the time interval of 3-4 seconds

### Steps to Reproduce

1. Install fabric loader 0.15.3 (latest) on 1.19.2
2. Install Fabric API
3. Install GregTechCEU modern  1.19.2-1.0.20.b
4. Log in
5. Bug occurs

### Additional Information

[latest.log](https://github.com/GregTechCEu/GregTech-Modern/files/13860745/latest.log)
It seems to be a problem with particles from "LDlib", which causes OpenGL to blow up

**Comment by S1mpleM0use** [comment]
https://youtu.be/NVaqOFcD2R8
video demonstration

**Comment by Exzept1on** [comment]
use forge pls :trollface:

**Comment by screret** [comment]
@Yefancy halp

**Comment by S1mpleM0use** [comment]
`Caused by: java.lang.RuntimeException: net.minecraft.class_2973: Invalid shaders/core/particle.json: Non [a-z0-9/._-] character in path of location: ldlib:ldlib:shaders/core/particle.vsh`

the problem seems to be in the name

**Comment by screret** [comment]
fabric is deead, fabric is dee-ee-eeaaad
