### ISSUE TITLE
A tooltip with a material element is not added for some custom mod items

### ISSUE THREAD

**Issue by Exzept1on** [GregTechCEu/GregTechCEu-1.19#723]
### GregTech CEu Version

1.0.20.b

### Recipe Viewer Installed

JEI

### Environment

Singleplayer, Open to LAN, Dedicated Server

### Cross-Mod Interaction

Unsure

### Expected Behavior

SiO2 should have been added for AE2 items after specifying setIgnored

### Actual Behavior

Nothing

### Steps to Reproduce

Use this in ur mod:
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/52341158/389011ae-cbdf-49b8-a488-a2710c7645a1)

Where my SiO2:
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/52341158/27efa3a4-389c-4bb4-81ac-9077484d1424)

Like that
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/52341158/73dcd3ce-ad83-4534-acc3-bd9019e41d27)

### Additional Information

This works with Vanilla items, but not works with some modded items from tfc or ae2, idk why

**Comment by screret** [comment]
we can't do that rn, tried, took way too long to load.

**Comment by screret** [comment]
currently, you need to register the unification data for those yourself.
