### ISSUE TITLE
World Generations.

### ISSUE THREAD

**Issue by BardSk** [GregTechCEu/GregTechCEu-1.19#724]
### Cross-mod Integration

Create,im_eng,thermals

### Feature Description

I want to make a generation for the server as in the vanilla version, not in veins. Or leave veins and add vanilla ore generation

**Comment by screret** [comment]
disable `removeVanillaOreGen` and `removeVanillaLargeOreVeins` in the config.

**Comment by BardSk** [comment]
Yes, thank you, already fixed)
