### ISSUE TITLE
EMI crashes when it's showing recipe steps in survival mode inventory

### ISSUE THREAD

**Issue by Despacito696969** [GregTechCEu/GregTechCEu-1.19#726]
### GregTech CEu Version

1.0.20b

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

I tried to see the steps to craft steel crate (but any other gregtech (i'm not sure if only gregtech) item should work), but it just crashes after I enable crafting steps and close the recipe tree. It doesn't happen in creative mode, but when I switched gamemode and opened my inventory it instantly crashed.

### Actual Behavior

doesnt crash smh

### Steps to Reproduce

1. Go into survival mode
2. Find steel crate (or probably any GT item) in EMI
3. Show it's recipe tree
4. Switch the mode to show crafting steps in the inventory
5. Exit to inventory, game should instantly crash

### Additional Information

EMI version: 1.0.30+1.20.1+forge
Forge: 47.2.0
Crash log on my instance that only had greg and EMI
[crash-2024-01-09_01.50.19-client.txt](https://github.com/GregTechCEu/GregTech-Modern/files/13867611/crash-2024-01-09_01.50.19-client.txt)

**Comment by Arborsm** [comment]
wtf

**Comment by Despacito696969** [comment]
It's still broken :trollface:
Forge: 47.2.16
Greg: gtceu-1.20.1-1.1.0-build_424
EMI: emi-1.0.30+1.20.1+forge
[latest.log](https://github.com/GregTechCEu/GregTech-Modern/files/13966633/latest.log)

Also tried updating forge and EMI
Forge: 47.2.20
Greg: gtceu-1.20.1-1.1.0-build_424
EMI: emi-1.1.0+1.20.1+forge
[latest.log](https://github.com/GregTechCEu/GregTech-Modern/files/13966670/latest.log)

**Comment by Arborsm** [comment]
hm? I test last time

**Comment by Arborsm** [comment]
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/44860537/c7e81a02-9b93-48bc-8bdd-a6823294aee3)
???

**Comment by Arborsm** [comment]
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/44860537/f5801399-9c57-4c36-938b-e7d774006247)

**Comment by Despacito696969** [comment]
i used crafting recipe

**Comment by Arborsm** [comment]
> i used crafting recipe

same to me

**Comment by Despacito696969** [comment]
https://github.com/GregTechCEu/GregTech-Modern/assets/56641258/94742ec6-b61d-453c-856f-7ea94cef3a95
this is what happens to me

**Comment by Arborsm** [comment]
ok it just happen, I think I know why now
