### ISSUE TITLE
GregTech tools are shown in every Creative Tab

### ISSUE THREAD

**Issue by Igneaalis** [GregTechCEu/GregTechCEu-1.19#730]
### GregTech CEu Version

gtceu-forge-1.19.2-1.0.20.b

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Expected Behavior

This bug occurred in version 1.0.20.a and higher. In the version 1.0.20 everything was working correctly.
The bug is that you can see GT tools in every creative tabs.
![2024-01-09_11 49 55](https://github.com/GregTechCEu/GregTech-Modern/assets/7469854/0481e79a-e283-459a-9a7e-be3c2e236a5a)
![2024-01-09_11 50 06](https://github.com/GregTechCEu/GregTech-Modern/assets/7469854/914b9413-6454-4faa-9bd6-36142387d5d1)
![2024-01-09_11 50 23](https://github.com/GregTechCEu/GregTech-Modern/assets/7469854/3159d7d8-1607-4263-b9ca-c7ab643d9aea)
![2024-01-09_11 50 40](https://github.com/GregTechCEu/GregTech-Modern/assets/7469854/1397d5be-c7fa-46cd-9e57-cb56f562a575)

### Actual Behavior

It's expected that tools will be shown only in the "GT" creative tab or in the "Tools" creative tab.

### Steps to Reproduce

Set gamemode to Creative and open any creative tab.

**Comment by BabyLy233** [comment]
same probleam

**Comment by LadyAelita** [comment]
Can confirm
