### ISSUE TITLE
Smart Filter same as in Omnifactory, for Electrolyzer and Centrifuge.

### ISSUE THREAD

**Issue by phrostt** [GregTechCEu/GregTechCEu-1.19#731]
### Feature Description

GTCE in Omnifactory has a smart filter, that will automatically pull the correct number of dusts for electrolyzer and centrifuge. GTCE in 1.20 in ATM9 does not have the same filter, its a huge quality of life feature.

**Comment by YoungOnionMC** [comment]
added in #1984
