### ISSUE TITLE
When i press E it crash on the client side

### ISSUE THREAD

**Issue by Jujubegamer** [GregTechCEu/GregTechCEu-1.19#732]
### GregTech CEu Version

gtceu-forge-1.20.1-1.0.20.b

### Recipe Viewer Installed

None

### Environment

dedicated server

### Cross-Mod Interaction

Yes

### Expected Behavior

Open the inventory

### Actual Behavior

crash

### Steps to Reproduce

i host a server minecraft Arclight with the modpack All The Mods 9 in 1.20.1. every thing load correctly but as soon as i press E to open the inventory it crash only on the client side and it say ( The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Registry entry not present: gtceu:nether_star_bucket )
![Capture d’écran (74)](https://github.com/GregTechCEu/GregTech-Modern/assets/69773637/783a82eb-0f6d-4d01-a80d-e87590b56bac)

### Additional Information

[crash-2024-01-09_19.08.16-client.txt](https://github.com/GregTechCEu/GregTech-Modern/files/13881540/crash-2024-01-09_19.08.16-client.txt)

**Comment by Igneaalis** [comment]
It's Arclight related issue. I had the same issue with Arclight and Dragon Survival

**Comment by screret** [comment]
liquid nether star is not a base GT thing.
@Drackion mind looking at this?

**Comment by Drackion** [comment]
if i remember to I'll do it tomorrow as i am off to bed
