### ISSUE TITLE
checking the recipe in an empty slot with [R] causes a crash in JEI.

### ISSUE THREAD

**Issue by redgoblin88** [GregTechCEu/GregTechCEu-1.19#733]
### GregTech CEu Version

1.0.20.b

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

When you have a gregtech crate GUI open with stuff inside, if you hover over an empty slot and press "r", the game will crash. at first i thought this was inventory sorter but i dont have that installed, just mouse tweaks and JEI that changes how you can use the gui stuff

### Actual Behavior

When you press "R" on an empty slot inside the crate with stuff in, the game will crash

### Steps to Reproduce

1. place a crate down
2. put some things into it (im not sure if this contributes/causes the issue, but this was the case i have the crash in)
3. hovering over an empty slot, press "R"

### Additional Information

Crashlog: https://pastebin.com/X0Lu4Tfx

Forge: 47.2.0
JEI: 15.2.0.27
Just Enough Resources: 1.4.0.238
Mouse tweaks: 2.25

**Comment by StellaBiscuit** [comment]
That confirms that ANY empty slot causes the crash

**Comment by screret** [comment]
looks like it's JEI's fault to me?
