### ISSUE TITLE
Watertight steel seems to be missing the recipe in 1.19.2

### ISSUE THREAD

**Issue by Schrubbls** [GregTechCEu/GregTechCEu-1.19#734]
### GregTech CEu Version

1.0.20.b

### Recipe Viewer Installed

REI

### Environment

SP

### Cross-Mod Interaction

Unsure

### Expected Behavior

There should be a recipe for Watertight Steel in the Alloy blast furnace

### Actual Behavior

There isn't a recipe neither dust nor ABS

### Steps to Reproduce

Looking up the recipe in REI

**Comment by Schrubbls** [comment]
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/8899590/753965d5-66c7-4f3e-a6b1-83cccf6a069e)

Hastelloy c-276 seems to be missing too

**Comment by Schrubbls** [comment]
Seems to be a REI skill issue

**Comment by mikerooni** [comment]
Can confirm that this is an REI issue indeed. Note that these are alloy blast smelter recipes.
