### ISSUE TITLE
Crash with using REI and crafting.

### ISSUE THREAD

**Issue by vadimas56** [GregTechCEu/GregTechCEu-1.19#743]
### GregTech CEu Version

1.0.20.b

### Recipe Viewer Installed

REI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

I will successfully craft the required item without crash.

### Actual Behavior

But when you try to craft something with "Move items" (REI function), the game flies out to the main menu with error "Internal Exception: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered"

### Steps to Reproduce

1.Download REI and REIPC and GTCEu modern
2.Install this
3.Go in singleplayer and try craft something with "move items"
P.S.
I took a sheaf of hay and pressed T (in which crafts is it used) and pressed the plus sign (move items) and got a crash in main menu.

### Additional Information

![2024-01-12_20 21 55](https://github.com/GregTechCEu/GregTech-Modern/assets/6242995/c208bd2f-4551-4547-8b03-f2f6faba35b8)
![2024-01-12_20 21 57](https://github.com/GregTechCEu/GregTech-Modern/assets/6242995/2b0527e4-5888-412a-a6c7-cf51354313c2)
![Безымянный](https://github.com/GregTechCEu/GregTech-Modern/assets/6242995/ae5dc118-20e3-40b1-834f-19a4b3014cd7)

**Comment by vadimas56** [comment]
Sry i forgot add crash logs D:
Here is latest.log 
https://mclo.gs/y2Jjsx9
Here is debug.log 
https://mclo.gs/Y3yBi45

**Comment by screret** [comment]
what's your REI version?

**Comment by vadimas56** [comment]
Rei version is 9.1.682 Forge-its last for MC1.19.2

**Comment by mikerooni** [comment]
I can't reproduce this unfortunately.  
Could you please post a list of your installed mods?

**Comment by vadimas56** [comment]
> I can't reproduce this unfortunately. Could you please post a list of your installed mods?
Hello , my mod list:
Forge
REI 
REIPC(Necessary addon for REI)
Gregtech CEU.

**Comment by screret** [comment]
rei plugin compat isn't necessary, though?

**Comment by vadimas56** [comment]
Forge version is - 43.3.7.
But without Reipc it still crashes to the main menu.
Back to home test without resource packs. Maybe because of them the crush.

**Comment by vadimas56** [comment]
Nothing has changed without resource packs.Additionally I installed (this is a necessity for REI) - Cloth Config and Architectury,both are latest version.
When creating world i clicked on the “data packs ” button when creating the world. I am attaching a screenshot, marked in red (as I understand it), they are not there?
Pack folder is empty.
![Безымянный](https://github.com/GregTechCEu/GregTech-Modern/assets/6242995/ed0bbb8a-a5b1-412d-a863-3af3781d905a)

**Comment by screret** [comment]
that doesn't matter. they're the mods' bundled datapacks, and work if you can make a world.

**Comment by vadimas56** [comment]
Ok,thanks to answer my dummy question,now i try delete .minecraft folder and reinstall "Minecraft launcher" and forge.

**Comment by vadimas56** [comment]
Everything is the same. Crash to the main menu when laying out a recipe. Reinstalled Minecraft (1.19.2), Forge (43.3.7).
I am attaching the latest logs. (rey-issues empty)
Crash time - 18:30:06.760
In latest.log and debug.log have 1 error( [main/ERROR] [mixin/]: Mixin config rei.mixins.json does not specify "minVersion" property )
I don’t know what to think anymore, can you advise me?
Mod list:
architectury: 6.5.85
cloth_config: 8.3.115
configuration: 2.2.0
forge: 43.3.7
gtceu: 1.0.20.b
ldlib: 1.0.22.a
minecraft: 1.19.2
mixinextras: 0.2.0-rc.2
roughlyenoughitems 9.1.682


</body>
</html>

[debug.log](https://github.com/GregTechCEu/GregTech-Modern/files/13979303/debug.log)
[latest.log](https://github.com/GregTechCEu/GregTech-Modern/files/13979300/latest.log)
[rei.log](https://github.com/GregTechCEu/GregTech-Modern/files/13979302/rei.log)

**Comment by vadimas56** [comment]
I will change REI to JEI and problem have solved.
