### ISSUE TITLE
Considering about adding a config to enable auto RF to GTEU Transform

### ISSUE THREAD

**Issue by YiRanMushroom** [GregTechCEu/GregTechCEu-1.19#746]
### Feature Description

GregTech Power is always not easy to distribute, and dangerous(easy to explode machines). In newer versions of Minecraft, ppl don't actually want to spend much time to play gregtech, and RF is generally easier to generate. If this were implemented, more modpack creates can put it in to their modpack and still have good interactions with other tech mods.

Although Converters are been added, just from my friend opinions, it's not the polybenzimidazole made them to quit, it's the cables, transformer, and messy wirings.

Not all players are GTNH players, even if they are, it's still a big head ache to manage the power system.

**Comment by screret** [comment]
kinda a skill issue tbh, don't ya think

**Comment by YiRanMushroom** [comment]
Yeah you are right, but just want to mention it in case you are planning it.
