### ISSUE TITLE
Interface problems in all mechanisms

### ISSUE THREAD

**Issue by BardSk** [GregTechCEu/GregTechCEu-1.19#755]
### GregTech CEu Version

gtceu-forge-1.20.1-1.0.17.jar

### Recipe Viewer Installed

JEI

### Environment

Server

### Cross-Mod Interaction

Unsure

### Expected Behavior

![2024-01-15_15 46 12](https://github.com/GregTechCEu/GregTech-Modern/assets/155981752/9ddccb95-8468-4180-8947-cd8e1330a12d)
![2024-01-15_15 44 39](https://github.com/GregTechCEu/GregTech-Modern/assets/155981752/205d5d6b-0237-4f88-ab66-f897cba21a4b)
![2024-01-15_15 44 35](https://github.com/GregTechCEu/GregTech-Modern/assets/155981752/a8aeb62e-675f-44c3-ace9-ea085ad5952f)
![2024-01-15_15 44 27](https://github.com/GregTechCEu/GregTech-Modern/assets/155981752/207a12f3-f9e6-4fd8-8156-e0836bd1cf60)
Interface problems in all mechanisms

### Actual Behavior

![2024-01-15_15 46 12](https://github.com/GregTechCEu/GregTech-Modern/assets/155981752/1570d371-8e4b-406a-ba38-bad42c451f15)
![2024-01-15_15 44 39](https://github.com/GregTechCEu/GregTech-Modern/assets/155981752/386eb60e-f8c6-4586-a6b1-1e7e8b0e0736)
![2024-01-15_15 44 35](https://github.com/GregTechCEu/GregTech-Modern/assets/155981752/748870a6-b815-49ff-9d96-af19316056b8)
![2024-01-15_15 44 27](https://github.com/GregTechCEu/GregTech-Modern/assets/155981752/1dc9209e-e098-436b-8ed3-a8a7ec2ec7b5)
Interface problems in all mechanisms

### Steps to Reproduce

Don`t know

### Additional Information

https://drive.google.com/drive/u/0/folders/1CIAcTULxLqslTVyBoFc1oTM9N86dFKj1   it my modpack. Mb helping

**Comment by screret** [comment]
do you have any resourcepacks?
also we need the latest.log at least

**Comment by screret** [comment]
Because I am NOT downloading a random zip full of jars off google drive

**Comment by BardSk** [comment]
[latest.log](https://github.com/GregTechCEu/GregTech-Modern/files/13939696/latest.log)

**Comment by screret** [comment]
_client_ latest.log

**Comment by BardSk** [comment]
[latest (1).log](https://github.com/GregTechCEu/GregTech-Modern/files/13939767/latest.1.log)

**Comment by screret** [comment]
something is making the GUI atlas all messed up but that doesn't say what.

**Comment by BardSk** [comment]
Can I somehow find out on my own what this could be? Or will only the search for mods help?

**Comment by screret** [comment]
start removing mods until it doesn't happen is all I can say for now

**Comment by BardSk** [comment]
Thanks, I'll try to fix it
