### ISSUE TITLE
Item dupe glitch with Item Filters.

### ISSUE THREAD

**Issue by MindBrain27** [GregTechCEu/GregTechCEu-1.19#760]
### GregTech CEu Version

gtceu-forge-1.20.1-1.0.20.b.jar

### Recipe Viewer Installed

REI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

I expect the mouse wheel function to do nothing within an Item Filter.

### Actual Behavior

When scrolling with mouse wheel on an item in an Item Filter it will either dupe or void the items.

### Steps to Reproduce

Set a Crate down, install a Robotic Arm or a Conveyor. Open the Cover settings with a Screwdriver. Set an item in the Item filter within the Robotic Arm or Conveyor. Used the mouse scroll feature (mouse tweaks?) on the item in the Item Filter to try and scroll an item in or out of your inventory.

If you have more of the items in your inventory and you scroll away, they will seemingly be stored in the actual Item Filter, you can see the number of items in the Item Filter change. If you have no items of that kind in your inventory and scroll towards, it will remove the item from the Item Filter and place it in your inventory.

### Additional Information

Mouse Tweaks and Inventory Essentials are both installed.

**Comment by mikerooni** [comment]
The dupe is caused by simple inventory sorter, in case you have that installed.  
Unfortunately that is something we can't fix on our end.

The scroll behavior (caused by mouse tweaks) is something I still have to look into.

**Comment by MindBrain27** [comment]
Interesting, I do have Inventory Sorter installed, and Mouse Tweaks as well. With Inventory Sorting off the dupe is no longer possible. Thanks!

**Comment by mikerooni** [comment]
I'm gonna have a look into the mouse tweaks bug as well in the future - maybe it's something we can fix on our end.

For sorting, I personally use inventory profiles next. It has way more features though, and takes a bit of configuring to set it up initially, but works great so far.  
I'd recommend it if you're looking for a replacement (and more than that).

**Comment by MindBrain27** [comment]
Amazing, thank you! Will look into that for sure! Does it work with GT Crates as well? Currently Inventory Sorting does not work inside a GT Crate.
