### ISSUE TITLE
Crashing on world gen

### ISSUE THREAD

**Issue by datcat31** [GregTechCEu/GregTechCEu-1.19#764]
### GregTech CEu Version

1.0.20.b

### Recipe Viewer Installed

EMI

### Environment

SP

### Cross-Mod Interaction

Yes

### Expected Behavior

Click the single player button on main menu to go to world select

### Actual Behavior

When i click SinglePlayer its crashes

### Steps to Reproduce

Load up game and start a world

### Additional Information

~100 mods installed
[latest.log](https://github.com/GregTechCEu/GregTech-Modern/files/13959797/latest.log)
[crash-2024-01-16_23.07.43-client.txt](https://github.com/GregTechCEu/GregTech-Modern/files/13959798/crash-2024-01-16_23.07.43-client.txt)

**Comment by screret** [comment]
Enable highTier in the GT config.
GCYR has an issue and I haven't been able to update it.
