### ISSUE TITLE
Make the Steam turbine accept Json recipes.

### ISSUE THREAD

**Issue by Leclowndu93150** [GregTechCEu/GregTechCEu-1.19#77]
### Cross-mod Integration

Cross mod with yo mom

### Feature Description

i want to be able to use Kubejs json recipe system to be able to use custom fuel on turbines.

**Comment by Drackion** [comment]
you can make them using the current Kubejs Integration, which will change soon.
```js
GTCEuServerEvents.recipe(event => {
                 event.builder('steam_turbine', 'meme')
		          .inputFluids('kubejs:energized_ooze 10')
		          .outputFluids('kubejs:mysterious_ooze 10')
		          .duration(10)
		          .EUt(-32)
		          .save(event.provider);
})
```

**Comment by screret** [comment]
> you can make them using the current Kubejs Integration, which will change soon.
> ```js
> GTCEuServerEvents.recipe(event => {
>                  event.builder('steam_turbine', 'meme')
> 		          .inputFluids('kubejs:energized_ooze 10')
> 		          .outputFluids('kubejs:mysterious_ooze 10')
> 		          .duration(10)
> 		          .EUt(-32)
> 		          .save(event.provider);
> })
> ```

Already changed.

**Comment by Leclowndu93150** [comment]
Oh thank you i didnt know that, i hope there will be a well documented wiki
