### ISSUE TITLE
Datapack validation error with ``disableManualCompression: false``

### ISSUE THREAD

**Issue by Fuyukai** [GregTechCEu/GregTechCEu-1.19#770]
### GregTech CEu Version

1.1.0

### Recipe Viewer Installed

None

### Environment

n/a

### Cross-Mod Interaction

No

### Expected Behavior

game does not crash when clicking singleplayer

### Actual Behavior

game *does* crash when clicking singleplayeer

### Steps to Reproduce

1. set `disableManualCompression` to ``false`` in the config
2. run the game
3. click singleplayer

### Additional Information

latest.log: https://gist.github.com/Fuyukai/75d3e25b6f894b713c82ece23c49f497
debug.log: https://gist.github.com/Fuyukai/ca864537dd716ad4ea48262d21a7df20

**Comment by Exzept1on** [comment]
Same error with `hardDyeRecipes: true`
