### ISSUE TITLE
Material Display Names are All English

### ISSUE THREAD

**Issue by CPearl0** [GregTechCEu/GregTechCEu-1.19#771]
### GregTech CEu Version

gtceu-1.20.1-1.1.0-build_425

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Expected Behavior

With language file the materials should display their Chinese name.

### Actual Behavior

![2024-01-18_08 38 23](https://github.com/GregTechCEu/GregTech-Modern/assets/115922715/70403cf4-3a56-457f-8b93-c37208260a1d)
![2024-01-18_08 39 12](https://github.com/GregTechCEu/GregTech-Modern/assets/115922715/c2003cdc-3917-4cc6-862d-3e6bf9505b9c)

### Steps to Reproduce

Turn the language to Chinese

### Additional Information

Neoforge version: 1.20.1-47.1.84

**Comment by screret** [comment]
the chinese language file hasn't been updated yet.
