### ISSUE TITLE
Incorrect Refined Ore Byproduct

### ISSUE THREAD

**Issue by Nyxane** [GregTechCEu/GregTechCEu-1.19#774]
### GregTech CEu Version

1.0.20.b

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

For the Refined Ore Maceration byproduct to match the Ore Diagram ex. Refined Nickel Ore Maceration give Iron dust as a byproduct
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/89574734/c5600915-3e71-42f5-96cf-9eb86e4367c0)

### Actual Behavior

Maceration of Refined Ore giving a Different Dust ex.
Refined Nickel Ore Maceration giving Platinum Dust
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/89574734/3ddca903-aba2-4d18-a544-314fad40e35b)

### Steps to Reproduce

View Ore Diagram on JEI for the Ore (ex. Refined Nickel Ore gives byproduct of Iron dust)

View Ore Maceration on JEI for the same ore, the outputs do not match (ex. Refined Nickel Ore gives byproduct for Platinum Dust)

In testing it seems to match the 2nd recipe (ex. Refined Nickel Ore giving Platinum dust rather than Iron dust)

### Additional Information

Currently on the latest pack of Gravitas 2 (Unsure if a pack issue or mod issue)

Current list:
Aluminium
Beryllium
Copper
Gold
Nickel
Platinum
Plutonium
Naq (this one is worst so far it gives Naq+)
Asbestos
Hematite
Sodalite
Chalcopyrite
Chromium
Cinnabar
Coal
Sheldonite
Bauxite
Magnesite
Molybdenite
Powellite
Pyrite
Pyrolusite
Ruby
Saltpeter
Scheelite
Tantalite
Sphalerite
Stibnite
Tetrahedrite
Tungstate
Uraninite
Yellow Limonite
Bornite
Chalcocite
Realgar
Pentlandite
Lepidolite
Glauconite Sand
Malachite
Talc
Soapstone
Kyanite
Pyrochlore
Olivine
Lapis
Apatite
Tricalcium Phosphate
Red Garnet
Yellow Garnet
Vanadium Magnetite
Pollucite
Bentonite
Fuller's Earth
Pitchblende
Monazite
Gypsum
Zeolite
Redstone
Electrotine

**Comment by Arborsm** [comment]
accurately, it's a bug of Ore Diagram #773

**Comment by Nyxane** [comment]
At the time of making the bug report that didn't exist :/
Spent 30+ minutes trying to grab that list D:
