### ISSUE TITLE
error when creating a world with Supplementaries in 1.1.0

### ISSUE THREAD

**Issue by Sovina1991** [GregTechCEu/GregTechCEu-1.19#775]
### GregTech CEu Version

gtceu-1.19.2-1.1.0

### Recipe Viewer Installed

None

### Environment

 Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

create a new world

### Actual Behavior

data pack error when creating

### Steps to Reproduce

create a world with gtceu-1.19.2-1.1.0.jar and supplementaries-1.19.2-2.4.16.jar

**Comment by screret** [comment]
latest.log?

**Comment by Sovina1991** [comment]
[minecraft-exported-crash-info-2024-01-18T17-58-59.zip](https://github.com/GregTechCEu/GregTech-Modern/files/13975009/minecraft-exported-crash-info-2024-01-18T17-58-59.zip)

**Comment by screret** [comment]
duplicate of #770.
