### ISSUE TITLE
Greg Basic Miner Eating batteries when chunk is unloaded.

### ISSUE THREAD

**Issue by Fishpit** [GregTechCEu/GregTechCEu-1.19#778]
### GregTech CEu Version

gtceu-forge-1.20.1-1.0.20.b

### Recipe Viewer Installed

JEI

### Environment

Multiplayer ATM server.

### Cross-Mod Interaction

Unsure

### Expected Behavior

Expected the battery slot to still have my Lithium battery in my miner.

### Actual Behavior

Came back to find it was empty. With no battery.

### Steps to Reproduce

Place charged battery in miner. 
Unload chunk by being either far enough away or waystone etc. 
Come back. 
Check machine.

### Additional Information

Haven't tested with other types of machine, tier, or type of battery.

**Comment by YoungOnionMC** [comment]
closed too early whoops
