### ISSUE TITLE
Can't use EMI view OreVein information in MP(Dedicated Server)

### ISSUE THREAD

**Issue by ZHENGLOC** [GregTechCEu/GregTechCEu-1.19#793]
### GregTech CEu Version

Forge 1.1.0&build.438

### Recipe Viewer Installed

EMI

### Environment

Dedicated Server

### Cross-Mod Interaction

Yes

### Expected Behavior

↓SP
![2024-01-21_10 19 58](https://github.com/GregTechCEu/GregTech-Modern/assets/24859848/9f919c38-0a53-450c-aa80-9b4d55cb12f1)
shift+r/U the Prospector to view ore vein information in EMI

### Actual Behavior

↓MP
![2024-01-21_10 32 39](https://github.com/GregTechCEu/GregTech-Modern/assets/24859848/560aaa79-ec38-4699-83b0-104224840684)
Actually can't view

### Steps to Reproduce

Just install: 
GTM-1.20.1-1.10/build-438
JEI-15.2.0.27
EMI-1.1.0
 configuration-forge-1.20.1-2.2.1.
(If you SP before connecting to the MP server, this bug will not reappear)

### Additional Information

[Dedicated Server-latest_log_gt_1.1.0.log](https://github.com/GregTechCEu/GregTech-Modern/files/13999843/Dedicated.Server-latest_log_gt_1.1.0.log)
[Dedicated Server-latest_log_gt_build_438.log](https://github.com/GregTechCEu/GregTech-Modern/files/13999844/Dedicated.Server-latest_log_gt_build_438.log)
[Player-latest_log_gt_build438.log](https://github.com/GregTechCEu/GregTech-Modern/files/13999850/Player-latest_log_gt_build438.log)
[Player-latest_log_gt_1.1.0.log](https://github.com/GregTechCEu/GregTech-Modern/files/13999851/Player-latest_log_gt_1.1.0.log)

**Comment by bigyihsuan** [comment]
I can confirm this as well, but with

- GTM v1.1.3b
- REI v12.0.684
- REI Plugin capabilities v12.0.93
- JER v1.4.0.247

in [Nomi-CEu/Nomi-CEu-Modern v0.1.1](https://github.com/Nomi-CEu/Nomi-CEu-Modern/releases/tag/v0.1.1).
