### ISSUE TITLE
java.lang.IllegalArgumentException: gtceu:compress_copper_to_ore_block: output items is empty

### ISSUE THREAD

**Issue by DanNetwalker** [GregTechCEu/GregTechCEu-1.19#798]
### GregTech CEu Version

GregTechCEu Modern v1.1.0

### Recipe Viewer Installed

None

### Environment

Starting a new single player map

### Cross-Mod Interaction

Yes

### Expected Behavior

It should process all the map startup and begin a new map.

### Actual Behavior

Crash out of the game, process crashed with exit code -1

### Steps to Reproduce

New map. Possibly dependant from other mods present, since it would be too obvious to not see before. Full crash log on "Additional Information"

### Additional Information

Crash log here: https://pastebin.com/zH3zXERA

**Comment by screret** [comment]
fixed in the next update.
