### ISSUE TITLE
Crash after new update

### ISSUE THREAD

**Issue by MindBrain27** [GregTechCEu/GregTechCEu-1.19#803]
### GregTech CEu Version

1.1.1

### Recipe Viewer Installed

REI

### Environment

Singleplayer/New World

### Cross-Mod Interaction

Yes

### Expected Behavior

Logging in to previous or new worlds without crashing.

### Actual Behavior

When trying to load a world I get an error that a datapack is invalid and to try opening in safe mode, safe mode doesn't work. If i try to start a new world I get a crash stating something about a rubber_log splitting. Even if I downgrade to the previous version 
I get the same errors.

### Steps to Reproduce

Update to new version, create new world.

https://pastebin.com/Xz3Y3uc2

**Comment by MindBrain27** [comment]
The game crashed whilst mouseclicked event handler
Error: java.lang.IllegalArgumentException: gtceu:rubber_log_separation: input items is empty

**Comment by mikerooni** [comment]
I can't reproduce this unfortunately.

You're currently running version 1.1.0 though. Could you please try to update to the latest version and try again?

**Comment by MindBrain27** [comment]
I just did again on the newest version, same issue.

https://pastebin.com/uvUxP3tD

Now it doesn't matter what version of GT i install, even if I go back a few versions it's the same. The only other mod I updated at the same time was Moonlight Lib.

**Comment by mikerooni** [comment]
Does it happen as well when you create a new world on an older version?

**Comment by MindBrain27** [comment]
On a new world i get this crash, on a previous world i get told my world is corrupt even in safe mode.

**Comment by mikerooni** [comment]
Could you please revert MoonlightLib to an older version and try again? I'm not sure if it may be related but since it doesn't seem to be reproducable in dev, it may be worth a try at least.

**Comment by MindBrain27** [comment]
I tried updating moonlight lib again and i got the same errors, i downgraded moonligfht lib to before the issue and got this instead

The game crashed whilst mouseclicked event handler
Error: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: gtceu:\u00A7rch

**Comment by screret** [comment]
That one's fixed.

**Comment by screret** [comment]
Report to moonlight lib.

**Comment by MindBrain27** [comment]
"Is your system in a non English language? I don't see my mod mentioned anywhere there idk why they told you to report here"

**Comment by screret** [comment]
We've had issues with it in the past.

**Comment by screret** [comment]
Sometimes moonlight lib just bricks our recipe injections for no reason iirc

**Comment by MindBrain27** [comment]
The only way i can get the pack to open now is if i delete GT, if i delete Moonlight lib its the same issues.

**Comment by MindBrain27** [comment]
@MehVahdJukaar
Owner
[MehVahdJukaar](https://github.com/MehVahdJukaar) commented [2 minutes ago](https://github.com/MehVahdJukaar/Moonlight/issues/151#issuecomment-1903913290)
That issue come straight from vanilla resource location parse code and called by their code too. I doubt touch either in the slightest

@MehVahdJukaar
Owner
[MehVahdJukaar](https://github.com/MehVahdJukaar) commented [now](https://github.com/MehVahdJukaar/Moonlight/issues/151#issuecomment-1903916198)
They seem to have some assets with a resource location containing § which is an invalid character

**Comment by MindBrain27** [comment]
After updating to gtceu-1.20.1-1.1.1.a.jar today everything works.
