### ISSUE TITLE
[Bug] Datapack issue

### ISSUE THREAD

**Issue by TheRealM18** [GregTechCEu/GregTechCEu-1.19#804]
### GregTech CEu Version

gtceu-1.20.1-1.1.1-build_445

### Recipe Viewer Installed

No Recipe Viewer

### Environment

Server

### Cross-Mod Interaction

No

### Expected Behavior

To be able to load on new server.

### Actual Behavior

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/5025664/0d56e90b-f0aa-4047-966c-eaa05779d66a)

### Steps to Reproduce

Install Gregtech build 439 or later, and the datapack is broken on it... fresh world each time.

### Additional Information

It is saying there is a messed up json, but could be that i have all hard mode recipes on.

**Comment by TheRealM18** [comment]
This is not a magma bug... it works in build 437

**Comment by trilexcom** [comment]
same here 
[crash-2024-01-21_19.57.08-client.txt](https://github.com/GregTechCEu/GregTech-Modern/files/14003447/crash-2024-01-21_19.57.08-client.txt)

**Comment by moguang2004** [comment]
same here
[crash-2024-01-22_11.15.59-client.txt](https://github.com/GregTechCEu/GregTech-Modern/files/14005351/crash-2024-01-22_11.15.59-client.txt)
