### ISSUE TITLE
net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: gtceu:\u00A7rch

### ISSUE THREAD

**Issue by DanNetwalker** [GregTechCEu/GregTechCEu-1.19#812]
### GregTech CEu Version

1.1.1

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

It should process all the map startup and begin a new map.

### Actual Behavior

Crash out of the game, process crashed with exit code -1

"The game crashed whilst mouseclicked event handler
Error: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: gtceu:\u00A7rch"

### Steps to Reproduce

New map. Maybe dependant on active language (es_es)? Full crash log on "Additional Information"

### Additional Information

https://pastebin.com/HMRL1cza

**Comment by screret** [comment]
already fixed.
