### ISSUE TITLE
[Bug] Render conflict with REI + Chisel and Bits + GregtechCEu

### ISSUE THREAD

**Issue by TheRealM18** [GregTechCEu/GregTechCEu-1.19#815]
### GregTech CEu Version

gtceu-1.20.1-1.1.1.a-build_451

### Recipe Viewer Installed

REI

### Environment

Cilent-Side

### Cross-Mod Interaction

Yes

### Expected Behavior

to be able to see the items without crashing when looking at the blocks

### Actual Behavior

When you go to a page that has a lot of gregtech items in it, that is set for chisel and bits time, it will crash only the client.

### Steps to Reproduce

Install build 451
Install rei
Install chisel and bits
do @chisel
go start scrolling, and get a out of bounds array error.

### Additional Information

[crash-2024-01-22_10.29.43-client.txt](https://github.com/GregTechCEu/GregTech-Modern/files/14011550/crash-2024-01-22_10.29.43-client.txt)
[crash-2024-01-22_10.38.53-client.txt](https://github.com/GregTechCEu/GregTech-Modern/files/14011551/crash-2024-01-22_10.38.53-client.txt)

**Comment by screret** [comment]
why the fuck do they ask for tint index 195 million???

**Comment by Exzept1on** [comment]
can confirm this
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/52341158/763d1102-d65c-4d90-aacd-8907051a12de)
