### ISSUE TITLE
Intermittent crashes viewing recipes with EMI

### ISSUE THREAD

**Issue by moozilla** [GregTechCEu/GregTechCEu-1.19#816]
### GregTech CEu Version

1.0.20.b

### Recipe Viewer Installed

EMI

### Environment

Singleplayer (GTCEu Modern pack)

### Cross-Mod Interaction

Yes

### Expected Behavior

Expected to be able to view recipes in EMI without the game crashing.

### Actual Behavior

Occasionally when viewing recipes in EMI the game will crash.

### Steps to Reproduce

I haven't been able to determine a pattern in why this is happening. The latest crash happened when I was viewing the recipe for MV circuit boards I believe when I switching to the chemical reactor tab.

I'm able to trigger the crash way more reliably when messing with the recipe tree viewer, but it also happens just looking at recipes normally.

### Additional Information

All crashes I've encountered have the same error message with slightly different stack traces

```
java.lang.ClassCastException: class net.minecraft.world.inventory.InventoryMenu cannot be cast to class com.lowdragmc.lowdraglib.gui.modular.ModularUIContainer (net.minecraft.world.inventory.InventoryMenu is in module minecraft@1.20.1 of loader 'TRANSFORMER' @1cba0321; com.lowdragmc.lowdraglib.gui.modular.ModularUIContainer is in module ldlib@1.0.22.a of loader 'TRANSFORMER' @1cba0321)
	at com.gregtechceu.gtceu.integration.emi.recipe.GTEmiRecipeHandler.getInputSources(GTEmiRecipeHandler.java:12) ~[gtceu-forge-1.20.1-1.0.20.b.jar%23260!/:?] {re:mixin,re:classloading}
	at dev.emi.emi.screen.EmiScreenManager.renderSlotOverlays(EmiScreenManager.java:825) ~[emi-1.1.0+1.20.1+forge.jar%23242!/:?] {re:mixin,re:classloading}
	at dev.emi.emi.screen.EmiScreenManager.render(EmiScreenManager.java:633) ~[emi-1.1.0+1.20.1+forge.jar%23242!/:?] {re:mixin,re:classloading}
	at dev.emi.emi.screen.RecipeScreen.m_88315_(RecipeScreen.java:250) ~[emi-1.1.0+1.20.1+forge.jar%23242!/:?] {re:mixin,re:classloading,pl:mixin:APP:ldlib-common.mixins.json:emi.RecipeScreenMixin,pl:mixin:A}
...
```

Attaching a few representative stack traces:
[crash-2024-01-22_20.25.33-client.txt](https://github.com/GregTechCEu/GregTech-Modern/files/14018375/crash-2024-01-22_20.25.33-client.txt)
[crash-2024-01-16_23.44.21-client.txt](https://github.com/GregTechCEu/GregTech-Modern/files/14018379/crash-2024-01-16_23.44.21-client.txt)
[crash-2024-01-19_23.48.56-client.txt](https://github.com/GregTechCEu/GregTech-Modern/files/14018380/crash-2024-01-19_23.48.56-client.txt)

**Comment by zix3r** [comment]
The same is happening for me too, here's my log aswell:
[https://mclo.gs/Pkvny8A](https://mclo.gs/Pkvny8A)

**Comment by Arborsm** [comment]
> The same is happening for me too, here's my log aswell: https://mclo.gs/Pkvny8A

update
