### ISSUE TITLE
GT Ores do not react to LambDynamicLights lighting

### ISSUE THREAD

**Issue by EntityinArray** [GregTechCEu/GregTechCEu-1.19#819]
### GregTech CEu Version

1.0.20.b

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

GT Ores should react to LambDynamicLights lighting

### Actual Behavior

GT Ores ignore LambDynamicLights lighting

https://github.com/GregTechCEu/GregTech-Modern/assets/18554021/4f176791-d04f-4612-8f1f-b9de659f8413

### Steps to Reproduce

1. Install GregTech-Modern and LambDynamicLights
2. Find some ores and whip out a torch
3. GT Ores ignore LambDynamicLights lighting

**Comment by screret** [comment]
Update. Update. Update. Update.

**Comment by EntityinArray** [comment]
Sorry to bother you again, but it seems that updates are only for (Neo)Forge. Fabric newest is still 1.0.20.b
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/18554021/f4358d34-daa1-47e6-9a29-e9ae946a07ca)

**Comment by Arborsm** [comment]
> Sorry to bother you again, but it seems that updates are only for (Neo)Forge. Fabric newest is still 1.0.20.b ![image](https://private-user-images.githubusercontent.com/18554021/299194025-f4358d34-daa1-47e6-9a29-e9ae946a07ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzQzMzUsIm5iZiI6MTcwNjA3NDAzNSwicGF0aCI6Ii8xODU1NDAyMS8yOTkxOTQwMjUtZjQzNThkMzQtZGFhMS00N2U2LTlhMjktZTlhZTk0NmEwN2NhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA1MjcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1YmYwMTQ0Y2I1MTJhOWMxZDc1ZjQ5Y2Y0MDhjNzM1NTNhNGU4ZDg4ZTY1ZWM0OGM2YjMzMTExMjZhYTMyMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.btpYBuRftScgTNlWOwPBxYns8Wsqu18U8hd3_xR9RGI)

play forge pls, cause the fabric support is stopped

**Comment by ghzdude** [comment]
Fabric support has been dropped by the Modern CEu dev team
