### ISSUE TITLE
"holding" item in gregtech GUI breaks rendering

### ISSUE THREAD

**Issue by redgoblin88** [GregTechCEu/GregTechCEu-1.19#820]
### GregTech CEu Version

1.1.1.a

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Expected Behavior

When you have any GUI open (primitive blast furnace, assemblers, crates, tanks e.c.t.) if you left click an item so you are "holding" it in your cursor, that has a 3d model (for example of tested block items so far: chest, scaffolding and composter) , you will notice this held item will render the model "inverted" or the back faces in front of the front faces

### Actual Behavior

for no broken rendering? so the back faces dont render in the front? not sure what else to say

### Steps to Reproduce

have an item in your inventory that has a 3d model render

open up any gui that is from gregtech, such as any of the machines or storage

"hold" the item in your hand and notice how the front textures get replaced with the back

### Additional Information

note: this also occurs to gregtech 3d models too, such as the "super tank"

vanilla blocks seen here (images stitched together so you dont have to scroll):

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/13396472/ad1538f6-cabb-4150-a93d-3eb797fcffcc)

**Comment by redgoblin88** [comment]
Thought i would show what happens if you hold them items inside of a vanilla container, in this case its inside of a vanilla chest gui

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/13396472/cac96c39-1195-4860-84e6-ac8a2ea24710)

**Comment by a-a-GiTHuB-a-a** [comment]
I think you flopped "expected" and "actual" behavior.

**Comment by RainPumpkin** [comment]
![image](https://github.com/user-attachments/assets/add796aa-345f-4699-a4d4-06ce15b34253)
still happens on latest

**Comment by Pumpkin7266** [comment]
![image](https://github.com/user-attachments/assets/3b2f0c81-6246-452c-afbd-dda97412b518)
still happens on latest

**Comment by krossgg** [comment]
Will not be fixed in the current state of mod until UI overhaul later this year.
