### ISSUE TITLE
Robotic Arm + Item Tag Filter, some sort of conflict

### ISSUE THREAD

**Issue by NIKITAzed** [GregTechCEu/GregTechCEu-1.19#821]
### GregTech CEu Version

gtceu-1.20.1-1.1.1.a.jar

### Recipe Viewer Installed

JEI

### Environment

Hosting Essential mod Multiplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

MV Robotic Arm filtered to "Supply Exact" "27"
Item Tag filtered to only allow "tiny_dusts"

only allow tiny dusts to pass in batches of 27

### Actual Behavior

nothing gets moved
removing the tag filter allows items through
changing "supply exact" to any other option allows items through

### Steps to Reproduce

put MV robot arm on MV packer, configure to input "supply exact" "27", add item tag filter with "tiny_dusts"

**Comment by YoungOnionMC** [comment]
![image](https://github.com/user-attachments/assets/61f99a76-81a2-4adc-b0ac-3811099a454a)
![image](https://github.com/user-attachments/assets/9402d85c-8bb0-4073-83fc-98e5007a0a0e)
Works fine as of 1.5.4
