### ISSUE TITLE
ME Stocking Input Hatch Eats Fluids

### ISSUE THREAD

**Issue by MrNoe93** [GregTechCEu/GregTechCEu-1.19#825]
### GregTech CEu Version

1.20.1-1.1.1.a

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Expected Behavior

I would be able to include an ME Stocking Input Hatch with a fluid inside, such as oxygen for a blast furnace, and it would hold the fluid until the recipe starts.

### Actual Behavior

The ME Stocking Input Hatch consumes the fluid even if no recipe is going and if there is the ingredients for a recipe in the other buses/hatches, it consumes the fluid and doesnt start a recipe.  It continues to consume the fluid until there is none left in the ME system.

### Steps to Reproduce

Setup a standard EBF and replace the input hatch with an ME Stocking Input Hatch set to oxygen and connected to an ME system with Oxygen.  I couldnt always reliable get it to happen, sometimes it would hold the fluid, but more often than not it would just consume it and do nothing.

**Comment by screret** [comment]
Correct! Nobody knows how (or can't bother) to fix it, though. 
Pls halp.

**Comment by MrNoe93** [comment]
Well, I guess at least this is here to inform people who come looking haha

Some more info, that idk if helps but since I noticed it:
It only does that for fluids that are part of a valid recipe for that multiblock, it ignores any others, like water in the blast furnace.  It also stops doing it if the work is disabled in the controller.

**Comment by StarL0st** [comment]
so rn I am attempting to recreate the issue, but I cant seem to get it to continuously chug on the fluid? the hatch is simply just holding the fluid and is not starting the recipe, was it more recurrent for you that it ate the fluid or viceversa?

**Comment by MrNoe93** [comment]
It would eat the fluid constantly and never start the recipe.
