### ISSUE TITLE
smelt raw redstone only get 1 redstone dust

### ISSUE THREAD

**Issue by RagingFireFY** [GregTechCEu/GregTechCEu-1.19#827]
### GregTech CEu Version

1.20.1-1.1.1.a-build 452

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Expected Behavior

smelt raw redstone get 5 redstone dust

### Actual Behavior

smelt raw redstone only get 1 redstone dust

### Steps to Reproduce

put the raw redstone in the furnace
or use recipe viewer check recipe

### Additional Information

raw cassiterite sand and raw coal also have this problem
smelt it should get 2 products

**Comment by screret** [comment]
correct. this is done because the raw ore drop is multiplied already.

**Comment by Arborsm** [comment]
> correct. this is done because the raw ore drop is multiplied already.

seems not work for overworld ores?
