### ISSUE TITLE
[Bug] Missing of changing button recipes

### ISSUE THREAD

**Issue by TheRealM18** [GregTechCEu/GregTechCEu-1.19#829]
### GregTech CEu Version

1.1.1.a-build_452

### Recipe Viewer Installed

REI

### Environment

Server

### Cross-Mod Interaction

No

### Expected Behavior

for all vanilla recipes for buttons to require saws

### Actual Behavior

Mangrove and Cherry are vanilla recipes

### Steps to Reproduce

Install REI
Install GTCEu
boot server, and make sure all hard recipes are on
check recipes for Mangrove and Cherry buttons

**Comment by jtuc** [comment]
Did you mean Cherry and Bamboo? Mangrove recipes look to be present:
https://github.com/GregTechCEu/GregTech-Modern/blob/27612c50a14ba051a317c60ad6ddb9e348b6ea41/src/main/java/com/gregtechceu/gtceu/data/recipe/configurable/RecipeAddition.java#L680

**Comment by TheRealM18** [comment]
Your right, it was bamboo and cherry...
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/5025664/5e7473f7-0551-4883-a09f-797986ed31a7)

also missing is cherry planks
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/5025664/abafab98-15ac-4c22-aa71-af9643899ec6)
