### ISSUE TITLE
All modded ores are transparent underwater and on surface

### ISSUE THREAD

**Issue by Toastryder** [GregTechCEu/GregTechCEu-1.19#830]
### GregTech CEu Version

1.1.1a

### Recipe Viewer Installed

None

### Environment

Single player

### Cross-Mod Interaction

Unsure

### Expected Behavior

I thought I was able to go minining for all the ores but I couldn't see the modded ones only the vanilla

### Actual Behavior

Literally as stated, I can not see the modded ores rather they are transparent. Jade picks them up and I can mine them and the texture appears in my hotbar but upon placed its like they are see-through. 

### Steps to Reproduce

Unsure

**Comment by Toastryder** [comment]
Sorry my mistake I was using JEI as well

**Comment by screret** [comment]
are you sure you're on 1.1.1.a?
