### ISSUE TITLE
Alloy Blast Smelter doesnt accept parallel control hatches

### ISSUE THREAD

**Issue by MrNoe93** [GregTechCEu/GregTechCEu-1.19#832]
### GregTech CEu Version

1.20.1-1.1.1.a

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Expected Behavior

The alloy blast smelter could have parallel control hatches installed, as indicated on its tooltip

### Actual Behavior

The alloy blast smelter doesnt accept parallel control hatches, unlike the other multiblocks like it

### Steps to Reproduce

Built an alloy blast smelter, swap out a casing for a parallel control hatch

**Comment by screret** [comment]
in this case it's the tooltip that's wrong. thanks for the report though
