### ISSUE TITLE
Crash with KubeJS

### ISSUE THREAD

**Issue by IWantToPlayMC** [GregTechCEu/GregTechCEu-1.19#835]
### GregTech CEu Version

1.1.1a-build_455

### Recipe Viewer Installed

No Recipe Viewer

### Environment

Multiplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

everything is working

### Actual Behavior

Crash on startup. All is working with gregtech 1.1.0
Error:
`
Failed to create mod instance. ModID: kubejs, class dev.latvian.mods.kubejs.forge.KubeJSForge
java.lang.ExceptionInInitializerError: null
	at com.gregtechceu.gtceu.integration.kjs.GregTechKubeJSPlugin.init(GregTechKubeJSPlugin.java:83) ~[gtceu-1.20.1-1.1.1.a-build_455.jar%23162!/:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at dev.latvian.mods.kubejs.util.KubeJSPlugins.forEachPlugin(KubeJSPlugins.java:116) ~[kubejs-forge-2001.6.4-build.127.jar%23163!/:2001.6.4-build.127]
	at dev.latvian.mods.kubejs.KubeJS.<init>(KubeJS.java:133) ~[kubejs-forge-2001.6.4-build.127.jar%23163!/:2001.6.4-build.127]
       
Caused by: java.lang.NullPointerException: Cannot invoke "com.gregtechceu.gtceu.api.data.chemical.material.IMaterialRegistryManager.getRegistry(String)" because "com.gregtechceu.gtceu.api.GTCEuAPI.materialManager" is null
	at com.gregtechceu.gtceu.integration.kjs.GTRegistryInfo.<clinit>(GTRegistryInfo.java:45) ~[gtceu-1.20.1-1.1.1.a-build_455.jar%23162!/:?]
`
[latest.log](https://github.com/GregTechCEu/GregTech-Modern/files/14071608/latest.log)

### Steps to Reproduce

Mods:
1) KubeJS and its dependencies
2) gtceu all 1.1.1a versions

### Additional Information

Some people have this error, for others everything starts fine

**Comment by TheRealM18** [comment]
Please give the actual crash log, and do you have a real minecraft account, as your error was a 401, which is an authenication error.

I have it running perfectly fine on kubejs and a bunch of other stuff,

Do you have enough ram dedicated to the system?

As long as we can not see the crash-log file they can not help...

The metrics that come with it, is normal and so know that its probably not their fault.

sorry for the rant, but that builds works perfectly fine with Greate which is an addon for both create and gregtech, which uses kubejs, so i do not know the issue.

**Comment by IWantToPlayMC** [comment]
No, I don't have a Minecraft license. Here is the crash: 
[crash-2024-01-27_12.59.06-fml.txt](https://github.com/GregTechCEu/GregTech-Modern/files/14071795/crash-2024-01-27_12.59.06-fml.txt)
also this bug was mentioned in the following issue: [https://github.com/GregTechCEu/GregTech-Modern/issues/782](url)

**Comment by Exzept1on** [comment]
> Please give the actual crash log, and do you have a real minecraft account, as your error was a 401, which is an authenication error.
> 
> I have it running perfectly fine on kubejs and a bunch of other stuff,
> 
> Do you have enough ram dedicated to the system?
> 
> As long as we can not see the crash-log file they can not help...
> 
> The metrics that come with it, is normal and so know that its probably not their fault.
> 
> sorry for the rant, but that builds works perfectly fine with Greate which is an addon for both create and gregtech, which uses kubejs, so i do not know the issue.

bro wtf, ppl from our server getting the same crash, it's gtceu bug, and it has been fixed here(probably, not tested for now), its not linked with mc licence or memory, or other shit: https://github.com/GregTechCEu/GregTech-Modern/commit/9f9f6f15c3694c0c9bba9a6a44bf896760baf8b6

**Comment by Exzept1on** [comment]
> No, I don't have a Minecraft license. Here is the crash: [crash-2024-01-27_12.59.06-fml.txt](https://github.com/GregTechCEu/GregTech-Modern/files/14071795/crash-2024-01-27_12.59.06-fml.txt) also this bug was mentioned in the following issue: [https://github.com/GregTechCEu/GregTech-Modern/issues/782](url)

Fixed here, dont worry: https://github.com/GregTechCEu/GregTech-Modern/commit/9f9f6f15c3694c0c9bba9a6a44bf896760baf8b6
