### ISSUE TITLE
[Feature] Abstract Item Registry

### ISSUE THREAD

**Issue by TheRealM18** [GregTechCEu/GregTechCEu-1.19#840]
### Cross-mod Integration

Productive Bees, Rechiseled, or Rechiseled Create

### Feature Description

These mods make there own recipe handing, and for productive bees, it registers them as an abstract string. Rechiseled, and Rechiseled create add it an abstract item, as they make there own way of handling itemstack.

It would be nice, for able to have like this:

VanillaRecipeHelper.addShapedRecipe(provider, "chisel", new output("Rechiseled.chisel"), "sP", 'P', "minecraft:stick");

**Comment by screret** [comment]
...what?

**Comment by screret** [comment]
just get them from the registry 5head

**Comment by TheRealM18** [comment]
They don't register them as Itemstacks, is the problem. they all have a custom registry handler.... for example, Productive Bees... this is there way of registering there blocks... https://github.com/JDKDigital/productive-bees/blob/dev-1.20.0/src/main/java/cy/jdkdigital/productivebees/setup/HiveType.java
