### ISSUE TITLE
Game won't launch after updating version of mod

### ISSUE THREAD

**Issue by Correlander** [GregTechCEu/GregTechCEu-1.19#846]
### GregTech CEu Version

gtceu-1.19.2-1.1.1.a.jar

### Recipe Viewer Installed

JEI

### Environment

N/A

### Cross-Mod Interaction

Yes

### Expected Behavior

The game to launch.

### Actual Behavior

The game doesn't launch.

### Steps to Reproduce

I click play.

### Additional Information

[crash-2024-01-29_15.19.32-fml.txt](https://github.com/GregTechCEu/GregTech-Modern/files/14089783/crash-2024-01-29_15.19.32-fml.txt)
crash report ^
![issue](https://github.com/GregTechCEu/GregTech-Modern/assets/53982700/f390af58-54b1-4c99-9286-bcf15ad0c33d)
what shows when it fails to launch^

The only change was I updated GTCEu Modern. KubeJS and GTCEu Modern both worked prior to updating. The previous version I was on was 1.19.2-1.0.13.e, if that matters.

**Comment by IWantToPlayMC** [comment]
try last release from github
