### ISSUE TITLE
Deepslate ore processing recipe generation is missing.

### ISSUE THREAD

**Issue by YiRanMushroom** [GregTechCEu/GregTechCEu-1.19#851]
### GregTech CEu Version

gtceu-1.20.1-1.1.2-build_459

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

Expect GTCEu can process deepslate ore like other ores

### Actual Behavior

Only forge hammer recipes are generated, macerator recipes are missing.

### Steps to Reproduce

Use JEI to check the recipe of deepslate ore, I checked deepslate iron ore.

**Comment by screret** [comment]
which deepslate ore? GT or vanilla?
