### ISSUE TITLE
1.12.1 Crash: java.lang.RuntimeException: Slot 1 not in valid range - [0,1)

### ISSUE THREAD

**Issue by FrozenGalaxy** [GregTechCEu/GregTechCEu-1.19#858]
### GregTech CEu Version

1.1.2

### Recipe Viewer Installed

JEI

### Environment

Dedicated

### Cross-Mod Interaction

Unsure

### Expected Behavior

No crash

### Actual Behavior

Crashes when right clicking the steam compressor thing

### Steps to Reproduce

Right clicking the steam compressor thing

### Additional Information

https://gist.github.com/FrozenGalaxy/53f2f14949abbf3a8299c7d41be11a14

**Comment by MindBrain27** [comment]
Also happens with a different slot (i think 37) in a Macerator and Chemical Reactor.

**Comment by StellaBiscuit** [comment]
Happened to me when I opened an extractor

**Comment by screret** [comment]
Oh did I never release the fix
