### ISSUE TITLE
Crash when starting the game

### ISSUE THREAD

**Issue by Sovina1991** [GregTechCEu/GregTechCEu-1.19#859]
### GregTech CEu Version

gtceu-1.19.2-1.1.2

### Recipe Viewer Installed

None

### Environment

 Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

starting game

### Actual Behavior

carsh

### Steps to Reproduce

start game with modpacks

### Additional Information

[minecraft-exported-crash-info-2024-01-31T10-51-46.zip](https://github.com/GregTechCEu/GregTech-Modern/files/14106659/minecraft-exported-crash-info-2024-01-31T10-51-46.zip)

**Comment by FooterManDev** [comment]
I am also having this issue, the version specified crashes with itself and Forge alone, no other mod conflicts are happening.
https://gist.github.com/FooterMan15/da9512539906ca4ddbb4fcf04644e720

**Comment by Tybob12** [comment]
I am also having the same issue on the 1.20.1 version in a dev workspace.

**Comment by GuffeTheGreat** [comment]
I have the same issues

**Comment by Cannoner** [comment]
1.19 Crash
[crash-2024-02-01_08.41.54-client(1.19.2).txt](https://github.com/GregTechCEu/GregTech-Modern/files/14125223/crash-2024-02-01_08.41.54-client.1.19.2.txt)
1.20 Crash
[crash-2024-02-01_08.41.54-client(1.19.2).txt](https://github.com/GregTechCEu/GregTech-Modern/files/14125223/crash-2024-02-01_08.41.54-client.1.19.2.txt)
Both versions crash, with possibly related reasons

**Comment by Ginsway** [comment]
1.1.2a has the same issue
[crash-2024-02-02_21.52.36-client.txt](https://github.com/GregTechCEu/GregTech-Modern/files/14140935/crash-2024-02-02_21.52.36-client.txt)

**Comment by TheRealM18** [comment]
There currently is an accidental dependency on Applied Energistics 2, try adding that to the pack, and should fix your issue

**Comment by GuffeTheGreat** [comment]
Fixed the issue for me

**Comment by FooterManDev** [comment]
Yeah that works.

**Comment by screret** [comment]
wtf how does that fix it???
