### ISSUE TITLE
ALCR circuit 0 recipe conflict (Sulfur, Sodium, Ruthenium Tetroxide, Carbon)

### ISSUE THREAD

**Issue by NIKITAzed** [GregTechCEu/GregTechCEu-1.19#861]
### GregTech CEu Version

gtceu-forge-1.20.1-1.0.20.b.jar

### Recipe Viewer Installed

JEI

### Environment

LAN

### Cross-Mod Interaction

Unsure

### Expected Behavior

Advanced Larged Chemical Reactor on no circuit setting combining 
5 Ruthenium Tetroxide Dust and 2 Carbon Dust for Ruthenium Dust
while also combining
2 sodium dust + 1 sulfur dust for 3 Sodium Sulfide Dust

### Actual Behavior

Sulfur and Carbon combined together to make 1 blaze powder

### Steps to Reproduce

put all 4 ingredients into a large chemical reactor and by chance it can happen

**Comment by screret** [comment]
ALCR is not a base GTCEu machine.

**Comment by NIKITAzed** [comment]
is the regular Large Chemical Reactor part of the base GTCEu ? both the item tags start with gtceu so I'm not sure what else they would be a part of

if yes, the same recipe conflict happens in the LCR

**Comment by screret** [comment]
wait why are you trying to do 2 recipes at the same time

**Comment by NIKITAzed** [comment]
I guess I could make that not a problem by putting an lv hatch rather than an LuV one so it's less likely to do that...

**Comment by NIKITAzed** [comment]
ok, limiting the input bus slots hasn't helped, it just created a different issue of different crafting ingredients being inputted that aren't compatible

I am trying to do 2 recipes at the same time because the Large Chemical Reactor is a multiblock chemical reactor, so rather than having a dozen small ones I just made 1 big one. and the craft I started needed multiple chem reactor recipes, if the LCR 
I also don't really understand what you mean by ALCR not being a base GTCEu machine (and I understand this is more on the part of my ignorance) but when I toggle F3+H it comes with a prefix of GTCEu, and not a different addon type mod
