### ISSUE TITLE
crash when mining block while holding file

### ISSUE THREAD

**Issue by IIIap** [GregTechCEu/GregTechCEu-1.19#866]
### GregTech CEu Version

1.1.2.a

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

i wanted to mine block with file (tool)

### Actual Behavior

mine crashed

### Steps to Reproduce

take file to hand and try do mine any block with it. it will crash

### Additional Information

as I understand it, you definitely need to be in survival and have jade enabled

here is crash-report: https://pastebin.com/LYG9LBBH

also here is a clip with a demonstration: https://jmp.sh/s/xX5pqdTRDe5afSgkETpN

**Comment by screret** [comment]
lmao I used the wrong glass pane class

**Comment by IIIap** [comment]
> lmao I used the wrong glass pane class

when we will get fix?

**Comment by screret** [comment]
soon

**Comment by IIIap** [comment]
> soon

thanks!
