### ISSUE TITLE
 java.lang.IllegalArgumentException: gtceu:zinc_sulfate: output items is empty [GAME CRASH]

### ISSUE THREAD

**Issue by autumnly24** [GregTechCEu/GregTechCEu-1.19#878]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.1.3

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

Forge 47.2.0

Citadel
Alliance of Valiant Arms Guns
AI Improvements
Alex's Mobs
Appleskin
Architectury API
AtomicStryker's Infernal Mobs
Balm
Better Chunk Loading
Bookshelf
Born In Chaos
Butcher's Delight
Carry On
Cave Dust
Chunk Sending
Clumps
Connectivity
Controlling
CorgiLib
CoroUtil
Corpse
Creeper Overhaul
Cupboard
CuriosAPI
DeathButThree
Distant Friends
Weeping Angels
DoesPotatoTick?
Dusk
Dynamic Trees
Embeddium
Embeddium Dynamic Lights
Embeddium Extras
Enchantment Descriptions
Enemy Expansion
Enhanced Celestials
Entity Culling
Farsighted Mobs
Fast Async World Save
Fastload
Ferritecore
From The Fog
Fullstack Watchdog
Functional Storage
Fungal Infection: Spore
Geckolib
**Gregicality Rocketry**
**Gregified Integrations**
**Gregtech CEU Modern**
**Gregtrip**
Hourglass
Ice And Fire Dragons
Jade
JEI
Lethal Cave Dwellers
Lethal Company Mobs
Limited Chunkloading - Chunk Cleanup
Lootr
Magma Monsters
Mob Sunscreen
Modernfix
Moonlightlib
Mouse Tweaks
Mutant Monsters
Mutants Buff
No Tree Punching
Nutritional Balance
Nyf's Spiders
Pam's Harvestcraft 2 Crops, Food Core, Food Extended, Trees
Patchouli
Pehkui
Polymorph
Puzzles Lib
Quark
Radium Reforged
RealmRPG: Pots & Mimics
Recipe Essentials
Record Days Survived
Redirector [Modern]
Resourceful Config
Sanity: Descent Into Madness
Saturn
Savage Ender Dragon
Searchables
Season HUD
Serene Seasons
Serene Seasons PHC2 Crops, Trees
Serene Seasons Fix
Server Performance - Smooth Chunk Saving
Sleep Tight
Smooth Boot
Sophisticated Backpacks
Sophisticated Core
Spoiled
Sunrise & Sunset Audio
Supplementaries
TenshiLib
TexTrue's Embeddium Options
The Box Of Horrors
Titanium
Tough As Nails
Tough As Tweaked
True Darkness
Volcanic Caverns
Waystones
Weather, Storms, and Tornadoes
Xaero's Suite
Zeta
Zombie Awareness

### Expected Behavior

Expected to open the world creation menu

### Actual Behavior

When pressing the singleplayer button, it crashes with the following crash report:
[crash-2024-02-06_00.53.57-client.txt](https://github.com/GregTechCEu/GregTech-Modern/files/14175481/crash-2024-02-06_00.53.57-client.txt)

### Steps to Reproduce

Launch Game
Try To Launch Singleplayer
Crash

**Comment by screret** [comment]
caused by gregtrip according to the log.
