### ISSUE TITLE
Most fluid goes purely white after updated mod from 1.0.19b to 1.1.2a

### ISSUE THREAD

**Issue by ccpemily** [GregTechCEu/GregTechCEu-1.19#879]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.20.1-1.1.2a

### Recipe Viewer Installed

JEI

### Environment

SMP/Dedicated Forge Server

### Cross-Mod Interaction

No

### Other Installed Mods

Embeddium, Oculus

### Expected Behavior

Some fluid should have their own color, such as Chloride, Fluorine.

### Actual Behavior

Most 2-state fluid (have fluid form and gas form, like Helium, Chloride...) are white, also included some commonly used fluid(e.g Sulfuric Acid), caused a lot of confusing to find correct fluid.

### Steps to Reproduce

Install GTCEuM 1.1.2a

**Comment by screret** [comment]
Fixed in 1.1.3.
