### ISSUE TITLE
crash when trying to initiate the game with optfine

### ISSUE THREAD

**Issue by BearOctopus** [GregTechCEu/GregTechCEu-1.19#884]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

minecraft 1.19.2 gtm 1.1.3 forge 43.3.7

### Recipe Viewer Installed

None

### Environment

singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

optfine 1.19.2_I2

### Expected Behavior

initiate normally

### Actual Behavior

crash quickly after trying to start up
log: https://mclo.gs/tjq4PCS

### Steps to Reproduce

start minecraft with gtm and optfine 

### Additional Information

tried remove optfine,it initiated successfully but crashed when creating a new world
log: https://mclo.gs/K6waZIU

**Comment by screret** [comment]
I see some issues with this report:
1. you didn't check for existing issues.
2. don't use optifine.

**Comment by BearOctopus** [comment]
get it
sorry for bothering
