### ISSUE TITLE
crash with kubejs and new gregtech version

### ISSUE THREAD

**Issue by IIIap** [GregTechCEu/GregTechCEu-1.19#885]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.1.3

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

GregTech Community Pack Modern

### Expected Behavior

update gregtech and continue to playing

### Actual Behavior

game is crashing in initialization

### Steps to Reproduce

update to 1.1.3 from 1.1.2.a and try to join to the game

### Additional Information

[crash-2024-02-06_18.45.12-fml.txt](https://github.com/GregTechCEu/GregTech-Modern/files/14182821/crash-2024-02-06_18.45.12-fml.txt)
[crash-2024-02-06_18.39.15-fml.txt](https://github.com/GregTechCEu/GregTech-Modern/files/14182822/crash-2024-02-06_18.39.15-fml.txt)

**Comment by screret** [comment]
remove the LDLib you've installed separately. GT comes with it built in.

**Comment by IIIap** [comment]
thanks, it works

have a nice day!
