### ISSUE TITLE
[1.19.2-1.1.3] KubeJS an error occured while loading into a world after an update from 1.1.2.a

### ISSUE THREAD

**Issue by Igneaalis** [GregTechCEu/GregTechCEu-1.19#888]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.19.2-1.1.3

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Forge: 43.2.21

ad_astra-forge-1.19.2-1.12.7.jar
Ad-Astra-Giselle-Addon-forge-1.19.2-1.19.jar
Applied-Botanics-forge-1.4.6.jar
appliedenergistics2-forge-12.9.9.jar
archaeology-api-1.19.2-1.0.0.jar
architectury-6.5.85-forge.jar
ars_nouveau-1.19.2-3.22.3.jar
AutoRegLib-1.8.2-55.jar
badpackets-forge-0.2.3.jar
BetterCompatibilityChecker-1.0.10-build.50.jar
biomancy-forge-1.19.2-2.3.1.0.jar
Botania-1.19.2-440-FORGE.jar
BotanicalMachinery-1.19.2-2.0.2.jar
botarium-forge-1.19.2-1.9.1.jar
bwncr-forge-1.19.2-3.14.1.jar
caelus-forge-1.19.2-3.0.0.6.jar
cc-tweaked-1.19.2-1.101.4.jar
cfm-7.0.0-pre35-1.19.2.jar
cgm-forge-1.19.2-1.3.7.jar
ChickenChunks-1.19.2-2.9.4.97-universal.jar
citadel-2.1.4-1.19.jar
clockwork-1.19.2-0.1.2-forge-6839926f09.jar
cloth-config-8.3.115-forge.jar
Clumps-forge-1.19.2-9.0.0+14.jar
CodeChickenLib-1.19.2-4.3.2.490-universal.jar
collective-7.30.jar
Controlling-forge-1.19.2-10.0+7.jar
CorgiLib-forge-1.19.2-1.0.0.34.jar
CosmeticArmorReworked-1.19.2-v1a.jar
create-1.19.2-0.5.1.f.jar
createaddition-1.19.2-1.2.2.jar
createbigcannons-forge-1.19.2-0.5.3.b.jar
Cucumber-1.19.2-6.0.10.jar
curios-forge-1.19.2-5.1.6.1.jar
deeperdarker-forge-1.19.2-1.2.2.jar
dragonmounts-1.19.2-1.1.4a.jar
DungeonsArise-1.19.2-2.1.54-release.jar
easy_npc_1.19.2-3.7.3.jar
embeddium-0.3.0.jar
endersdelight-1.19-1.2.2.jar
EnigmaticLegacy-2.26.5.jar
eureka-1192-1.2.0-beta.2.jar
ExtendedCrafting-1.19.2-5.1.10.jar
extremesoundmuffler-3.39.jar
FarmersDelight-1.19.2-1.2.4.jar
ferritecore-5.0.3-forge.jar
FluxNetworks-1.19.2-7.1.4.13.jar
forbidden_arcanus-1.19.2-2.1.5.jar
framework-forge-1.19.2-0.6.16.jar
ftb-library-forge-1902.4.1-build.236.jar
ftb-quests-forge-1902.5.8-build.345.jar
FTBQuestsOptimizer-forge-1.2.1-1.19.2.jar
ftb-teams-forge-1902.2.14-build.123.jar
fullbrightnesstoggle-4.0.jar
geckolib-forge-1.19-3.1.40.jar
gtceu-1.19.2-1.1.2.a.jar
immersive_paintings-0.6.7+1.19.2-forge.jar
item-filters-forge-1902.2.9-build.51.jar
jei-1.19.2-forge-11.6.0.1018.jar
journeymap-1.19.2-5.9.7-forge.jar
konkrete_forge_1.8.0_MC_1.19-1.19.2.jar
kotlinforforge-3.12.0-all.jar
kubejs-create-forge-1902.2.4-build.36.jar
kubejs-forge-1902.6.2-build.54.jar
L_Enders_Cataclysm-1.90 tongue fixed-1.19.2.jar
LibX-1.19.2-4.2.8.jar
modernfix-forge-5.13.0+mc1.19.2.jar
moonlight-1.19.2-2.3.6-forge.jar
MouseTweaks-forge-mc1.19-2.23.jar
MythicBotany-1.19.2-3.0.2.jar
NethersDelight-1.19-3.1.jar
oculus-1.6.9.jar
oculus-flywheel-compat-0.2.1.jar
Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.1.6.jar
PackagedAuto-1.19.2-3.2.5.18.jar
PackagedExCrafting-1.19.2-3.2.1.13.jar
Patchouli-1.19.2-77.jar
pneumaticcraft-repressurized-1.19.2-4.3.14-49.jar
Powah-4.0.11.jar
Quark-3.4-418.jar
resourcefulconfig-forge-1.19.2-1.0.20.jar
resourcefullib-forge-1.19.2-1.1.24.jar
rhino-forge-1902.2.3-build.284.jar
rubidium-extra-0.4.19-build.105.jar
SandBox-1.19.2-1.0.1.jar
shutupexperimentalsettings-1.0.5.jar
sophisticatedcore-1.19.2-0.5.111.525.jar
sophisticatedstorage-1.19.2-0.8.56.681.jar
spore_1.19.2_2.0.2b.jar
Stargate Journey-1.19.2-0.6.19.jar
supermartijn642configlib-1.1.8-forge-mc1.19.jar
supermartijn642corelib-1.1.16-forge-mc1.19.2.jar
supplementaries-1.19.2-2.4.19.jar
swingthroughgrass-1.19.2-1.10.0.jar
TerraBlender-forge-1.19.2-2.0.1.136.jar
titanium-1.19.2-3.7.4-28.jar
TravelersTitles-1.19.2-Forge-3.1.2.jar
valhelsia_core-forge-1.19.2-0.5.0.jar
valkyrienskies-119-2.1.2-beta.1.jar
voicechat-forge-1.19.2-2.4.32.jar
void_above_nether_1.0.0_forge_1.19.2.jar
wthit-forge-5.21.0.jar
YungsApi-1.19.2-Forge-3.8.10.jar
YungsBetterDungeons-1.19.2-Forge-3.2.2.jar
YungsBetterNetherFortresses-1.19.2-Forge-1.0.6.jar
YungsBetterStrongholds-1.19.2-Forge-3.2.0.jar
YungsBetterWitchHuts-1.19.2-Forge-2.1.0.jar

### Expected Behavior

In GT version 1.19.2-1.1.2.a everything worked fine with KubeJS and its scripts.

### Actual Behavior

I updated GT mod to a newer version and now i get this error when trying to load in a world: https://imgur.com/a/CrKC4jh ("Errors in currently selected data packs prevented the world from loading. You can either try to load it with only the vanilla data pack ("safe mode"), or go back to the title screen and fix it manually.") But there is no problem with data packs (all removed completely, and "safe mode" doesn't work either).

### Steps to Reproduce

Install JEI, KubeJS and GT 1.19.2-1.1.3 and load into a world.

### Additional Information

It was caused by an 1.1.3 update.

**Comment by screret** [comment]
would help if you provided logs.

**Comment by Igneaalis** [comment]
latest.log: https://pastebin.com/4NgkpfbJ there is **no crash**

**Comment by Igneaalis** [comment]
Additional information: an error occures **only if kubejs' scripts are present**! For example, changing a vanilla recipe.

```js
ServerEvents.recipes( event => {
  event.shapeless('minecraft:stone', ['minecraft:iron_ingot'])
}
```

**Comment by dnk1234567** [comment]
This bug can also be reproduced on 1.20.1, Forge 47.2.6, gtceu 1.1.3 with minimal environment.
If you selected to create a world then the game will crash. 
```
java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because the return value of "java.util.Map.get(Object)" is null
	at net.minecraft.world.item.crafting.RecipeManager.handler$dei000$gtceu$cloneVanillaRecipes(RecipeManager.java:4044) ~[client-1.20.1-20230612.114412-srg.jar%231110!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:86) ~[client-1.20.1-20230612.114412-srg.jar%231110!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:34) ~[client-1.20.1-20230612.114412-srg.jar%231110!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
```
If you want to load a existing world then you will got a warning that the datapacks are broken and need "safe mode" to get in.

**Comment by screret** [comment]
> This bug can also be reproduced on 1.20.1, Forge 47.2.6, gtceu 1.1.3 with minimal environment. If you selected to create a world then the game will crash.
> 
> ```
> java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because the return value of "java.util.Map.get(Object)" is null
> 	at net.minecraft.world.item.crafting.RecipeManager.handler$dei000$gtceu$cloneVanillaRecipes(RecipeManager.java:4044) ~[client-1.20.1-20230612.114412-srg.jar%231110!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
> 	at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:86) ~[client-1.20.1-20230612.114412-srg.jar%231110!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
> 	at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:34) ~[client-1.20.1-20230612.114412-srg.jar%231110!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
> ```
> 
> If you want to load a existing world then you will got a warning that the datapacks are broken and need "safe mode" to get in.

1. different crash.
2. try the latest dev build.

**Comment by Exzept1on** [comment]
> This bug can also be reproduced on 1.20.1, Forge 47.2.6, gtceu 1.1.3 with minimal environment. If you selected to create a world then the game will crash.
> 
> ```
> java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because the return value of "java.util.Map.get(Object)" is null
> 	at net.minecraft.world.item.crafting.RecipeManager.handler$dei000$gtceu$cloneVanillaRecipes(RecipeManager.java:4044) ~[client-1.20.1-20230612.114412-srg.jar%231110!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
> 	at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:86) ~[client-1.20.1-20230612.114412-srg.jar%231110!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
> 	at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:34) ~[client-1.20.1-20230612.114412-srg.jar%231110!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
> ```
> 
> If you want to load a existing world then you will got a warning that the datapacks are broken and need "safe mode" to get in.

I can confirm that some users of our modpack have seen the same crash (but on 1.20.1 with gtceu 1.1.3)

**Comment by dnk1234567** [comment]
> > This bug can also be reproduced on 1.20.1, Forge 47.2.6, gtceu 1.1.3 with minimal environment. If you selected to create a world then the game will crash.
> > ```
> > java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because the return value of "java.util.Map.get(Object)" is null
> > 	at net.minecraft.world.item.crafting.RecipeManager.handler$dei000$gtceu$cloneVanillaRecipes(RecipeManager.java:4044) ~[client-1.20.1-20230612.114412-srg.jar%231110!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
> > 	at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:86) ~[client-1.20.1-20230612.114412-srg.jar%231110!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
> > 	at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:34) ~[client-1.20.1-20230612.114412-srg.jar%231110!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If you want to load a existing world then you will got a warning that the datapacks are broken and need "safe mode" to get in.
> 
> 1. different crash.
> 2. try the latest dev build.

1. I send this issue here because I saw he also meet datapack error and it may related to the vanilla recipes.
2. It seems that 1.1.3-build_485 already fixed it. Many Thanks!
