### ISSUE TITLE
Crash on Pipe Connected to Machine

### ISSUE THREAD

**Issue by Phoupraw** [GregTechCEu/GregTechCEu-1.19#89]
### GregTech CEu Version

1.0.3-alpha

### Recipe Viewer Installed

REI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Expected Behavior

No crashing.

### Actual Behavior

Crashed.

### Steps to Reproduce

1. Place a steam boiler.
2. Place a small copper fluid pipe next to its outlet.
3. Crash, and still crash when re-entering the world. The save is corrupted.

### Additional Information

[minecraft-exported-crash-info-2023-05-21T19-02-42.zip](https://github.com/GregTechCEu/GregTechCEu-1.19/files/11524330/minecraft-exported-crash-info-2023-05-21T19-02-42.zip)

**Comment by Yefancy** [comment]
fixed in #29
