### ISSUE TITLE
Alloy blast smelter - parallel hatch

### ISSUE THREAD

**Issue by Y3llowL1ght** [GregTechCEu/GregTechCEu-1.19#894]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.20.1-1.1.1.a

### Recipe Viewer Installed

JEI

### Environment

single

### Cross-Mod Interaction

Yes

### Other Installed Mods

gtceum community pack 1.3.0

### Expected Behavior

Alloy blast smelter multiblock can use parallel hatch as it is written in tooltip
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/42408361/e1d07656-c8dc-4648-8310-b7abf51ffb9f)

### Actual Behavior

It does not form when parallel hatch is present

### Steps to Reproduce

Form the working multi, try to reform with the parallel hatch introduced

### Additional Information

i did not check on the latest version, but looking at the code(def. branch)/github log i dont think it is fixed or even documented :P
also not even sure if it is intended, making the issue since tooltup says it should be able to use the p.hatch

**Comment by screret** [comment]
me when I don't test the latest version.
