### ISSUE TITLE
Travel Anchor block is not recoverable

### ISSUE THREAD

**Issue by Alves24** [GregTechCEu/GregTechCEu-1.19#898]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.1.3 485 build

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

None

### Expected Behavior

Recoverable with a pickaxe

### Actual Behavior

Is not recoverable with any tool or silktouch enchantment

### Steps to Reproduce

Try to break it on survival mode

**Comment by PrototypeTrousers** [comment]
wrong mod bro

**Comment by Alves24** [comment]
Yep sorry
