### ISSUE TITLE
Laser target hatch and Laser resource hatch crashes the game and breaks the save data when it's connected.

### ISSUE THREAD

**Issue by Kuroneko3722** [GregTechCEu/GregTechCEu-1.19#899]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.20.1 1.1.2a

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

SkyGreg 1.19

### Expected Behavior

Works normally as dynamo hatch and energy hatch.

### Actual Behavior

Game crashes and breaks the save data the moment laser pipe is connected, has to use backup to fix.

### Steps to Reproduce

Place a 256A luv laser source hatch on substation, then connect it to an active transformer with 256A laser target hatch. 
4096A laser hatches also breaks.
Not just substation to active transformer, active transformer to active transformer with laser hatch breaks too.

### Additional Information

The modpack is using 1.1.2a as newer version has critical bugs on ores. Ores can't be smelted or grinded if it updates.

**Comment by screret** [comment]
does this happen on the latest version?
