### ISSUE TITLE
ConnectedTexturesMod incompatibility (Forge)

### ISSUE THREAD

**Issue by h3tR** [GregTechCEu/GregTechCEu-1.19#9]
### GregTech CEu Version

v1.0.0

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

Expected for both mods to run simultaneous and work together.

### Actual Behavior

A Minecraft forge instance with both CTM and GregtechCEu + ldlib will not start

### Steps to Reproduce

Start Minecraft with forge while CTM, GTCeu and ldlib are installed.

**Comment by Yefancy** [comment]
we have our own CTM.
