### ISSUE TITLE
Use Forge Connected Textures Standard & Add Facade Mixin

### ISSUE THREAD

**Issue by Drackion** [GregTechCEu/GregTechCEu-1.19#90]
### Feature Description

-  [x] Connected textures now use and apply the getAppearance() standard by Forge, allowing them to connect across other mods' facades, etc. (1.19)

(From the create changelog)

--------------------------------------------------------------------------------------------------------------------------------------------

- [x] We also need to add a mixin to fix facades/etc not getting the material block texture correctly

![2023-05-22_16 19 19](https://github.com/GregTechCEu/GregTechCEu-1.19/assets/64641342/fb7dabcd-0a5e-4b10-85fb-83bf0b8c145a)

**Comment by screret** [comment]
Fixed in GregTechCEu/GregTechLib-1.19#2
