### ISSUE TITLE
cant create new world

### ISSUE THREAD

**Issue by IIIap** [GregTechCEu/GregTechCEu-1.19#900]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.1.3

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Gregtech Modern Community Pack

### Expected Behavior

create new world

### Actual Behavior

got crash

### Steps to Reproduce

click "Create new world" in world list

### Additional Information

[crash-2024-02-10_22.15.58-client.txt](https://github.com/GregTechCEu/GregTech-Modern/files/14230305/crash-2024-02-10_22.15.58-client.txt)
[crash-2024-02-10_22.25.55-client.txt](https://github.com/GregTechCEu/GregTech-Modern/files/14230306/crash-2024-02-10_22.25.55-client.txt)
[crash-2024-02-10_22.20.10-client.txt](https://github.com/GregTechCEu/GregTech-Modern/files/14230307/crash-2024-02-10_22.20.10-client.txt)

**Comment by screret** [comment]
try the latest github build.

**Comment by IIIap** [comment]
> try the latest github build.
with latest release from github i cant even join 

[crash-2024-02-10_23.41.42-client.txt](https://github.com/GregTechCEu/GregTech-Modern/files/14230451/crash-2024-02-10_23.41.42-client.txt)

**Comment by screret** [comment]
remove your separately installed LDLib.

**Comment by screret** [comment]
it's bundled with GT

**Comment by IIIap** [comment]
> remove your separately installed LDLib.

I accidentally restored it from the recycler. all works fine, thx
