### ISSUE TITLE
high pressure steam furnace has no recipes

### ISSUE THREAD

**Issue by gre4kapi** [GregTechCEu/GregTechCEu-1.19#901]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.1.3

### Recipe Viewer Installed

EMI

### Environment

Single and Multiplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

TerraFirmaGreg ModPack

### Expected Behavior

High Pressure Steam Furnace has many recipes

### Actual Behavior

High Pressure Steam Furnace has no recipes

### Steps to Reproduce

1) Install gtceu-1.20.1-1.1.3

**Comment by screret** [comment]
fixed already. try a dev build.
