### ISSUE TITLE
Large miners do not produce 3x more crushed ore than macerators

### ISSUE THREAD

**Issue by JoshX9706** [GregTechCEu/GregTechCEu-1.19#902]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.1.3

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

ATM9

### Expected Behavior

As the tooltip states, the large miner should "produce 3x more crushed ore than a macerator"
so I expect it to produce 6 crushed ore for normal ores, as macerators make 2 crushed ore per normal ore
and it should make 12 crushed ore for nether/end ores, as macerators make 4 crushed ore per nether/end ore
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/47550807/6d66cbb7-4ebc-4d64-8210-d03843ff760a)

### Actual Behavior

In tests, after having the miner clear out the entire rest of the chunk to remove error, I placed 8 ore under it. It produced:
24 crushed magnetite ore for 8 normal ore; 3 crushed ore on average
42 crushed molybdenum ore for 8 end ore; 5.25 crushed ore on average
these are a far cry from the advertised rates
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/47550807/c48429c1-0436-4f32-9f5b-642c12afbd25)

### Steps to Reproduce

use a chunk destroyer to clear out the entire chunk of blocks
run the miner on 1x1 chunk mode until it removes all the "phantom" ore
place 8 ore under and around it, so that the mining pipe wouldn't potentially delete ore
restart miner (I cycled through chunk scale then enabled the machine)
count the crushed ore

### Additional Information

as my current atm9 installation isnt up to date, nor has the latest gregtech mod, I updated it in a separate profile to verify this.

**Comment by screret** [comment]
guess we gotta bump up the fortune level used

**Comment by cuberyl-catastrophe** [comment]
> guess we gotta bump up the fortune level used

Doesn't fortune not work on ores?

**Comment by screret** [comment]
this is special cased to work.
