### ISSUE TITLE
Create 0.5.1 Breaks gtceu compat

### ISSUE THREAD

**Issue by Drackion** [GregTechCEu/GregTechCEu-1.19#91]
### GregTech CEu Version

v1.0.3

### Recipe Viewer Installed

REI

### Environment

Singleplayer Forge

### Cross-Mod Interaction

Yes

### Expected Behavior

To launch

### Actual Behavior

Minecraft fails to load gtceu.

https://paste.gg/p/anonymous/b93b14d04cdb4ffa8638793f3037460c

### Steps to Reproduce

Forge 42.2.3
gtceu 1.0.3
create 0.5.1
then launch

**Comment by Yefancy** [comment]
create forge 0.5.1 has big changes: repacking and include flywheel. but create fabric hasn't released an available version yet, while theyre working on 0.5.1 fabric these days. this will be fixed when fabric 0.5.1 out
