### ISSUE TITLE
Ceramics require pressing before sintering

### ISSUE THREAD

**Issue by EntityIridescent** [GregTechCEu/GregTechCEu-1.19#914]
### Feature Description

Some materials, specifically tungsten carbide (WC) can be rolled into plates and other shapes. While I understand it is just a mod and doesn't have to be completely realistic, I think it would be a cool idea to use the Mixer to combine tungsten, carbon, and other binders into a "green" unfired ceramic powder or paste and pressed in the Forming Press. They could then be fired in the blast furnace to obtain the final plate or other component.

**Comment by Markh3tr** [comment]
I really like this idea, however I believe this feature would be more fit for customized packs or addons than in base GT.

**Comment by screret** [comment]
too complex for the base mod IMO, do it in your pack if you want to.
