### ISSUE TITLE
EBF in ATM9 won't process the arsenic trioxide recipe

### ISSUE THREAD

**Issue by leeroberts4** [GregTechCEu/GregTechCEu-1.19#915]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.1.3.b

### Recipe Viewer Installed

JEI

### Environment

dedicated server

### Cross-Mod Interaction

Unsure

### Other Installed Mods

ATM9 version 0.2.46

### Expected Behavior

I feed the cobaltite dust and oxygen to the EBF to produce arsenic trioxide.

### Actual Behavior

the EBF gets stuck on with no flickering (I have two 4x battery buffers supplying the power) and if I toggle it off and on it voids the resources.
![EBF](https://github.com/GregTechCEu/GregTech-Modern/assets/139653017/18788f5f-1c10-4b2c-be5a-bf30d0a052ea)

### Steps to Reproduce

I have tried rebuilding the EBF and relocating it with no change.

**Comment by Sakreton** [comment]
I have the same issue, in the same version and the same environment, as far as i tested it, this affects more multiblocks, Coke ovens, assembly lines. With all tested recipes affected the way described above

**Comment by screret** [comment]
fairly certain this is related to the broken asyncRecipeSearch config, could you test again?
