### ISSUE TITLE
Electric Furnace not working in 1.1.3

### ISSUE THREAD

**Issue by ccpemily** [GregTechCEu/GregTechCEu-1.19#921]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.20.1-1.1.3b-build498

### Recipe Viewer Installed

None

### Environment

SSP

### Cross-Mod Interaction

No

### Other Installed Mods

Architectury

### Expected Behavior

Electric furnace should smelt raw meat to cooked meat.

### Actual Behavior

Put some raw chicken into an Advanced Electric Furnace, then supply it with Medium Lithium Battery, but nothing happens.
![a](https://github.com/GregTechCEu/GregTech-Modern/assets/56390205/87f15d5a-b253-43c5-94a8-d327edf2646e)

### Steps to Reproduce

Put some raw chicken into an Advanced Electric Furnace, then supply it with Medium Lithium Battery

**Comment by jorgsaa** [comment]
I also have the same problem on 1.19.2-1.1.3.b-build_497 (no recipes work afaik)
