### ISSUE TITLE
Large steam boiler no work

### ISSUE THREAD

**Issue by Lazy3ah** [GregTechCEu/GregTechCEu-1.19#924]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.1.3

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

The modpack I am playing is Sky Greg

### Expected Behavior

As the title says, the boiler is running normally before the update, and after the update, it is on standby, does not consume steam, does not generate energy.

### Actual Behavior

fix

### Steps to Reproduce

Normal assembly large steel steam boiler introduction steam

### Additional Information

It seems he couldn't detect the steam in the input chamber.

**Comment by Lazy3ah** [comment]
sry my english is bad may  Actual Behavior is "As the title says, the boiler is running normally before the update, and after the update, it is on standby, does not consume steam, does not generate energy."

**Comment by screret** [comment]
assuming fixed.
