### ISSUE TITLE
JADE does not show pipe content

### ISSUE THREAD

**Issue by KraftKraftKraft** [GregTechCEu/GregTechCEu-1.19#925]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1-1.1.3.b

### Recipe Viewer Installed

None

### Environment

Single

### Cross-Mod Interaction

Yes

### Other Installed Mods

Jade-1.20.1-forge-11.8.0

### Expected Behavior

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/129421418/84d1e5e4-97f5-47b0-9b6b-2785fa449aa9)
gtceu-1.20.1-1.1.3

### Actual Behavior

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/129421418/97881315-91d2-4d69-9697-3a21bf27fce2)
gtceu-1.20.1-1.1.3.b

### Steps to Reproduce

1

**Comment by FakemanG** [comment]
I can't use any pipe to transfer anything ,not only it doesn't show its contents.
