### ISSUE TITLE
Plasma Turbines and Gas Turbines and not working

### ISSUE THREAD

**Issue by cairn1111** [GregTechCEu/GregTechCEu-1.19#928]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.1.3.b

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

EMI, The One Probe

### Expected Behavior

The Plasma/Gas turbine will consume fuel and generate EU

### Actual Behavior

Multiblock forms but stays idle. It does not start the recipe.

### Steps to Reproduce

1)Construct the multiblock
2) Ensure all maintenance issues are taken care of
3) Ensure the turbine is provided a rotor
4) Ensure the turbine is provided with fuel
5) Notice the turbine will stay Idling

**Comment by KraftKraftKraft** [comment]
+
we need gas turbine)

**Comment by Lazy3ah** [comment]
Hey bro I have the same problem you have.
I modified the configuration file and it seems to work.
set asyncRecipeSearch to false maybe a solution.
Please back up your archive in case of unexpected errors

**Comment by cairn1111** [comment]
> Hey bro I have the same problem you have. I modified the configuration file and it seems to work. set asyncRecipeSearch to false maybe a solution. Please back up your archive in case of unexpected errors

Thank you for the suggestion!
That did the trick.
I'm not sure if there's any other unintended affect but so far so good!

**Comment by xavierlauzon** [comment]
I have set asyncRecipeSearch to false in my gtceu.yaml config, however, I am still having the issue of the turbine sitting idle without generating EU. Any tips?

**Comment by z0the** [comment]
> Hey bro I have the same problem you have. I modified the configuration file and it seems to work. set asyncRecipeSearch to false maybe a solution. Please back up your archive in case of unexpected errors

Thanks man, it worked for me. Minecrfat ver 1.20.1
