### ISSUE TITLE
Major typo in auto generated recipe ID

### ISSUE THREAD

**Issue by Leclowndu93150** [GregTechCEu/GregTechCEu-1.19#93]
### GregTech CEu Version

1.0.39

### Recipe Viewer Installed

REI

### Environment

SP

### Cross-Mod Interaction

No

### Expected Behavior

![image](https://github.com/GregTechCEu/GregTechCEu-1.19/assets/73310949/ef68e675-dcbd-4954-a358-e14d181ad534)
distilled*

### Actual Behavior

![image](https://github.com/GregTechCEu/GregTechCEu-1.19/assets/73310949/f40c1cdb-754e-4dc2-b0b2-cd5ad816f67f)
distlled

### Steps to Reproduce

become gay ?

### Additional Information

thanks

**Comment by screret** [comment]
fixed in #92.
