### ISSUE TITLE
Can't get distilled water from basic steam turbine generator

### ISSUE THREAD

**Issue by MatthiasMann** [GregTechCEu/GregTechCEu-1.19#931]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.20.1-1.1.3.b

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

GregTech Community Pack Modern + Whetstones + Waystones

### Expected Behavior

according to JEI the steam turbine generator should produce 4mB of distilled water for every 320mB of steam

### Actual Behavior

The output slot stays empty, I tried to configure it's output but the machines seems to have no configurable outputs. I also placed a barrel on top which also did not receive any distilled water.

### Steps to Reproduce

- have the steam turbine generator connected via small bronze pipes to some boiler
- have steam going into the generator
- consume the generated power

**Comment by Drackion** [comment]
on purpose, distilled water should only be a by product of the multi block steam turbines

**Comment by MatthiasMann** [comment]
Then this should be hidden in JEI?

**Comment by screret** [comment]
well no, as the multiblocks use the same recipes.

**Comment by MatthiasMann** [comment]
Hmm - maybe hide the output slot on the small generators?

**Comment by AnotherNeko** [comment]
the smaller steam turbines should have the same output tank capacity as the low pressure / high pressure steam extractors - 0/0 mB. That would make it obvious that the steam turbine has no room for distilled water.

**Comment by Twisted6** [comment]
Found this after Googling this same problem. It needs to be made more obvious that the single block doesn't output distilled water.

**Comment by screret** [comment]
It shouldn't even have the output slot, but that was deemed too annoying and fragile to make with our current systems. 
We're in the process of swapping UI implementations currently, though, so this might be fixed in a couple months.
