### ISSUE TITLE
Gregtech Microprocessor Supercomputer not crafteble

### ISSUE THREAD

**Issue by raupi11** [GregTechCEu/GregTechCEu-1.19#934]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-1.20.1-1.1.3.b.jar

### Recipe Viewer Installed

JEI

### Environment

Dedicated Server

### Cross-Mod Interaction

No

### Other Installed Mods

ATM 9

### Expected Behavior

All the Recipes for Microprocessor Supercomputers not work in the Circuit Assembler.

### Actual Behavior

The crafting dont start.

### Steps to Reproduce

Manual fill the Circuit Assembler with  the  required Components, nothing happens.
Autocraft with AE2 dont work too.

**Comment by Markh3tr** [comment]
Can't recreate this in base GT, so it is definitely related to cross mod interactions

**Comment by screret** [comment]
1. not enough info
2. works for me, does the machine have power and solder?
