### ISSUE TITLE
Items filters not working on pipes

### ISSUE THREAD

**Issue by hgjensen** [GregTechCEu/GregTechCEu-1.19#936]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.1.3.b

### Recipe Viewer Installed

JEI

### Environment

Dedicated Server

### Cross-Mod Interaction

No

### Other Installed Mods

ATM9

### Expected Behavior

Chest A <-conveyor,import-> Pipe <-item filter for coal-> Chest B

When putting a piece of cobblestone into Chest A, it should stay there.

### Actual Behavior

The cobblestone goes to Chest B

### Steps to Reproduce

Place vanilla chest A and B with one block between them
Place normal tin pipe between chests.
Place conveyor on pipe facing chest A. Configure for import mode.
Place item filter on pipe facing chest B. Configure to whitelist coal.

Put any non-coal block into chest A and it will end up in chest B.

### Additional Information

When configuring the filter, the option to filter insert/extract or both, does not work. It always reverts to "Filter Insert".
The same thing happens with Item Tag Filter.

The filter works if I put it inside an actual conveyor set to export mode, and the "Manual I/O" is set to "Filtered".

**Comment by YoungOnionMC** [comment]
fixed in #2126
