### ISSUE TITLE
Extreme lag when looking at cables

### ISSUE THREAD

**Issue by EntityIridescent** [GregTechCEu/GregTechCEu-1.19#937]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.1.3b

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Stabx Modern Guns (by stabilizer_king)
YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)
Quark (by Vazkii)
Macaw's Windows (by sketch_macaw)
Dungeons and Taverns (by Nova_Wostra)
OpenBlocks Elevator (by vsngarcia)
Whisperwoods (by itsmeowdev)
U Team Core (by HyCraftHD)
YUNG's Better Strongholds (Forge) (by YUNGNICKYOUNG)
Polymorph (Fabric/Forge/Quilt) (by TheIllusiveC4)
Almost Unified (by AlmostReliable)
Star Wars Planets Ad Astra! [Forge/Fabric] (by TathanDev)
Cupboard (by someaddon)
Stargate Journey (by Povstalec)
Immersive Engineering (by BluSunrize)
[Let's Do] API (by Cristelknight)
Rubidium (by Asek3)
Applied Energistics 2 (by thetechnici4n)
Ensorcellation (by TeamCoFH)
Open Loader (by DarkhaxDev)
Simple Backups (by MelanX)
Lazy DataFixerUpper(LazyDFU) [FORGE] (by Corgi_Taco)
Ex Nihilo: Sequentia - Mekanism Addon (by NovaMachina)
Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)
Embeddium/Rubidium Extras (by Anthxny)
Patchouli (by Vazkii)
Global Packs (by JTK222)
Towns and Towers (by Biban_Auriu)
Enhanced Celestials - Blood, Blue, & Harvest (Super) Moons (by Corgi_Taco)
Xaero's World Map (by xaero96)
Fusion (Connected Textures) (by SuperMartijn642)
True Darkness (by GrondagTheBarbarian)
ForgeEndertech (by EnderLanky)
FastWorkbench (by Shadows_of_Fire)
Balm (Forge Edition) (by BlayTheNinth)
Spice of Life: Carrot Edition (by lordcazsius)
Entity Collision FPS Fix (by Corgi_Taco)
AutoRegLib (by Vazkii)
Industrial Foregoing Tweaker (by Mrthomas20121)
Light Overlay (Rift/Forge/Fabric) (by shedaniel)
Better Fps - Render Distance[Forge] (by someaddon)
Stellar View (by Povstalec)
Chimes (by BlewberryPie)
Just Enough Items (JEI) (by mezz)
Supplementaries (by MehVahdJukaar)
Bookshelf (by DarkhaxDev)
YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)
Yeetus Experimentus (by Sunekaer)
GregTechCEu Modern (by KilaBash)
AppleSkin (by squeek502)
Resourceful Config (by ThatGravyBoat)
WorldEdit (by sk89q)
Architectury API (Fabric/Forge/NeoForge) (by shedaniel)
Naturalist (by Starfish_Studios)
Nature's Compass (by Chaosyr)
AI Improvements (by QueenOfMissiles)
Connected Glass (by SuperMartijn642)
Steve's Meteors (by Lil_Cerb)
Simple Planes (Forge) (by przemykomo)
Rotten Creatures (by fusionstudiomc)
CoFH Core (by TeamCoFH)
Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4)
Block Swap (by Corgi_Taco)
Macaw's Furniture (by sketch_macaw)
Ad Astra: Giselle Addon (by 지젤쟝다)
In Control! (by McJty)
Saturn (by AbdElAziz333)
Twigs (by ninnih_)
William Wythers' Expanded Ecosphere (by Cristelknight)
Simply Light (by Flanks255)
ImmediatelyFast (by RaphiMC)
Realm RPG: Fallen Adventurers (by nocubeyt)
Advanced Hook Launchers (by EnderLanky)
CorgiLib (by Corgi_Taco)
Embeddium/Rubidium Dynamic Lights (by Anthxny)
Tetra (by mickelus)
Framework (by MrCrayfish)
Philip's Ruins (by philipmoddev)
Clumps (by Jaredlll08)
Cloth Config API (Fabric/Forge/NeoForge) (by shedaniel)
Titanium (by Buuz135)
YUNG's Extras (Forge) (by YUNGNICKYOUNG)
The One Probe (by McJty)
Placebo (by Shadows_of_Fire)
AttributeFix (by DarkhaxDev)
Farmer's Delight (by vectorwing)
MrCrayfish's Gun Mod (by MrCrayfish)
The Accurate Backrooms (by ShadyOcclusion872)
Industrial Foregoing (by Buuz135)
Controlling (by Jaredlll08)
Mekanism (by bradyaidanc)
mutil (by mickelus)
CC: Tweaked (by SquidDev)
The Graveyard (FORGE) (by finallion_13)
Additional Guns (by AutovwDev)
FerriteCore ((Neo)Forge) (by malte0811)
FastFurnace (by Shadows_of_Fire)
Polymorphic Energistics (by ninety)
Useful Backpacks (by HyCraftHD)
Structory (by botanydev)
Loot Integrations[Forge/Fabric] (by someaddon)
Straw Statues [Forge & Fabric] (by Fuzs)
Ad Astra (by AlexNijjar)
Not Enough Crashes (Forge) (by NatanFudge)
Mekanism Generators (by bradyaidanc)
Chunk Loaders (by SuperMartijn642)
GeckoLib (by Gecko)
Moonlight Lib (by MehVahdJukaar)
JEITweaker (by Jaredlll08)
From The Fog (by LunarEclipseStudios)
Just CTGUI (by 300f20t)
Botarium (by CodexAdrian)
GraveStone Mod (by henkelmax)
Another Furniture (by Starfish_Studios)
Fast Leaf Decay (by olafskiii)
Ex Nihilo: Sequentia (by NovaMachina)
Puzzles Lib [Forge & Fabric] (by Fuzs)
Cognition (formerly Experience Obelisk) (by cyanog3n)
TerraBlender (Forge) (by TheAdubbz)
SuperMartijn642's Core Lib (by SuperMartijn642)
Protect Mobs From Daylight (by AnEngineerMan)
SuperMartijn642's Config Lib (by SuperMartijn642)
Integrated API (by CraisinLord)
MemoryLeakFix (by FX_PR0CESS)
Delightful (by brnbrd)
[Let's Do] Bakery (by satisfy)
InsaneLib (by Insane96)
Supernatural (by Jusey1z)
Dark Paintings (by DarkhaxDev)
Curios API (Forge/NeoForge) (by TheIllusiveC4)
YUNG's Bridges (Forge) (by YUNGNICKYOUNG)
Additional Structures (by XxRexRaptorxX)
YUNG's API (Forge) (by YUNGNICKYOUNG)
Resourceful Lib (by ThatGravyBoat)
Ex Nihilo: Sequentia - AE2 Addon (by NovaMachina)
Buried Wrecks (by Mrbysco)
Mouse Tweaks (by YaLTeR)
Modern UI (by BloCamLimb)
CraftTweaker (by Jaredlll08)
The Man From The Fog (by M_Productions)
CullLessLeaves Reforged (Unofficial) (by ccr4ft3r)
ModernFix (by embeddedt)
Crafting Tweaks (by BlayTheNinth)
Xaero's Minimap (Fair-play Edition) (by xaero96)

### Expected Behavior

Connections for wires can be made and altered without lag to the client or server. 

### Actual Behavior

Whenever wires or the corresponding orientation overlay is rendered, the client experiences a massive performance hit. 

### Steps to Reproduce

1. Place lengths of wire ~3-4 blocks, with multiple machines attached.
2. (Optional) Hold wire cutters and hover over the wire to display the config overlay. 
3. Framerate significantly drops.

### Additional Information

It seems to lag more when holding wire cutters, which renders the overlay. It also seems to lag more with regular cables compared to superconductors, indicating it might be an issue with calculating wire resistances over short distances.

**Comment by screret** [comment]
@Yefancy you might want to look at this?
