### ISSUE TITLE
Crash after clicking singleplayer in main menu: Cannot invoke "com.gregtechceu.gtceu.api.capability.IElectricItem.getMaxCharge()" because "powerUnit" is null

### ISSUE THREAD

**Issue by SpiritSb2O** [GregTechCEu/GregTechCEu-1.19#941]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.1.3.b

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

- Functional Storage [1.20.1-1.2.7
]
- Labels [1.20-1.20]
- AE2 Things [1.2.1]
- Create Sifter [1.20.1-1.8.1.e-22
]
- Glodium [1.20-1.3-forge]
- Ars Nouveau [4.9.0
]
- Curios API [5.7.0+1.20.1
]
- Just Enough Items [15.3.0.4]
- GeckoLib 4 [4.4.2]
- Create Enchantment Industry [1.2.7.h
]
- Dimensional Paintings [2.0.2
]
- Rechiseled: Create [1.0.2]
- Gateways To Eternity [4.2.3]
- Just Enough Characters [4.5.9]
- Aquaculture Delight [1.0.0]
- Cloth Config v10 API [11.1.118]
- Embeddium [0.3.4+mc1.20.1]
- Silent Lib [8.0.0
]
- Another Furniture [1.20.1-3.0.1]
- ME Requester [1.20.1-1.1.4]
- Fusion [1.1.0c]
- Jade Addons [5.2.2
]
- FTB Ultimine [2001.1.4]
- ExtendedAE [1.20-1.0.11-forge]
- Iron Jetpacks [7.0.3
]
- Construction Wand [1.20.1-2.11
]
- RFToolsUtility [1.20-6.0.5
]
- Clumps [12.0.0.3
]
- Tom's Simple Storage Mod [1.6.5
]
- Builder's Delight [1.2]
- MmmMmmMmmmmm [1.20-1.8.14]
- CosmeticArmorReworked [1.20.1-v1a]
- Apothic Attributes [1.2.1]
- Elevator Mod [1.20.1-lex-1.9]
- McJtyLib [1.20-8.0.3
]
- Comforts [6.3.5+1.20.1]
- Decorative Blocks [4.1.3]
- RFToolsStorage [1.20-5.0.2
]
- Sophisticated Core [0.6.3.553]
- Thermal Foundation [11.0.2]
- FTB Filter System [1.0.2]
- Nether's Delight [1.20.1-4.0]
- Macaw's Fences and Walls [1.1.1]
- Sophisticated Storage [0.9.6.720]
- Iron Furnaces [4.1.4]
- Create Sabers [1.3.0]
- Highlighter [1.1.9
]
- Resourcefulconfig [2.1.2]
- AppleSkin [2.5.1+mc1.20.1
]
- Ferrite Core [6.0.1
]
- Entangled [1.3.17]
- Macaw's Bridges [2.1.1]
- Fast Leaf Decay [31]
- Kambrik [6.1.1+1.20.1]
- CoFH Core [11.0.0]
- Iron's Spells 'n Spellbooks [1.20.1-2.2.2]
- Better Compatibility Checker [4.0.8]
- Chipped [3.0.4]
- Jade [11.7.1
]
- Ars Ocultas [1.2.1]
- Better Combat [1.8.4+1.20.1]
- Integrated API [1.3.5+1.20.1-forge]
- DimStorage [8.0.1]
- FTB Chunks [2001.2.5]
- I18nUpdateMod [3.5.3]
- Just Enough Calculation [4.0.4]
- Light Overlay [8.0.0]
- Just Enough Resources [1.4.0.247]
- FTB Teams [2001.1.4]
- Patchouli [1.20.1-84-FORGE
]
- CC: Tweaked [1.109.6]
- Create Ore Excavation [1.4.2
]
- Silent Gear [3.5.3
]
- Lighting Wand [8.0.0
]
- Advanced Peripherals [0.7.38r]
- Create: Bells & Whistles [0.4.3-1.20.x]
- Overloaded Armor Bar [1.20.1-1
]
- Supplementaries [1.20-2.7.36]
- Legendary Tooltips [1.4.5
]
- Building Gadgets 2 [1.0.6
]
- Create Crafts & Additions [1.20.1-1.2.3
]
- Classic Bar [1.20.1-1
]
- Productive Bees [1.20.1-12.3.1]
- Waystones [14.1.3]
- CraftingTweaks [18.2.2]
- Kiwi Library [11.5.3
]
- Searchables [1.0.2
]
- Torchmaster [20.1.5]
- Puzzles Lib [8.1.17]
- Enchanting Infuser [8.0.2]
- Fruits Delight [1.0.8
]
- Ars Énergistique [1.1.5]
- Create: Design n' Decor [0.3.0]
- SuperMartijn642's Config Library [1.1.8]
- SmartBrainLib [1.13]
- Configured [2.2.2]
- Architectury [9.1.13]
- Chunk Loaders [1.2.8a]
- Macaw's Doors [1.1.0]
- Biomes O' Plenty [18.0.0.592
]
- Shrink [1.4.5
]
- Create Mechanical Extruder [1.20.1-1.5.7.e-22
]
- Oculus [1.6.15a]
- Create Deco [2.0.1-1.20.1-forge]
- SuperMartijn642's Core Lib [1.1.17]
- Fast Workbench [8.0.4]
- Create Confectionery [1.1.0]
- Ars Elemental [1.20.1-0.6.4.1
]
- Item Filters [2001.1.0-build.59]
- Creeper Overhaul [3.0.1]
- Lootr [0.7.31.77]
- ModernFix [5.13.0+mc1.20.1]
- AttributeFix [21.0.4]
- Create: Interiors [0.5.2]
- Dramatic Doors [1.20.1-3.1.5]
- Extreme Sound Muffler [3.41-forge-1.20
]
- Delightful [3.4.2
]
- Polymorph [0.49.2+1.20.1]
- Cucumber Library [7.0.7
]
- Oculus Flywheel Compat [1.20.1-0.2.4
]
- Pylons [4.2.1
]
- Iceberg [1.1.18
]
- Aquaculture 2 [2.5.1]
- Farmer's Delight [1.20.1-1.2.4]
- Controlling [12.0.2
]
- Quark [4.0-436]
- Zeta [1.0-13
]
- FTB Library [2001.1.5]
- Dank Storage [8
]
- FastFurnace [8.0.1]
- Titanium [3.8.25
]
- Tool Belt [1.20.0
]
- create: things and misc [1.0.0]
- Naturalist [4.0.3]
- Balm [7.2.1]
- End's Delight [1.0.1]
- Sophisticated Backpacks [3.20.1.1012]
- FTB Essentials [2001.2.2]
- Placebo [8.6.1]
- Modonomicon [1.59.0]
- Every Compat [1.20-2.6.33]
- TerraBlender [3.0.1.4
]
- RFToolsBuilder [1.20-6.0.4
]
- AutoRegLib [1.8.2-55
]
- EdivadLib [2.0.1]
- Embeddium Extras [2.0.0]
- Moonlight Library [1.20-2.9.17]
- Player Animator [1.0.2-rc1+1.20]
- AE Additions [5.0.5]
- Explorer's Compass [1.20.1-1.3.3-forge]
- Mouse Tweaks [2.25
]
- Corail Woodcutter [3.0.4
]
- Item Collectors [1.1.9]
- Miner's Delight [1.20.1-1.2.3
]
- kotlinforforge-4.10.0-all
- Handcrafted [3.0.6]
- Better Advancements [0.3.2.162]
- Applied Cooking [4.0.0]
- Ars Creo [4.0.1
]
- Journeymap [5.9.18]
- Create [0.5.1.f
]
- Hostile Neural Networks [5.2.1]
- Simple Planes [1.20.1-5.2.7
]
- Easy Villagers [1.20.1-1.0.17]
- Twigs [1.20.1-3.1.1]
- FTB XMod Compat [2.1.0]
- Ocean's Delight [1.0.2-1.20
]
- Crafting On A Stick [1.1.4]
- Not Enough Crashes [4.4.7+1.20.1]
- RFToolsBase [1.20-5.0.2
]
- Sebastrn Lib [4.0.0]
- GregTech [1.1.3.b]
- Applied Energistics 2 [15.0.21]
- Trash Cans [1.0.18b]
- Bountiful [6.0.3+1.20.1]
- Athena [3.1.1]
- XNet [1.20-6.0.2
]
- Macaw's Trapdoors [1.1.2]
- Create: Steam 'n' Rails [1.5.3+forge-mc1.20.1]
- AE2WTLib [15.2.1-forge]
- CC:C Bridge [1.6.3-forge]
- AEInfinityBooster [1.20.1-1.0.0+21
]
- Macaw's Windows [2.2.1]
- Prism [1.0.5]
- Modular Routers [12.1.1+mc1.20.1]
- Geophilic Reforged [1.2.0]
- Silent Compat [1.3.5
]
- Create: Central Kitchen [1.3.9.e
]
- PneumaticCraft: Repressurized [6.0.14+mc1.20.1]
- PolyLib [2000.0.3-build.97]
- Crate Delight [1.0.4]
- Simple Magnets [1.1.10]
- Caelus API [3.1.0+1.20]
- Nature's Compass [1.20.1-1.11.2-forge]
- MEGA Cells [2.3.2-1.20.1]
- Integrated Dungeons and Structures [1.8.1+1.20.1
]
- Resourceful Lib [2.1.23]
- Ender's Delight [1.0.3]
- Rechiseled [1.1.5c]
- FTB Backups 2 [1.0.23]
- CookingForBlockheads [16.0.1]
- Artifacts [9.2.2]
- Macaw's Furniture [3.2.2]
- Occultism [1.116.0]
- Thermal Integration [11.0.0]
- Additional Lanterns [1.1.1]
- TexTrue's Embeddium Options [0.1.5+mc1.20.1]

### Expected Behavior

Expected to create a new world without crashing

### Actual Behavior

Crash when trying to create a new world
[crash-2024-02-21_16.45.25-client.txt](https://github.com/GregTechCEu/GregTech-Modern/files/14356753/crash-2024-02-21_16.45.25-client.txt)

### Steps to Reproduce

1) Clicking "Singleplayer"
2) Crash

**Comment by TheRealM18** [comment]
In the lastest version on curseforge, 1.1.3.b works fine getting into singleplayer by itself.  Have you tried removing Just Enough Crashes as it can blame the wrong mod.  It willl also run it in a invalid state.

**Comment by SpiritSb2O** [comment]
> In the lastest version on curseforge, 1.1.3.b works fine getting into singleplayer by itself. Have you tried removing Just Enough Crashes as it can blame the wrong mod. It willl also run it in a invalid state.

I spent some time to check which mod caused this problem, and GTM indeed works correctly in most occasions. Just Enougth Crashes is innocent, i doubt that "Configured" mod caused this problem

**Comment by SpiritSb2O** [comment]
> In the lastest version on curseforge, 1.1.3.b works fine getting into singleplayer by itself. Have you tried removing Just Enough Crashes as it can blame the wrong mod. It willl also run it in a invalid state.

Now I'm sure that coft team's mod caused this problem. It is strange that ATM9 also have thermals and gregtech, but it doesn't have this problem.
