### ISSUE TITLE
In-Game ID Standardization

### ISSUE THREAD

**Issue by stanieldev** [GregTechCEu/GregTechCEu-1.19#95]
### Feature Description

As I have been working in the source code, a lot of the ingame IDs for items/blocks follow 2 different ways of modeling: "itemkind.material" and the 1.13 flattening ID standard like "energium_dust."

I propose that GTCEu 1.19 and beyond follow the 1.13 standard for IDs.
Let me know how you devs feel about it and if you approve, I'll submit a pull request.

**Comment by screret** [comment]
Seems reasonable to me, but i want to know what the others think too

**Comment by htmlcsjs** [comment]
i (as a mainly 1.12) dev feel we should keep the oreprefix before the material, making it consistant between the two versions of the mod

**Comment by screret** [comment]
Welllll issue is then it won't be consistent with anything else, but i'd like some other discriminator than `.`

**Comment by stanieldev** [comment]
There is another implementation that would still include it.
So the 1.13 standard is English direction. We could instead have the name reverse-English.

So things could be written as "machine_frame_lv" or "lv_machine_frame."

**Comment by lukaslcf** [comment]
Should we close this issue, now that #103 is merged.
