### ISSUE TITLE
Issue with custom machine.

### ISSUE THREAD

**Issue by MindBrain27** [GregTechCEu/GregTechCEu-1.19#955]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-1.20.1-1.1.3.b.jar

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Sky Greg

### Expected Behavior

Creating a custom electric machine with a proper machine UI.

### Actual Behavior

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/74363414/16a07f53-f943-4547-ad9a-055ce3fed2b9)
I get a machine, everything works, recipes show in JEI, but the machine has no UI.

### Steps to Reproduce

GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
    event.create('test_electric')
        .category('test_electric')
        .setEUIO('in')
        .setMaxIOSize(1, 1, 1, 1)
        .setSlotOverlay(false, false, GuiTextures.SOLIDIFIER_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.COOLING)
})

GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('test_electric', 'simple', GTValues.LV, GTValues.MV, GTValues.HV, GTValues.EV, GTValues.IV, GTValues.LuV, GTValues.ZPM, GTValues.UV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('test_electric')
        .tankScalingFunction(tier => tier * 3200)
        .workableTieredHullRenderer("gtceu:block/machines/compressor");

})

### Additional Information

I don't know what I'm missing but within the online docs and some scripts I found I cannot seem to get past this.

**Comment by screret** [comment]
you want to do `.recipeType('test_electric', true, true)`
