### ISSUE TITLE
UI for Conveyors similar to Pumps

### ISSUE THREAD

**Issue by xllvrr** [GregTechCEu/GregTechCEu-1.19#958]
### Feature Description

Is it possible to have the same UI for conveyors as pumps by the way? Because with pumps a little GUI similar to the wrenches comes out allowing you to denote where to place the pump. But the same GUI doesn't exist for conveyors

**Comment by ExpLog** [comment]
I just wanted to add that it's super hard to place the conveyors facing a machine because of that. You need to first place all the pipes, then all the covers, then finally the machine in order for it to work.

**Comment by YoungOnionMC** [comment]
fixed in #1929
