### ISSUE TITLE
Tooltip improvements for fluid container & batteries

### ISSUE THREAD

**Issue by MatthiasMann** [GregTechCEu/GregTechCEu-1.19#959]
### Feature Description

In Nomifactory (gregtech-1.12.2-2.7.4-beta) is a nice feature which shows:
- for batteries (in inventory / battery box): the remaining time at 1A continuous output - this is useful when you have a blast furnace running from a battery (or through a battery with smaller power generation)
- for fluid cells / tanks: the amount of ingots / plates (fluid volume divided by 144mB rounded down)

I would love to see these in GT-Modern too.

**Comment by YoungOnionMC** [comment]
fixed in #1550 and #1551
