### ISSUE TITLE
GregTech slows down `ItemTooltipEvent` massively

### ISSUE THREAD

**Issue by Technici4n** [GregTechCEu/GregTechCEu-1.19#964]
See https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/7698.

Zooming in on the profile:
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/13494793/1fbd00cb-92c1-48e6-bb79-6c1e9aab1b61)

The most likely culprit is https://github.com/GregTechCEu/GregTech-Modern/blob/7554d1d69d173bf361cdcefc7d2428324a7c0a2e/src/main/java/com/gregtechceu/gtceu/api/data/chemical/ChemicalHelper.java#L225-L234 returning `null` from `computeIfAbsent`. To quote the documentation:

> If the mapping function returns `null`, no mapping is recorded.

**Comment by MKr4zy** [comment]
Tested with the current Version: 1.1.3.b-build_516

Works now without a significant lagspike.
I've run a spark profiler and tried to reproduce the original Problem, theres still a small lag, but way less noticable then before.

https://spark.lucko.me/NnXiYS5kBh
