### ISSUE TITLE
Pipe Transfer rate And Steam Boiler tooltips Bug

### ISSUE THREAD

**Issue by yaohuomhuom** [GregTechCEu/GregTechCEu-1.19#965]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.1.3.b

### Recipe Viewer Installed

No Recipe Viewer

### Environment

SinglePlayer

### Cross-Mod Interaction

No

### Other Installed Mods

No Other Mod

### Expected Behavior

Tiny Bronze Fluid Pipe in toolip say 20mB/t Transfer rate;
And HP Steam Liquid Boiler toolip say 30L/t steam produces（is 1L == 10mb in minecraft????）;

### Actual Behavior

Tiny Bronze Fluid Pipe in game transfer  200mB/t;
And HP Steam Liquid Boiler in game produces 300mb/t;

### Steps to Reproduce

just use HP Steam Liquid Boiler start produces steam and use Tiny Bronze Fluid Pipe transfer to the Drum，see the steam amount in gui。

### Additional Information

bronze pipe transfer rate set here

https://github.com/GregTechCEu/GregTech-Modern/blob/7554d1d69d173bf361cdcefc7d2428324a7c0a2e/src/main/java/com/gregtechceu/gtceu/common/data/materials/FirstDegreeMaterials.java#L106

but i see something like this，maybe this is why 20mb/t to 200mb/t ???

https://github.com/GregTechCEu/GregTech-Modern/blob/7554d1d69d173bf361cdcefc7d2428324a7c0a2e/src/main/java/com/gregtechceu/gtceu/common/blockentity/FluidPipeBlockEntity.java#L127

https://github.com/GregTechCEu/GregTech-Modern/blob/7554d1d69d173bf361cdcefc7d2428324a7c0a2e/src/main/java/com/gregtechceu/gtceu/common/blockentity/FluidPipeBlockEntity.java#L217

about  HP Steam Liquid Boiler ，maybe just change the  tooltips，in code it really just 300mb/t

https://github.com/GregTechCEu/GregTech-Modern/blob/7554d1d69d173bf361cdcefc7d2428324a7c0a2e/src/main/java/com/gregtechceu/gtceu/common/machine/steam/SteamLiquidBoilerMachine.java#L69

https://github.com/GregTechCEu/GregTech-Modern/blob/7554d1d69d173bf361cdcefc7d2428324a7c0a2e/src/main/java/com/gregtechceu/gtceu/api/machine/steam/SteamBoilerMachine.java#L186

**Comment by sirjoekcb** [comment]
1L is 1mb

I'm not sure if it applies to the single block boilers, but I believe the large boilers output the amount in the tooltip on average but only actually generate steam every 5 ticks. 

If these are actually generating the higher amount per tick that is another contributor to boiler balance being so wonky.

**Comment by yaohuomhuom** [comment]
> 1L is 1mb
> 
> I'm not sure if it applies to the single block boilers, but I believe the large boilers output the amount in the tooltip on average but only actually generate steam every 5 ticks.
> 
> If these are actually generating the higher amount per tick that is another contributor to boiler balance being so wonky.

i recheck the game and find the gui update in 0.5s so call 10tick ,so 30L/t = 30mb/t =300mb/10t ，20mb/t = 200mb/10t，tooltip is right。
