### ISSUE TITLE
Support for outputting items from input buses using pipes

### ISSUE THREAD

**Issue by gjmhmm8** [GregTechCEu/GregTechCEu-1.19#967]
### Feature Description

Currently, GregTech does not support the ability to output items from input buses using pipes. This limitation can be problematic for players who want to automate their item handling more efficiently.
I suggest adding a feature that would allow players to connect pipes to input buses and extract items from them. This would provide a more versatile and flexible way to manage item transportation within a GregTech-based setup.
By implementing this feature, players would be able to create more complex and optimized automation systems, improving the overall gameplay experience.
Thank you for considering this request. I look forward to seeing this feature implemented in a future update.

**Comment by screret** [comment]
just don't push in stuff you don't want in there?
