### ISSUE TITLE
energy hatch

### ISSUE THREAD

**Issue by Snakedon** [GregTechCEu/GregTechCEu-1.19#973]
### Checked for existing issues

- [x] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.1.3b

### Recipe Viewer Installed

JEI

### Environment

multi

### Cross-Mod Interaction

Unsure

### Other Installed Mods

atm9

### Expected Behavior

In most multiblocks it is written that you can install from 1 to 3 input hatch, but even if you install 2-3 of these, the multiblock still thinks that it costs only 1.
For example, a 2x16-amp UV, but it says 8 million instead of 16.
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/48630889/2330f1c8-393a-4757-beb7-12dcd046aa1b)
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/48630889/96e93ede-f10a-4481-98e1-a227360f5a34)

### Actual Behavior

for example, on the Mega Fusion Reactor, neutronium with 256 hatch parallels cannot be crafted, because it requires about 38 million, and 1 UHF input for 16 amperes gives a current of 33 million eu per tick.

### Steps to Reproduce

any multiblock with more than 1 input hatch.

**Comment by screret** [comment]
works fine for me.
