### ISSUE TITLE
Incorrect localization files.

### ISSUE THREAD

**Issue by 300f20t** [GregTechCEu/GregTechCEu-1.19#974]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.1.3.b

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Jade

### Expected Behavior

The title with the translation will be displayed.

### Actual Behavior

The title with the translation not displayed.

### Steps to Reproduce

Look at the ore indicator from JADE

### Additional Information

I guess the problem is not with JADE, but with the localization files. Most likely, there is simply no name for it. Perhaps this causes a problem with other mods for viewing block names.

**Comment by 300f20t** [comment]
![2024-03-17_15-15-25](https://github.com/GregTechCEu/GregTech-Modern/assets/93136063/888309f8-1a3c-4d33-a554-770de5e0a71e)

**Comment by screret** [comment]
we do make the lang files be correct, these items are dynamically generated so they can't all have their own ids.
this is the fault of whatever block info display mod you have using the wrong method for getting the name of the block.
