### ISSUE TITLE
Replacing a drum causes electric pumps to stop working

### ISSUE THREAD

**Issue by G1R-Productions** [GregTechCEu/GregTechCEu-1.19#975]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.1.3.b

### Recipe Viewer Installed

None

### Environment

Dedicated server

### Cross-Mod Interaction

Yes

### Other Installed Mods

Gravitas2

### Expected Behavior

Replacing an empty drum with a full drum while connected to an electric pump and fluid storage should empty the full drum

### Actual Behavior

Replacing an empty drum with a full drum results in the new full drum not being emptied until the pipe with the pump is broken and replaced with the pump.

### Steps to Reproduce

Empty a drum from the side with an electric pump then break the empty drum and place down a new full drum.

**Comment by G1R-Productions** [comment]
My current work around is to place a drum down and put a pump on that drum set to input. On one side I have a pipe with a pump to a tank and on the side with the pump I can put down a full drum and it will drain. When that drum is empty I can place a new drum. This is super janky but it works until the pump on a pipe is fixed.

**Comment by Igneaalis** [comment]
Item pipes with Conveyor Modules behave exactly like this! If I break a barrel with a pipe connected with it via conveyor module, then the whole pipe network doesn't behave like it must to. Building something automated with GT pipes causes a lot of issues and struggling :(

**Comment by Spicierspace153** [comment]
fixed as of 1.5.0
