### ISSUE TITLE
GT Machines not recognized as catalysts in EMI tree

### ISSUE THREAD

**Issue by steph-lion** [GregTechCEu/GregTechCEu-1.19#977]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.1.3.b

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Nomifactory Modern modpack

### Expected Behavior

When using tree recipe, the machine should be visible as a catalyst

### Actual Behavior

When using something like a Wiremill to create wires, the tree on EMI doesn't show the icon/model for the machine used. It only shows the name when hovered.
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/52045633/ad0a33f5-8c5e-4b39-8e3e-862fd62c10be)
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/52045633/58302a36-8b69-46aa-b844-711daf5f910e)

### Steps to Reproduce

1. Click on aluminum wire
2. Check for the recipe with the wiremill and press the tree icon
3. No machine shown in the tree

### Additional Information

Already reported on EMI repo, it says that it's GT's "fault". https://github.com/emilyploszaj/emi/issues/478

**Comment by Arborsm** [comment]
it's render issue with Embeddium

**Comment by embeddedt** [comment]
This does not appear to be an Embeddium bug. I can reproduce it without as well if `use-batched-renderer` is disabled in `config/emi.css`. Embeddium likely triggers the issue because EMI automatically disables the batching renderer with it present.

**Comment by Leclowndu93150** [comment]
My last guess is ImediatelyFast

**Comment by embeddedt** [comment]
Nope, tested in a standalone instance with just GregTech+EMI and could reproduce.

**Comment by Arborsm** [comment]
> This does not appear to be an Embeddium bug. I can reproduce it without as well if `use-batched-renderer` is disabled in `config/emi.css`. Embeddium likely triggers the issue because EMI automatically disables the batching renderer with it present.

odd? last time I tried GregTech+EMI it was rendering normally.

**Comment by Arborsm** [comment]
oops, wrong reply

**Comment by Arborsm** [comment]
> Nope, tested in a standalone instance with just GregTech+EMI and could reproduce.

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/44860537/87236e1f-5ca8-4535-ad65-1b94101e690e)
hm?

**Comment by embeddedt** [comment]
You need to disable the batched renderer in EMI as I mentioned above.

**Comment by Leclowndu93150** [comment]
do i need to enable it back in my modpack ?

**Comment by Arborsm** [comment]
> Embeddium likely triggers the issue because EMI automatically disables the batching renderer with it present.

my bad, I didn't notice the last sentence ><

**Comment by steph-lion** [comment]
Any news? What's the fix for this then?

**Comment by Arborsm** [comment]
turn `use-batched-renderer` to `true`

**Comment by steph-lion** [comment]
It seems that new EMI's release fixed this problem. Update EMI mod.

**Comment by screret** [comment]
thanks for that info
