### ISSUE TITLE
Question regarding textures

### ISSUE THREAD

**Issue by Ezoteric** [GregTechCEu/GregTechCEu-1.19#990]
### Feature Description

I got a couple of questions regarding the textures as I am doing the puredbcraft for them.

1. Are small ore blocks being used?
2. In assets\gtceu\textures\block\multiblock, most of them use the same textures, is this planned to be changed, if not, could you just make a generic folder so all the ones that use the same texture will use that 1 texture as having 20 of the same is an unnecessary extra load.
3. With the fluid/gas/etc, you have a couple that use their own texture and others use 1 generic file of their type, why is that and could this also just use that 1 generic for their type, again seems like an unnecessary extra load.
4. Are emissive layers being used? ( i have 2 installs, 1 with optifine and 1 with oculus.

Just my 2 cent.

**Comment by screret** [comment]
already answered 1, 2, 3
4: you need the Shimmer mod for that now.

**Comment by Ezoteric** [comment]
Same dude :D thnx again m8
