### ISSUE TITLE
Macerator not processing silk touched vanilla ores

### ISSUE THREAD

**Issue by loving2** [GregTechCEu/GregTechCEu-1.19#991]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.1.3.b

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

ATM9

### Expected Behavior

Expected to produce crushed redstone from `minecraft:redstone_ore`

### Actual Behavior

The `minecraft:redstone_ore` is not processed

### Steps to Reproduce

1) Give yourself some vanilla silk-touched redstone ore
2) Put it in a Macerator with power
3) Nothing happens

### Additional Information

I checked the recipe for macerating silk-touched redstone ore from the dumped recipes, and it looks to use a `forge:intersection` of the tags `forge:ores/redstone` and `forge:ores_in_ground/stone`

Both of those tags are present on the vanilla redstone ore, and the recipe even shows up in JEI as being possible. Yet when inserted in the macerator nothing happens.

GT's redstone ore works fine in the macerator. I also checked other mod's silk-touched ores that the macerator should be able to handle (because the tags are present on the ores and it shows in JEI as being possible) and found that none of them worked in it. They do seem to work just fine in a forge hammer, but that just checks for the tag `forge:ores/redstone` for example.

**Comment by loving2** [comment]
I also tested this on the latest build available, build_521, where it was still present

**Comment by z0the** [comment]
I have the same issue
