### ISSUE TITLE
Tranformer internal buffer too small to support larger amp loads

### ISSUE THREAD

**Issue by dimondmine2** [GregTechCEu/GregTechCEu-1.19#997]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.1.3b

### Recipe Viewer Installed

JEI

### Environment

Multiplayer dedicated server

### Cross-Mod Interaction

Unsure

### Other Installed Mods

Gravitas 2

### Expected Behavior

LV transformers can out put their maximum allowed amps if supplied with enough input power

### Actual Behavior

All MV to LV transformers have an internal buffer of 256 EU. If I wish to turn 16 MV amps to 64 LV amps using a transformer, the internal buffer of the transformer is not large enough to do that in a single tick. The internal buffer of each MV to LV transformer is always 256, regardless of the transformer (1x 2x 4x etc). My issue is that I am supplying the 16MV amps to 64 LV amps transformer with plenty of MV amps, however the transformer is not outputting as many LV amps as expected based on the MV amps I am inputting. I suspect the cause of this is the size of the internal buffer being only 256 EU. This issue of internal buffer scalaing may also affect other tiers of transformers.

### Steps to Reproduce

Set up one LV transformer to power 8 LV thermal centrifuges at the same time, stepping down from MV power. Not all machines will receive enough power. Even using super conductor cable.

### Additional Information

none

**Comment by UltimateEnforcer** [comment]
I even struggle with a 1A MV transformer, to transform 1A HV to 4A MV consistently enough for my EBF to run.
